### ISSUE TITLE
Silence errors respecting error_reporting setting

### ISSUE THREAD

**Issue by PatchRanger** [getsentry/sentry-php#1000]
Sentry should respect `error_reporting` setting.
It's important, because sometimes it's required to change this setting dynamically to consciously "silence": for example, to avoid warning caused by "include"ing missing file.

Symptoms are described in https://github.com/symfony/symfony/issues/36472 .
Cause is described in https://github.com/symfony/symfony/issues/36472#issuecomment-615164279 .

I am going to create PR soon.

**Comment by Jean85** [comment]
This should have been fixed in #1196, can anyone confirm?
