### ISSUE TITLE
How to provide my own http client implementation?

### ISSUE THREAD

**Issue by enumag** [getsentry/sentry-php#1004]
Hi, I'd like to use this library but since it's not tied into any specific Http library I'd like to provide my own implementation. How can I do that?

I'm not interested in any existing guzzle-based, curl-based or any other adapter. I don't even want to use `php-http/discovery`. I simply want to specify my own implementation which will be based on [`amphp/http-client`](https://github.com/amphp/http-client). (As far as I know there is no existing package providing the integration.)

So far I was unable to find a way to do that. The documentation only states that the sdk is not tied to any specific implementation but there doesn't seem to be any option to provide my own.

**Comment by enumag** [comment]
I found a [setHttpClient](https://github.com/getsentry/sentry-php/blob/f7645df23d00a1102db3f8ca5de997763e599a21/src/ClientBuilder.php#L161) method but it's deprecated. And it doesn't specify what I should use instead.

**Comment by Jean85** [comment]
That deprecation was added in #855, where we introduced the `setTransportFactory` method. You should use that one, and create your transport inside the `TransportFactory` implementation that you would provide.

**Comment by enumag** [comment]
Yeah I'm trying to do that... I got this far:

```php
$options = ['dsn' => '...'];
$client = ClientBuilder::create($options)
    ->setTransportFactory(
		new class implements \Sentry\Transport\TransportFactoryInterface {
			public function create(Options $options): TransportInterface
			{
				return new HttpTransport(
					$options,
					/* provide http client factory */,
                    /* provide request factory */,
					true,
					false
				);
			}
		}
    )
    ->getClient();
SentrySdk::init()->bindClient($client);
```

The current problem I'm trying to solve is finding request factory. This library is using [`MessageRequestDiscovery::find()`](https://github.com/getsentry/sentry-php/blob/f7645df23d00a1102db3f8ca5de997763e599a21/src/ClientBuilder.php#L310) but that is deprecated as well so I don't want to use it.

It says I should use `\Http\Discovery\Psr17FactoryDiscovery` instead, presumably this means `Psr17FactoryDiscovery::findRequestFactory()`. So I tried that.

This however returns `Psr\Http\Message\RequestFactoryInterface` but `Sentry\Transport\HttpTransport` wants `Http\Message\RequestFactory`.

----

Overall navigating through all of this deprecated stuff is getting very complicated. Especially since this library itself is also relying on deprecated API. From a library that claims to not be tied to any specific Http implementation, providing my own is extremely difficult.

**Comment by Jean85** [comment]
Unfortunately this lib predates a few of the PSR standards that we should use for that. For example, `HttpTransport` should use `Psr\Http\Message\RequestFactoryInterface`, but we probably couldn't change that to avoid breaking BC.

You do not have to use `HttpTransport` though, you can implement `TransportInterface` directly, and `ClosableTransportInterface` if you want.

**Comment by enumag** [comment]
Yeah, I did that... It works in the end... but the entire hack has like 120 lines. And I'm still not sure how to deal with exceptions since [`Deferred::reject()`](https://github.com/php-http/client-common/blob/master/src/Deferred.php#L117) requires a `ClientExceptionInterface` instead of `Throwable`. Can you give me some advice how to handle that?

**Comment by ste93cry** [comment]
I'm closing this due to the fact that a lot of time passed, and in the meanwhile the version 3 of the SDK got released. Feel free to open a new issue if the issue persist.
