### ISSUE TITLE
GzipEncoderPlugin incorrectly claims to use PSR-17 stream factory

### ISSUE THREAD

**Issue by enumag** [getsentry/sentry-php#1006]
https://github.com/getsentry/sentry-php/blob/f7645df23d00a1102db3f8ca5de997763e599a21/src/HttpClient/Plugin/GzipEncoderPlugin.php#L21

The doc comment says that the plugin is using a PSR-17 stream factory. However it is actually using [`Http\Message\StreamFactory`](https://github.com/getsentry/sentry-php/blob/f7645df23d00a1102db3f8ca5de997763e599a21/src/HttpClient/Plugin/GzipEncoderPlugin.php#L9) which is something else. PSR-17 factory is `\Psr\Http\Message\StreamFactoryInterface`.

**Comment by Jean85** [comment]
PHPDoc is fixable. We could probably fix it?

Changing the type alltogether maybe is a BC?

**Comment by ste93cry** [comment]
>Changing the type alltogether maybe is a BC?

This is indeed a BC, but I planned to do it in `3.0` where we can drop support for Httplug `1.x` and thus also of its own HTTP-related interfaces. However in the meanwhile we could transform the typehint to an union of `Psr\Http\Message\StreamFactoryInterface` and `Http\Message\StreamFactory` and handle both implementations
