### ISSUE TITLE
Slowness calling server

### ISSUE THREAD

**Issue by dorianrod** [getsentry/sentry-php#1007]
Hi,
Last time I tried Sentry on php side performance falled down.  I guess this is caused by server call. Is there a way to just log errors and message on every page call, then every X minutes send all the logs to sentry servers (e.g. using a CRON that call a script to send all awaiting logs) ?
If not, is it something you'd consider (or maybe you already have considered it and reject it for on purpose) ?
Have a nice day
DR

**Comment by ste93cry** [comment]
>Is there a way to just log errors and message on every page call, then every X minutes send all the logs to sentry servers

You can use a custom transport or try to use the `SpoolTransport` transport to buffer the errors and send them whenever you think is more appropriate. You should be able to achieve logging to file by creating a custom implementation of the `SpoolInterface` interface

**Comment by Jean85** [comment]
Would sending at shutdown obtain the same effect @ste93cry? Is it still doable?

**Comment by ste93cry** [comment]
>Is it still doable?

Sending events at the shutdown is the default behavior right now and won't change until `3.0`. The user is asking anyway for a solution similar to the spool, and out-of-the-box the support for this feature is present
