### ISSUE TITLE
Adding exception properties to the event as extra data

### ISSUE THREAD

**Issue by enumag** [getsentry/sentry-php#1010]
I'd like to have a better control over what data are added to `\Sentry\Event`. In particular, my exceptions often have some custom properties with important details about what caused the exception. Since the exception object itself isn't serialized in anyway (Sentry SDK only takes the message, class and stacktrace), I'd like to add some callback to add the data myself.

The closest thing to what I need seems to be the [`Client::prepareEvent()`](https://github.com/getsentry/sentry-php/blob/f7645df23d00a1102db3f8ca5de997763e599a21/src/Client.php#L164-L187) method since it transforms the original `$payload` to and Event instance. So unless I missed some already existing way, I need one of the following:

a. The `before_send` callback to be passed the original `$payload` array (since the payload holds the original exception) [here](https://github.com/getsentry/sentry-php/blob/f7645df23d00a1102db3f8ca5de997763e599a21/src/Client.php#L186).
b. A way to provide my own `EventFactoryInterface` instance (the ClientBuilder currently doesn't allow that).

What do you think? Can we make something like that happen? Basically I need some extension point that would get both the payload and the event instance (and maybe the Scope too) so that I can add what I need.

The easiest solution in my opinion is to pass the event and the payload a callback.

**Comment by enumag** [comment]
Hmm perhaps I just found what I need [here](https://github.com/getsentry/sentry-php/blob/f7645df23d00a1102db3f8ca5de997763e599a21/src/State/Scope.php#L319). If I add a custom scope with an EventProcessor then it might work...

**Comment by ste93cry** [comment]
> b. A way to provide my own `EventFactoryInterface` instance (the ClientBuilder currently doesn't allow that).

Glad we didn't allow this as the factory is something on my list of things to deprecate: the coupling needed between it and the client itself is too much to let it survive the next major version

>The `before_send` callback to be passed the original `$payload` array (since the payload holds the original exception) [here](https://github.com/getsentry/sentry-php/blob/f7645df23d00a1102db3f8ca5de997763e599a21/src/Client.php#L186).

This is something we can indeed do, contribution is welcome :+1: 

>If I add a custom scope with an eventProcessor callback then it might work

This is the only viable solution I can think of right now

**Comment by enumag** [comment]
The eventProcessor works fine for me so I think I'll close this. Thanks!
