### ISSUE TITLE
Additional data with Monolog

### ISSUE THREAD

**Issue by enumag** [getsentry/sentry-php#1014]
Some of my calls to Monolog contain additional data in the `$context` array. I need to get some of these data into the `\Sentry\Event` object. I want to use an event processor for that since it gets both the Event instance and the original `$payload` array (see #1010).

The issue is that the data I need don't make it into the `$payload` array at the moment. The Monolog Handler only copies the exception but the rest of `$record['context']` is thrown away:

https://github.com/getsentry/sentry-php/blob/97bbca2c828651dfbd04769c94c1cc8b37e096a3/src/Monolog/Handler.php#L53-L55

Do I have to write my own Monolog Handler for this or can we improve the existing one in this library to pass the data into the payload?

**Comment by enumag** [comment]
Related to https://github.com/amphp/http-server/pull/310.

**Comment by Jean85** [comment]
Changing the handler was previously shot down due (and explained) in #844 & #848; TL;DR, we cannot assume what's inside Monolog context, so extracting info bu default could lead to unwanted stuff.

There's also https://github.com/B-Galati/monolog-sentry-handler that could help you in getting more information from Monolog.

Our handler is final, but you can surely use nested handler to avoid rewriting it.

**Comment by enumag** [comment]
> Our handler is final, but you can surely use nested handler to avoid rewriting it.

I don't see how in this case.

**Comment by Jean85** [comment]
In the same way that special handler do, decorating the original handler: https://seldaek.github.io/monolog/doc/02-handlers-formatters-processors.html#wrappers--special-handlers

**Comment by enumag** [comment]
I managed to get the data through the existing Handler by implementing `Monolog\Processor\ProcessorInterface`:

```php
namespace App\Library\Monolog;

use Monolog\Processor\ProcessorInterface;

final class RequestExtraProcessor implements ProcessorInterface
{
	public function __invoke(array $record): array
	{
		if (array_key_exists('request', $record['context'])) {
			$record['context']['extra']['request'] = $record['context']['request'];
		}

		return $record;
	}
}

**Comment by nnatter** [comment]
For completion; As far as I understand, the solution of registering a monolog processor described in https://github.com/getsentry/sentry-php/issues/1014#issuecomment-626673372 **does not work with version 4 of this bundle**. 

If you want to do this with version 4 of this bundle, you need to decorate the monolog handler (or register your own handler) like described in https://github.com/getsentry/sentry-php/pull/848#issuecomment-605322356.
