### ISSUE TITLE
with_locals not available anymore

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry-php#1015]
The current PHP SDK doesn't support the `with_locals` option anymore?
Is there a special reason for this? This feature was quite handy in the older versions of sentry.

**Comment by Jean85** [comment]
What are you referring to? I don't see any reference to that in the source code of 1.x.

**Comment by cleptric** [comment]
The option itself was not present before, but it still sent local variables along with stackframes.
Is there a way to get this to work with the current SDK as well?

**Comment by Jean85** [comment]
Do you mean that you want to see the arguments that are passed to functions present in the stackframes?

That functionality is still present: https://github.com/getsentry/sentry-php/blob/97bbca2c828651dfbd04769c94c1cc8b37e096a3/src/Stacktrace.php#L160-L174

![Schermata da 2020-05-08 11-20-38](https://user-images.githubusercontent.com/6729988/81391837-0e1c3f00-911e-11ea-8c4d-678b3e28e4dc.png)

If you're not seeing those, maybe it's a bug? Or something wrong in your environment.

**Comment by cleptric** [comment]
Alright, it was indeed a configuration issue on my end.
PHP 7.4 introduced a new .ini setting that ignores stack-trace args by default.

```
; Allows to include or exclude arguments from stack traces generated for exceptions
; Default: Off
; In production, it is recommended to turn this setting on to prohibit the output
; of sensitive information in stack traces
zend.exception_ignore_args = On
```

**Comment by allan-simon** [comment]
I was bite by that , and spent 3 hours before finally finding this issue , maybe it's something worth noting somewhere in the doc ?

**Comment by rvanlaak** [comment]
Also landed here, as I'm missing the argument values in my stack traces for a while. We are using Frankenphp, so am trying to figure out where this value gets set to `On`, as `cat /usr/local/etc/php/php.ini | grep exception_ignore_args` tells us that `zend.exception_ignore_args = On`.

Worth knowing; there is an RFC for PHP 8.5 to modify the default value to `On` for all environments: https://wiki.php.net/rfc/exception_ignore_args_default_value

And, thanks for nicely having this documented in the configure section I've apparently ignored ;-) https://docs.sentry.io/platforms/php/guides/symfony/#configure

**Edit:** the default value for `php.ini-production` actually already is `On`:

https://github.com/php/php-src/blob/e408bcafb245b6e598fe656564aa6fd97414dec2/php.ini-production#L157-L160

**Comment by stayallive** [comment]
The default is `On` (and also what the RFC advocates for) which is what you don't want in this case. You want it `Off`, the config controls if args are ignored. You don't want them ignored if you want to see them in you stacktraces this is also what we mention in our docs in various places and in the [troubleshooting](https://docs.sentry.io/platforms/php/troubleshooting/) section.
