### ISSUE TITLE
Minimum stability fail

### ISSUE THREAD

**Issue by antivir88** [getsentry/sentry-php#1026]
$ composer require sentry/sdk:2.0.3
./composer.json has been updated
Loading composer repositories with package information                                                                                                                                                             Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sentry/sdk 2.0.3 -> satisfiable by sentry/sdk[2.0.3].
    - sentry/sdk 2.0.3 requires sentry/sentry ^2.0.1 -> satisfiable by sentry/sentry[2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.3.0, 2.3.1, 2.3.2, 2.4.0, 2.4.x-dev] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by Jean85** [comment]
Please post your PHP version and at least the config part of your `composer.json`, or we can't help you.

**Comment by antivir88** [comment]
{
    "require" : {
        "twig/twig": "1.18.1",
        "mikehaertl/phpwkhtmltopdf": "^2.4"
    },
    "minimum-stability" : "stable",
    "config": {
        "use-include-path": true
    }
}

**Comment by antivir88** [comment]
php 7.3
