### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by gjedeer** [getsentry/sentry-php#1029]
https://docs.sentry.io/error-reporting/configuration/?platform=php

> request_bodies
> 
> This parameter controls if integrations should capture HTTP request bodies. It can be set to one of the following values:
> 
>     never: request bodies are never sent.
>     small: only small request bodies will be captured where the cutoff for small depends on the SDK (typically 4KB)
>     medium: medium-sized requests and small requests will be captured. (typically 10KB)
>     always: the SDK will always capture the request body for as long as sentry can make sense of it

When trying to use the request_bodies option:

```
Fatal error: Uncaught Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException: The option "request_bodies" does not exist. Defined options are: "attach_stacktrace", "before_breadcrumb", "before_send", "capture_silenced_errors", "class_serializers", "context_lines", "default_integrations", "dsn", "enable_compression", "environment", "error_types", "excluded_exceptions", "http_proxy", "in_app_exclude", "in_app_include", "integrations", "logger", "max_breadcrumbs", "max_request_body_size", "max_value_length", "prefixes", "project_root", "release", "sample_rate", "send_attempts", "send_default_pii", "server_name", "tags". in /home/***/public_html/vendor/symfony/options-resolver/OptionsResolver.php:798
Stack trace:
#0 /home/***/public_html/vendor/sentry/sentry/src/Options.php(56): Symfony\Component\OptionsResolver\OptionsResolver->resolve(Array)
#1 /home/***/public_html/vendor/sentry/sentry/src/ClientBuilder.php(115): Sentry\Options->__construct(Array)
#2 /home/***/public_html/ in /home/***/public_html/vendor/symfony/options-resolver/OptionsResolver.php on line 798

```

**Comment by Jean85** [comment]
FTR, the right option is `max_request_body_size`.

**Comment by guilliamxavier** [comment]
And `never` should be `none` (#1019)

**Comment by guilliamxavier** [comment]
I found related getsentry/sentry-docs#1408: the problem is that the Python client indeed uses `request_bodies` (and `never`)
