### ISSUE TITLE
Question: Can we log a captured exception?

### ISSUE THREAD

**Issue by realtebo** [getsentry/sentry-php#1040]
I'm using Laravel 5.x ... 7.x 

I ask you if there is a way to log via Sentry an already captured Exception, in a catch block I mean.

**Comment by Jean85** [comment]
This is normally done with:
```php
try{
    // ...
} catch(\Throwable $e) {
    captureException($e);
}
```
If the exception does not rise, it's not captured automatically. For other details, @stayallive knows more since he maintains `sentry-laravel`.

**Comment by stayallive** [comment]
^ this is the way to do this.

If you want to use the Laravel container it could look more like this:

```php
try {
    // your code that could throw an exception
} catch (\Throwable $e) {
    if (app()->bound('sentry')) {
        app('sentry')->captureException($e);
    }
}
```

You can also use which should also log the exception to your log files:

```php
try {
    // your code that could throw an exception
} catch (\Throwable $e) {
    report($e);
}
```

Your choice what makes the most sense in your situation.

**Comment by realtebo** [comment]
It works thanks.

I cannot find it in the documentation, if missing I suggest to addd

**Comment by stayallive** [comment]
It's here so I think we got it covered :)

> https://docs.sentry.io/platforms/php/#capturing-errors

**Comment by realtebo** [comment]
Thanks for all help.

I was looking only into api doc, thanks for pointing me to right doc page
