### ISSUE TITLE
Sentry seems to be breaking with php-http/curl-client

### ISSUE THREAD

**Issue by wagnerjsilva** [getsentry/sentry-php#1041]
This issue has now started to happen in one of our system, and the stack trace points to sentry.

Any ideas? 

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Http\Client\Curl\Client::__construct() must be an instance of Psr\Http\Message\ResponseFactoryInterface or null, instance of Nyholm\Psr7\Factory\HttplugFactory given, called in /home/wagner_silva/testing-engine/vendor/sentry/sentry/src/HttpClient/HttpClientFactory.php on line 139 and defined in /home/wagner_silva/testing-engine/vendor/php-http/curl-client/src/Client.php:79
Stack trace:
#0 /home/wagner_silva/testing-engine/vendor/sentry/sentry/src/HttpClient/HttpClientFactory.php(139): Http\Client\Curl\Client->__construct(Object(Nyholm\Psr7\Factory\HttplugFactory), Object(Nyholm\Psr7\Factory\HttplugFactory), Array)
getsentry/sentry#1 /home/wagner_silva/testing-engine/vendor/sentry/sentry/src/Transport/DefaultTransportFactory.php(58): Sentry\HttpClient\HttpClientFactory->create(Object(Sentry\Options))
getsentry/sentry#2 /home/wagner_silva/testing-engine/vendor/sentry/sentry/src/ClientBuilder.php(307): Sentry\Transport\DefaultTransportFactory->create(Object(Sentry\Options))
getsentry/sentry#3 /home/wagner_silva/testing in /home/wagner_silva/testing-engine/vendor/php-http/curl-client/src/Client.php on line 79

**Comment by untitaker** [comment]
Please file SDK issues against the correct repo.

**Comment by wagnerjsilva** [comment]
Hi Unitaker,

Not sure where else I'm supposed to file this issue.

I'm a sentry customer, and the UI pointed me to log this issue here.

I've also logged a support request, as Sentry is part of a reporting system, which is broken because of this problem.

I'm not entirely sure it's related to Sentry, but the stack trace leads me to believe so.

**Comment by ste93cry** [comment]
This is the almost the same error being reported in #1039, thus I think that the solution is the same. Would you mind checking if you are using an old version of `sentry/sdk` and in case update it?

**Comment by wagnerjsilva** [comment]
It's indeed very similar. 

I've tried removing sentry all together and putting it back following the documented instructions in GH.

I ended up with the following composer.json and same issue.

```
  "require": {
    "behat/mink": "*@stable",
    "behat/mink-selenium2-driver": "*@stable",
    "facebook/webdriver": "dev-master",
    "symfony/yaml": "*",
    "behat/mink-extension": "*",
    "zendframework/zend-dom": "^2.7.2",
    "behat/behat": "^3.6",
    "nyholm/psr7": "^1.2",
    "sentry/sentry": "^2.4",
    "php-http/curl-client": "^2.1"
  },

**Comment by wagnerjsilva** [comment]
Managed to get it working by reverting everything back to version 21.
Please note your git hub instructions result into a broken experience: 

https://github.com/getsentry/sentry-php

```
php composer.phar require sentry/sentry php-http/curl-client

**Comment by ste93cry** [comment]
>Please note your git hub instructions result into a broken experience:

Thanks for noticing this, we will update the README asap to reflect a working DX experience.

>Managed to get it working by reverting everything back to version 21.

If you are not interested in using a specific HTTP client implementation (e.g. cURL vs Guzzle), can you please try removing the `sentry/sentry` and `php-http/curl-client` packages and require `sentry/sdk` instead?

**Comment by wagnerjsilva** [comment]
No worries. Not really bothered about the http client implementation, so I removed that.

Do you think version 24 would work if we don't include a http client?

**Comment by Jean85** [comment]
`sentry/sdk` is a metapackage that requires the main client (`sentry/sentry`) and a suggested HTTP Client (Guzzle 6). If you don't care about which is used, that should be enough.

**Comment by ste93cry** [comment]
Closing as we should have solved the issue in the mentioned PR. Release will follow shortly, probably at the beginning of the next week
