### ISSUE TITLE
UriFactoryDiscovery MessageFactoryDiscovery StreamFactoryDiscovery: deprecated

### ISSUE THREAD

**Issue by michabbb** [getsentry/sentry-php#1042]
hi there,

with sentry 2.4.1 i get notified about deprecated classes:

![image](https://user-images.githubusercontent.com/3524595/86589449-034f2080-bf8e-11ea-8950-d92a589f5691.png)

can someone please tell me, what i should use here ?
i´m aware that the deprecated classes say something like:

> Consider using Psr17FactoryDiscovery

but i never used them and don´t know howto replace them.

thanks for any help!

**Comment by ste93cry** [comment]
Unfortunately there is nothing you can do, the codebase is typehinted against some deprecated classes (they were superseded by a standardized PSR implementation later) and we cannot change this without breaking BC. We will solve the issue on version 3.0 by relying more on PSR standards and less on Httplug
