### ISSUE TITLE
[Feature] CodeIgniter 4 integration

### ISSUE THREAD

**Issue by MGatner** [getsentry/sentry-php#1043]
I love the snazzy Laravel and Symfony integrations I see in the docs (https://docs.sentry.io/platforms/php/). Any chance we could get an official integration for [CodeIgniter 4](https://codeigniter.com)? It has a cURL client and exception handling already so it should be a straightforward integration, and I would be glad to contribute to a repo that started this project.

**Comment by stayallive** [comment]
Hi @MGatner, this would be a great chance to become an OSS maintainer 😉

I don't believe there are any plans for an official integration, but as you can see in the README many have contributed 3rd party integrations for their favorite platform building on this SDK.

You could take a look at the integrations on how they utilize the PHP SDK and only build a bridge with the platform to not duplicate the error handling and/or rebuild the many options.

We would be really happy if you have an integration published to add it to the README!

**Comment by MGatner** [comment]
Thanks! Might be a bit but I will hold onto this to do. I use Stripe in all my production projects so it would save some performance having a tighter integration.

**Comment by stayallive** [comment]
Awesome! Please open up a PR to the README when you have it published so we can link others looking for this to your integration 💪

**Comment by campio97** [comment]
Hello everyone,

I am exploring the possibility of integrating Sentry with CodeIgniter 4. Has anyone already developed this integration? If not, would anyone be interested in collaborating on creating a dedicated Sentry-CodeIgniter4 SDK?

For error logging, the basic Sentry-PHP SDK is sufficient, but when it comes to performance monitoring and tracing, a more integrated solution is necessary. CodeIgniter 4 already gathers all the essential data for performance and traces through its debug toolbar, which uses collectors (see: https://codeigniter4.github.io/userguide/testing/debugging.html). We could potentially leverage these collectors, making the development of the SDK relatively straightforward.

What are your thoughts on this? Looking forward to your feedback and any potential collaboration!
