### ISSUE TITLE
PHP 5.6 issue on composer install of sentry/sdk 1.x

### ISSUE THREAD

**Issue by adhatama** [getsentry/sentry-php#1045]
Looks like `sentry/sdk:1.x` still used for old PHP 5.6 compatibility. But it fails when I run `composer install` with `"sentry/sdk": "1.x"`

```
Problem 1
    - The requested package sentry/sdk 1.x exists as sentry/sdk[0.0.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 3.x-dev, dev-master] but these are rejected by your constraint.
```

My PHP version
```
root@apache:/var/www/html# php -v
PHP 5.6.40 (cli) (built: Jan 23 2019 00:10:05)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```
Could somebody help me what I missed? Thanks!

**Comment by Jean85** [comment]
`sentry/sdk` is a metapackage that was created alongside `sentry-php` 2.0, which do not support PHP 5.6. You have to use `sentry/sentry-php` 1.x to do that.

**Comment by adhatama** [comment]
Thanks @Jean85 for the fast response.
I tried to use `"sentry/sentry-php": "1.x"` but it got error
```
Problem 1
    - The requested package sentry/sentry-php could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it
```

Then I tried to use `"sentry/sentry": "1.x"` and the `composer install` worked. But I'm not sure about that since it gave error
```
PHP Fatal error:  Call to undefined function Sentry\\init()
```

Is `"sentry/sentry": "1.x"` is the correct one?

**Comment by adhatama** [comment]
I think I missed about the documentation. For sentry 1.x we should use this docs here https://github.com/getsentry/sentry-php/tree/1.11.0 is that correct?

**Comment by adhatama** [comment]
Ok it works great now using those configuration above. Thanks @Jean85 for the direction.
