### ISSUE TITLE
Question: how to have breadcrumb for http request from external libraries ?

### ISSUE THREAD

**Issue by allan-simon** [getsentry/sentry-php#1046]
I first get to know sentry from my experience in python, and one thing that was really awesome was the capacity to sentry to hook into the `request` library , and to display the http request made by 3rd party libraries

it seems that it's not the case with sentry-php,  is it:

  1.  something that already exists but one has to configured
  2.  not coded yet, but PR welcomed ?
  3.  impossible due to the fact it's too hard/impossible to monkey patch 3rd party libraries to hook into them 

even having just `guzzle` would already be a great step forward I think

**Comment by Jean85** [comment]
Coding this kind of things inside this library would be overkill, since there isn't a single way to do external calls in PHP; also, I don't see a clean way to do in from here, without interfering with the user's code.

OTOH, publishing a third-party integration of this kind would probably be easier. Also, there are already a couple of official integrations present for common frameworks.

**Comment by allan-simon** [comment]
ok , my remark was mostly because the sentry for python comes with integration for popular tool/libraries

**Comment by allan-simon** [comment]
https://docs.sentry.io/platforms/python/#integrations

**Comment by allan-simon** [comment]
I see that now there is a GuzzleTracingMiddleware,  would it be possible (would you accept PR?)  to have a middleware not for the tracing but for the breadcrumb ?  (that one would have to manually setup , but at least the code would be there, like for tracing)

**Comment by allan-simon** [comment]
for Guzzle I wrote this 

```
<?php
declare(strict_types=1);

namespace App\Service;

use GuzzleHttp\Exception\RequestException;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Sentry\SentrySdk;
use Sentry\State\HubInterface;

final class GuzzleBreadcrumbMiddleware {
    /**
     * Category is the name of the service called (e.g Swan)
     */
    public static function addRequestToSentry(string $category = 'guzzle', bool $outputBody = false, bool $outputResponse = false): \Closure
    {
        return function (callable $handler) use ($category, $outputBody, $outputResponse): \Closure {
            return function (RequestInterface $request, array $options) use ($category, $handler, $outputBody, $outputResponse) {

                if ($request->getMethod() === 'POST' && $outputBody) {
                    \Sentry\addBreadcrumb(new \Sentry\Breadcrumb(
                        \Sentry\Breadcrumb::LEVEL_INFO,
                        \Sentry\Breadcrumb::TYPE_DEFAULT,
                        $category . ' body',
                        $request->getBody()->__toString(),
                    ));
                }

                $handlerResponseCallback = static function (ResponseInterface $response) use ($category, $request, $outputResponse) {
                    \Sentry\addBreadcrumb(new \Sentry\Breadcrumb(
                        \Sentry\Breadcrumb::LEVEL_INFO,
                        \Sentry\Breadcrumb::TYPE_HTTP,
                        $category,
                        '',
                        [
                            'method' => $request->getMethod(),
                            'status_code' => $response->getStatusCode(),
                            'url' => $request->getUri()->__toString(),
                        ]
                    ));
                    if ($outputResponse) {
                      \Sentry\addBreadcrumb(new \Sentry\Breadcrumb(
                          \Sentry\Breadcrumb::LEVEL_INFO,
                          \Sentry\Breadcrumb::TYPE_DEFAULT,
                          $category . ' response',
                          $response->getBody()->__toString(),
                      ));
                    }
                    return $response;
                };

                // handle the response or exception
                $handlerExceptionCallback = static function (\Throwable $exception) use ($category, $request) {
                    if ($exception instanceof RequestException) {
                        \Sentry\addBreadcrumb(new \Sentry\Breadcrumb(
                            \Sentry\Breadcrumb::LEVEL_INFO,
                            \Sentry\Breadcrumb::TYPE_HTTP,
                            $category,
                            $request->getBody()->__toString(),
                            [
                                'method' => $request->getMethod(),
                                'status_code' => $exception->getResponse()->getStatusCode(),
                                'url' => $request->getUri()->__toString(),
                            ]
                        ));
                    }
                    throw $exception;
                };

                return $handler($request, $options)->then(
                    $handlerResponseCallback,
                    $handlerExceptionCallback,
                );
            };
        };
    }
}

```

**Comment by allan-simon** [comment]
here, outside of the getBody I think the other stuff are avaiable with only PSR interfaces so it can be made to fit any PSR compliant library , which would seems a good fit for this sdk ?

**Comment by ste93cry** [comment]
>I see that now there is a GuzzleTracingMiddleware

The main reason we implemented this middleware was to have a sort of example of how tracing works

>would it be possible (would you accept PR?) to have a middleware not for the tracing but for the breadcrumb ?

It would indeed be possible, but as already said in the past doing this means that we may receive a lot of requests for supporting other libraries as well, which will add burden to the maintenance of this project that I'm not sure we are able to sustain. Also, although the code may just require a PSR interface, it still has to be implemented in a way compatible with each library either using a middleware, an event or whatever else third parties are using, so I have some doubts we can have something really generic and "plug & play". If everything reduces to a function that accepts a RequestInterface and a ResponseInterface and calls addBreadcrumb(), I don't see much value in it

**Comment by allan-simon** [comment]
I don't see why it would not add much value, the way it is done in the other SDK , is that `http` breadcrumb only show you the 
   * http method 
   * http URL
   * status code 

(which is anyway the only stuff you can put in a sentry http breadcrumb...) 

all of which are provided by PSR which is once again php standard by now, not binding you to a specific library, and which are all already pretty useful, no ?

**Comment by ste93cry** [comment]
I'm closing this because there are no plans for now to integrating more third parties lib support into this package. Should the need arise again in the future from multiple people we can re-evaluate the situation.
