### ISSUE TITLE
Duplicate errors

### ISSUE THREAD

**Issue by gintsmurans** [getsentry/sentry-php#1049]
Started writing this issue, but in middle of it figured out how to do this. Decided to post it anyway, If anyone else is having similar issues, because I couldn't find too many discussions about this.

I originally had a custom exception_handler and error_handler, that sent all errors/exceptions to an e-mail. After migrating to sentry (which btw is excellent:), I got rid of the email stuff, but I am still using exception handlers for better formatting. Also, to be able to catch php errors, I am turning all errors into exceptions - for example to catch division by zero error.

```
function sp_error_handler($errno, $errstr, $errfile, $errline)
{
    // @ used
    if (error_reporting() === 0) {
        return false;
    }

    // Throw all the errors as exceptions, so they can be handled as they should
    throw new ErrorException($errstr, 0, $errno, $errfile, $errline);
}
```

When and error was thrown, we got two entries in sentry:
![image](https://user-images.githubusercontent.com/56369/87524886-6e38df80-c691-11ea-9d4f-095a1b414a0e.png)

Which is basically the same error, only second one is from sp_error_handler function. Solved it by creating a custom class `SpErrorException` that extends `ErrorException` and throwing it instead of `ErrorException` and then adding `excluded_exceptions` parameter to sentry init like this:

```
    Sentry\init([
        'dsn' => $_ENV['SENTRY_DSN'],
        'release' => Config::$items['git_commit_hash'],
        'environment' => Config::$items['environment'],
        'attach_stacktrace' => true,
        'excluded_exceptions' => [
            '\Core\Models\SpErrorException'
        ]
    ]);
```

Now, when php "throws" error, sentry catches it, then custom handler also catches it, throws our custom exception, but sentry ignores that exact exception class.

**Comment by stayallive** [comment]
Hey @gintsmurans, thanks for sharing this! I'm sure somebody else might find this useful.

I am going to close this "issue" since otherwise we will keep it open forever (discussions may never end) and you have found (in my eyes the correct) solution to this problem.

Feel free to open up an issue if you think based on this discussion you'd like to propose an enhancement to the SDK.

**Comment by gintsmurans** [comment]
Nice, thanks for not just deleting it. :)
