### ISSUE TITLE
Update sentry-php-sdk to SDK 2.4.x

### ISSUE THREAD

**Issue by timeverts** [getsentry/sentry-php#1053]
Can you please release a new version of `getsentry/sentry-php-sdk` meta package that requires `"sentry/sentry": "^2.4"` so we can use the latest SDK version with that meta package?

Thanks.

**Comment by stayallive** [comment]
Hi @timeverts, the current `getsentry/sentry-php-sdk` meta package requires `"sentry/sentry": "^2.3"` which also includes 2.4.x, see: https://semver.mwl.be/#!?package=sentry%2Fsentry&version=%5E2.3&minimum-stability=stable.

So there is no need for us to release a new version and running `composer update` should give you version `2.4.1` (as of the writing of this comment). You can check what version composer installed using: `composer show | grep 'sentry'`.

If it doesn't show `2.4.1` (after running `composer update`) can you share your `composer.json`?

**Comment by timeverts** [comment]
You were right! Sorry to have wasted your time. I misunderstood that composer version constraint. A composer update did indeed pull in version 2.4.1.

**Comment by timeverts** [comment]
You were right! Sorry to have wasted your time. I misunderstood that composer version constraint. A composer update did indeed pull in version 2.4.1.

**Comment by stayallive** [comment]
No problem 👍
