### ISSUE TITLE
Enable serializeAllObjects option in Serializer

### ISSUE THREAD

**Issue by FandaOG** [getsentry/sentry-php#1054]
Hi,
how can I enable serializeAllObjects in Serializer class? I'd like to have serialized all objects and I don't want to create classSerializer for every class:

![image](https://user-images.githubusercontent.com/61017336/88366100-7f1bdc00-cd88-11ea-9759-956c72a9ecdb.png)

I've tried to find a way how to enable it but I can not find it. The definition is here:
https://github.com/getsentry/sentry-php/blob/b2cfb8b9e524727db63592fd5183e7a48058bb73/src/Serializer/AbstractSerializer.php#L64

Thanks.

**Comment by ste93cry** [comment]
There is no option to easily configure this flag. You should instantite the serializer on your own, call the `setSerializeAllObjects()` method and set the instance in the SDK client using the client builder's `setSerializer` method. Something like this should work:

```php
$serializer = new Sentry\Serializer(...);
$client = \Sentry\ClientBuilder::create([...])
    ->setSerializer($serializer)
    ->getClient();

Sentry\SentrySdk::getCurrent()->bindClient($client);
```
