### ISSUE TITLE
Default Integrations duplicate events without Additional Data

### ISSUE THREAD

**Issue by nialltiernan** [getsentry/sentry-php#1056]
Hi,

I have a web application with a custom error handler, where I set some Additional Data and capture the exception. Default Integrations are enabled, so Sentry emits two events for each exception thrown by my app. One event is emitted by my own error handler, and the other event is emitted by one of the Default Integrations. In my case this is 
`\Sentry\Integration\ExceptionListenerIntegration`

When viewing the event on Sentry.io, the Additional Data is present only in the event which I have captured. If the event displayed is the one emitted by _ExceptionListenerIntegration_, then I must navigate to the other event to see the Additional Data.

I disabled the Default Integrations but then noticed that my events were containing much less information. This was because some of the integrations enrich the events with useful information that I don't want to lose. Here is my problem.

- If I leave Default Integrations enabled, 50% of the time I need to navigate to the other event in order to see my Additional Data. Also I am send each event twice.
- If I disable Default Integrations, I lose all data enrichment provided about the request, transaction and the context

This seems to me like an unnecessary trade off and I wonder if I am not mistaken.

After digging into the code, it seems to me that the Default Integrations can be split into two groups. Those that emit events and those that enrich data. Having a single option to toggle all of these on/off seems like a bug to me.

- Emit
`ErrorListenerIntegration`, `ExceptionListenerIntegration`, `FatalErrorListenerIntegration`
- Enrich
`RequestIntegration`, `TransactionIntegration`, `FrameContextifierIntegration`

It makes sense to me that I should be able to enable/disable any of these, or at least either of the two groups. For now I will disable the emitters myself.

Please let me know if I have missed something. Any feedback would be welcome.

Thanks

**Comment by ste93cry** [comment]
Since version `2.4` the `integrations` option accepts a `callable(array $defaultIntegrations): array` that you can use to return a fully customized list of integrations

**Comment by stayallive** [comment]
This is an example on how to use that to remove the listener integrations from that list:

https://github.com/getsentry/sentry-laravel/blob/2dfcf9e0bd83856ee7abba25bb3ade8960081430/src/Sentry/Laravel/ServiceProvider.php#L141-L166

So in your case it could look something like this (I have not tested this code):

```
\Sentry\init([
    'dsn' => '...',
    'integrations' => static function (array $integrations) {
        return array_filter($integrations, static function (\Sentry\Integration\IntegrationInterface $integration): bool {
            if ($integration instanceof \Sentry\Integration\ExceptionListenerIntegration) {
                return false;
            }

            return true;
        });
    },
]);
```

**Comment by nialltiernan** [comment]
Thanks guys for the feedback! I went for the Laravel solution.

Because this wasn't documented I made a new [issue ](https://github.com/getsentry/sentry-docs/issues/1946) in the docs repository to update it.

Thanks again.
