### ISSUE TITLE
GuzzleHttp 7 support

### ISSUE THREAD

**Issue by caugner** [getsentry/sentry-php#1059]
**Background**: I'm using `sentry/sentry-laravel` (1.8.0) in my project as well as `guzzlehttp/guzzle`.

**Problem**: I would like to upgrade to Guzzle 7, but unfortunately `sentry/sdk` blocks this due to its dependency on `php-http/guzzle6-adapter` (which requires `guzzlehttp/guzzle ^6.0`).

Is there any chance to resolve this blockage?

**Comment by stayallive** [comment]
I've posted a workaround for this earlier today: https://github.com/getsentry/sentry-laravel/issues/360#issuecomment-667851533.

**Comment by stayallive** [comment]
So. Finally we've updated our `sentry/sdk` package to no longer use Guzzle (any version) and thus you can install `sentry/sentry` or the Laravel integration without any changes or workarounds.
