### ISSUE TITLE
Sentry PHP Tracing/Performance support for WordPress

### ISSUE THREAD

**Issue by archon810** [getsentry/sentry-php#1062]
Hi,

This is a follow-up to https://github.com/getsentry/sentry-laravel/pull/358#issuecomment-669804042, with the goal of adding the new PHP Tracing/Performance support specifically for WordPress.

Thanks.

**Comment by stayallive** [comment]
I've moved this issue to the WordPress plugin repository I think you meant to place it: stayallive/wp-sentry#68.
