### ISSUE TITLE
captureRequestBody if statement not working as intended

### ISSUE THREAD

**Issue by Gabb1995** [getsentry/sentry-php#1065]
I have a request which is failing then calling sentry to log it.
This specific request is very big as it has a 20mb file base64encoded in it.

Therefore its running outofmemory in RequestIntegration::captureResponseBody() in line 202 where it calls $requestBody->getContents. Now obviously the solution would be to use max_request_body_size option in the config and I am setting this to small already but in the if statement before the getContents:

        if (
            'none' === $maxRequestBodySize ||
            ('small' === $maxRequestBodySize && $requestBody->getSize() > self::REQUEST_BODY_SMALL_MAX_CONTENT_LENGTH) ||
            ('medium' === $maxRequestBodySize && $requestBody->getSize() > self::REQUEST_BODY_MEDIUM_MAX_CONTENT_LENGTH)
        ) {
            return null;
        }

the $requestBody->getSize() function is returning null so it never goes in this if statement and returns null.
the getSize function its using is in Zend\Diactoros\Stream:

    /**
     * {@inheritdoc}
     */
    public function getSize() : ?int
    {
        if (null === $this->resource) {
            return null;
        }

        $stats = fstat($this->resource);
        if ($stats !== false) {
            return $stats['size'];
        }

        return null;
    }
and it returns null because fstat is returning 0
and then it runs out of memory here:

    /**
     * {@inheritdoc}
     */
    public function getContents($maxLength = -1) : string
    {
        if ($this->reachedEof) {
            return $this->cache;
        }

        $contents     = stream_get_contents($this->resource, $maxLength);
        $this->cache .= $contents;

        if ($maxLength === -1 || $this->eof()) {
            $this->reachedEof = true;
        }

        return $contents;
    }
 in stream_get_contents I tried making the maxlength less and also printing stream_get_contents with maxlength 20000 example and it is not an empty string or anything its the actual request body.

**Comment by Jean85** [comment]
Moved this under `sentry-php` since the offending code is the `RequestIntegration`, which is from the base library, not the Symfony integration.
