### ISSUE TITLE
3.0 Roadmap

### ISSUE THREAD

**Issue by iluuu1994** [getsentry/sentry-php#1073]
Sorry for being *that* guy 😆 but we're very interested in using performance monitoring in Sentry and I was wondering when we can expect 3.0 to be released so we can start using it. Thanks! 🙂

**Comment by ste93cry** [comment]
We just releated the [first beta](https://github.com/getsentry/sentry-php/releases/tag/3.0.0-beta1) :tada:

**Comment by iluuu1994** [comment]
Awesome 😊 I'll start experimenting with it today and let you know how it goes.

**Comment by ste93cry** [comment]
`3.0` has been released, closing this :grinning:
