### ISSUE TITLE
Memory leaks in HttpTransport on flush when pendingRequests is empty (daemon mode call flush each finish process payload)

### ISSUE THREAD

**Issue by amoseev** [getsentry/sentry-php#1082]
We call flush after every process payload in daemon.

In case empty pendingRequests in class HttpTransport occours memory leaks.
Generator take memory for context.
yield release memory only when real message sends in sentry.

```php
  final class HttpTransport {

    private function cleanupPendingRequests(): void
    {
        $requestGenerator = function (): \Generator {
            foreach ($this->pendingRequests as $key => $data) {
                yield $key => $this->httpClient->sendAsyncRequest($data[0]);
            }
        };
    }
///
 }

```

Code for problem reproduction
 (use guzzle async)

```php

$dsn = '<DSN>';

$options = \array_merge(
    [
        'max_value_length' => 1048576,
        'send_attempts'    => 1,
        'server_name'      => gethostname(),
        'send_default_pii' => true,
    ],
    [
        'dsn' => $dsn,
    ]
);

\Sentry\init($options);

function sendSentryMessage(string $message)
{
    $hub = \Sentry\SentrySdk::getCurrentHub();
    $hub->captureMessage($message);
}

function finishDaemonProcess()
{
    $hub = \Sentry\SentrySdk::getCurrentHub();
    /** @var \Sentry\FlushableClientInterface $client */
    $client = $hub->getClient();
    $client->flush();
}

$countRunsGlobal = 0;
for ($i = 0; $i < 100_000_000; $i++) {
    // process each message. May load saome objects
    $object = array_fill(0, 10000, 'test');

    // in some moments errors occours and we send sentry , message
    if ($i % 20_000 === 0) {
        sendSentryMessage('test ' . $i);

        echo sprintf('-> real send sentry message; i=%s; memory: %s; time: %s' . PHP_EOL, $i, (int) (memory_get_usage(false)), date('H:i:s'));
    }

    // each process message finish witf "flush" command. Call $client->flush();
    finishDaemonProcess();

    // log memory usage sampling
    if ($i % 1_000 === 0) {
        echo sprintf('test sentry memory leaks; i=%s; memory: %s; time: %s' . PHP_EOL, $i, (int) (memory_get_usage(false)), date('H:i:s'));
    }

//    $gcStatus = gc_status();
//    $countRuns = $gcStatus['runs'] ?? 0;
//    if ($countRuns > $countRunsGlobal) {
//        $countRunsGlobal = $countRuns;
//        echo sprintf('! garbage collector worked; i=%s; memory: %s; time: %s' . PHP_EOL, $i, (int) (memory_get_usage(false)), date('H:i:s'));
//    }
}

```

Output:
-> real send sentry message; i=0; memory: 1776432; time: 07:42:23
test sentry memory leaks; i=0; memory: 1844160; time: 07:42:23
test sentry memory leaks; i=1000; memory: 5842048; time: 07:42:24
test sentry memory leaks; i=2000; memory: 9844728; time: 07:42:24
test sentry memory leaks; i=3000; memory: 13945336; time: 07:42:24
test sentry memory leaks; i=4000; memory: 17849336; time: 07:42:24
test sentry memory leaks; i=5000; memory: 22146552; time: 07:42:24
test sentry memory leaks; i=6000; memory: 26050552; time: 07:42:24
test sentry memory leaks; i=7000; memory: 29954552; time: 07:42:24
test sentry memory leaks; i=8000; memory: 33858552; time: 07:42:24
test sentry memory leaks; i=9000; memory: 38024696; time: 07:42:24
test sentry memory leaks; i=10000; memory: 42452984; time: 07:42:24
test sentry memory leaks; i=11000; memory: 46356984; time: 07:42:25
test sentry memory leaks; i=12000; memory: 50260984; time: 07:42:25
test sentry memory leaks; i=13000; memory: 54164984; time: 07:42:25
test sentry memory leaks; i=14000; memory: 58068984; time: 07:42:25
test sentry memory leaks; i=15000; memory: 61972984; time: 07:42:25
test sentry memory leaks; i=16000; memory: 65876984; time: 07:42:25
test sentry memory leaks; i=17000; memory: 70305272; time: 07:42:25
test sentry memory leaks; i=18000; memory: 74209272; time: 07:42:25
test sentry memory leaks; i=19000; memory: 79161872; time: 07:42:25
-> real send sentry message; i=20000; memory: 83074432; time: 07:42:26
test sentry memory leaks; i=20000; memory: 4985904; time: 07:42:27
test sentry memory leaks; i=21000; memory: 8889904; time: 07:42:27
test sentry memory leaks; i=22000; memory: 12793904; time: 07:42:27
test sentry memory leaks; i=23000; memory: 16697904; time: 07:42:27
test sentry memory leaks; i=24000; memory: 20601904; time: 07:42:27
test sentry memory leaks; i=25000; memory: 24505904; time: 07:42:27
test sentry memory leaks; i=26000; memory: 28409904; time: 07:42:27
test sentry memory leaks; i=27000; memory: 32313904; time: 07:42:27
test sentry memory leaks; i=28000; memory: 36217904; time: 07:42:27
test sentry memory leaks; i=29000; memory: 40121904; time: 07:42:28
test sentry memory leaks; i=30000; memory: 44025904; time: 07:42:28
test sentry memory leaks; i=31000; memory: 47929904; time: 07:42:28
test sentry memory leaks; i=32000; memory: 51833904; time: 07:42:28
test sentry memory leaks; i=33000; memory: 55737904; time: 07:42:28
test sentry memory leaks; i=34000; memory: 59641904; time: 07:42:28
test sentry memory leaks; i=35000; memory: 63545904; time: 07:42:28
test sentry memory leaks; i=36000; memory: 67449904; time: 07:42:28
test sentry memory leaks; i=37000; memory: 71353904; time: 07:42:28
test sentry memory leaks; i=38000; memory: 75257904; time: 07:42:28
test sentry memory leaks; i=39000; memory: 79161904; time: 07:42:29
-> real send sentry message; i=40000; memory: 83074464; time: 07:42:29

**Comment by Ocramius** [comment]
Can report that this is also biting us hard: memory increases massively, and quickly, at each processed message.

On a message queue with 300k messages, we observed ~100Mb leaked this way.

We're looking at first upgrading to `sentry/sentry-symfony:^4`, then verifying this again, and hopefully providing a patch for it, if still reproducible there.

**Comment by ste93cry** [comment]
>We're looking at first upgrading to `sentry/sentry-symfony:^4`

That version uses the newer SDK which sends events one by one syncronously, so I don't expect the same problem to occur. It would be nice of course to understand the root cause of the issue in the 2.x version, but I have no clue

**Comment by Ocramius** [comment]
I just verified that moving that the `sentry/sentry-symfony:^4` upgrade does indeed get rid of the problem overall :+1:

**Comment by Jean85** [comment]
Thank you!
