### ISSUE TITLE
Invalid character in default release version

### ISSUE THREAD

**Issue by VincentLanglet** [getsentry/sentry-php#1089]
Hi @Jean85, I'm getting:

![image](https://user-images.githubusercontent.com/9052536/93063570-bfa42180-f676-11ea-8e42-45d98d5be3e2.png)

I don't know which character is invalid, but a `str_replace` could fix the issue.

**Comment by Jean85** [comment]
Moving this under `sentry-php` because it's not something bound to the bundle.

@HazAT is it normal that the `/` or `@` char is considered invalid for a release?

**Comment by HazAT** [comment]
Yeah, `/` is not allowed, `@` is ok.
Our documentation around this is poor but I would recommend using the commit sha.

**Comment by Jean85** [comment]
@VincentLanglet then it's up to you, you used the `/` in the branch name probably, right?

**Comment by VincentLanglet** [comment]
Yes.

But the name is generated by https://github.com/Jean85/pretty-package-versions
I would have expected the library do replace the `/` by something else.
