### ISSUE TITLE
Debug Mode / Internal Logger

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-php#1090]
There should be an option called `debug: boolean` which enables the SDK internal debug logging.

The SDK should emit some log statements for the user to understand what's happening in case the SDK isn't working as expected.

In case internal errors in the SDK happens the logger should log errors, if `debug` is enabled it should also print debug helpful messages.

Example from JS:

![image](https://user-images.githubusercontent.com/363802/93204535-8cd15a80-f756-11ea-9b5b-8a172d232e77.png)

**Comment by ste93cry** [comment]
We already have a few places where we log debug messages, but the logger must be a PSR-3 compatible implementation whose instance must be passed from the outside. The closest thing to `console.log` in JS is the `error_log` function, but I've seen it so little used that I think it's worthless

**Comment by Jean85** [comment]
I agree with @ste93cry: leveraging PSR-3 is the right move here, since it's a really common format that has so many config options to use.

**Comment by HazAT** [comment]
So my point is that it should be easy to enable for users, how will it look like for someone activating this?

**Comment by ste93cry** [comment]
This is a sample code (wrote it on the fly without testing it) that should set the logger instance

```php
$client = \Sentry\ClientBuilder::create([...])
    ->setLogger(...)
    ->getClient();
```

We could have a `debug` option, but it would not make sense because you have to set the instance of the logger somehow

**Comment by Jean85** [comment]
Yes, and we cannot take for granted a default logging location: in a dockerized environment that would be stdout/stderr, otherwhise it could be some file, at which point we don't know the correct path.

Maybe we could tackle this at the framework integration level? The framework has a logging system in place and the integration could intercept a `true` value for that option as a "inject the default logger".

**Comment by ste93cry** [comment]
I think you explained very well my thinking, kudos to you :beer: 

>Maybe we could tackle this at the framework integration level?

I think this would indeed be a good choice, people using the base SDK will not have a so easy way to just do `init()` and get a working logger but people using frameworks will have, and as a bonus point it will be integrated with the logging system they already (hopefully) use

**Comment by ste93cry** [comment]
Closing this because the logger support is already in place 😃
