### ISSUE TITLE
Composer\InstalledVersions.php No such file or directory

### ISSUE THREAD

**Issue by sergeycherepanov** [getsentry/sentry-php#1095]
Warning: include(Composer\InstalledVersions.php): failed to open stream: No such file or directory

PHP 7.1.33
Composer version 1.10.10 2020-08-03 11:35:19

**Comment by sergeycherepanov** [comment]
Issues caused by second custom autoloader

**Comment by 99linesofcode** [comment]
We just got bitten by this error which seems to be related to [this](https://github.com/Jean85/pretty-package-versions/pull/39) issue caused by a change to composer. It has been fixed in the `2.0.4`  version of  `pretty-package-versions`.

Can we bump the minor?

**Comment by ste93cry** [comment]
Sure we can, would you be so gentle to open a PR?
