### ISSUE TITLE
No performance data captured using GuzzleTracingMiddleware

### ISSUE THREAD

**Issue by dsgepers** [getsentry/sentry-php#1102]
Using the code from the docs I have the problem that no performance data is captured from my guzzle requests. (using it to call external services)

```php
use Sentry\Tracing\GuzzleTracingMiddleware;

$stack = HandlerStack::create();
$stack->push(GuzzleTracingMiddleware::trace());

$client = new Client([
    'handler' => $stack
]);
$result = $this->client->request('POST', "{$this->uri}/do/something/", [
    'auth' => [$this->username, $this->password],
    'json' => $payload,
]);
```

This Middleware never captures performance data for me. I was trying to trace why, but didn't get a conclusive answer, basically it's because in the `GuzzleTracingMiddleware:34` it calls `$span->finish`, but $span is a `\Sentry\Tracing\Span` (where in the finish method no event is captures) instead of a `\Sentry\Tracing\Transaction` (where in the finish method an event is captured). But I'm not sure why this property is a Span instead of a Transaction.

My relevant package versions:

```json
        "guzzlehttp/guzzle": "^7.0",
        "sentry/sdk": "^3.0"
```

**Comment by Jean85** [comment]
Maybe this is fixed by #1099 ?

**Comment by stayallive** [comment]
I don't think so. To enable performance tracing in general a transaction has to be started first and at the end that transaction needs to be finished to be sent. This is up to the user to implement the starting of the transaction (as early as possible) and finish the transactions (as late as possible) so the request can be measured.

The `GuzzleTracingMiddleware` simply adds a `span` (or measurement) to the transaction.

See our docs about manual instrumentation: https://docs.sentry.io/platforms/php/performance/#manual-instrumentation, the `startTransaction` should go right after your composer autoload require if possible and finish right at the end of your application. I include some example code how your `index.php` could look like to hopefully clarify:

```php
<?php

// Make sure we know when the script started
define('APP_START_TIME', microtime(true));

// Require your autoload
require __DIR__ . '/vendor/autoload.php';

$transactionContext = new TransactionContext();
$transactionContext->setName($_SERVER['REQUEST_URI'] ?? '<unknown transaction>');
$transactionContext->setOp('http.server');
$transactionContext->setStartTimestamp(APP_START_TIME);
$transaction = \Sentry\startTransaction($transactionContext);

// We let the SDK know about the transaction so integrations like `GuzzleTracingMiddleware` can add spans to the transaction
\Sentry\SentrySdk::getCurrentHub()->setSpan($transaction);

//
// Your app code goes goes here basically...
//

// Finish the transaction and it will be sampled according to the `traces_sample_rate`
$transaction->finish();

**Comment by ste93cry** [comment]
I'm going to close this issue as there have not been updates for a long time. Feel free to reopen if the problem persist
