### ISSUE TITLE
[3.0] Frame context is not populated

### ISSUE THREAD

**Issue by IonBazan** [getsentry/sentry-php#1103]
This is a regression introduced in v3.0.0 during Frame refactoring.
When stacktrace file name and stripped file name is same, the context is not populated by FrameContextifierIntegration.

See:
https://github.com/getsentry/sentry-php/blob/65030a1376b900aee06a4f477bbf320bc8dc9c52/src/FrameBuilder.php#L87
https://github.com/getsentry/sentry-php/blob/65030a1376b900aee06a4f477bbf320bc8dc9c52/src/Integration/FrameContextifierIntegration.php#L81-L83

I would suggest to fallback to `$frame->getFile()` when `$frame->getAbsoluteFilePath()` is `null` or removing the conditions while building an instance of `Frame`.

**Comment by stayallive** [comment]
[`3.0.3`](https://github.com/getsentry/sentry-php/releases/tag/3.0.3) was just released fixing this 👍 

Thank you for the report and even fixing this 💪
