### ISSUE TITLE
Identifying User by username produces an Error

### ISSUE THREAD

**Issue by ahaurat** [getsentry/sentry-php#1107]
According to the docs, one of `id`, `username`, `email`, or `ip_address` are required:
https://docs.sentry.io/platforms/javascript/guides/react/enriching-events/identify-user/

However, including only a `username` produces an error due to this line:
https://github.com/getsentry/sentry-php/blob/17588a2a00d2c4f3f55d847cdb5684ee676c4e1e/src/UserDataBag.php#L74

**Comment by ste93cry** [comment]
This is in conflict with https://develop.sentry.dev/sdk/event-payloads/user/ which says that ``You should provide at least either an `id` (a unique identifier for an authenticated user) or `ip_address` (their IP address)``. @HazAT what's the correct behavior?

**Comment by ahaurat** [comment]
If it helps, I can verify that the `sentry-python` package allows username only. We have been using that as our identifier on python projects and so would like to be consistent and do the same in our PHP projects if possible.

**Comment by ahaurat** [comment]
Went ahead and created a PR in case it's determined that `username` and `email` are valid identifiers. Thanks for taking a look at this!

**Comment by kamilogorek** [comment]
@ste93cry docs were not exhaustive enough, so they are not updated from:

> You should provide at least either an id (a unique identifier for an authenticated user) or ip_address (their IP address).

to:

> You should provide at least one of id, email, ip_address, username for Sentry to be able to tell you how many users are affected by one issue (for example). Sending a user that has none of these attributes (and only custom attributes) is valid, but not as useful.

So `UserDataBag.php` guard is not necessary and can be safely removed.

**Comment by stayallive** [comment]
[`3.0.3`](https://github.com/getsentry/sentry-php/releases/tag/3.0.3) was just released fixing this 👍 

Thank you for the report, and also for starting the fix 💪
