### ISSUE TITLE
How to implement TransportInterface in 3.0?

### ISSUE THREAD

**Issue by enumag** [getsentry/sentry-php#1109]
When implementing my own `TransportInterface` I need to serialize the Event somehow. In 2.x there was a method `Event::toArray()` which no longer exists and the upgrade guide doesn't say what to use instead.

Looking into your `HttpTransport`, it's now using the `PayloadSerializerInterface` to serialize the event. However this interface is internal which means I shouldn't use it.

How am I supposed to serialize the event now? Maybe the `PayloadSerializerInterface` should be non-internal?

**Comment by ste93cry** [comment]
>In 2.x there was a method `Event::toArray()` which no longer exists and the upgrade guide doesn't say what to use instead.

This should indeed be fixed, a PR is more than welcome :+1: 

>Maybe the `PayloadSerializerInterface` should be non-internal?

The interface should indeed not be `@internal`. The implementation was marked like that because I thought that we may need to change how an event is serialized (speaking about the payload) and I didn't want to be locked in a BC-break free policy in this case

**Comment by enumag** [comment]
Okay... See #1110. But then again how do I get a default instance of `PayloadSerializerInterface` when I can't call `new PayloadSerializer()` because it's internal?

**Comment by ste93cry** [comment]
>I can't call `new PayloadSerializer()` because it's internal?

The only thing that the annotation does is to signal to users that the class is not covered by any BC-break policy because it's a class that should be used as part of the internal API, so the answer is to just use it or reimplement the code into your own serializer.

**Comment by ste93cry** [comment]
Closing this because it's pretty old and I think it has been answered
