### ISSUE TITLE
v3: Frame->absoluteFilePath is always null

### ISSUE THREAD

**Issue by caugner** [getsentry/sentry-php#1113]
I maintain a legacy app with Smarty templates which causes a lot of Notice noise. We have been filtering these in the `before_send` callback by comparing the last frame's absolute file path against the directory in which those Smarty templates reside in.

After upgrading to `sentry/sdk` v3, we noticed that these Notices were no longer filtered.

Debugging showed that all `Frame->absoluteFilePath`s are now `null`, which hadn't been the case in v2.

https://github.com/getsentry/sentry-php/blob/f09173d6100a0fd802b666b8a00c0bd2a1b472a3/src/Frame.php#L34-L37

The [Upgrade guide](https://github.com/getsentry/sentry-php/blob/master/UPGRADE-3.0.md) doesn't mention this. Is this a bug or a breaking change?

**Comment by caugner** [comment]
Oh, it looks like this was already reported in #1103 and fixed in #1104.

**Comment by stayallive** [comment]
You are correct, this fix will be released later.

I'll close the issue in the meantime since it was already fixed.

**Comment by stayallive** [comment]
[`3.0.3`](https://github.com/getsentry/sentry-php/releases/tag/3.0.3) was just released fixing this 👍
