### ISSUE TITLE
PHP Fatal error:  Uncaught Symfony\Component\HttpClient\Exception\ClientException: event rejected due to rate limit in ResponseTrait.php:282

### ISSUE THREAD

**Issue by ruudk** [getsentry/sentry-php#1117]
We had some issues in our project that caused us to be rate limited. But now the Sentry SDK throws exceptions, instead of silently ignoring it. This makes the problem only worse.

Shouldn't this exception be caught?

```
$ composer show | grep sentry
sentry/sdk                              2.2.0   This is a metapackage shipping sentry/sentry with a recommended HTTP client.
sentry/sentry                           2.5.0   A PHP SDK for Sentry (http://sentry.io)
sentry/sentry-symfony                   3.5.3   Symfony integration for Sentry (http://getsentry.com)
```

**Comment by ste93cry** [comment]
Any exception thrown by the HTTP client should be catched, right. Anyway, without knowing at least the version of the SDK you are using or without a stacktrace it's impossible to help you more

**Comment by ruudk** [comment]
You're right. I added the versions to it. Since this was happening on production I don't have a stacktrace as this was the only trace left in the logs.
