### ISSUE TITLE
Sentry can't detect errors if a request body size is zero

### ISSUE THREAD

**Issue by Bziks** [getsentry/sentry-php#1118]
Sentry can't detect errors if a request body size is zero.
Example:
```php
do {
    try {
        abs();
    } catch (Throwable $e) {
        $s .= str_repeat('*', 1e3);
    }
} while (++$i < 1e6);
```
I get an error "Allowed memory size..."

I found place, where can I fix it, class **RequestIntegration**:
```php
if (
    null === $requestBodySize ||
>>>    0 === $requestBodySize ||   <<<
    'none' === $maxRequestBodySize ||
    ('small' === $maxRequestBodySize && $requestBodySize > self::REQUEST_BODY_SMALL_MAX_CONTENT_LENGTH) ||
    ('medium' === $maxRequestBodySize && $requestBodySize > self::REQUEST_BODY_MEDIUM_MAX_CONTENT_LENGTH)
) {
    return null;
}
```

Probably you add this small fix in the next release?

**Comment by ste93cry** [comment]
Thank you for reporting the bug, a contribution would be happily accepted. Would you be the hero that fixes the bug by opening two PRs, one targeting the `master` branch and one the `2.x` branch? Please also remember to add a test case to the `RequestIntegrationTest` class

**Comment by Bziks** [comment]
Sure! How can I get access?

**Comment by ste93cry** [comment]
You have to fork this repository, make a branch with your changes and then open a PR. If it's your first time contributing you can find a ton of articles on the web that explains all steps: [here](https://www.dataschool.io/how-to-contribute-on-github/) is one, picked totally randomly

**Comment by ste93cry** [comment]
This has been fixed in both `2.x` and `3.x`, thank you for the contribution
