### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by rask** [getsentry/sentry-php#1122]
How's the plan for PHP 8 support? RC1 is available already and some folks might want to stay on the edge for new projects.

Currently Composer informs me that Sentry SDK 3.x only supports PHP 7.2-7.4.

**Comment by ste93cry** [comment]
You can track the progress in #1087. I don't think we have particular blockers on our side, we were just waiting for some deps to be compatible with PHP 8

**Comment by rask** [comment]
Thanks, will follow that PR.
