### ISSUE TITLE
Captured message stack traces are not being sent by default (payload serialized decision)

### ISSUE THREAD

**Issue by rootpd** [getsentry/sentry-php#1127]
Hi all,

I am trying to attach stack traces to the captured messages (not exceptions).

- I initialize `Client` with `attach_stacktrace` set to `true`.
- I call `captureMessage('foo`)
- Indeed, the tracked event has the stack trace correctly set when I try to debug it.
- The `payloadSerializer` doesn't include it in the final payload, because there are no exceptions (I'm tracking the message).
  https://github.com/getsentry/sentry-php/blob/b1c8679177f0f869ae5b177e9d29fc6007bff121/src/Serializer/PayloadSerializer.php#L145-L149

I stumbled upon #859, but it looks like it doesn't really handle this very issue.

I also tried to use my own `payloadSerializer,` but setting it up would require copying lot of private methods outside of `Client` initialization and it didn't feel right. Even more when you mentioned that it should be automatically attached (https://github.com/getsentry/sentry-php/issues/859#issuecomment-516355370).

Am I missing something here?

Thanks for any help.

**Comment by aleks256** [comment]
I looks like it is already fixed here - https://github.com/getsentry/sentry-php/pull/1123 - but not released yet.

**Comment by rootpd** [comment]
You are right, it does look like it. In that case closing this up, will wait for the next release.

Thanks!
