### ISSUE TITLE
HTTP_HOST undefined when running from command line

### ISSUE THREAD

**Issue by manavo** [getsentry/sentry-php#113]
I looked in Client.php and see that there is a check for REQUEST_URI to exist, to not throw errors if we are running from the command line.

Would it be better to check HTTP_HOST for that? When running a command line script in Laravel 4, it seems like Raven threw this error itself, caught it and reported it.

Happy to send a pull request with that, just want to double check if that is an acceptable solution!

**Comment by stayallive** [comment]
Looks like this was fixed in c27fe51, if the problem persists please open a new issue.
