### ISSUE TITLE
3.0.4: Option "excluded_exceptions" does not exist

### ISSUE THREAD

**Issue by MGatner** [getsentry/sentry-php#1130]
Since updating to `3.0.4` I've been getting this error message:

> The option "excluded_exceptions" does not exist. Defined options are: "attach_stacktrace", "before_breadcrumb", "before_send", "capture_silenced_errors", "class_serializers", "context_lines", "default_integrations", "dsn", "enable_compression", "environment", "error_types", "http_proxy", "in_app_exclude", "in_app_include", "integrations", "logger", "max_breadcrumbs", "max_request_body_size", "max_value_length", "prefixes", "release", "sample_rate", "send_attempts", "send_default_pii", "server_name", "tags", "traces_sample_rate", "traces_sampler".

Here's my integration:
```
Sentry\init([
	'dsn'                 => getenv('sentry.dsn'),
	'excluded_exceptions' => ['CodeIgniter\Exceptions\PageNotFoundException'],
]);
```

No other special configurations or anything. Environment:

OS: Ubuntu 20.04
Host: Apache
PHP: 7.4

**Comment by ste93cry** [comment]
That option has been removed and the replacement is the `IgnoreErrorsIntegration` integration. You can configure it like this:

```php
Sentry\init([
    ...,
    'integrations' => [
        ...,
        new IgnoreErrorsIntegration([
            'ignore_exceptions' => ['CodeIgniter\Exceptions\PageNotFoundException'],
        ]),
    ],
])
```

**Comment by MGatner** [comment]
Thanks for the response.

Was this something I missed moving from `v2` to `v3`? How come it just now started breaking with `3.0.4`?

**Comment by ste93cry** [comment]
> Was this something I missed moving from `v2` to `v3`? How come it just now started breaking with `3.0.4`?

The option was deprecated in [version `2.3`](https://github.com/getsentry/sentry-php/blob/master/CHANGELOG.md#230-2020-01-08). I don't know if you jumped straight from `2.x` to `3.0.4`, but it ceased to exit in `3.0` anyway
