### ISSUE TITLE
Getting Fatal Error "Allowed memory size" when i try send to sentry Fatal Error "Allowed memory size"

### ISSUE THREAD

**Issue by Alexey2369** [getsentry/sentry-php#1142]
In the constructor class `\Sentry\ClientBuilder` the parameter `sdkVersion` [is filled as](https://github.com/getsentry/sentry-php/blob/master/src/ClientBuilder.php#L79) `PrettyVersions::getVersion('sentry/sentry')->getPrettyVersion()`.

When i use composer install with `--optimize` flag, i haven't packages versions map in `\PackageVersions\Versions::VERSIONS`. Sentry sdk version resulting from `FallbackVersions::getVersion($packageName);`. But in `FallbackVersions::getPackageData` has code:

```
$data = \json_decode(\file_get_contents($path), \true);
```

where path - `composer.lock` file

File weighs more, than free RAM, and I get Fatal Error "Allowed memory size".

**Comment by ste93cry** [comment]
First, which version of the SDK are you using? Second, I'm unable to reproduce the issue. I tried installing the deps of this package using `--optimize-autoloader` and `PackageVersions\Versions::VERSIONS` is filled. Do you see the following messages when when running `composer install`?

```
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
```

**Comment by Alexey2369** [comment]
Versions:
`sentry/sentry`: `dev-master@bab5b73dbaf5f0ff62317e1611d952764d5514a9`
`sentry/sdk`: `dev-master@089858b1b27d3705a5fd1c32d8d10beb55980190`

Try it:
```sh
composer install --no-scripts --no-autoloader --no-dev

composer dump-autoload --no-scripts --optimize --no-dev
```

**Comment by ste93cry** [comment]
The problem resides in the usage of the `--no-scripts` option. Is there any good reason you want to skip executing the scripts at the end of `composer install`?

**Comment by Alexey2369** [comment]
It works. Thank you!
