### ISSUE TITLE
Missing PSR context properties

### ISSUE THREAD

**Issue by mrtus** [getsentry/sentry-php#1145]
In older versions the PSR context properties were always available on events in the "extra" bag.
In the latest versions this is no longer the case.

As per [PSR-3 1.2](https://www.php-fig.org/psr/psr-3/#12-message): `Placeholder names MUST correspond to keys in the context array.`

I would make a PR to add this ability back to the `Sentry\Monolog\Handler` by using `$record['context']` and put those values in the "extra" bag.

```php
$this->hub->withScope(function (Scope $scope) use ($record, $event, $hint): void {
  $scope->setExtra('monolog.channel', $record['channel']);
  $scope->setExtra('monolog.level', $record['level_name']);

  foreach($record['context'] as $contextKey => $contextValue) {
    // TODO what about the exception itself? Log the class or completely ignore?
    $scope->setExtra($contextKey, $contextValue);
  }

  $this->hub->captureEvent($event, $hint);
});
```

What about the exception itself? Log the class or completely ignore as it is already processed through
```php
if (isset($record['context']['exception']) && $record['context']['exception'] instanceof \Throwable) {
  $hint->exception = $record['context']['exception'];
}
```

Would this contribution be accepted or is this ability available and am I simply missing something?

I'm looking forward to your response.

**Comment by ste93cry** [comment]
It looks like we aren't able to avoid this issue popping up from time to time :disappointed: Please take a look at #848 (one of the many similar issues) to understand the reasoning about why we won't revert the decision of not blindly adding the context data of Monolog to the Sentry extras

**Comment by mrtus** [comment]
> It looks like we aren't able to avoid this issue popping up from time to time 😞 Please take a look at #848 (one of the many similar issues) to understand the reasoning about why we won't revert the decision of not blindly adding the context data of Monolog to the Sentry extras

I'll have to respectfully disagree and while I do understand the reasoning behind this decision, this issue, I reckon, will keep popping up, it will probably for the reason as mentioned in the description.

> As per PSR-3 1.2: Placeholder names MUST correspond to keys in the context array.

While these are indeed recommendations they are there to allow a better design of frameworks, allow plug-and-play between different implementations, easy adaptability by other developers and frameworks, and many more. These PSR were thoughtfully compiled into a set of rules.

The [PSR-3 1.3](https://www.php-fig.org/psr/psr-3/#13-context) also states that:
> Every method accepts an array as context data. This is meant to hold any extraneous information that does not fit well in a string. The array can contain anything. Implementors MUST ensure they treat context data with as much lenience as possible. A given value in the context MUST NOT throw an exception nor raise any php error, warning or notice.

To pick up on the fact that the context can contain everything, they included a great example for the `Exception` object, stating that implementers must verify the `Exception` type.
> If an Exception object is passed in the context data, it MUST be in the 'exception' key. Logging exceptions is a common pattern and this allows implementors to extract a stack trace from the exception when the log backend supports it. Implementors MUST still verify that the 'exception' key is actually an Exception before using it as such, as it MAY contain anything.


So an alternative solution, to simply not include them, could be to cast these context values to strings or completely ignore them if they are anything other than a scalar value and thus mitigate non-scalar values.

Another alternative solution could be to include an optional handler e.g. `Sentry\Monolog\ContextCopyingHandler` in the library that does copy these context values to the extra bag so this decision of logging the context values is up to the adopter of the library?

Without including a solution in this library it forces teams/organisations to either go into a dependency hell, fork, duplicate code, or wrap this library with its own distributing library with extra tooling, for easy use in a distributed services ecosystem.

With this I hope the decision of not including these context values in the extra bag can be reconsidered.
