### ISSUE TITLE
Event tags overwritten by options

### ISSUE THREAD

**Issue by matthijsthoolen** [getsentry/sentry-php#1146]
It seems like that it's impossible to set tags on a custom event. 

Reproduction:

`$event = Event::createEvent();
$event->setTags(['tag' => 'disappears']);
$sentry->captureEvent($event);`

This tag will never reach Sentry server.

Some investigation leads me to "Sentry/src/Client.php" on row 232 the tags are set to $this->options->getTags();
setTags just overwrites the tags set in the event, shouldnt this be a append/merge instead? 

Or is there another way to add a tag to this event only?

**Comment by ste93cry** [comment]
>shouldnt this be a append/merge instead

Yes, it should. Would you mind opening a PR to fix this bug?

**Comment by matthijsthoolen** [comment]
Yes, I have opened a pull request. I have also fixed the same issue for some other properties. #1148
