### ISSUE TITLE
Errors reported twice as Error & Sentry\Exception\FatalErrorException

### ISSUE THREAD

**Issue by Starfox64** [getsentry/sentry-php#1156]
Same as #720 but creating a new issue as it was for 1.X and things have changed a lot since.

I am using the SDK (no integrations) and whenever an error occurs (PHP errors, exceptions are not duplicated) they are reported twice: once as a normal `Error` and another time as a `Sentry\Exception\FatalErrorException`

Here is how the same error is reported twice in sentry:
```
Error: Call to a member function test() on null
#2 /controller/Extranet/IndexController.php(50): Controller\Extranet\IndexController::show
#1 /libs/Class/Launcher.php(226): Launcher::start
#0 /index.php(6): null
```

```
Sentry\Exception\FatalErrorException: Error: Uncaught Error: Call to a member function test() on null in /var/www/controller/Extranet/IndexController.php:50
Stack trace:
#0 /var/www/libs/Class/Launcher.php(226): Controller\Extranet\IndexController->show()
#1 /var/www/index.php(6): Launcher->start()
#2 {main}
  thrown
#0 /controller/Extranet/IndexController.php(50): null
```

### Environment

PHP: 7.3.25
Sentry: 3.1.1

**Comment by Jean85** [comment]
Could you please share with us how did you set up Sentry in your project? Do you have any custom error handler that could interfere with it? Do you use any official integration?

**Comment by Starfox64** [comment]
I have been able to narrow it down to an issue with the newrelic extension, it seems to be interfering despite it's error collector being disabled. Will follow up on that shortly.

For reference, here is how Sentry is initialized
```php
Sentry\init([
  'dsn' => $this->config->sentryUrl,
  'release' => $this->config->getReleaseName(),
  'environment' => 'production',
  'error_types' => E_ALL & ~E_WARNING & ~E_USER_WARNING & ~E_NOTICE & ~E_USER_NOTICE,
  'max_request_body_size' => 'medium',
  'max_value_length' => 8192,
  'send_default_pii' => true,
  'tags' => [
    'deployment' => $this->config->getSystemName(),
    'release.commit' => $this->config->getCommitHash()
  ]
]);

$this->logger->pushHandler(new Axone\Util\MonologBreadcrumbHandler());
```

Shortly after, my custom error handler is registered
```php
register_shutdown_function(function () use ($launcher)
{
  $err = error_get_last();
  $fatalErrors = E_ERROR | E_PARSE | E_CORE_ERROR | E_COMPILE_ERROR | E_STRICT;

  if ($err && $fatalErrors & $err['type']) {
    ob_clean();
    // Prevents displayErrorPage from killing the script after executing, in previous sentry versions
    // I had issues with errors not being reported at all.
    $launcher->dieOnError = false;
    $launcher->displayErrorPage(500);
  }
});
```

**Comment by ste93cry** [comment]
I see you are using Monolog, if you have a custom error handler that logs the errors to one of its channels I suggest you to disable our `(Error|Exception|FatalError)ListenerIntegration` integrations to avoid double reports

**Comment by ste93cry** [comment]
Given that this is a bug in the New Relic PHP agent and we cannot do anything for it, I will close this issue and mark it as "Won't fix"
