### ISSUE TITLE
Class 'TransactionContext' not found.

### ISSUE THREAD

**Issue by dadambickford** [getsentry/sentry-php#1159]
I feel like I must be doing something silly but I've grinded on this a while and haven't come up with anything.

This sample has worked for general error reporting for a couple months now:

```php
	// Init php backend Sentry reporting 
	include('vendor/autoload.php');
	Sentry\init([
		'dsn' => 'dns_link',
		'error_types' => E_ERROR | E_PARSE | E_CORE_ERROR | E_COMPILE_ERROR | E_USER_ERROR | E_RECOVERABLE_ERROR
	]);
```

I recently upgraded the sentry/sdk package to try and add the perf tracing, but running into issues when adding the default example.

For upgrade and version context, this was the recent change:
  - Upgrading sentry/sentry (2.5.1 => 3.1.1)
  - Upgrading sentry/sdk (2.2.0 => 3.1.0)
  
PHP version was recently upgraded to 7.4.13.
  
and the example code I added:

```php
	$transactionContext = new TransactionContext();
	$transactionContext->setName($_SERVER['REQUEST_URI'] ?? '<unknown transaction>');
	$transaction = Sentry\startTransaction($transactionContext);
	$transaction->finish();
```

But no matter how I use the vendor autoload I only get the "Class 'TransactionContext' not found" fatal error. I see some examples use `require` instead of `include` or some other examples in the same code base use `require_once` but that doesn't seem to change anything. 

Thanks in advance.

**Comment by stayallive** [comment]
Have you tried it like this?

```php
	$transactionContext = new Sentry\Tracing\TransactionContext();
	$transactionContext->setName($_SERVER['REQUEST_URI'] ?? '<unknown transaction>');
	$transaction = Sentry\startTransaction($transactionContext);
	$transaction->finish();
```

I think you are missing the import and looking at [the docs](https://docs.sentry.io/platforms/php/performance/) I think it's us that made you make this mistake!

I'll keep this open so I don't forget to fix this documentation bug but that should help you forward at least.

**Comment by dadambickford** [comment]
That was it! thank you @stayallive.

**Comment by stayallive** [comment]
No problem! Good luck with implementing 👍
