### ISSUE TITLE
php  SDK installation throws "call to undefined function"

### ISSUE THREAD

**Issue by tibz7** [getsentry/sentry-php#1160]
## Important Details

How are you running Sentry?
On-Premise 

## Description
On php7.4 with Phalcon 4.1 project.
when adding the ` Sentry\init(['dsn' => 'qwerty' ]);` it throws ` Call to undefined function Sentry\init()`.
It does not matter where i place the call, i m always getting the same error. sentry exists in the vendor and is well referenced in the vendor autoload.php . there is no custom autoload.php

## Steps to Reproduce
follow the doc described here: https://docs.sentry.io/platforms/php/.

### What you expected to happen
No errors, be able to use sentry SDK as described in the documentation

**Comment by ste93cry** [comment]
It may be a stupid answer, but please ensure that you prefix the `Sentry` namespace with a backslash if your code is namespaced

**Comment by tibz7** [comment]
Yes I tried that too

**Comment by stayallive** [comment]
You can double check the installation succeeded by checking your `vendor` folder and seeing if there is a `sentry` folder in there, it's possible `composer require sentry/sdk` failed for some reason and the package was never installed.

And as @ste93cry mentioned trying `\Sentry\init(['dsn' => 'qwerty']);` is also a good idea, but I think you already tried that 👍

**Comment by tibz7** [comment]
@stayallive Yes there is something in the `vendor` and i tried with the `\` too

**Comment by stayallive** [comment]
In that case are you calling `\Sentry\init(['dsn' => 'qwerty']);` after your `require 'vendor/autoload.php'`? The composer autoloader needs to be loaded first before the class is available.

**Comment by tibz7** [comment]
Yes this is how i call it actually
```

// get namespaces from Composer
$map = include __DIR__ . '/../../vendor/composer/autoload_namespaces.php';
$psr4 = include __DIR__ . '/../../vendor/composer/autoload_psr4.php';
$map = array_merge($map, $psr4);

foreach ($map as $k => $values) {
    $k = trim($k, '\\');
    if (!isset($namespaces[$k])) {
        $dir = '/' . str_replace('\\', '/', $k) . '/';
        //$namespaces[$k] = implode($dir . ';', $values) . $dir;
        $namespaces[$k] = implode(';', $values);
    }
}
$loader->registerNamespaces($namespaces);
$classMap = include __DIR__ . '/../../vendor/composer/autoload_classmap.php';
$loader->registerClasses($classMap);

$loader->register();
Sentry\init(['dsn' => 'https://12345' ]);

```

**Comment by ste93cry** [comment]
Is there any reason about why you don't simply do `require_once __DIR__ . '/../../vendor/autoload.php'`?

**Comment by tibz7** [comment]
So if I do the require.... It works!
But we use this way for some performance reasons. it reduces drastically
the loading time (up to 3x).
Is there a way to combine both ?
Sorry, I'm not an PHP expert

**Comment by stayallive** [comment]
I have no clue why or what your auto loading code is doing but I don't think this is how composer intended it to work.

Maybe the author of the custom auto loader code you are using can take a look at it to see why it's unable to load that function?

**Comment by ste93cry** [comment]
>So if I do the require.... It works!

It works because in your code you are not loading the `vendor/composer/autoload_files.php` file which in turn would load our `functions.php` file where `Sentry\init()` is defined. Do that and everything should be fine, but be aware that as @stayallive said this is not how Composer is meant to be used for autoloading, if you want to optimize the loading then there are some features specifically tailored for that job, e.g. the `--optimize-autoloader` flag of the Composer CLI. You can take a look at [the documentation](https://getcomposer.org/doc/articles/autoloader-optimization.md) to see what you can do to improve the situation without relying on all that custom code which may be also breaking other things that you didn't notice yet

**Comment by tibz7** [comment]
Thank you for the help. I asked the author, and he said it was for
optimization and he did not know about the --optimize-autoloader. Seems
it's a new feature....
However I don't find either this option when I run composer.phar, even
though I have version 2.0.8.
When i asked the author to run try to install sentry on his Vagrant machine
he kept getting this error during installation, could that be related?
```

Syncing devize/closure-compiler (dev-master 2fc9ffc) into cache
- Syncing fabfuel/prophiler (2.0.0) into cache
- Syncing tpyo/amazon-s3-php-class (dev-master 62ae202) into cache
- Installing composer/package-versions-deprecated (1.11.99.1): Extracting
archive
Plugin initialization failed
(include(/var/www/vendor/composer/package-versions-deprecated/src/PackageVersions/Installer.php):
failed to open stream: No such file or directory), uninstalling plugin
- Removing composer/package-versions-deprecated (1.11.99.1)
Install of composer/package-versions-deprecated failed
[RuntimeException]Could not delete
/var/www/vendor/composer/package-versions-deprecated/src:

```

**Comment by ste93cry** [comment]
>Seems it's a new feature....

No, it's there since a very long time 😉 

>When i asked the author to run try to install sentry on his Vagrant machine he kept getting this error during installation, could that be related?

If the installation aborts because of an error of course the autoloader won't be generated. Anyway, for issues with Composer you may find more support asking around on Stackoverflow

**Comment by ste93cry** [comment]
I'm closing the issue because solutions have been provided and further support is out of scope for this repo
