### ISSUE TITLE
Is the "logger" option deprecated?

### ISSUE THREAD

**Issue by AndreKR** [getsentry/sentry-php#1162]
Since there is no specific list of available configuration options in the docs, I'm going by `Options::configureOptions()`. There's still an option `"logger"`, but setting it has no effect any more.

It's also not mentioned in the docs, but that doesn't seem to mean anything, `"prefixes"` isn't mentioned in the docs either. However, it kind of makes sense that `logger` would be deprecated, because Sentry encourages having separate projects for the different loggers (SDKs).

**Comment by ste93cry** [comment]
>Since there is no specific list of available configuration options in the docs

The list is [here](https://docs.sentry.io/platforms/php/configuration/options/), but you're right in saying that not all options are documented, be them specific of the SDK or not. I don't know the reason about why some options shared across all SDKs are not documented (e.g. `logger`), but we can definitely improve the situation and a contribution is always welcome

>There's still an option `"logger"`, but setting it has no effect any more
>However, it kind of makes sense that `logger` would be deprecated

As far as I know this option is not deprecated, and it's definitely used [here](https://github.com/getsentry/sentry-php/blob/b1c8679177f0f869ae5b177e9d29fc6007bff121/src/Serializer/PayloadSerializer.php#L56)

**Comment by AndreKR** [comment]
> As far as I know this option is not deprecated, and it's definitely used [here](https://github.com/getsentry/sentry-php/blob/b1c8679177f0f869ae5b177e9d29fc6007bff121/src/Serializer/PayloadSerializer.php#L56)

Well, that's the `logger` field of the `Event`, which may or may not be conceptually different from the `logger` *option*. The option is not copied into the `Event` any more (in 1.x it was).

**Comment by ste93cry** [comment]
Oh I see, I didn't notice that the value was not coming from the options but rather from the event. It's definitely a bug and not something wanted so a contribution is welcome to fix it

**Comment by AndreKR** [comment]
I'm afraid I won't be able to do it because I'm still lacking a firm grasp of how data flows among Hub, Scope, Client, Integration and Options.
