### ISSUE TITLE
Upgrade ocramius/package-versions

### ISSUE THREAD

**Issue by simPod** [getsentry/sentry-php#1178]
Having `ocramius/package-versions` require to v1 prevents using `roave/you-are-using-it-wrong:^1.8` which allows PHP 8.

https://github.com/getsentry/sentry-php/blob/db8a322f87983bb4f3cd8db01f9a9a593efe72a3/composer.json#L29

In order not to lock consumers to PHP 7 we should upgrade `ocramius/package-versions` here which would also require raising min required PHP version to v7.4

_I guess_

**Comment by Jean85** [comment]
#1170 already tries to solve this by removing the requirement completely, but it's currently blocked by a CI issue.
