### ISSUE TITLE
Monolog handler does not report $record['context'] other than $record['context']['exception']

### ISSUE THREAD

**Issue by bits4breakfast** [getsentry/sentry-php#1179]
👋  - I've just (finally) upgraded the SDK to the latest version straight from the legacy one (1.8) and to my surprise the Monolog handler does not copy anything from the `$record` context other than the exception - everything else is discarded. I don't know if this is a known issue/conscious choice but I couldn't find any context (no pun intended) around that. I can eventually make changes myself however I wanted to make sure this was not something removed in the past.

Cheers

**Comment by Jean85** [comment]
Yes this was intentional. See discussions in #848 for explanations.
