### ISSUE TITLE
Track errors occurring before Sentry initialisation?

### ISSUE THREAD

**Issue by jhogervorst** [getsentry/sentry-php#1182]
I just ran into a situation where some request exceeded the [`max_input_vars` limit](https://www.php.net/manual/en/info.configuration.php#ini.max-input-vars). According to the docs:

>  If there are more input variables than specified by this directive, an `E_WARNING` is issued, and further input variables are truncated from the request.

However, I did not see this warning in Sentry. I presume this is because the warning already occurred before my script got executed and Sentry got initialised, so Sentry never had the chance to catch it.

**It would have been very helpful if this error was tracked by Sentry. And I imagine there could be other kinds of errors occurring before scripts start executing, that could also be helpful to track.**

Maybe Sentry could (get an option to) track errors before it is initialised, using something like [`error_get_last()`](https://www.php.net/manual/en/function.error-get-last.php)?

I’m not sure whether this could/would work, but I just want to explain this situation and how it would have been helpful if Sentry would have tracked this.

**Comment by ste93cry** [comment]
Sentry tracks errors as soon as you call the global `init()` function. What prevents you from doing that earlier?

**Comment by jhogervorst** [comment]
@ste93cry The error which I ran into is related to the parsing of the HTTP request. I expect it already happens before the PHP script starts execution. So it doesn’t matter how early I initialise Sentry, it will always be too late to catch these kind of errors.
