### ISSUE TITLE
User Feedback // Last eventId

### ISSUE THREAD

**Issue by ChriStef** [getsentry/sentry-php#1186]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
3.1.4

### Steps to Reproduce

1. What = https://docs.sentry.io/platforms/php/enriching-events/user-feedback/
2. you = Info that php code Sentry\State\Hub::getCurrent()->getLastEventId();
3. did = but ended to an error Call to undefined method Sentry\State\Hub::getCurrent()

### Expected Result

What you thought would happen = I think the info is wrong!!!

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs? = img
![Screenshot_86](https://user-images.githubusercontent.com/35404268/107982986-b7596500-6fcd-11eb-8ec9-768cd17e20fb.jpg)

reporting back to my sentry.io issue dashboard!!! What do you think? Installation was = composer require sentry/sdk

Im missing some steps? or wiki page is not updated  with current state? Please help me, I want to use the user feedback.

**Comment by stayallive** [comment]
This looks to be outdated indeed and incorrect unfortunately.

So you can move forward quickly, this is the correct method when using 3.x:

```php
\Sentry\SentrySdk::getCurrent()->getLastEventId();
```

I am keeping this issue open so I won't forget to fix the documentation with correct code examples.

**Comment by ChriStef** [comment]
Thanks for the quick insides! 

I should wait the newest docs, your code snippet isnt working as well :/

**Comment by stayallive** [comment]
Can you tell me what isn't working about the snippet I sent? Same error,  another error or no ID?

**Comment by ChriStef** [comment]
Yes of course = Same undefined error!

**Comment by stayallive** [comment]
Yep you are absolutely right 🤦  sorry, I copied and pasted too much...

```php
\Sentry\SentrySdk::getCurrentHub()->getLastEventId();
```

The above is confirmed to be the correct one 👍

**Comment by ChriStef** [comment]
I think this is the good one :)

**Comment by stayallive** [comment]
I am keeping this issue open so I won't forget to fix the documentation with correct code examples, it will be closed after I have a PR open to fix the docs, glad you can continue at least!
