### ISSUE TITLE
Suppressed PHP warning is send to Sentry

### ISSUE THREAD

**Issue by bobvandevijver** [getsentry/sentry-php#1195]
### Environment

**How do you use Sentry?**
Self hosted 21.2.0

**Which SDK and version?**
```
bobvandevijver@webdev:/var/www/dev$ composer show | grep sentry
sentry/sdk                              3.1.0     This is a metapackage shipping sentry/sentry with a recommended HTTP client.
sentry/sentry                           3.2.0     A PHP SDK for Sentry (http://sentry.io)
sentry/sentry-symfony                   4.0.3     Symfony integration for Sentry (http://getsentry.com)
```

We're using PHP 7.3.27 on Debian 10. The issue started after upgrading to v4 of the `sentry/sentry-symfony`. This upgrade included:

| Package | Old version | New version |
| -- | -- | -- |
| sentry/sdk | 2.2.0 | 3.1.0
| sentry/sentry | 2.5.2 | 3.2.0
| sentry/sentry-symfony | 3.5.3 | 4.0.3 |

### Steps to Reproduce

Symfony tries to silence an include warning during the HTTP Kernel initialization, as the container cache is allowed to not exist. If that is the case, the container variables is reset and the application should continue without any notification whatsoever. The error reporting is restored directly after the "critical" part in the finally handler.

See the [Kernel](https://github.com/symfony/symfony/blob/fc016ddd922c955ccf4ea342110c32a4da5c9df4/src/Symfony/Component/HttpKernel/Kernel.php#L443) class implementation of Symfony, line 443 for the error level adjustment, line 469 for the line that generates the warning and the finally block on 480-482 that restores the error reporting.

This means that #1183 and #1087 are probably related to this particular issue.

For this particular case the line marked as [broken code](https://github.com/getsentry/sentry-php/pull/1087/files#diff-1b2bb2c6377ff609b2d252005cc6151091a6a904b51993bb607120b3e5dd62c2L268-R268) in #1183 was actually doing its job:

![image](https://user-images.githubusercontent.com/1835343/110535144-2f740000-8120-11eb-9c8e-ee6c0558bef3.png)

So, a small reproduction would be:

```php
$errorLevel = error_reporting(\E_ALL ^ \E_WARNING);
try {
  include 'non-existing-file.php';
} finally {
  error_reporting($errorLevel);
}
```

### Expected Result

The error should not be logged into Sentry, as it is suppressed using an explicit `error_reporting` call.

### Actual Result

But is isn't...

![image](https://user-images.githubusercontent.com/1835343/110536718-15d3b800-8122-11eb-8bec-e0f06df12f34.png)

**Comment by Jean85** [comment]
The PHP error reporting doesn't actually influence what Sentry reports, the SDK has a dedicated `error_types` option with the same bitmask usage to do that; and the silenced errors interception are meant for the `@` operator. 

I don't know if we should use the same interception for those cases too, but in any way those error could be reported anyway if you have `capture_silenced_errors` set to `true.

As for the Symfony specific situation, is that happening during cache warmup? I didn't encounter this issue since I warm it up in the build and not in prod...

**Comment by bobvandevijver** [comment]
Using the `error_types` is no valid solution here, as the purpose is to temporarily block only the warning emitted here, and not the errors. See line 442 of the Kernel class:

```
// Silence E_WARNING to ignore "include" failures - don't use "@" to prevent silencing fatal errors
```

And I actually do not see any reference to the `error_types` option in the Sentry error handler, but that is probably checked elsewhere then.

`capture_silenced_errors` is not set, so it defaults to `false`, which is confirmed by the Sentry screenshot as an `ErrorException` is reported instead of a `SilencedErrorException`.

This indeed happens during the `cache:clear` command. It didn't happen with the previous Sentry version, so at least the behaviour changed since then.

> The PHP error reporting doesn't actually influence what Sentry reports

But if this is the case, then why is the PHP `error_reporting` function used to determine whether it is a silenced error? Currently, on PHP 7 it only checks for the value 0, which means that only when all error reporting has been disabled, it is marked as silenced. I guess bringing back the `error_reporting() & $level` would already solve this issue as your then actually checking whether the configured PHP bitmask marks the error passed to the error handler as being silenced or not...

**Comment by Jean85** [comment]
> And I actually do not see any reference to the error_types option in the Sentry error handler, but that is probably checked elsewhere then.

Yes, that's checked afterwards, in the integration: https://github.com/getsentry/sentry-php/blob/f35ffc85a383c22f82098a82ba283a73c0267fa0/src/Integration/ErrorListenerIntegration.php#L38-L40

> But if this is the case, then why is the PHP error_reporting function used to determine whether it is a silenced error? Currently, on PHP 7 it only checks for the value 0, which means that only when all error reporting has been disabled, it is marked as silenced. I guess bringing back the error_reporting() & $level would already solve this issue as your then actually checking whether the configured PHP bitmask marks the error passed to the error handler as being silenced or not...

That's possibly true. As you correctly pointed out, #1183 and #1087 changed this behavior, making those errors no longer silenced. IMO we should revert it, but I would like to ask @ste93cry & @stayallive for their opinion.

**Comment by stayallive** [comment]
Hi @bobvandevijver,

> But if this is the case, then why is the PHP error_reporting function used to determine whether it is a silenced error?

The current definition of a silenced error is this in the Sentry SDK: 

https://github.com/getsentry/sentry-php/blob/f35ffc85a383c22f82098a82ba283a73c0267fa0/src/Exception/SilencedErrorException.php#L7-L10.

When the Sentry client is initialised the value of `error_reporting()` is copied and determines what is being reported to Sentry regardless of what happens to the `error_reporting()` value afterwards.

There has been a serie of changes that led to this behaviour unfortunately but right now the `error_types` is set to a static value and we should change this to use `error_types()` whenever it's checking what errors to allow to be reported unless the option is set by the user in the code @Jean85 mentioned. This would solve your issue and some concerns raised by my fixes of the silenced error detection code.

**Comment by Jean85** [comment]
@stayallive your proposed fix would only work if the `error_types` is not already used by the user. IMHO we should revert to the previous behaviour, which contradicts the comment linked by you: apart from `@` silenced errors, errors below the `error_reporting()` limit were marked as silenced too by the Sentry SDK.

**Comment by bobvandevijver** [comment]
Sounds like a valid solution to me! I just tested it in my environment with the changeset below, and at least for my described use case it works as I would expect.

```diff
diff --git a/src/Options.php b/src/Options.php
index 8b5c5bd..486b4fc 100644
--- a/src/Options.php
+++ b/src/Options.php
@@ -411,7 +411,7 @@ public function setTags(array $tags): void
      */
     public function getErrorTypes(): int
     {
-        return $this->options['error_types'];
+        return $this->options['error_types'] ?? error_reporting();
     }

     /**
@@ -716,7 +716,7 @@ private function configureOptions(OptionsResolver $resolver): void
                 return $event;
             },
             'tags' => [],
-            'error_types' => error_reporting(),
+            'error_types' => null,
             'max_breadcrumbs' => self::DEFAULT_MAX_BREADCRUMBS,
             'before_breadcrumb' => static function (Breadcrumb $breadcrumb): Breadcrumb {
                 return $breadcrumb;
@@ -748,7 +748,7 @@ private function configureOptions(OptionsResolver $resolver): void
         $resolver->setAllowedTypes('server_name', 'string');
         $resolver->setAllowedTypes('before_send', ['callable']);
         $resolver->setAllowedTypes('tags', 'string[]');
-        $resolver->setAllowedTypes('error_types', ['int']);
+        $resolver->setAllowedTypes('error_types', ['null', 'int']);
         $resolver->setAllowedTypes('max_breadcrumbs', 'int');
         $resolver->setAllowedTypes('before_breadcrumb', ['callable']);
         $resolver->setAllowedTypes('integrations', ['Sentry\\Integration\\IntegrationInterface[]', 'callable']);
```

**Comment by stayallive** [comment]
Cool. I'll brew up an PR to make this change. I think this is a good solution to keep as many options open as possible 👌
