### ISSUE TITLE
Errors and performance tracing doesn't seem to work together well

### ISSUE THREAD

**Issue by IMN-MichaelL** [getsentry/sentry-php#1203]
### Environment

PHP: 7.2.24-1
Ubuntu: 16.04

**How do you use Sentry?**
self-hosted/on-premise: Sentry 21.3.0

**Which SDK and version?**
sentry/sdk                           3.1.0
sentry/sentry                        3.2.0
Managed by composer

Sentry init (based on documentation):
```
Sentry\init(array(
    'dsn' => $config->sentry->dsn,
    'traces_sample_rate' => 1.0,
    'traces_sampler' => static function (Sentry\Tracing\SamplingContext $context): float {
        if (false !== strpos($context->getTransactionContext()->getName(), 'health')) {
            // Discard transactions that have 'health' in their name
            return 0.0;
        }
        // Sample rate for all other transactions
        return 1.0;
    },
));
```

### Steps to Reproduce

There are 2 different scenarios, caught and uncaught errors. Below I use the example code shown in the documentation for transactions to monitor performance.

1. This is the uncaught error code:
```
$transactionContext = new \Sentry\Tracing\TransactionContext();
$transactionContext->setName('Testing cli error');
$transactionContext->setOp('test');
$transaction = \Sentry\startTransaction($transactionContext);

sleep(2);
throw new \Exception('this is a test');

$transaction->finish();
```

2. This is the caught error code:
```
$transactionContext = new \Sentry\Tracing\TransactionContext();
$transactionContext->setName('Testing cli error');
$transactionContext->setOp('test');
$transaction = \Sentry\startTransaction($transactionContext);

sleep(2);
try {
    throw new \Exception('this is a test');
} catch (\Exception $e) {
    \Sentry\captureException($e);
}

$transaction->finish();
```

### Expected Result

In both scenarios I would expect that the transaction would be aware of the exception and both reflect it in the failure rate for the transaction and related issue list. Perhaps there is something I am not doing correctly?

### Actual Result

1. With uncaught errors the transaction is never completed and sentry is entirely unaware of it.
2. With the caught error the transaction is sent but is unaware of any errors.

**Comment by Jean85** [comment]
If you're not using any official integration or you don't have any way to catch the exception at a higher level, it's not Sentry's fault, it's normal PHP behavior: an uncaught exception interrupts the flow abruptly, and we don't have any way to handle this differently.

As for transactions unaware of errors, it was already reported and discussed in https://github.com/getsentry/sentry-symfony/issues/462#issuecomment-791370494, and according to @stayallive it should be working fine thanks to https://github.com/getsentry/sentry-php/blob/d9fdc40728dc58936f59e9b2e1104163fdcafe24/src/State/Scope.php#L355-L358

**Comment by IMN-MichaelL** [comment]
That is correct, I am not using any integrations. I understand that exceptions break the flow abruptly, but due to the fact that Sentry is aware of said uncaught exceptions they are clearly being caught by the Sentry client (via ErrorHandler.php). It just seems odd that it is unaware of an ongoing transactions, hence it being unexpected.

Ok, I missed that issue when I was looking to see if someone had this problem. Looking over that issue and doing some testing these are my following observations:

```
$transactionContext = new \Sentry\Tracing\TransactionContext();
$transactionContext->setName('caught cli error');
$transactionContext->setOp('test');
$transaction = \Sentry\startTransaction($transactionContext);

sleep(2);
try {
    throw new \Exception('caught error');
} catch (\Exception $e) {
    \Sentry\captureException($e);
}

$transaction->finish();
```
The above error is stored in sentry but without a trace id.

```
$transactionContext = new \Sentry\Tracing\TransactionContext();
$transactionContext->setName('caught cli error adding trace');
$transactionContext->setOp('test');
$transaction = \Sentry\startTransaction($transactionContext);

\Sentry\configureScope(function (\Sentry\State\Scope $scope) use ($transaction): void {
    $scope->setSpan($transaction);
});

sleep(2);
try {
    throw new \Exception('caught error adding trace');
} catch (\Exception $e) {
    \Sentry\captureException($e);
}

$transaction->finish();
```
The above error is stored in sentry with a trace id. I am able to use the search by trace button to find the associated trace (of course that link is missing in the other direction).


Just to see what happens, I ran an additional with uncaught exceptions:
```
$transactionContext = new \Sentry\Tracing\TransactionContext();
$transactionContext->setName('uncaught cli error adding trace 3');
$transactionContext->setOp('test 2');
$transaction = \Sentry\startTransaction($transactionContext);

\Sentry\configureScope(function (\Sentry\State\Scope $scope) use ($transaction): void {
    $scope->setSpan($transaction);
});

sleep(2);

throw new \Exception('uncaught error adding trace 3');

$transaction->finish();
```
The above code results in the error in sentry having a trace id but when searching by trace no transactions are listed. That leads me to believe open transactions are not finished when handling an uncaught exception, perhaps that is a design decision?

So it appears the issue is that scope is not made aware of the span correctly, meaning the code snippet you sent doesn't get past the null check.

Let me know if there is any more details I can provide to help get to the bottom of this.

Thank you!

**Comment by IMN-MichaelL** [comment]
Also one more thing, as a work around for transactions being unaware of errors, I am using the setStatus function on the transaction object passing in `SpanStatus::internalError()`. That will at least allow the failure rate on transactions to be more accurate.

**Comment by ste93cry** [comment]
>The above error is stored in sentry but without a trace id

This is expected and by design as far as I know because `startTransaction()` does not set the transaction on the current scope, so Sentry has no way of keeping track of it

>That leads me to believe open transactions are not finished when handling an uncaught exception, perhaps that is a design decision?

Correct, unfinished transactions (and spans) are not sent and this is by design as far as I know. However, the fact that we don't finish a transaction when a fatal error or an uncaught exception occurs could be considered a bug indeed. I'm not sure how other SDKs treat this case, but we should clearly align the behaviour to them. @bruno-garcia can you please tell us what is the expected behaviour?

**Comment by IMN-MichaelL** [comment]
> This is expected and by design as far as I know because `startTransaction()` does not set the transaction on the current scope, so Sentry has no way of keeping track of it

So forgive me if I am mistaken, but upon a cursory look, startTransaction() is called on the currentHub just like ConfigureScope(). So the fix in my mind would be set the scope in the automatically in the Hub->startTransaction function: https://github.com/getsentry/sentry-php/blob/4f6f8fa701e5db53c04f471b139e7d4f85831f17/src/State/Hub.php#L222


> Correct, unfinished transactions (and spans) are not sent and this is by design as far as I know. However, the fact that we don't finish a transaction when a fatal error or an uncaught exception occurs could be considered a bug indeed. I'm not sure how other SDKs treat this case, but we should clearly align the behaviour to them. @bruno-garcia can you please tell us what is the expected behaviour?
As far as I can tell the Javascript Sentry library handles this correctly. Transactions are correctly aware of errors and vice versa. The fact that in the Performance section has a failure rate statistic (which would be very helpful) suggests that regardless of errors, the transaction should be finished and sent to Sentry. So it really wouldn't make much sense as a design decision and definitely suggests it's a bug.

I hope this can be resolved since the functionality is very useful.

**Comment by ste93cry** [comment]
>So the fix in my mind would be set the scope automatically in the Hub->startTransaction function

Yes, but as I said as far as I know no SDK does this and the JS SDK also has an [example](https://github.com/getsentry/sentry-docs/blob/accc6ca4b3f6c37de86fddcab4bbe265dd16240f/src/includes/performance/add-spans-example/javascript.mdx) where they show that the transaction must be bound to the span manually, so I'm pretty sure it's a by-design thing that we don't have to change.

>So it really wouldn't make much sense as a design decision and definitely suggests it's a bug

I tend to agree, but before asking to code or coding myself the bugfix I want to be sure to avoid all of us to lose time with something not meant to work like that

**Comment by IMN-MichaelL** [comment]
> where they show that the transaction must be bound to the span manually, so I'm pretty sure it's a by-design thing that we don't have to change.

I see what you mean from that example. `// set the transaction on the scope so it picks up any errors` Wouldn't you always want that functionality? It's rather bizarre in my opinion to not just default that. It would probably make the most sense to have that as a parameter or a config option when creating the transaction honestly.

I will also add that I haven't done much with the Javascript SDK yet, but the default functionality just seems to work.

**Comment by ste93cry** [comment]
>Wouldn't you always want that functionality?

My answer is yes, and to be honest I don't have any clue about the reason of why the transaction is not set on the span inside `startTransaction()`, but if I have to bet I would say that it's done to avoid the overriding any existing transaction.

>I will also add that I haven't done much with the Javascript SDK yet, but the default functionality just seems to work

It works because the JS SDK enable some integrations out-of-the-box that make the tracing work for common things, but this is possible because the APIs of the browser are standard and therefore you have an expectation of what you are gonna work with. In PHP instead, users can use any library/framework/package out of here and supporting all of them would simply put too much burden on maintenance of this package.

**Comment by IMN-MichaelL** [comment]
> but if I have to bet I would say that it's done to avoid overriding any existing transaction.

I was just thinking about that actually. I guess the question I then have is, should you ever have more than one transaction happening at a time? I haven't actually tried doing that. My understanding was that you would start a transaction and then use spans attached to said transaction to monitor anything happening within the transaction context. I would agree that it gets a bit tricky because if you do allow multiple simultaneous transactions then what I am asking for would result in overriding existing transactions. If you aren't meant to have multiple simultaneous transactions then it wouldn't be an issue but I would also make sure the SDK doesn't allow it.

Thinking a bit more about this I have actually had multiple simultaneous spans going to achieve a tree of information (which I had to write some code for since the parent span id was always the transaction). A transaction is just a span but could still be treated differently to avoid multiple transactions at the same time. That said, I am sure there is a good reason to support multiple transactions at once. Could support an array of spans though.


> but this is possible because the APIs of the browser are standard and therefore you have an expectation of what you are gonna work with

That is a very fair point, thank you.

**Comment by Jean85** [comment]
I generally agree that setting the transaction in the Scope automatically should be the default, this is the second time that I see someone stumbling on this without realizing the missing piece.

But I also agree that we need direction on this: @bruno-garcia or @HazAT can you weigh in here?

As for sending out incomplete transactions, I think it's too dangerous to do it here in the base SDK, because it would mean sending stuff out while in "error mode" inside an error handler and with too much "unknown unknowns"; it would be instead easier to achieve in an official integration, where we could take more stuff for granted, due to the presence of a known framework.

**Comment by IMN-MichaelL** [comment]
> I generally agree that setting the transaction in the Scope automatically should be the default, this is the second time that I see someone stumbling on this without realizing the missing piece.

I mean, besides being something one would expect to be automatic, the documentation doesn't seem to address it at all. Perhaps until something is done about it the documentation should be updated to reflect this?

> As for sending out incomplete transactions, I think it's too dangerous to do it here in the base SDK, because it would mean sending stuff out while in "error mode" inside an error handler and with too much "unknown unknowns"; it would be instead easier to achieve in an official integration, where we could take more stuff for granted, due to the presence of a known framework.

I guess that is fair but perhaps there could be a configuration option? I don't see any harm giving developers the choice of whether it's too dangerous or not. You can give a warning about it being dangerous. It's worth noting that the trace data does add more information that can be useful in tracking down why an error happens.
