### ISSUE TITLE
Current version of Sentry 1.x cannot be installed on PHP 8; old versions of 1.x can however

### ISSUE THREAD

**Issue by mfb** [getsentry/sentry-php#1207]
### Environment

PHP 8.x with Sentry PHP 1.x

### Steps to Reproduce

Attempt to install current version of Sentry PHP 1.x on PHP 8.x, for example sentry/sentry:^1.7.0

### Expected Result

The current version of Sentry 1.x can be installed.

### Actual Result

`sentry/sentry[1.7.0, ..., 1.11.0] require php ^5.3|^7.0 -> your php version (8.0.3) does not satisfy that requirement.`

Note, older versions of Sentry PHP can be installed on PHP 8, for example `composer require sentry/sentry:^1` will install sentry/sentry 1.6.2

I realize that Sentry 1.x is ancient history, however it would be useful if legacy apps could install the current version on PHP 8, as a "bridge" until they are upgraded to support Sentry SDK 3.x

**Comment by stayallive** [comment]
That has most likely to do with that we used to have incorrect version constraint (`>=5.2.4`) that allowed too much versions.

> Please note that the 1.x branch of the Sentry PHP SDK is no longer actively maintained and will only receive bug-fix and security updates.

I don't think we will be able to make this happen, as far as I know 1.x was never tested with 8.x and it would require us to dust it of just for 8.x compat which probably requires some fixes too.

I'm leaning towards, just upgrade when you upgrade to 8.x, 1.x is also not compatible with the new API in newer versions of sentry.io (and up-to-date self-hosted instances) so the update would probably come sooner or later anyway.

**Comment by ste93cry** [comment]
I agree with @stayallive, we don't even have a working CI for that version as Travis has been replaced with GitHub Actions and we never did the switch on that branch. Any work on that version is for basically no benefit at all, we don't have the resources to do it and I'm pretty sure noone wants to put his time to do it. But, indeed, we should at least update the README to say that that version is no longer maintained, not even for security fixes.

**Comment by stayallive** [comment]
@ste93cry that quote is from the readme and also copied in the 1.11.0 release notes even 👌 so we're good there.

**Comment by mfb** [comment]
I guess I was imagining that a new but unsupported release could be made, just tweaking the composer.json to allow it to be installed.  But if not, then the work-around would be to not install the library via composer..

**Comment by ste93cry** [comment]
>so we're good there.

The note is saying that that version is receiving bug-fix and security updates while it's not true, so the note is wrong and should be adjusted

>I was imagining that a new but unsupported release could be made, just tweaking the composer.json to allow it to be installed

There is nothing preventing us to do it, but I don't think it's the correct thing to do: I see highly unlikely that that version works on PHP 8, even though maybe at a first glance it may look like it does

>the work-around would be to not install the library via composer

The time it will take to find and test workarounds to install the old library on PHP 8 in my opinion may be spent in better ways, but this is my opinion :wink:

**Comment by mfb** [comment]
Wel,l it appears to be working fine on PHP 8 so far.

Currently the older release branches of https://www.drupal.org/project/raven - which require Sentry SDK 1.x - are running on 2524 different websites, which is far more than the number of sites using the current release branches, which require Sentry SDK 3.x.  Thus is the nature of open source libraries for websites - they tend to be integrated by developers and then stick around until the site is thoroughly rearchitected, or disappears...

**Comment by ste93cry** [comment]
>it appears to be working fine on PHP 8 so far

We had to change some code in the error handler to make it work on PHP 8, so I'm pretty sure that with such an old version you would have subtle bugs and/or things not working as expected. If there was no need to make those changes we would not have done them 😅 Anyway, as I said, that version is EOL, I'm sorry

**Comment by mfb** [comment]
In this case, Sentry's error handler isn't used - https://www.drupal.org/project/raven disables it - so I don't think we will run into this problem. Our existing integration tests (which includes handling fatal errors and other things) do all pass on PHP 8.

**Comment by ste93cry** [comment]
>In this case, Sentry's error handler isn't used

I didn't know, I'm sorry. However, we're not going to change our minds about releasing a new compatible version of `1.x`, not least because it would mean "encouraging" people to use an old SDK, which in turn means that if people can use it on new versions of PHP and they find bugs or want new features, they will come here to ask for support. Please try to see it from the perspective of us OSS maintainers and the consequences for us if we decide to take such choice. I can feel and understand your frustration, but that's it

**Comment by mfb** [comment]
Just to be clear, I am not frustrated at all, it was just a suggestion to allow existing integrations to keep working.  I definitely think it's a very good idea to no longer fix bugs or otherwise support this branch, so updating the README is a good idea.

**Comment by ste93cry** [comment]
>I am not frustrated at all

Sorry, said like this it sounds a bit rude and that was not my intention. What I meant was that I could understand if you didn't like the decision. Hopefully, all is good 👍 

>updating the README is a good idea

Yea, we will take care of it ASAP
