### ISSUE TITLE
Allow integer release

### ISSUE THREAD

**Issue by sc0rp10** [getsentry/sentry-php#1209]
Which SDK and version?

`php sentry/sentry-symfony:^4.0`

### Steps to Reproduce

1. Set a numeric `release` value

### Expected Result

Working reporting

### Actual Result

Error `The option "release" with value 12345 is expected to be of type "null" or "string", but is of type "int".`

It would be nice, if we can use integer release identificators - this might be numeric application version for example.

**Comment by sc0rp10** [comment]
Of course, I can make a PR with this changes myself. Dear maintainers, what do you think?

**Comment by Jean85** [comment]
Well, as a workaround, you can surely pass `'123456'` in...

**Comment by ste93cry** [comment]
As far as I know a release version must be a string and the server does not accept a number, but I didn't try it. We could automatically cast a number to a string in the Symfony SDK, but I don't think we should allow to set a number in the options of the SDK. Typehinting exists for a reason, after all.

**Comment by Jean85** [comment]
I agree with @ste93cry on this one.
