### ISSUE TITLE
[README] Quick Start doesn't work

### ISSUE THREAD

**Issue by sirian** [getsentry/sentry-php#1212]
### Steps to Reproduce

```bash
$ composer require sentry/sentry php-http/curl-client
$ php test.php
```

test.php
```php
<?php
require_once './vendor/autoload.php';

\Sentry\init(['dsn' => 'https://ffffffffffffffffffffffffffffffff@sentry.io/1']);
```

### Actual Result

![image](https://user-images.githubusercontent.com/897643/115153943-0cbefa80-a081-11eb-817b-730466a44d03.png)

**Comment by Jean85** [comment]
You're probably right; we also ditched the curl client some time ago because it had multiple issues. We could probably replace that indication with an equivalent of what we suggest in `sentry-sdk`.

**Comment by sirian** [comment]
`composer require sentry/sentry` doesn't work at all. What if I want to use only some classes from this package and not use \Sentry\init at all? Why I need to install additional http packages?

![image](https://user-images.githubusercontent.com/897643/115604380-f8ca0180-a2e9-11eb-85c1-f12a8049d3e8.png)

**Comment by Jean85** [comment]
Because this library requires an HTTP transport, and we're not providing it out of the box, but instead we require those meta-packages.

If you don't want them, you can declare that your project `provides` them in your `composer.json`, but if it will break anyway, you'll be on your own.
