### ISSUE TITLE
Performance penalty

### ISSUE THREAD

**Issue by sirian** [getsentry/sentry-php#1213]
`\Sentry\init()` has huge overhead. Do you really need to setup `http client` each time? Even if there was no calls captureMessage/captureException? It shoudl be done lazy (on demand). We have huge performance penalty on production.

Simple examples with blackfire report below.  loadClass was called 103 times. You really need this classes during init?
```php
Http\Client\Common\PluginClient
Http\Client\Common\Plugin\AuthenticationPlugin
Http\Client\Common\Plugin\DecoderPlugin
Http\Client\Common\Plugin\ErrorPlugin
Http\Client\Common\Plugin\HeaderSetPlugin
Http\Client\Common\Plugin\RetryPlugin
Http\Discovery\ClassDiscovery
Http\Discovery\Exception\NoCandidateFoundException
Http\Discovery\Exception\PuliUnavailableException
Http\Discovery\Exception\StrategyUnavailableException
Http\Discovery\Psr17FactoryDiscovery
Http\Discovery\Strategy\CommonClassesStrategy
Http\Discovery\Strategy\CommonPsr17ClassesStrategy
Http\Discovery\Strategy\PuliBetaStrategy
Http\Factory\Guzzle\RequestFactory
Http\Factory\Guzzle\ResponseFactory
Http\Factory\Guzzle\StreamFactory
Http\Factory\Guzzle\UriFactory
Sentry\HttpClient\Authentication\SentryAuthentication
Sentry\HttpClient\HttpClientFactory
Sentry\HttpClient\Plugin\GzipEncoderPlugin
Sentry\Serializer\AbstractSerializer
Sentry\Serializer\PayloadSerializer
Sentry\Serializer\RepresentationSerializer
Sentry\Serializer\Serializer
Sentry\StacktraceBuilder
Sentry\Transport\DefaultTransportFactory
Sentry\Transport\HttpTransport
Symfony\Component\HttpClient\CurlHttpClient
Symfony\Component\HttpClient\HttpClient
Symfony\Component\HttpClient\HttplugClient
Symfony\Component\HttpClient\Internal\ClientState
Symfony\Component\HttpClient\Internal\CurlClientState
Symfony\Component\HttpClient\Internal\DnsCache
Symfony\Component\HttpClient\Internal\HttplugWaitLoop
```

test1.php
```php
<?php
require_once __DIR__ . '/../vendor/autoload.php';
echo microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'];
```

test2.php
```php
<?php
require_once __DIR__ . '/../vendor/autoload.php';
\Sentry\init(['dsn' => 'https://ffffffffffffffffffffffffffffffff@example.com/1']);
echo microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'];
```

![image](https://user-images.githubusercontent.com/897643/115154835-8fe24f80-a085-11eb-947e-4db2f6ecd98f.png)

![image](https://user-images.githubusercontent.com/897643/115154849-9e306b80-a085-11eb-9042-b72b0fcca708.png)

**Comment by Jean85** [comment]
The difference is probably huge in your measurement because you're comparing to an "empty" app, which does nothing else.
We're talking about 4ms, it's not that much.
Also, did you measure that with opcache on? And did you dump an optimized autoloader?

**Comment by sirian** [comment]
Our application responses in less than 4-5ms. Sentry (with opcache, optimized autoloader, etc...) adds 1.5-2ms in normal situation.But this time drastically increases when workload get's higher. And LA increases x2-x3 times with one single line - Sentry\init. I will try to create minimal docker example with some bencmark

**Comment by Jean85** [comment]
Are you using any special setup like Swoole, PHP-PM, Roadrunner?

Also, the init leverages an autodiscovery tool for getting the PSR-18 HTTP client automatically, maybe providing the client by hand will reduce the performance hit?

**Comment by sirian** [comment]
> maybe providing the client by hand will reduce the performance hit?

Yes, sure. We already did it a long time ago - we implement RedisSpoolTransport. Instead of making http requests (because there may be bunch of problems like dns resolving, sentry maintainance, etc...), we push events to redis, and then in backgound proceess send them to sentry. 
It'll be great to have at least `CallbackTransport` from the box with easy usage like 
```
$client = new CallbackClient($options, fn($event) => $redis->push(serialize($event)));
SentrySdk::init()->bindClient($client);
```

where callback may return anything instead of PromiseInterface.  Because this is ugly... 

```
class CustomTransport implements TransportInterface 
...
public function send($event) {
    $this->redis->send(serialize($event));
    return new GuzzleHttp\Promise\FulfilledPromise(new \Sentry\Response(ResponseStatus::success(), $event));
}
```

Next, why `PayloadSerializer` marked as `@internal` and `final`? What if I want customize a bit serialization process? I need to copy wholle PaylloadSerializer class? The same applies to `Event`, `Client` classes. IMO `SDK` should be more flexible, and less coupled with other packages. less final classes, less private methods. SDK should be extendable and help developers, instead of giving troubles.
Why sdk depends 100500 http libraries (guzzle, php-http, symfony/http...)?  Why do use promises in `HttpTransportInterface` and `HttpTransport`  if currently you in fact send blocking requests from HttpTransport? `$response = $this->httpClient->sendAsyncRequest($request)->wait();`
<details>
<summary>100500 http libs</summary>

```
  - Installing clue/stream-filter (v1.5.0): Extracting archive
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing php-http/message-factory (v1.0.2): Extracting archive
  - Installing php-http/promise (1.1.0): Extracting archive
  - Installing psr/http-client (1.0.1): Extracting archive
  - Installing ralouphie/getallheaders (3.0.3): Extracting archive
  - Installing symfony/http-client (v5.2.6): Extracting archive
  - Installing guzzlehttp/psr7 (1.8.1): Extracting archive
  - Installing php-http/message (1.11.0): Extracting archive
  - Installing php-http/httplug (2.2.0): Extracting archive
  - Installing php-http/discovery (1.13.0): Extracting archive
  - Installing php-http/client-common (2.3.0): Extracting archive
  - Installing jean85/pretty-package-versions (2.0.3): Extracting archive
  - Installing guzzlehttp/promises (1.4.1): Extracting archive
  - Installing http-interop/http-factory-guzzle (1.0.0): Extracting archive
  ```

</details>

What about sending event after sendind response to client (for example `register_shutdown_function`)? Next what about sending events in batch? this is what the SDK should provide. Instead of annoying problems with install and usage https://github.com/getsentry/sentry-php/issues/1212

At this time i use package `sentry/sentry` (of course as I mentioned in https://github.com/getsentry/sentry-php/issues/1212 - \Sentry\init didn't work at all). Hopefully `SentrySdk::init()->bindClient($client);` works

**Comment by Jean85** [comment]
> Yes, sure. We already did it a long time ago - we implement RedisSpoolTransport.

If you do not want to rely on Sentry.io uptime and cut HTTP issues, you can deploy Relay: https://docs.sentry.io/product/relay/

> Why sdk depends 100500 http libraries (guzzle, php-http, symfony/http...)?

Guzzle is used for promises and PSR-7. 
PHP-HTTP is [HTTPlug](http://httplug.io/), which we leverage to NOT bind the implementation to a specific HTTP client; this reduces the average number of libraries for the end users, because they can reuse the HTTP client of their choice (or none at all, like you).
The Symfony client is the proper PSR-18 that we suggest.

> Why XXX marked as @internal and final?

Because we, as maintainers, we need to reduce the amount of work that we need to do. `final` and `@interal` reduce the API surface covered by SemVer and which could generate breaking changes, reducing our freedom of movement.

> Why do use promises in HttpTransportInterface and HttpTransport if currently you in fact send blocking requests from HttpTransport? $response = $this->httpClient->sendAsyncRequest($request)->wait();
>
> What about sending event after sendind response to client (for example register_shutdown_function)?

We did that in 2.x, and we had a fair share of issues due to that, see #787 #799 #811 #813 
Also, that approach does a fair amount of assumptions on the end user's app, which are not always true.

> What about sending events in batch?

You can implement yourself with a buffered transport. We cannot do it, still because it will require a fair amount of assumptions that we cannot make.

**Comment by sirian** [comment]
Let's continue discussion. Look at this blackfire profile from real project (~60k RPM).
Profile took 20ms, and 25% of this time was spent on initialization of sentry. One half - `Options::__construct`, and the other half - `ClientBuilder`. 

![image](https://user-images.githubusercontent.com/897643/124339171-228a8900-dbb5-11eb-8715-d7db59b2a27e.png)

One problem can be solved - I could write own `TransportFactory`. But second problem worse - because I couldn't extend `final class Options`. And the only way is to copy whole class, put it anythere in project and modify autoload rules.

But then there will be other problems
1. IDE will complain on duplicated classes
2. Code quality tools like php-stan will crash with `PHP Fatal error:  Cannot declare class Sentry\Options, because the name is already in use`
3. Same problems could be with opcache.preload
etc...

So I repeat my advice my requests/wishes
1. Instantiate http client lazy (on demand). It's not needed in 99% of requests. Only when exception occurs
2. Either simplify `Options::__construct` or make it extendable (not final).
3. Make SDK more flexible. For example in `sentry/sentry-symfony` there is no need to resolve options, validate and parse DSN on every request. It should be done only once (when container builds)
4. On the one hand you say `we leverage to NOT bind the implementation to a specific HTTP client; ` but on the other hand you force developers to use Guzzle promises in `TransportInterface`. We doesn't use HTTP client on web servers. It's a very bad practice - you block worker until request finished. And there are ton of problems - RTT between servers, ssl/tls handshaking every time, there could be DNS lag, etc..
Instead of http requests from web servers - we push events in redis queue and then handle it in background.

Example: three lines of code block process for 250ms. 

```
require_once __DIR__ . '/../vendor/autoload.php';
\Sentry\init(['dsn' => 'https://....']);
\Sentry\captureMessage('test');
```

![image](https://user-images.githubusercontent.com/897643/124340574-d47a8300-dbbe-11eb-9274-2b6844223aef.png)

**Comment by ste93cry** [comment]
>three lines of code block process for 250ms

Looking at the last image you attached, it's clearly visible (and expected) that what is taking most of the time is the send of the event. Changing HTTP client, not using promises, whatever, will not change this fact because PHP is not async. If you want to reduce that time either you send the events delaying them somehow (a queue, etc), or there is nothing we can do here to improve your situation.

**Comment by stayallive** [comment]
I do want to add to this discussion that reducing HTTP wait times can be done by deploying [Relay](https://docs.sentry.io/product/relay/getting-started/) inside or closer to your own infrastructure.

There is a little docs for PHP on this [regarding performance monitoring](https://docs.sentry.io/platforms/php/performance/#improve-response-time) but this also works for regular events and can even improve reliability since [Relay](https://docs.sentry.io/product/relay/getting-started/) retries requests in the background instead of having multiple retries done in PHP increasing the request times even more.

So purely for decreasing the HTTP wait time there is nothing we can do inside the PHP SDK (since PHP is not async) as Stefano mentioned, but you can look at [Relay](https://docs.sentry.io/product/relay/getting-started/) to improve the situation.

There are most likely other gains to be had as you pointed out (and we would be thrilled to see PR's for that) but `curl_*` calls are what they are and are required and their execution times depend on the network which is outside of control of the SDK.

**Comment by Jean85** [comment]
I'm not sure if it's 100% feasible, but making the client service in the bundle lazy could be an easy performance win. @sirian can you test it out? You would need to add `lazy: true` to the service definition, and require `symfony/proxy-manager-bridge` (if you don't already).

The only case in which this wouldn't work is if some codepath triggers the client anyway...

And before going there: we can't do the same for the Options because they're used in multiple places.

**Comment by sirian** [comment]
> I'm not sure if it's 100% feasible, but making the client service in the bundle lazy could be an easy performance win. @sirian can you test it out? You would need to add `lazy: true` to the service definition, and require `symfony/proxy-manager-bridge` (if you don't already).
> 
> The only case in which this wouldn't work is if some codepath triggers the client anyway...
> 
> And before going there: we can't do the same for the Options because they're used in multiple places.

![image](https://user-images.githubusercontent.com/897643/124675123-b5cd0280-dec4-11eb-8d34-ea0104173eed.png)

**Comment by sirian** [comment]
@ste93cry 
> Looking at the last image you attached, it's clearly visible (and expected) that what is taking most of the time is the send of the event. Changing HTTP client, not using promises, whatever, will not change this fact because PHP is not async. If you want to reduce that time either you send the events delaying them somehow (a queue, etc), or there is nothing we can do here to improve your situation.

Last screenshot was added to this quote about TransportInterface:

> On the one hand you say we leverage to NOT bind the implementation to a specific HTTP client; but on the other hand you force developers to use Guzzle promises in TransportInterface. We doesn't use HTTP client on web servers. It's a very bad practice - you block worker until request finished. And there are ton of problems - RTT between servers, ssl/tls handshaking every time, there could be DNS lag, etc..

My advice to simplify TransportInterface from
```php
interface TransportInterface
{
    public function send(Event $event): PromiseInterface;
    public function close(?int $timeout = null): PromiseInterface;
}
```

to this

```php
interface TransportInterface
{
    public function send(Event $event);
}
```

**Comment by sirian** [comment]
> I do want to add to this discussion that reducing HTTP wait times can be done by deploying [Relay](https://docs.sentry.io/product/relay/getting-started/) inside or closer to your own infrastructure.

It's not a solution. It doesn't matter which endpoint you will use: **Sending HTTP request from WEB server is a bad practice**.
There are not persistent connections for curl between requests. So on each request you need to establish new connection with endpoint. This is not cheap. Especially for https. And there are more other problems - just read this: https://www.w3.org/Protocols/HTTP-NG/http-prob.html

**Comment by sirian** [comment]
> And before going there: we can't do the same for the Options because they're used in multiple places.

You can. if you make `class Options` non final - than in sentry/symfony you can do smth like this;

```
class FrozenOptions extends Options
{
     public function __construct($resolvedOptions) {
          $this->options = $resolvedOptions;
     }
}
```

And change service `sentry.client.options` in `SentryExtension`
```php
...
$container
            ->register('sentry.client.options', FrozenOptions::class)
            ->setPublic(false)
            ->setArgument(0, $options);

```

That's all. All problems comes from `final` keyword

**Comment by Jean85** [comment]
> It's not a solution. It doesn't matter which endpoint you will use: **Sending HTTP request from WEB server is a bad practice**.
> There are not persistent connections for curl between requests. So on each request you need to establish new connection with endpoint. This is not cheap. Especially for https. And there are more other problems - just read this: https://www.w3.org/Protocols/HTTP-NG/http-prob.html

If even an HTTP connection is a big overhead for you (TLS is not required, you can deploy Relay even locally), you can write a transport that is covertly a spooler, which then sends events in the background.

**Comment by mfb** [comment]
It would be amazing if the SDK made it super easy to init Sentry with a spooler in ~2 lines of code, such as the CallbackTransport described above.

**Comment by Jean85** [comment]
That seems a very nice and simple addition, and we could even leverage it in our tests. I'm happy to review & accept a PR for that!
