### ISSUE TITLE
Option to remove binding of query variables?

### ISSUE THREAD

**Issue by mr-feek** [getsentry/sentry-php#1216]
The laravel package has the [option](https://docs.sentry.io/platforms/php/guides/laravel/configuration/laravel-options/) to disable the binding of query variables. How should we accomplish this functionality in the generic php package?

**Comment by stayallive** [comment]
The plain PHP SDK has no automatic capturing of SQL queries and/or the bindings. 

So the way to remove then is to not submit them to Sentry as a user 😜

Can we help with a specific problem you are having or was this just a general question?

**Comment by mr-feek** [comment]
Hmmm I'm certainly seeing them logged in sentry, let me debug it a bit more then!

**Comment by stayallive** [comment]
Of you are just using the plain PHP SDK someone had implemented sending breadcrumbs. So maybe look for `addBreadcrumb` calls in your codebase. 

Or is it not showing up in the breadcrumbs but in the stacktrace itself? We collect some local variables with the stacktrace which might be what you are seeing?

**Comment by mr-feek** [comment]
Thank you for the quick response @stayallive !

We are manually reporting `Doctrine\DBAL\Exception\DriverException` 's when our queries fail and noticed that the query variables are being sent over the wire to sentry -- will dig into "the why" more!

**Comment by stayallive** [comment]
Cool. Let us know if we can help with figuring it out. 

But possibly you can take a look at the `before_send` option where you can inspect and modify an event before it's sent to the Sentry server in case you want to make sure something is not transmitted by removing some data from the event like those variables.

**Comment by mr-feek** [comment]
> We collect some local variables with the stacktrace which might be what you are seeing?

This did  indeed seem to be the issue. We had a simple fix of just reporting a new generic `\Exception` with the same message. 

```
try {
    // stuff
} catch (Throwable $e) {
    if ($e instance of Doctrine\DBAL\Exception\DriverException) {
           $e  = new \Exception($e->getMessage());
    }
      //  report to sentry
}
```
