### ISSUE TITLE
I am having trouble sending a message

### ISSUE THREAD

**Issue by brunobrante** [getsentry/sentry-php#1217]
I need to send error messages from an external api that is accessed by my system. I read the sentry documentation and it is not so clear how to do it, it only says what method I have to pass. Do I have to use setContext ? How do you use setContext?  I tried to put it before sending a message or exception but it didn't work. Somebody could help me? 

```
\Sentry\configureScope(function (\Sentry\State\Scope $scope): void {
                $scope->setContext('character', [
                  'name' => 'Mighty Fighter',
                  'age' => 19,
                  'attack_type' => 'melee'
                ]);
});
\Sentry\captureMessage("test");
```

There is even a post on stackoverflow asking the same question.  https://stackoverflow.com/questions/66265215/where-to-add-context-to-sentry-php

**Comment by stayallive** [comment]
Hi @brunobrante,

Sorry to see that you have trouble setting up the scope.

You are doing it right though, just to sanity check I've copied your code in a test project and it works:

![image](https://user-images.githubusercontent.com/1090754/117564133-cf132780-b0aa-11eb-80e7-990763cbc339.png)

Are you sure you are not reading over it in the Sentry interface? You also didn't mention the version of the PHP SDK you are using, are you on `3.x` or are you on an older version?

**Comment by brunobrante** [comment]
@stayallive Wow, now I can find where the context is thanks to your printscreen. It just went unnoticed. Can you tell me if what I'm doing is right? I want to pass the errors from an external api, is this the right way ?  Or is there another method ?

**Comment by stayallive** [comment]
If you are just getting messages as strings this is fine (although I'd still use `withScope` to prevent other messages or exception in your app to get the same context as your API messages which is probably not what you want).

But if your API library or code throws an exception replace `captureMessage` with `captureException` and pass the exception to it like: `\Sentry\captureException($exception);` this will capture more context on where in your code the error occurred.

So those are the 2 options, but both are good. It depends on you use case and what you want to see.

**Comment by brunobrante** [comment]
@stayallive Thank you very much, it helped a lot!

**Comment by stayallive** [comment]
No worries, glad to help and good luck with the setup 💪
