### ISSUE TITLE
Sentry broken with latest Composer

### ISSUE THREAD

**Issue by cmcfadden** [getsentry/sentry-php#1219]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
PHP 3.2.2

### Steps to Reproduce

After updating to the latest Composer (2.0.14, release 5/21/2021), Sentry will trigger errors in the Composer autoloader, even for cases that aren't fatal errors in the application.

This is due to the change [Composer made to getRawData](https://github.com/composer/composer/pull/9816) which is used by Jean85/pretty-package-versions, a dependency of Sentry. 

The Jean85 developer is reviewing a [PR fix](https://github.com/Jean85/pretty-package-versions/pull/39) but for the moment sentry users should avoid updating to composer 2.0.14.

### Expected Result

Sentry to work like normal

### Actual Result

PHP throws an error due to the call to getRawData.

**Comment by ste93cry** [comment]
Closing this because we cannot do anything here, the fix as you already noticed must be done upstream
