### ISSUE TITLE
Local variables are not showing on stack trace

### ISSUE THREAD

**Issue by rbisol** [getsentry/sentry-php#1220]
Which SDK and version?
PHP SDK v3.2.2
PHP v7.2.34

A user is reporting an issue with the local variables passed as function arguments are not present in their stack traces in Sentry.

I was unable to reproduce the issue. When testing the feature, the function arguments are present in my stack trace, as you can see in the screenshot. The difference in my case is that I'm using PHP v8.0.3.

<img width="781" alt="Screenshot 2021-05-27 at 14 46 07" src="https://user-images.githubusercontent.com/64906376/119829178-434b2900-befb-11eb-9a5b-94b5d15f9dea.png">

Digging the code, I found this function that captures the stack trace and add it to the event that uses the constant `DEBUG_BACKTRACE_IGNORE_ARGS`, which according to PHP docs control if the function arguments should are omitted or not

https://github.com/getsentry/sentry-php/blob/4f6f8fa701e5db53c04f471b139e7d4f85831f17/src/Client.php#L289-L305

https://www.php.net/manual/en/function.debug-backtrace.php

Is this issue indeed related to the constant and it is configured locally by the user? Also, does the PHP version have an impact on this behaviour?

**Comment by ste93cry** [comment]
>Is this issue indeed related to the constant and it is configured locally by the user?

Yes, the issue is related to the use of that constant. The only reason for its use was to save some memory, but we can definitely change this. I would still avoid `DEBUG_BACKTRACE_PROVIDE_OBJECT` though because we don't care about the `$object` index. Contribution is welcome 😃

**Comment by asteinlein** [comment]
Any progress on this? I'm affected by this issue (I'm probably the customer that reported this).

**Comment by ste93cry** [comment]
Released in version [`3.3.1`](https://github.com/getsentry/sentry-php/releases/tag/3.3.1)
