### ISSUE TITLE
Unable to configure http plugins

### ISSUE THREAD

**Issue by xepozz** [getsentry/sentry-php#1224]
You are creating Error plugin directly in [code](https://github.com/getsentry/sentry-php/blob/3.3.1/src/HttpClient/HttpClientFactory.php#L168). That's why I can't pass my own config to that plugin.

How can I configure these plugins?

**Comment by ste93cry** [comment]
Actually there is no easy way to configure the plugins, the best thing I can suggest you is to create your own HTTP client factory to set them

**Comment by xepozz** [comment]
It makes some problems to simple update package.

**Comment by ste93cry** [comment]
I'm not sure I get what you mean 🤔

**Comment by xepozz** [comment]
When you update http client factory I can't just update the package and use new features.
What's the problem to add ability to configure factory's behaviour?

**Comment by ste93cry** [comment]
>What's the problem to add ability to configure factory's behaviour?

There's no problem, besides the fact that my opinion is that the less code we have to maintain the better it is for everyone. So, if there is a real need for you to being able to customize the plugins we add then we can find a solution, but if you just want to add more plugins then something like the [`PluggableHttpClientFactory`](https://github.com/getsentry/sentry-php/blob/2.x/src/HttpClient/PluggableHttpClientFactory.php) that was present in version `2.x` is enough and can be implemented directly in your project

**Comment by xepozz** [comment]
I can't just overwrite HttpClientFactory. You don't use DI to use this class.
I also need to overwrite TransportFactory. It's not the best thing that I would like do.

**Comment by xepozz** [comment]
Don't forget about it :)

**Comment by cleptric** [comment]
I don't think this is something worth adding to the SDK itself, as this sounds like something people need very rarely.
