### ISSUE TITLE
Ignore certain transactions in performance monitoring?

### ISSUE THREAD

**Issue by specialtactics** [getsentry/sentry-php#1232]
Hi

I noticed this is a feature of sentry, but seemingly not of the PHP SDK. What I would like to do is ignore some transactions by putting some code inside of them - for example, to exclude a health check transaction.

Thanks

**Comment by stayallive** [comment]
The snippet in the docs is missing but you can use the `traces_sampler` option which accepts a callback to make you decisions: https://docs.sentry.io/platforms/php/configuration/filtering/#using-sampling-to-filter-transaction-events.

Something like:

```php
\Sentry\init([
  'dsn' => 'https://examplePublicKey@o0.ingest.sentry.io/0',
  'traces_sampler' => function (\Sentry\Tracing\SamplingContext $context): float {
	// Make sure that if the parent request was sampled this request is also sampled
	if ($context->getParentSampled()) {
		return 1.0;
	}

	// Do not sample healthchecks
	if (!empty($_GET['_health'])) {
		return 0.0;
	}

	// Sample 30% of everything else 
    return 0.3;
  },
]);
```

The `if (!empty($_GET['_health'])) {` can ofcourse be replaced with anything you'd like 👍 

We will make sure to update the linked documentation with a full example like this in the future.

Let me know if this works for you!
