### ISSUE TITLE
GuzzleTracingMiddleware should conform with expected features for HTTP client implementations

### ISSUE THREAD

**Issue by mfb** [getsentry/sentry-php#1233]
### Expected Result

GuzzleTracingMiddleware should conform with the recently documented "expected features" for HTTP client implementations: https://develop.sentry.dev/sdk/features/#http-client-integrations

### Actual Result

The span.op is http.guzzle rather than http.client, sentry-trace HTTP header is not added, span status is not set.

**Comment by ste93cry** [comment]
Closing because this has been solved in the referenced PR. Since it’s not a bug because I think that at the time the middleware was created there wasn’t yet a common standard, we will release the enhancement with the next minor version
