### ISSUE TITLE
cannot work in swoole framework hyperf

### ISSUE THREAD

**Issue by jadechenlei** [getsentry/sentry-php#1236]
### Environment

How do you use Sentry?
version 3.1.0

Which SDK and version?
php

cannot work in swoole framework hyperf,  hao can i change the http_handle to support those framework base swoole、
the framework doc is [url](https://hyperf.wiki/2.0/#/zh-cn/guzzle?id=%e4%bd%bf%e7%94%a8-swoole-%e9%85%8d%e7%bd%ae)

**Comment by stayallive** [comment]
Unfortunately it looks like that documentation page is not available in english and I don't really understand what you are asking? What is it what you are trying to do and what is not working? Can you show some code of what you are doing that is not working?

**Comment by mcharytoniuk** [comment]
@jadechenlei It's late, but maybe it will be useful for someone. 

Sentry uses Guzzle as a default transport and Swoole auguments TCP requests to make them asynchronous. In order for Sentry reporter to work you need to wrap it in a coroutine.

This will not work:

```php
<?php

use function Sentry\captureException;
use function Sentry\init as sentryInit;

Runtime::enableCoroutine(SWOOLE_HOOK_ALL);

init([
    'dsn' => SENTRY_DSN,
]);

try {
    throw new LogicException('test');
} catch (Throwable $err) {
    captureException($err);
}
```

This will work:

```php
<?php

use function Sentry\captureException;
use function Sentry\init as sentryInit;
use function Swoole\Coroutine\run;

Runtime::enableCoroutine(SWOOLE_HOOK_ALL);

init([
    'dsn' => SENTRY_DSN,
]);

run(function () {  
    try {
        throw new LogicException('test');
    } catch (Throwable $err) {
        // `captureException` call is inside a coroutine, it will work
        captureException($err);
    }
});
```

You can also implement your own transport that wraps requests in coroutines (as mentioned above)

**Comment by huangdijia** [comment]
see https://github.com/friendsofhyperf/sentry
