### ISSUE TITLE
php://input can be supported

### ISSUE THREAD

**Issue by bastiendonjon** [getsentry/sentry-php#124]
I received data in PHP with php://input by a ajax request to send json string in POST.

However, Sentry do not display data like $_POST and $_GET

**Comment by dopesong** [comment]
Any news on this?

**Comment by johnboy-leeds** [comment]
This would also be of benefit to us.

**Comment by Jean85** [comment]
For 1.x, in reality this is already marked somewhat as a bug (or at least as related) in #531

**Comment by ste93cry** [comment]
Closing as this feature has been implemented in version `1.x`. In version `2.x` I would not support it for the reasons outlined above. It's anyway really simple to add a custom middleware that will do it, and we could even think to provide an implementation out-of-the-box that is not enabled by default
