### ISSUE TITLE
HOWTO: how to show big json in sentry's GUI?

### ISSUE THREAD

**Issue by jokaorgua** [getsentry/sentry-php#1240]
Hello. 

I just need an advice. I'm sending json in post request to my API server and dump's it to sentry in case of an Exception.
This json has the following data
```json
{
"field1": "10_chars",
"field2":"20_chars",
"field3":"100kb_chars",
"field4":"15_chars",
"field5":"35_chars",
}
```

Due to my debug everything is ok on client's side. The whole request is being sent to sentry but sentry's GUI shows the body as
```
{
"field1": "10_chars",
"field2":"20_chars",
"field3":"7kb_chars..."
}
```

So the problems are:
1. The field3 is truncated to 7-8kb (I do not mind)
2. Fields after field3 are not shown at all

I'm using sentry Sentry 21.8.0 and latest symfony sentry PHP

I just want to understand - is this client's issue on my side e.g. incorrect configuration or server side can be adjusted or fixed ?

Thank you

**Comment by jokaorgua** [comment]
I think this is not an issue of serialization. I've debugged it to PayloadSerializer.php:163 - it generates the correct request.
After that the JSON::encode is called and the correct content is returned in JSON, with all the fields. 
After that the Stream is being created and sent to PSR7 async request where the stream body is taken with getContents

**Comment by jokaorgua** [comment]
I think this is a bug in sentry - maybe in the parser of incoming messages or in GUI

I've opened an issue https://github.com/getsentry/sentry/issues/28460

**Comment by jokaorgua** [comment]
this ticket can be closed. nothing related to sentry client 

the explanation is here https://github.com/getsentry/sentry/issues/28460#issuecomment-915949970

**Comment by stayallive** [comment]
Great, thanks for your update 👍
