### ISSUE TITLE
Sentry init conflict with WP CLI

### ISSUE THREAD

**Issue by Kenert** [getsentry/sentry-php#1241]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) with PHP SDK (\Sentry\init). Init call is placed in a [Bedrock](https://github.com/roots/bedrock) (WordPress) environment file (config/environments/production.php).

Which SDK and version?
Sentry PHP SDK 3.1
PHP 7.4.22

### Steps to Reproduce

1. Install and setup Bedrock.
2. Install Sentry SDK.
3. Place \Sentry\init call inside an environment file (for example, config/environments/production.php).
4. Try to use WP CLI (ensure environments match).

### Expected Result

WP CLI works.

### Actual Result

WP CLI doesn't work. It fails to load WordPress and produces no output.

I was able to make a workaround by wrapping the Sentry init call around a check against WP CLI (if it doesn't exist, init):
```
/**
 * Sentry Configuration
 */
if (!defined('WP_CLI') || !WP_CLI) {
    \Sentry\init(
        [
            'dsn'               => 'dsn',
            'attach_stacktrace' => true,
            'environment'       => 'production',
            'error_types'       => E_ERROR | E_USER_ERROR,
            'sample_rate'       => 1.0,
        ]
    );
}
```

**Comment by stayallive** [comment]
Well, that's interesting. 

But this is not really much to go on... I mean there has to be some error or something in WP CLI detecting something and it exiting. 

Have you tried it with WP_DEBUG set to true and/or increasing the WP CLI verbosity to the maximum?

Just to be sure before attempting to do this ourselfs, you are using the `sentry/sdk` package and not a WordPress plugin in a totally clean Bedrock install?

**Comment by Kenert** [comment]
> Well, that's interesting.
> 
> But this is not really much to go on... I mean there has to be some error or something in WP CLI detecting something and it exiting.
> 
> Have you tried it with WP_DEBUG set to true and/or increasing the WP CLI verbosity to the maximum?
> 
> Just to be sure before attempting to do this ourselfs, you are using the `sentry/sdk` package and not a WordPress plugin in a totally clean Bedrock install?

Thanks for the words of advice. 

We found out that this is apparantly a Composer version conflict.

If installing this package via Composer v1 and trying to use WP CLI, the following error is thrown:
`Fatal error: Uncaught OutOfBoundsException: Package "sentry/sentry" is not installed in phar:///usr/local/Cellar/wp-cli/2.5.0/bin/wp/vendor/composer/InstalledVersions.php:674`

We solved it by switching to Composer v2 and reinstalling our packages. Issue seems to be fixed.

**Comment by stayallive** [comment]
Super interesting, but happy switching to composer v2 fixed it.

I'll close the issue for now but if future readers encounter this feel free to comment again.

**Comment by Jean85** [comment]
The switch to Composer 2 probably changes the version of `jean85/pretty-package-versions`, see https://github.com/Jean85/pretty-package-versions#compatibility
