### ISSUE TITLE
Verify `php_uname` function availability before calling `EnvironmentIntegration.setOsContext()`

### ISSUE THREAD

**Issue by giilby** [getsentry/sentry-php#1243]
Similarly to #985, I'm using sentry-php (via [wp-sentry](https://github.com/stayallive/wp-sentry)) with a WordPress site hosted on Flywheel. Unfortunately, wp-sentry doesn't currently provide a way to properly override the default integrations set up by sentry-php. Looking at the changes made in #1072, it seems like a straightforward way to remedy this issue would be to  wrap `EnvironmentIntegration:31` with a check to see if the `php_uname` function is available. Is there any reason not to do this? I'm happy to submit a PR with the change if it makes sense. Thanks!

**Comment by ste93cry** [comment]
As I mentioned in the past, I think this is the classic case of "security through obscurity" and by wrapping the function calls with a `function_exist` check may open the door to end up like WordPress that checks that all functions exist. Anyway, I would happily accept a PR if you want to propose the change 😄

**Comment by ste93cry** [comment]
The fix has been released in version `3.3.3`
