### ISSUE TITLE
Product Availability Tracking per SDK

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-php#1255]
We would like to add a configuration file per SDK starting with PHP or a PHP framework, which will allow for creating a machine readable feature availability form. 

Related requests:

https://github.com/getsentry/sentry-release-registry/issues/39

https://github.com/getsentry/sentry-docs/issues/3107

Related PR:

https://github.com/getsentry/sentry-java/pull/1527

**Comment by ste93cry** [comment]
Is this something that still makes sense to keep open or has the attempt been abandoned?

**Comment by stayallive** [comment]
Yep it for sure is. Although not as much progress has been made as I wanted (by a long shot) yet 😅

**Comment by ste93cry** [comment]
Then let's put this into the backlog so that the bot doesn't close it 😃

**Comment by antonpirker** [comment]
I also like the idea a lot. 
But I guess the first step for this would be to compile a list of features that can be implemented the SDKs. I think we do not have this kind of list right now.

**Comment by cleptric** [comment]
Closing this for now, we might revisit this in the future.
