### ISSUE TITLE
php-fpm error not send to Sentry when error_log set to file

### ISSUE THREAD

**Issue by robjuz** [getsentry/sentry-php#1258]
### Environment

PHP 7.4.10
"sentry/sentry": "^3.1"

### Steps to Reproduce
in `/etc/php/7.4/fpm/php.ini`
```ini
error_log = /var/www/logs/php-error.log
```

```php
<?php
require 'init_autoloader.php';
Sentry\init(
        [
            'dsn' => getenv('SENTRY_DSN'),
        ]
    );

throw new Exception('Sentry Test Script');
```

### Expected Result
Error reported in sentry

### Actual Result
Error NOT reported in sentry

after setting
```ini
error_log = syslog
```

error is reported as expected

**Comment by Jean85** [comment]
Are you sure that you (or one of your other deps) are not setting a custom error handler in your autoloader?
