### ISSUE TITLE
How can i init sentry twice? 

### ISSUE THREAD

**Issue by daqniwloe** [getsentry/sentry-php#1261]
I'm using sentry in moodle, so, i need init sentry twice to get db errors and the other errors. So, when i init, he disable my another init. 

So, I need to know how to do an init twice or how do I make the init go off.

```
<?php  // Moodle configuration file


unset($CFG);
global $CFG;
try{ // dentro do try é chamado o erro apenas 1x. Em cima do try, o mesmo erro é listado 2x. 
   require_once (__DIR__ . '/vendor/autoload.php');
  Sentry\init(['dsn' => 'https://4e2a8d4b6a8a406ca6eaa4521fbbd1c2@o1060358.ingest.sentry.io/6055183']);
  
$CFG = new stdClass();

$CFG->dbtype    = 'mariadb';
$CFG->dblibrary = 'native';
$CFG->dbhost    = 'localhost';
$CFG->dbname    = 'moodle';
$CFG->dbuser    = 'root';
$CFG->dbpass    = '';
$CFG->prefix    = 'mdl_';
$CFG->dboptions = array (
  'dbpersist' => 0,
  'dbport' => '',
  'dbsocket' => '',
  'dbcollation' => 'utf8_unicode_ci',
);

$CFG->wwwroot   = 'http://localhost/moodle';
$CFG->dataroot  = 'C:\\xampp\\moodledata';
$CFG->admin     = 'admin';

//Allow to display all errors and not save cache(Only for Developers)
// $CFG->debug = E_ALL;
// $CFG->debugdisplay = 1;
// $CFG->langstringcache = 0;
// $CFG->cachetemplates = 0;
// $CFG->cachejs = 0;
// $CFG->perfdebug = 15;
// $CFG->debugpageinfo = 1;

$CFG->directorypermissions = 0777;

require_once(__DIR__ . '/lib/setup.php');
Sentry\init([
  'dsn' => null
]);
}catch(\Throwable $exception){

 
  Sentry\captureException($exception);


//   \Sentry\init([
//     'dsn' => 'https://4e2a8d4b6a8a406ca6eaa4521fbbd1c2@o1060358.ingest.sentry.io/6055183', 
//     'traces_sample_rate' => 1.0
// ]);

}

require_once (__DIR__ . '/vendor/autoload.php');
Sentry\init(['dsn' => 'https://4e2a8d4b6a8a406ca6eaa4521fbbd1c2@o1060358.ingest.sentry.io/6055183' ]);
Sentry\captureLastError();

// There is no php closing tag in this file,
// it is intentional because it prevents trailing whitespace problems!
```

**Comment by Jean85** [comment]
I'm sorry but I don't understand why you would need two different instances for the same application.

In any way, the `init` function is just the "shortcut", what you would probably do is create two different `Hub`s with two different options set & clients. But I would discourage it, maybe you can split your errors at a different level?

**Comment by daqniwloe** [comment]
> I'm sorry but I don't understand why you would need two different instances for the same application.
> 
> In any way, the `init` function is just the "shortcut", what you would probably do is create two different `Hub`s with two different options set & clients. But I would discourage it, maybe you can split your errors at a different level?

I put sentry in moodle. In moodle, 1 file calls the entire system. That's why I need 2 inits.

Can you give me an example of how to create two different `hubs `with two differents options set and clients?

**Comment by Jean85** [comment]
> I put sentry in moodle. In moodle, 1 file calls the entire system. That's why I need 2 inits.

That's the norm with a modern PHP application, where you have a front controller. What "split" would you like to have in Sentry? Do you want to split issues per-tenant? Can't you use tags or other event additional data to enrich the data on Sentry?

> Can you give me an example of how to create two different hubs with two differents options set and clients?

The difference always boils down to the client and the injected options, so you would need something like this:
```php
use Sentry\ClientBuilder;
use Sentry\HttpClient\HttpClientFactory;
use Sentry\SentrySdk;
use Sentry\State\Hub;
use Sentry\State\HubInterface;

$client1 = ClientBuilder::create($options1);
$client2 = ClientBuilder::create($options2);

$hub1 = new Hub($client1);
$hub2 = new Hub($client2);

SentrySdk::setCurrentHub($hub1);
```
Point is though that you can have just one active hub at a time, so you would need to capture events explicitly with one hub or the other to route events correctly.

**Comment by daqniwloe** [comment]
Its works, but now, traces_sample_rate is not working. I only put `'traces_sample_rate' => 1.0`. It's should appears on "Peformance" ant Sentry dashboard, but nothing appears

```
  Sentry\init([
    'dsn' => 'https://4e2a8d4b6a8a406ca6eaa4521fbbd1c2@o1060358.ingest.sentry.io/6055183', 
    'traces_sample_rate' => 1.0,
  ]);
```

**Comment by stayallive** [comment]
There is (as you probably already seen) no Moodle plugin that provides this out of the box (see all known 3rd party integrations: https://github.com/getsentry/sentry-php#3rd-party-integrations).

Because we are a userland implementation (instead of a PHP plugin) there is no automatic performance tracing available. You need to do some work here to profile your application (or in this case Moodle) manually unfortunately, we only have some automated performance profiling when using the Symfony or Laravel SDKs at the moment. 

The documentation on how to integrate tracing yourself in any PHP application can be found here: https://docs.sentry.io/platforms/php/performance/#custom-instrumentation. But I must warn that the documentation is a bit sparse at the moment. If you need help you can check out [Discord](https://discord.com/invite/sentry) or the [forums](https://forum.sentry.io/).

Since I think the original question is answered I'm closing the issue but feel free to reopen if that was mistaken.
