### ISSUE TITLE
async work

### ISSUE THREAD

**Issue by drmax24** [getsentry/sentry-php#1262]
curl_multi_init
works asynchronous

sentry-php does not

sentry-php can actually cause your project to go down via blocking on external operations with this crap sentry library.
The problem we experienced many times with this exciting sentry-php over the years.
Without async work this library is not production grade.

**Comment by Jean85** [comment]
This is not the proper way to address the OS work of fellow developers. I'm locking this down, please come back with a more civil tone.

You replied in the same way in https://github.com/getsentry/sentry-php/issues/1005#issuecomment-966193546, so you know and you've seen what difficulties we have to implement an async transport out of the box. There are multiple strategies that you can use (spooling, custom transport, Relay) to lessen this issue, so you're free to try them out, or to contribute an async transport with a dedicated package; we would gladly link to it in our readme.

**Comment by smeubank** [comment]
I can assure you that we (Sentry employee here full disclaimer) are sensitive to whether or not our SDKs have a negative impact on anyone's application. There are a lot of internal discussions and even research initiatives to investigate how much impact we have. I know it is not the same but I would refer to https://github.com/getsentry/sentry-sdk-benchmark where engineers from sentry dedicated considerable thought and effort to demonstrably measure the impact our SDKs have on applications.
I know it is not the same as this issue, but we are aware that there are some scenarios where design choices related to the Unified API are not ideal. We truly appreciate feedback, but we would also appreciate a certain level of respect in our OS forums like this. @Jean85  as always thank your for your contributions!
