### ISSUE TITLE
sentry/sdk 3.3.4 is not found

### ISSUE THREAD

**Issue by michaelschem** [getsentry/sentry-php#1265]
### Environment

Kubernetes environment 

sentry/sdk: 3.3.0

### Steps to Reproduce

1) Create composer.json file with the following contents

```
{
    "require": {
        "stripe/stripe-php": "^6.7",
        "sendgrid/sendgrid": "~7",
        "rmccue/requests": ">=1.0",
        "sentry/sdk": "3.3.4",
        "pelago/emogrifier": "^3.0",
        "taxjar/taxjar-php": "^1.9"
    }
}
```

2) Create docker file with `RUN composer install` as one of the steps.
3) build docker 

### Expected Result

The Docker completes its build.

As shown [here](https://docs.sentry.io/platforms/php/) it seems that 3.3.4 is the latest version.

### Actual Result

```
 > [stage-1 16/17] RUN composer install:
#30 0.292 Do not run Composer as root/super user! See https://getcomposer.org/root for details
#30 0.339 No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
#30 0.339 Loading composer repositories with package information
#30 1.214 Updating dependencies
#30 1.305 Your requirements could not be resolved to an installable set of packages.
#30 1.305
#30 1.305   Problem 1
#30 1.305     - Root composer.json requires sentry/sdk 3.3.0, found sentry/sdk[dev-switch-from-travis-ci-to-github-actions, dev-master, 0.0.2, 2.0.0, ..., 2.2.0, 3.0.0-beta1, 3.0.0, 3.1.0] but it does not match the constraint.
#30 1.305
```

**Comment by Jean85** [comment]
`sentry/sdk` is a metapackage, which version is not strictly in sync with the main package, which is `sentry/sentry`.

You can still use the metapackage, it will install the needed HTTP transport packages that we suggest out of the box; but its latest version is 3.1, but it turn you'll get `sentry/sentry` with 3.3.4.
