### ISSUE TITLE
Send extra data in capture events

### ISSUE THREAD

**Issue by pe1uca** [getsentry/sentry-php#1266]
In the legacy raven client extra data can be send to the capture methods as described in here https://docs.sentry.io/clients/php/usage/  

```php
$sentryClient->captureException($ex, array(
    'extra' => array(
        'php_version' => phpversion()
    ),
));
```

While migrating to this new client found out that is missing this functionality.  

In theory it could be done with EventHint like this
```php
\Sentry\captureException(
	new \Exception('testing'),
	\Sentry\EventHint::fromArray([
		'extra' => [
			'var' => 'some other data',
		],
	])
);
```
But this doesn't work.
Here we can see that the extra of hint is never merged to the event
https://github.com/getsentry/sentry-php/blob/ecbd09ea5d053a202cf773cb24ab28af820831bd/src/Client.php#L220-L228

This should also be [documented](https://docs.sentry.io/platforms/php/usage/), like it is for the RavenClient, once is implemented

**Comment by pe1uca** [comment]
As a workaround, it can be set using the `before_send` callback
```php
$sentry_config['before_send'] = function (\Sentry\Event $event, ?\Sentry\EventHint $hint) { 
    $event->setExtra($hint->extra); 
    return $event; 
};
```

**Comment by stayallive** [comment]
All data is now set using the scope, this can be permanent (configureScope) or temporary (withScope). 

See our docs: https://docs.sentry.io/platforms/php/enriching-events/context/#structured-context. 

The scope also contains methods to set extra data but in the documentation examples for context is given.

**Comment by pe1uca** [comment]
Well, that's doable.  
I just have some comments, I'd say I'm nitpicking.

1. Sending the data to the scope callback.
In the example the extra data is hardcoded, to actually send the context we'll also need to send the data to the function.  
So, following the same example, where we might have several variables to send.
```php
$name = 'Mighty Fighter';
$age = 19;
$attack_type = melee;

\Sentry\withScope(function (\Sentry\State\Scope $scope) use ($e, $name, $age, $attack_type): void {
    $scope->setContext('character', [
        'name' => $name,
        'age' => $age,
        'attack_type' => $attack_type
    ]);
});
```

For this example we could wrap that in a single object.
Then the same would be true when wanting to send more information.
```php
$character = new Character();
$character->name = 'Mighty Fighter';
$character->age = 19;
$character->attack_type = 'melee';

$level = new Level();
$level->name = 'First level';
$level->weather = 'Rainy'

\Sentry\withScope(function (\Sentry\State\Scope $scope) use ($e, $character, $level): void {
    $scope->setContext('character', (array) $character);
    $scope->setContext('level', (array) $level);
});
```
We could send everything in a single variable, but I think that'll defeat the purpose of the context's name,
or walk the array to extract the names and call setContext individually (similar to what needs to be done for `before_send` explained below).

2. Garbage stacktrace
After implementing one of those, we'll also find that now we have some extra stacktrace in our events from the callback.
![image](https://user-images.githubusercontent.com/15692727/144138936-cf4370f1-f462-43f4-8a35-5eb13fec34e7.png)

3. Manually walk all contexts to pre-process
I'm using `before_send` to sanitize the data sent to sentry, that's why I found the first workaround.  
That can easily be done with the example I mentioned since we have an array that we can extract and set in a single step
`$event->setExtra(sanitize($hint->extra));`
I think it'll be great to have `setContexts`, because right now it needs to be done like this to take into account all contexts.
```php
$sentry_config['before_send'] = function (Sentry\Event $event) {
    $contexts = $event->getContexts();
    foreach ($contexts as $name => $ctx) {
        $ctx = sanitize($ctx);
        $event->setContext($name, $ctx);
    }
    return $event;
};
```

~~4. (very opinionated, probably exaggerated, might as well ignore) Adding more code to a simple capture.
Now I'm required to make 1 call with an anonymous function, include in `use` the variables to send, a call for each context that might be set, and then doing the actual capture.~~

**Comment by pe1uca** [comment]
Sharing my helper function to have a similar functionality as legacy versions.  

```php
function sentry_capture_exception_with_context(\Throwable $exception, ?\Sentry\EventHint $hint = null, array $contexts = [])
{
	$event_id = '';
	\Sentry\withScope(function (\Sentry\State\Scope $scope) use ($exception, $hint, $contexts, &$event_id): void {
		foreach ($contexts as $name => $ctx) {
			$ctx = sanitize($ctx);
			$scope->setContext($name, $ctx);
		}

		$event_id = strval(\Sentry\captureException($exception, $hint));
	});

	return $event_id;
}
```

**Comment by m4tthumphrey** [comment]
I've just run into this and would easily be solved if the `$extra` property on `EventHint` was copied to the `Event` object when sent to Sentry.

So instead of simply being able todo this:

```php
captureException($e, EventHint::fromArray([
    'extra' => ['foo' => 'bar']
]));
```

I am having todo this:

```php
$event = Event::createEvent();
$event->setExtra(['foo' => 'bar']);

captureEvent($event, EventHint::fromArray([
    'exception' => $e
]));```

Unless I'm missing something?

**Comment by stayallive** [comment]
We are not fixing this because extra data is deprecated: https://docs.sentry.io/platforms/php/enriching-events/context/#additional-data

Please use [context](https://docs.sentry.io/platforms/php/enriching-events/context/) instead which should work properly and as expected!

See also #1779.

**Comment by m4tthumphrey** [comment]
@stayallive 

Oh, OK that makes sense thanks! So is the only way to add context to a one-off capture to use `withScope()` closure?

**Comment by stayallive** [comment]
Yes using scopes is the intended way to make temporary adjustments for just a single capture.

See also the docs example for this: https://docs.sentry.io/platforms/php/enriching-events/context/#structured-context

**Comment by m4tthumphrey** [comment]
Do you see any reason not todo it like this..?

```php
$event = Event::createEvent();
$event->setContext('foo', [
    'bar' => 123
]);

captureEvent($event, EventHint::fromArray([
    'exception' => $e
]));
```
