### ISSUE TITLE
429 shouldn't be retried

### ISSUE THREAD

**Issue by Jean85** [getsentry/sentry-php#1279]
When Sentry servers responds with a 429, we shouldn't retry it. The `RetryPlugin` should be configured accordingly.

See https://github.com/getsentry/sentry-php/issues/1204#issuecomment-1012957177

**Comment by stayallive** [comment]
Actually looking at the code for the `RetryPlugin`, unless I'm misunderstanding this might already behave as expected?

https://github.com/php-http/client-common/blob/d135751167d57e27c74de674d6a30cef2dc8e054/src/Plugin/RetryPlugin.php#L73-L80

**Comment by Jean85** [comment]
It doesn't retry when it's between 500 and 600, so 429 IS retried immediately.

**Comment by stayallive** [comment]
It's not being retried I'll continue the discussion in #1279, something else is going on.
