### ISSUE TITLE
Socket connection problems

### ISSUE THREAD

**Issue by shiromart** [getsentry/sentry-php#128]
Hello! Recently, I catch some errors of sentry client library(raven-php) on my project, developed on yii framework:
[25-Oct-2013 12:27:38 Europe/Moscow] PHP Warning: socket_sendto(): unable to write to socket [1]: Операция не позволяется( <- Operation is not permitted) in */protected/extensions/yii-sentry/lib/Raven/Client.php on line 453

It's a phantom error, that appear sometimes, with no any logs and other problems.

There are no checks of socket creation in a code:

``` php
        $sock = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);
        socket_sendto($sock, $raw_data, strlen($raw_data), 0, $host, $port);
        socket_close($sock);

        return true;
```

maybe it will be more pleasant to use it, if it will look like:

``` php

        $sock = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);
        if ($sock === false) {
            return false;
        }
        $sent = @socket_sendto($sock, $raw_data, strlen($raw_data), 0, $host, $port);
        socket_close($sock);
        return $sent === false;
```

or something else, with some error processing.

P.S. "@" used only for example!

Thanks.

**Comment by ste93cry** [comment]
I'm closing this as it's not relevant anymore
