### ISSUE TITLE
The .gitattributes file is missing entries 

### ISSUE THREAD

**Issue by williamdes** [getsentry/sentry-php#1287]
### Problem Statement

Same as https://github.com/getsentry/sentry-laravel/issues/540

### Solution Brainstorm

```
vendor/sentry/sentry
├── AUTHORS <---------- Remove it ??
├── CHANGELOG.md
├── codecov.yml <---------- Remove it
├── composer.json
├── .github <---------- Remove the folder
│   └── workflows
│       ├── ci.yaml
│       ├── publish-release.yaml
│       ├── stale.yml
│       └── static-analysis.yaml
├── LICENSE
├── phpbench.json <---------- Remove it
├── .php-cs-fixer.dist.php <---------- Remove it
├── phpstan-baseline.neon <---------- Remove it
├── psalm-baseline.xml <---------- Remove it
├── README.md
├── src [...]
├── UPGRADE-2.0.md <---------- Remove it ?
└── UPGRADE-3.0.md <---------- Remove it ?

15 directories, 97 files
```

**Comment by williamdes** [comment]
> @williamdes I think you meant to make this issue for [`sentry-php`](https://github.com/getsentry/sentry-php), transferring.

Yes indeed, sorry for the mistake. I forgot to double check

**Comment by ste93cry** [comment]
Would you be open to contributing the necessary changes?

**Comment by williamdes** [comment]
Yes, but if you have push access sending one commit will be quicker than me doing it some day when I can :)

**Comment by ste93cry** [comment]
I've read that the Sentry guys enabled the branch protection on all their master braches, so I think I can't do it anymore. Anyway, opening a PR is a good way to keep track of the changes 😃
