### ISSUE TITLE
Allow hooking into sending transactions (sampling)

### ISSUE THREAD

**Issue by saibotk** [getsentry/sentry-php#1304]
Hello,

i took a deep dive into the repository to find a way to filter out certain performance traces, that should not be sampled and sent to sentry. For example i want to be able to preemptively filter out every 404 request (in my example use-case im using the laravel package). 
Sadly i found that, the before_send hook is not applied for transactions, is there a reason for this behavior? (Might also be something we should add to the documentation)

If this hook cannot also be used for transactions, I'd like to suggest adding a second hook specific to this use-case.
Sadly this cannot be covered in a sampler function, because at this point the request has just started and the outcome is not yet known.

I'd love to hear ideas or feedback and to see this implemented.
Thank you for the amazing library :)

**Comment by Jean85** [comment]
Thank you!

IIRC the sampler option can be adjusted at any point in time before the trace is actually sent, so you should find the right hook in the framework to call and set it to `0.0`. Since you mention you're using Laravel, I should call @stayallive for help :smile:

**Comment by stayallive** [comment]
I think the `traces_sampler` callback is what you are looking for.

We have documented it here:
- https://docs.sentry.io/platforms/php/guides/laravel/configuration/laravel-options/#advanced-sample-rate
- https://docs.sentry.io/platforms/php/guides/laravel/configuration/options/#traces-sampler

Let me know if that works for you!

**Comment by stayallive** [comment]
Oh, yeah sorry I tried to answer too quickly :)

I think the best way is to use a middleware in your application, something like this:

```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Sentry\State\HubInterface;
use Symfony\Component\HttpFoundation\Response;

class SentrySamplerMiddleware
{
    public function handle(Request $request, Closure $next): mixed
    {
        // If Sentry is not registered it is not active and we don't need to do anything
        if (!app()->bound(HubInterface::class)) {
            return $next($request);
        }

        /** @var \Symfony\Component\HttpFoundation\Response $response */
        $response = $next($request);

        $transaction = app(HubInterface::class)->getTransaction();

        // If we have a transaction, set it to not be sampled if the request response code is a 404
        if ($transaction !== null && $response->getStatusCode() === Response::HTTP_NOT_FOUND) {
            $transaction->setSampled(false);
        }

        return $response;
    }
}
```

I tried to make it as clear as possible, in Sentry terms the "transaction" span is the "root" of the performance tracing, and it holds the information about if it's sampled. Until it's sent you can modify this at any moment in your application so maybe you have a better place to modify the sampled state of the transaction, be mindful that the `getTransaction()` can return `null`.

Hope this helps more 😉

**Comment by saibotk** [comment]
Wow, thank you very very much, this is exactly what i needed.

You really made my day. 
In terms of response time 11/10 and your answer is perfectly on-point THANK YOU very very much!

Wish you both a nice day!
