### ISSUE TITLE
PHP ENUMs errors aren't reported to Sentry

### ISSUE THREAD

**Issue by LocalHeroPro** [getsentry/sentry-php#1320]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.5.0.dev0

### Steps to Reproduce

1. Write PHP ENUM
```php
//
enum AwesomeEnum: int
{
    case SOMETHING = 1;
    case ANOTHER_CASE = 2;
}
```
2. Trigger error
```php
///
$enum = AwesomeEnum::from('some-string');
```
3. Laravel store that error in log, but
```log
//
"exception":"[object] (TypeError(code: 0): App\\Enums\\AwesomeEnum::from(): Argument getsentry/sentry#1 ($value) must be of type int, string given)
//
```
5. Sentry do nothing.

### Expected Result

Sentry get errors from ENUMs errors.

### Actual Result

Sentry don't show those errors.

**Comment by Jean85** [comment]
This is really strange. An uncaught `TypeError` should be caught by Sentry anyway. Can you reproduce this issue in a smaller scale, like with a test here?

@stayallive do you think something in Laravel could interfere?

**Comment by stayallive** [comment]
It shouldn't AFAIK. @LocalHeroPro a few questions:

- did you register Sentry with the `reportable` or using the log channel?
- are other exception reported to Sentry?

**Comment by LocalHeroPro** [comment]
1. Like here: https://docs.sentry.io/platforms/php/guides/laravel/
![image](https://user-images.githubusercontent.com/42643563/169337088-6b940ef8-9255-4740-9487-ee9768643260.png)
3. Yes, proof: 
![image](https://user-images.githubusercontent.com/42643563/169336294-25162c36-6be6-4c1f-ba15-3f2c8a6dd112.png)

**Comment by LocalHeroPro** [comment]
@Jean85 could you provide some example, link to that test?

**Comment by Jean85** [comment]
You can probably start from a PHPT test, which is very high level; try using this one as a starting point and replace the error with your case: https://github.com/getsentry/sentry-php/blob/master/tests/phpt/error_handler_captures_error.phpt

**Comment by LocalHeroPro** [comment]
I have other issues that don't Sentry don't catch.
```
[2022-06-14 08:57:01] prd.ERROR: App\Services\Dpd\PackageService::sendPackage {"order_shipping_line_id":26264,"exception":"[object] (ErrorException(code: 0): DOMDocument::createElement(): unterminated entity reference             quo at /data/www/example.com/html/app/Services/Dpd/PackageService.php:196)
```
Why?

**Comment by Jean85** [comment]
Without any additional information, we're unable to help you. The standard installation should catch any uncaught exceptions by default. Maybe you have some additional configuration that is conflicting with Sentry? Are you using the default options or do you have any custom value set?

**Comment by LocalHeroPro** [comment]
As I can see, I have that configuration: https://github.com/getsentry/sentry-php/issues/1320#issuecomment-1131878371.

> The standard installation should catch any uncaught exceptions by default

It means, if I catch exception using try catch, so that exceptions can't be reported in standard configuration?
Example:
```php
throw new UnexpectedValueException('Connection error. Check the correctness of the credentials.'); // will be reported to the Sentry

try {
    $e = 1 / 0;
} catch (Throwable $e) {
    // that will NOT be reported to the Sentry?
}
```

**Comment by Jean85** [comment]
If you have
```php
try {
    $e = 1 / 0;
} catch (Throwable $e) {
    // no op
}

return;
```
yes, this does not get caught. No exception is rising, so we can't do anything about it. We may catch warning or deprecations, because they get to the error handler anyway, even if the flow is not interrupted. But otherwise you will not get them you'll have to add a manual catch of the exception by Sentry in the `catch` block.

**Comment by LocalHeroPro** [comment]
Exception is raised: we can't divide by zero, so catch blok catch exception.

**Comment by Jean85** [comment]
Raised and caught, also not rethrown. 

Sentry SDK is able to automatically capture only uncaught exceptions.
