### ISSUE TITLE
sdk have issue with multiple composer autoload

### ISSUE THREAD

**Issue by phpooya** [getsentry/sentry-php#1336]
`php 7.4` `"sentry/sdk": "2.0.3"`

there is a problem on `Sentry\init()` initializing if you require multiple composer autoload with different packages. (**note: sentry is present in one of them**)
because of using `Composer\InstalledVersions` in `Jean85\PrettyVersions`, in some cases the other composer class will load and there is no sentry in it.

```
OutOfBoundsException: Package "sentry/sentry" is not installed in /var/www/html/vendor2/composer/InstalledVersions.php:201
Stack trace:
#0 /var/www/html/vendor/jean85/pretty-package-versions/src/PrettyVersions.php(25): Composer\InstalledVersions::getPrettyVersion()
#1 /var/www/html/vendor/sentry/sentry/src/ClientBuilder.php(107): Jean85\PrettyVersions::getVersion()
#2 /var/www/html/vendor/sentry/sentry/src/ClientBuilder.php(115): Sentry\ClientBuilder->__construct()
#3 /var/www/html/vendor/sentry/sentry/src/functions.php(14): Sentry\ClientBuilder::create()
#4 /var/www/html/App.php(24): Sentry\init()
#5 {main}
```

thanks

**Comment by phpooya** [comment]
Yes. I'll take a try to solve it

**Comment by Jean85** [comment]
IMHO it should be solved on the project side: autoloaders are nestable, so you should have a single one that's able to reach every piece of code\class.
