### ISSUE TITLE
Improve release flow

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry-php#1348]
A few ideas on how we can make the whole release process a bit more straightforward and align it better with other SDKs.

### Generate changelogs

Like on the Python SDK, we should enable `changelogPolicy: auto` so changelogs will be updated and pushed automatically. This will require us to be stricter about the commit messages, but this is already encouraged.

### Set version number

~~Like on the Python SDK, we should expose the SDK version number in the code and update it automatically via a new release.~~ done in https://github.com/getsentry/sentry-php/pull/1367

**Comment by Jean85** [comment]
> This will require us to be stricter about the commit messages, but this is already encouraged.

Since we do squash-merge on PRs, that shouldn't be too hard.

> Like on the Python SDK, we should expose the SDK version number in the code and update it automatically via a new release.

This is already possible in a dynamic way using `jean85/pretty-package-versions`, which is already a dependency, and it exposes the version reading from Composer. It's already used to show it in events.
