### ISSUE TITLE
Timeout is not supported like stated in the docs? 

### ISSUE THREAD

**Issue by PurHur** [getsentry/sentry-php#1354]
### How do you use Sentry?

Self-hosted/on-premise

### Version

3

### Steps to Reproduce

1) Have a lot of applications
2) Log a lot of stuff
3) Do nothing but let sentry crash randomly (Or shut it off)
4) Crash all other apps because sentry is not responding anymore. 

### Expected Result

Not crashing all applications which use the sentry server

### Actual Result

Hello,

i have a question about the docs and answers i found here in PRs/Issues.

Its about a timeout the api (should) provide when contacting a sentry server.
https://docs.sentry.io/platforms/php/configuration/options/

The docs define two `http_connect_timeout` and `http_timeout`. Which indicate that the client has an option to use a timeout. 
But issues like this:
https://github.com/getsentry/sentry-php/pull/967
Tell me that the options isnt used? I couldnt find a line in the code that its really passend by so i am now curios if the SDK still supports a default timeout out of the box, without setting a special HTTPclient. There are multiple issues like that. They describe the problem Sentry has passing around the timeout options to custom clients and so its not implemented anymore (silently???)

So is the timeout option still in use? It is supposed to be documented?

**Comment by ste93cry** [comment]
>Tell me that the options isnt used? I couldnt find a line in the code that its really passend by

Support for configuring one of the out-of-the-box supported HTTP clients using the `http_connect_timeout` and `http_timeout` options have been implemented in #1282. Is this what you are looking for?

**Comment by PurHur** [comment]
Yes thank you. I will look for deployed code on my side but your hint to the PR does REALY help to tell my boss there is a timeout. I will have to confirm that this is deployed to the current packages since i am not saw any "timeout" in the current code. But really thank you showing me the lines.
