### ISSUE TITLE
Undefined index: HTTP_HOST

### ISSUE THREAD

**Issue by AidasK** [getsentry/sentry-php#136]
```
"PHP message: PHP Notice:  Undefined index: HTTP_HOST in /home/.../common/vendor/raven/raven/lib/Raven/Client.php on line 594
```

https://github.com/getsentry/raven-php/blob/master/lib/Raven/Client.php#L594

Maybe we should check if `HTTP_HOST` is defined.

**Comment by stayallive** [comment]
Looks like this was fixed in c27fe51, if the problem persists please open a new issue.
