### ISSUE TITLE
Add tracePropagationTargets option

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry-php#1361]
### Problem Statement

https://develop.sentry.dev/sdk/performance/#tracepropagationtargets

The `GuzzleTracingMiddleware` currently propagates the `sentry-trace` and soon the `baggage` header on each instrumented request.

### Solution Brainstorm

Add the `tracePropagationTargets` option.

**Comment by Jean85** [comment]
What should `tracePropagationTargets` do? We can't do anything "automagically" in the base PHP SDK... Maybe it's feasible in the framework integrations, on the framework-provided clients.

**Comment by cleptric** [comment]
We have to check for it in the `GuzzleTracingMiddleware` and add the Option. Thereafter, we have to update Laravel and Symfony as well.

**Comment by stayallive** [comment]
That option configures when we sent the `sentry-trace` and `baggage` headers with the request.

See: https://docs.sentry.io/platforms/javascript/performance/instrumentation/automatic-instrumentation/#tracingorigins

No need for any magic or automagic anything, just statically configured by the user 😄
