### ISSUE TITLE
Remove jean85/pretty-package-versions dependency

### ISSUE THREAD

**Issue by PabloKowalczyk** [getsentry/sentry-php#1377]
### Problem Statement

Hello, after https://github.com/getsentry/sentry-php/pull/1374 being merged, is there any reason to keep this dependency?

### Solution Brainstorm

Remove it :)

**Comment by stayallive** [comment]
It is still required:

- https://github.com/getsentry/sentry-php/pull/1374#issuecomment-1253636864
- https://github.com/getsentry/sentry-php/pull/1374#issuecomment-1253638556
