### ISSUE TITLE
GuzzleTracingMiddleware can potentially leak private data in baggage header

### ISSUE THREAD

**Issue by mfb** [getsentry/sentry-php#1395]
### How do you use Sentry?

Self-hosted/on-premise

### Version

3cefa7b69f2ebb4e0042c4f39e5c18bf573a4cab

### Steps to Reproduce

I noticed that the GuzzleTracingMiddleware adds the baggage header, which contains various metadata such as the transaction name, to all outbound requests to external URLs.

I'm concerned that some data that isn't intended to be shared with third-parties could be sent via this avenue. For example, the transaction name might include the URL that is currently being accessed, which might include some secret or identifying tokens in the path or query string.

Whereas previously, only a relatively harmless sentry-trace identifier was being sent.

It seems like, by default, sending extra baggage data needs to be limited to certain acceptable external hosts?  Or at a minimum, usage of this middleware needs to be much better documented?

### Expected Result

No data is sent unintentionally to remote sites.

### Actual Result

A baggage HTTP header is sent to remote site, which might contain something like `sentry-trace_id=0123456789,sentry-sample_rate=1,sentry-transaction=GET%20http%3A%2F%2Fdev.example.com%2Fpassword%2Freset%3Ftoken%3Dsecret,sentry-public_key=0123456789,sentry-release=beta,sentry-environment=dev`

**Comment by cleptric** [comment]
Thanks for sharing your concerns about this.
I want to add a few things.

- If you want to instrument outgoing requests with the `GuzzleTracingMiddleware`, you must manually set this up in your application code. We do not register it automatically, so by default, our SDK never runs this code. We have an open issue to document it better https://github.com/getsentry/sentry-docs/issues/5512
- There is an open issue to add the `tracePropagationTargets` option https://github.com/getsentry/sentry-php/issues/1361
- This SDK does not start any transaction automatically, but our Laravel and Symfony SDK do. Both frameworks do not use Guzzle by default.

Maybe it's a good idea to include the new option in the `3.9.0` release as well. So far, this didn't go out yet.

**Comment by mfb** [comment]
Ok I didn't see #1361 when I filed this :) I'd say good idea to add the trace propagation targets option as it seems to be a more-or-less a requirement of the DSC spec to not send this header everywhere? Based on my very quick skim. There might be some other minor things to check, like should baggage values be appended to the header if possible.

I don't use GuzzleTracingMiddleware either, in fact I was just copying the new code there to see what happens, but my concern is someone might copy that code without actually groking what happens.

I would also say that the transaction name "quality" requirements should be carefully documented + implemented. e.g. it appears that sentry-symfony just passes the whole request path into the transaction name, and now this data will be automatically sent elsewhere.

**Comment by cleptric** [comment]
Not automatically. this is opt-in.
I'll get a PR ready which introduces `trace-propagation-targets`.
