### ISSUE TITLE
Nesting level too deep - recursive dependency?

### ISSUE THREAD

**Issue by oojacoboo** [getsentry/sentry-php#1398]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

3.9.0

### Issue

This is a rather strange issue and I'm not quite sure how to reproduce as I don't get much from the stack-trace.

`Sentry\Exception\FatalErrorException` is being thrown with the error:
> Error: Nesting level too deep - recursive dependency?

The stack-trace is showing the call at `/srv/www/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:192` which is `if ($arguments !== $call[1]) {`.

Being that it's a Sentry exception, I can only assume that this lib is trying to get a stack-trace or parse the Symfony DI layer for some reason.

The strange thing about this error is that it's only occurring on AWS when the ELB is hitting the server's internal private IP, as the ELB does.  Normal application requests do not appear to be triggering this error, at least from what I can tell in the Sentry logs.  The errors are occurring across every node in the cluster at a 10 second interval (every ELB request for health-check).

I should further state that rolling back to 3.8.1 resolves this issue.

Any insight into what changed in 3.9.0 that might lead to this issue?

**Comment by cleptric** [comment]
Is your app running Symfony, using our [Symfony SDK](https://github.com/getsentry/sentry-symfony)?
This SDK has no dependency on https://github.com/symfony/dependency-injection so I'm not sure what is going on as we also don't throw a `FatalErrorException` in the codebase.

**Comment by oojacoboo** [comment]
@cleptric we are not using that lib.  I also see the exception in this lib:

https://github.com/getsentry/sentry-php/blob/master/src/Exception/FatalErrorException.php
https://github.com/getsentry/sentry-php/blob/master/src/ErrorHandler.php#L328

**Comment by oojacoboo** [comment]
And here is the shutdown function being registered that throws the Exception

https://github.com/getsentry/sentry-php/blob/master/src/ErrorHandler.php#L186

**Comment by cleptric** [comment]
I meant we do not `throw` the `FatalErrorException` explicitly.

This will be tricky to reproduce though. Mind sharing some details about your application, dependencies and your AWS setup (EC2/ECS/?, OS, PHP version)? You can do so via `michi (@) sentry.io`.

**Comment by oojacoboo** [comment]
I sent an email with some of our application details.  I think it's best to debug this from the angle of what's changed in the latest version, since downgrading the version resolves the issue.

There aren't any errors in our logs either, from the 3.8.1 version.  So, it's not like 3.9.0 is catching some new error and reporting it where 3.8.1 did not.  3.9.0 appears to be creating this error, itself.

**Comment by Jean85** [comment]
There's something that I don't understand though: why is the `AutoWire` pass being called in prod? Shouldn't it be called at build time, and its result be cached?

**Comment by cleptric** [comment]
Looks like there is something else going on and the SDK is not the root cause of it.
