### ISSUE TITLE
3.9.0 adds breaking change to PayloadSerializer

### ISSUE THREAD

**Issue by ChrisHSandN** [getsentry/sentry-php#1399]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

3.9.0

### Steps to Reproduce

Prior to 3.9.0 PayloadSerializer had no constructor. Therefore the previous working code of:
```php
$payloadSerializer = new PayloadSerializer();
```

### Expected Result

The API continues to function with no constructor arguments until a major version number increases.

### Actual Result

Now fails with
> `Too few arguments to function Sentry\Serializer\PayloadSerializer::__construct(), 0 passed`

**Comment by ste93cry** [comment]
Technically speaking, this is not a bug nor something that we have to fix: the class was marked as `@internal` since the beginning, so if you rely on it then you accept the risk of it changing in a breaking manner

**Comment by ChrisHSandN** [comment]
Ah my bad, I didn't spot that `@internal`.

I shall close this as you are right, I will update our code to match the new signature.

**Comment by cleptric** [comment]
I could also get this fixed for you 😄.
I'm curious about your use case of the `PayloadSerializer`. Something we could improve there?

**Comment by ChrisHSandN** [comment]
It is not the most elegant usage I will warn you!

On some of our development environments we prefer to get instant output if an exception would be sent to Sentry (plus it has all the extra details bundled with it which are great for debugging). To do this we use `sendCallback` and needed a way to format the `Event`:

```php
‘sendCallback’ => function (Event $event): ?Event {
    if (!DEVELOPMENT) {
        return $event;
    }

    $PayloadSerializer = new PayloadSerializer();

    $eventJson = $PayloadSerializer->serialize($event);

    $eventArray = json_decode($eventJson, true);

    // ... some additional logic which formats and sorts the array

    var_dump($eventArray);

    return null;
}
```

`PayloadSerializer` seemed to be the best way to convert an `Event` into an array rather than having to effectively write all the logic from `toArray`.
