### ISSUE TITLE
Curl Issue - HTTP 417 error

### ISSUE THREAD

**Issue by crisward** [getsentry/sentry-php#140]
**Quick one, issue and fix. I was getting this error from curl.**

Expectation Failed

The expectation given in the Expect request-header
field could not be met by this server.
The client sent

```
Expect: 100-continue
```

Only the 100-continue expectation is supported.

**The quick fix was to add this to your code (line 454 of Client PHP)**

```
      $headers = array(
            'User-Agent' => $client_string,
            'X-Sentry-Auth' => $this->get_auth_header(
                $timestamp, $client_string, $this->public_key,
                $this->secret_key),
            'Content-Type' => 'application/octet-stream',
            'Expect'=>''
        );
```

**Comment by stayallive** [comment]
Looks like this could be a configuration issue than an issue with this library.

Closing this issue because it is quite old, if there is still a problem please open a new issue.
