### ISSUE TITLE
Support Guzzle 7 on Sentry 2.5.x SDK

### ISSUE THREAD

**Issue by joaopbnogueira** [getsentry/sentry-php#1406]
### Problem Statement

Sentry 2.5.x SDK requires  `"guzzlehttp/psr7": "^1.7"` causing software that depends on it (because we can't yet upgrade to SDK 3.x) to be unable to upgrade to `"guzzlehttp/psr7": "^2.0"`.

### Solution Brainstorm

Since guzzlehttp/psr7 2.x (and guzzle 7) is largely backwards compatible, changing the dependency to something a bit more flexible should cause no issues, i.e. change `"guzzlehttp/psr7": "^1.7"` to `"guzzlehttp/psr7": "^1.7 | ^2.0"`

**Comment by stayallive** [comment]
@joaopbnogueira, out of curiousity, why is upgrading to SDK 3.x not an option for you?

We have not updated 2.x for almost 2 years now and although I understand your problem I'm not sure if there is much benefit of doing so now considering possibly issues that might arrise. It will also take some time to get the 2.x branch out of the mothballs and make sure that the "largely backwards compatible" holds up and or is no issue for the SDK.

**Comment by joaopbnogueira** [comment]
Regarding the update to SDK 3.x, we're planning it, but right now we're stuck at self-hosted Sentry 9.1.2 and this would be a way to give us some time to upgrade the Sentry server and then update the SDK.

As a side-note what happens right now is that composer ends up picking up sentry-sdk 2.2 (because it doesn't depend on  guzzlehttp/psr7).

Thanks for looking into this issue @stayallive.

**Comment by cleptric** [comment]
@joaopbnogueira Did you already try to use SDK 3.x with Sentry 9.1.2? We're still sending errors to the store API, so this might actually just work.

**Comment by joaopbnogueira** [comment]
Actually no, I'll give it a try.

**Comment by stayallive** [comment]
At some point it will, but that will probably happen in version 4. The only thing you can't use is performance tracing, but of course your server version is also not supporting that in any way so you might be good indeed with 3.

**Comment by joaopbnogueira** [comment]
Seems to be working just fine, thank you!
