### ISSUE TITLE
Can't replace Options::setProjectRoot() with IgnoreErrorsIntegration when upgrading

### ISSUE THREAD

**Issue by AJenbo** [getsentry/sentry-php#1425]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

3.11.0

### Steps to Reproduce

1. Follow the instructions to upgrade from 2.0 to 3.0
2. See :

> Removed the following methods from the Options class, use the IgnoreErrorsIntegration integration instead:
> 
>     Options::getExcludedExceptions()
>     Options::setExcludedExceptions()
>     Options::isExcludedException()
>     Options::getProjectRoot()
>     Options::setProjectRoot()
> 
3: Get stumped on how to use IgnoreErrorsIntegration to replace Options::setProjectRoot()

### Expected Result

There should still be a way to set the project root dynamically for projects that have a dynamic deployment folder.

### Actual Result

A relevant reference in the upgrade docs.

**Comment by Jean85** [comment]
This seems a documentation error. `setProjectRoot` should be superseeded by putting the folder in the list of "in app" paths with `Options::setInAppIncludedPaths`

**Comment by cleptric** [comment]
You can take a look at `Options::setPrefixes`

https://github.com/getsentry/sentry-php/blob/master/src/Options.php#L102-L113
