### ISSUE TITLE
Improve 'ignore_exceptions' configuration to allow to ignore even 'previous' exceptions

### ISSUE THREAD

**Issue by DeimantasTamo** [getsentry/sentry-php#1426]
### Context
Currently we have a problem, where a specific exception is caught and wrapped as "BadRequestHttpException". Including it in `ignore_exceptions` list is too general, and including the specific exception (which is included as previous exception) does not work for `ignore_exceptions` configuration, since it only checks the main exception and does not iterate previous exceptions `Sentry\Integration\IgnoreErrorsIntegration:102`. 

### Expected Result
Ability to ignore exceptions which are wrapped in general exceptions as previous exceptions. 

### Actual Result
`ignore_exceptions` list allows only top level exceptions to be ignored.

**Comment by cleptric** [comment]
As a quick fix, you might look into the `beforeSend` callback or a custom integration.
Doesn't look like that was ever supported in the `IgnoreErrorsIntegration`.
