### ISSUE TITLE
It's not possible to have manual sampling done when  traces_sample_rate is 0 

### ISSUE THREAD

**Issue by allan-simon** [getsentry/sentry-php#1437]
### Environment

* PHP 8.1.11
* Symfony 6.1
* Ubuntu 20.04
* Sentry sdk 4.4.0 

### Steps to Reproduce

1. create a project with `traces_sample_rate` set to `0` 
2. create a dummy symfony command 
3. at the beginning of the command force sampling decision by putting

```
          $transactionContext = new \Sentry\Tracing\TransactionContext();
          $transactionContext->setParentSampled(false);
          $transactionContext->setSampled(true);
```

### Expected Result

All run of this command should be sampled

### Actual Result

Nothing, no sample send

### Other important information

Setting the  `traces_sample_rate` to `0.000001`  workaround the issue, and the sampling is *always* sent (as expected)

Is there a special treatment for `0` that is considered as a global switch off that can't be overrided ?

**Comment by cleptric** [comment]
Thanks for letting us now know about this.

Looking at https://github.com/getsentry/sentry-php/blob/master/src/State/Hub.php#L219, we do indeed ignore the passed in sampling context by returning too early.

See https://develop.sentry.dev/sdk/performance/#sampling

**Comment by cleptric** [comment]
@allan-simon Can you let us know which version of the [sentry/sentry](https://packagist.org/packages/sentry/sentry) package you have installed locally by running `composer info`. [3.12.0](https://github.com/getsentry/sentry-php/releases/tag/3.12.0) might have actually fixed that.

**Comment by allan-simon** [comment]
ah indeed, I will check tomorrow, if it was tagged 5 days ago I think I may have missed it !

**Comment by cleptric** [comment]
`null` will turn off tracing as a whole. In your case, you should use `0`.
