### ISSUE TITLE
Undefined constant "Sentry\Util\UUID_TYPE_RANDOM"

### ISSUE THREAD

**Issue by abramov-ks** [getsentry/sentry-php#1442]
### How do you use Sentry?

Self-hosted/on-premise

### Version

3.3.0

### Steps to Reproduce

Add to composer.json
{"sentry/sdk": "3.3.0"}

### Expected Result

normal

### Actual Result

Got PHP Fatal error:  Uncaught Error: Undefined constant "Sentry\Util\UUID_TYPE_RANDOM" in ~/vendor/sentry/sentry/src/Util/SentryUid.php:20

Solved with adding { "symfony/polyfill-uuid": "v1.27.0" }

**Comment by stayallive** [comment]
Which PHP version are you using? And any framework package or just this one?

**Comment by Jean85** [comment]
This is the incriminated code: https://github.com/getsentry/sentry-php/blob/29c19a772f32122a742d2c840a3852e027b90e3b/src/Util/SentryUid.php#L19-L21

@abramov-ks it seems that you have a `uuid_create` function present, which does not seem to be provided by `ext-uuid`, hence the failure. Maybe we should change the condition of the `if` to check for the presence of the extension (or of the polyfill)? Or require the polyfill directly?
