### ISSUE TITLE
Segmentation fault when used with php-ssh2

### ISSUE THREAD

**Issue by PITDeveloper** [getsentry/sentry-php#1445]
### How do you use Sentry?

Self-hosted/on-premise

### Version

3.3.0

### Steps to Reproduce

I have pasted below a docker container with a test environment to reproduce the issue:

[https://github.com/PITDeveloper/sentry-php-error](https://github.com/PITDeveloper/sentry-php-error)

The steps to reproduce are to

- install php-ssh2 ( 1.3.1 ) on PHP 7.4 or 8.0.2
- add\Sentry\init to top of script
- have your php script attempt to run any command using the php ssh2 extension
- script ends in segfault

If you comment out your \Sentry\init at the top of the script it runs fine.

### Expected Result

ssh2 stream contents

### Actual Result

Segmentation fault (core dumped)

**Comment by cleptric** [comment]
Thanks, I'll take a look.

**Comment by cleptric** [comment]
I'm unable to reproduce this. Do you have more details, some stack traces, error logs, something?

**Comment by stayallive** [comment]
I am running SSH2 on production (with PHP 8.1 though) without problems for the past few months.

You mention PHP 8.0.2, have you tried with the latest 8.0.28? It might be a PHP / SSH2 extension related issue, we might just surface it. I can't immediately think of a way for userland code to otherwise segfault the PHP process.

**Comment by PITDeveloper** [comment]
So I have done a bit more testing, and after updating our phpfpm docker container to 8.0.28, and updating our sentry-php install to the latest version it still does seem to happen.  However, if we remove our explicit ssh2_disconnect statement it no longer happens.  If we set the connection variable to null or unset the variable it doesn't trigger.

Unfortunately, because this is a segmentation fault error, the only log I seem to get is:
WARNING: [pool www] child 23143 exited on signal 11 (SIGSEGV - core dumped) after 16.980335 seconds from start

I have provided below code we are testing:

`
$command = "echo test";
$server = "REDACTED";
$username = "REDACTED";
$password = "REDACTED";
$port = 22;

$connection = ssh2_connect( $server, $port );
ssh2_auth_password( $connection, $username, $password );

$stream = ssh2_exec( $connection, $command );

stream_set_blocking( $stream, true );

$streamOutput = ssh2_fetch_stream( $stream, SSH2_STREAM_STDIO );
$result = stream_get_contents( $streamOutput );

stream_set_blocking( $stream, false );

ssh2_disconnect( $connection );
echo $result;
`
