### ISSUE TITLE
Log exception's code

### ISSUE THREAD

**Issue by erickskrauch** [getsentry/sentry-php#1450]
### Problem Statement

I work a lot with the [Twilio SDK](https://github.com/twilio/twilio-php). In case of an error, a [RestException](https://github.com/twilio/twilio-php/blob/0739f62e6280d9a20925d2f30a71bfd2bcac48f5/src/Twilio/Version.php#L84-L88) is thrown with a text description of the error, as well as a code in [their internal error system](https://www.twilio.com/docs/api/errors). In the current implementation, I can't see this code.

### Solution Brainstorm

According to Sentry's documentation, there is a [exception's meta information](https://develop.sentry.dev/sdk/event-payloads/exception/#meta-information), which seems to be the way to provide the wanted information.

I have [tried to implement it](https://github.com/getsentry/sentry-php/compare/master...erickskrauch:sentry-php:32257d37f6fd405004b0c018534a8408d25130bc), but it seems like Sentry filters out this field on the service side (I checked that this field presented just before JSON encoding when a request is about to be sent).

**Comment by erickskrauch** [comment]
Ok, I [managed](https://github.com/getsentry/sentry-php/compare/master...erickskrauch:sentry-php:54d94d0cbf1996c19df8474a6b1cf7da7ad99605) to get it to work!

**Comment by hubertdeng123** [comment]
Seems like this is a backlog item, so moving it there

**Comment by cleptric** [comment]
Closed in #1451

**Comment by rvanlaak** [comment]
The collection of exception `code` is great! It nicely pops up in the Sentry issue report after upgrading PHP SDK to latest.

But, it seems we are unable to filter on it in the issues overview. Will that feature be added soon? 

Will Sentry also be able to based on that exception code more reliably group issue occurrences? That will allow us to more extensively use variables in the exception message (that sometimes lead to Sentry reporting issues as separate ones).

![image](https://user-images.githubusercontent.com/2707563/217271131-25fe3517-e5e4-49a1-afa1-54a0a62498d7.png)

**Comment by cleptric** [comment]
@rvanlaak Gald you like the new feature! I passed on your feedback to our product team, thanks for letting us know.

**Comment by rvanlaak** [comment]
Thanks! Happy to help wherever I can, really love your product and the transparency on the development of it.

**Comment by cleptric** [comment]
@rvanlaak Didn't forget about this! 😄

You can subscribe to https://github.com/getsentry/sentry/issues/45760.
It's sadly a bit more involved, but we'll get there.
