### ISSUE TITLE
Events missing body keys when the key is a number

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-php#1469]
Laravel 8
Sentry-SDK: 3.2.0
`max_request_body_size => always`

A user noticed the Keys from the request body are missing in the Sentry event. It can be easily reproducible by sending a POST request with the following body, and making it throw an error:

```
{
    "851":"loja carcharias",
    "862":"loja carcharias",
    "860": 122
}
```

In Sentry it shows as:

```
[
"loja carcharias", 
"loja carcharias", 
122
]
```

It seems like the body in this case is treated as an array instead of a dictionary. The "key" values are lost, treated as indexes in an array. Also noticeable when there is a mix of numerical and string keys. For example:

```
{
    "851":"loja carcharias",
    "name":"loja carcharias",
    "860": 122
    }
```

results in:

```
{
"0": "loja carcharias", 
"1": 122, 
"name": "loja carcharias"
}
```

### Steps to Reproduce
1. Create a basic Laravel app with the sentry sdk
2. Make that it throws an error with a POST request
3. Sent a POST request with JSON body examples above.

### Expected Result

All keys will show up in Sentry, regardless of being numbers or strings. This is possibly a platform limitation due to how php handles types.

**Comment by cleptric** [comment]
@rbisol released via https://github.com/getsentry/sentry-php/releases/tag/3.14.0
