### ISSUE TITLE
PHP Profiling

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry-php#1474]
We're currently exploring to extend our Profiling product to support PHP.

Under the hood, we'll use Wikipedia's open-source sampling profiler [Excimer](https://github.com/wikimedia/mediawiki-php-excimer).

Profiles are sent as envelopes and ingested through Relay, and later processed by our profiling service Vroom. Our [Sample format](https://github.com/getsentry/develop/pull/841) is pretty close to what speedscope.app can parse, and Excimer already supports receiving structured speedscope data as well.

Some things we need to work on

- Add new config options for  tweaking the profiler config
- Create abstractions that wrap the Excimer stubs
- Create abstractions that transform the speedscope data into something ingestable (Parts of #1466 may be required here)
- Explore how we can easily enable people to install the Excimer extension

**Comment by tillkruss** [comment]
Bref just added Excimer support on AWS Lambda functions: https://github.com/brefphp/extra-php-extensions/pull/484
