### ISSUE TITLE
Dangling $serializer constructor argument

### ISSUE THREAD

**Issue by zerkms** [getsentry/sentry-php#1479]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

3.13.1

### Steps to Reproduce

1. https://github.com/getsentry/sentry-php/blob/9c4f8d9dbd2e4e5b4a7df24c55b30754761b2896/src/Client.php#L82-L110
1. `$serializer` is not used

### Expected Result

It should be used, or documented as "kept for historical reasons" or something along the lines.

### Actual Result

.

**Comment by cleptric** [comment]
Fixed and released via https://github.com/getsentry/sentry-php/releases/tag/3.14.0
