### ISSUE TITLE
Serializer calls $value->getId() but this method could have function argument(s)

### ISSUE THREAD

**Issue by mfb** [getsentry/sentry-php#1486]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

3.13.1

### Steps to Reproduce

When serializing an object, the SDK calls `$value->getId()` but for a couple of my classes, the getId() method actually has a required function argument, and so the object is serialized as `{serialization error}` .  In case you're wondering why getId() would have an argument, one example would be that the method doesn't get its own ID, it gets the ID of some other object that you pass in as the function argument.

This is a minor issue as it only affects the serialization output - nothing is thrown outside of the serializer. But I was thinking there could be an extra try/catch around this call, so any thrown error can be ignored and the usual class name can be returned?

### Expected Result

The object should be serialized as `'Object ' . \get_class($value)`

### Actual Result

The object is serialized as `{serialization error}`

**Comment by mfb** [comment]
Oops, looks like this was already fixed in dev branch via #1483 :D

**Comment by cleptric** [comment]
Released via https://github.com/getsentry/sentry-php/releases/tag/3.14.0
