### ISSUE TITLE
[regression] default serializer does not handle properly protected object id

### ISSUE THREAD

**Issue by sylver** [getsentry/sentry-php#1487]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

3.13.1

### Steps to Reproduce

1. In a wordpress + woocommerce setup
2. init sentry with minimum arguments inside a custom woocommerce plugin
  ```
  \Sentry\init([ 'dsn' => '**redacted**' ]);
  ```
3. Throw an exception to be caught and handled by sentry

WordPress 6.1.1
Woocommerce 7.3.0
PHP 7.4

But the problem should be reproducible with any inspected object having a protected id

Seems related to this PR addition in `3.13` : https://github.com/getsentry/sentry-php/pull/1443

Does not append if I downgrade to `3.12.1`

### Expected Result

The actual exception from the plugin should be catch and send to sentry, as expected.

### Actual Result

A sentry specific exception is raised due to serializer trying to read a protected id in a woocommerce object.
This exception is the one transmitted to sentry dashboard instead of the actual application exception expected to be catched.

In `Sentry\Serializer\AbstractSerializer::serializeValue()` :

```
Error: Cannot access protected property Automattic\WooCommerce\Admin\Overrides\Order::$id
```

Appears in sentry.io issues as

![2023-03-05T16:52:30_screenshot](https://user-images.githubusercontent.com/3833987/222971197-04d173c4-1345-4133-a06e-b9d435d2f145.png)

```
Sentry\Exception\FatalErrorException

Error: Uncaught Error: Cannot access protected property Automattic\WooCommerce\Admin\Overrides\Order::$id in /var/www/html/wp-content/plugins/**redacted**/vendor/sentry/sentry/src/Serializer/AbstractSerializer.php:246
```

**Comment by cleptric** [comment]
Fixed in https://github.com/getsentry/sentry-php/pull/1483. We will cur a release this week.

**Comment by sylver** [comment]
Totally missed it, sorry for the duplicate.

**Comment by cleptric** [comment]
Released via https://github.com/getsentry/sentry-php/releases/tag/3.14.0
