### ISSUE TITLE
Add option to disable gzip compression

### ISSUE THREAD

**Issue by Nodge** [getsentry/sentry-php#149]
Because functions `gzcompress()` and `base64_encode()` require too much memory when handling a memory exhausted fatal error. I should usualy reserve about 2mb of memory to track this errors.

**Comment by stayallive** [comment]
The ErrorHandler reserves 10mb of memory by default to handle these situations.

https://github.com/getsentry/sentry-php/blob/master/lib/Raven/ErrorHandler.php#L188

If this is still an issue please do re-open.

**Comment by ste93cry** [comment]
Just for reference, this has been implemented in version 2.0. The option is called `encoding` and accepts these values: `gzip` or `json`. The first value means that the whole body of the request to a Sentry server will be encoded in base64 and then gzipped. Also, these operations are now done with stream filters, so I think it should improve the performance and required memory
