### ISSUE TITLE
sentry/sentry not installable with openai-php/client

### ISSUE THREAD

**Issue by regnerisch** [getsentry/sentry-php#1506]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

3.16.0

### Steps to Reproduce

Run `composer require openai-php/client` and `composer require sentry/sentry`.

### Expected Result

Both librarys should be installable.

### Actual Result

Because of `php-http/discovery: ^1.11, <1.15` it is not possible to install sentry. Maybe it is possible to upgrade `php-http/discovery` to a newer version?

**Comment by stayallive** [comment]
See https://github.com/getsentry/sentry-php/pull/1504
We need to do some more testing, so expect a release next week.

**Comment by regnerisch** [comment]
Thanks :) This would be awesome

**Comment by ankurk91** [comment]
3.17 released
