### ISSUE TITLE
"Extra" data send in captureMessage() does not appear in Sentry

### ISSUE THREAD

**Issue by ruedigerm-playster** [getsentry/sentry-php#1512]
### Environment

I use 

- "laravel/framework": "9.52.5",
- "sentry/sentry-laravel": "3.3.2"

### Steps to Reproduce

I added this code in my api route file
```
Route::get('/debug-sentry', function () {
    app('sentry')->captureMessage(
        'Sentry Test message',
        Severity::info(),
        EventHint::fromArray(['extra' => ['name' => 'rudi']])
    );
    return response()->json([
        'status' => 'ok'
    ]);
});
```

### Expected Result

I expect to see the "extra" information (name => rudi) in the issue that I generated.

### Actual Result

The issue is created, but there is no extra info in the issue on the Sentry website present.

Am I doing something wrong, or is this a bug?

**Comment by ruedigerm-playster** [comment]
@cleptric I basically just want to "enrich" the captured message with some meta information.
e.g. after an API call I wanna capture the response payload.

Up until now I sometimes serialized the payload and set it as the "message", but that doesn't seem like the right approach and it looks ugly.

To me, the "setContext()" would be more appropriate if I wanna set a context for the full request (e.g. set email, userId...), but it seems overly complex (using closure and 2 function calls) for just adding some meta-info to the message, like for my API response example.

Would you see any smarter way for what I wanna do?

**Comment by stayallive** [comment]
The `withScope` is exactly made for this purpose, that changes made to the scope only live for as long as the closure runs so your example:

```php
Route::get('/debug-sentry', function () {
    \Sentry\withScope(function (\Sentry\State\Scope $scope) {
        $scope->setContext('extra', [
            'name' => 'rudi',
        ]);

        \Sentry\captureMessage('Sentry Test message', \Sentry\Severity::info());
    });

    return response()->json([
        'status' => 'ok'
    ]);
});
```

Do keep in mind that the `setExtra` exists on the `$scope` but it is technically deprecated in the product and we advise you to use a context of some description (which you could still name "extra" but better to choose something more descriptive for your use case):

> In addition to structured contexts, Sentry supports adding unstructured "Additional Data" via `set_extra`. Additional Data is deprecated in favor of structured contexts and should be avoided when possible.
> https://docs.sentry.io/platforms/php/guides/laravel/enriching-events/context/#additional-data

**Comment by ruedigerm-playster** [comment]
ok thanks for explaining. I wrote a little helper function to make it easier to use for me

```
    public static function sentryCaptureMessage(
        string $message,
        Severity $severity,
        array $data = [],
        string $contextNamespace = 'Custom Context'
    ): void
    {
        withScope(function (Scope $scope) use ($message, $severity, $data, $contextNamespace) {
            if ($data) {
                $scope->setContext($contextNamespace, $data);
            }

            captureMessage($message, $severity);
        });
    }
```

**Comment by stayallive** [comment]
Sounds good. Thanks for sharing 🙏
