### ISSUE TITLE
Add maglnet/composer-require-checker in CI

### ISSUE THREAD

**Issue by Jean85** [getsentry/sentry-php#1521]
### Problem Statement

https://github.com/getsentry/sentry-symfony/issues/714#issuecomment-1525083220:

> Btw, _sentry/sentry_ has the same issue in `GuzzleTracingMiddleware`.

### Solution Brainstorm

@cleptric we should avoid similar issues in the future by adding https://packagist.org/packages/maglnet/composer-require-checker in CI

_Originally posted by @Jean85 in https://github.com/getsentry/sentry-symfony/issues/714#issuecomment-1523646872_

We can also use https://packagist.org/packages/irstea/composer-require-checker-shim if we don't want to pollute our dependencies.

**Comment by Jean85** [comment]
Same as https://github.com/getsentry/sentry-symfony/issues/716

**Comment by ste93cry** [comment]
The `GuzzleTracingMiddleware` class is not used by this package and it was provided mostly as an example for the tracing feature itself. I don't think we should require a package used by it if the class itself is optional.

**Comment by cleptric** [comment]
With 4.0 I think we're good here.
