### ISSUE TITLE
Expose custom params in exceptions

### ISSUE THREAD

**Issue by erickskrauch** [getsentry/sentry-php#1524]
### Problem Statement

For example, I have such a code:
```php
final class NotOkStatusException extends \Exception {

    public function __construct(public readonly string $status) {
        parent::__construct("The response from external provider wan't \"OK\"");
    }

}
```

I successfully get an exception in Sentry, but I don't see what the `status` was. And I can't find any way to get into the serialization process to expose this value after all.

### Solution Brainstorm

There is already exists `class_serializers` param which allows to write custom serializers for params. But it doesn't apply to exceptions.

It seems that some separate mechanism for handling exceptions is needed. In the simplest case, you could just collect all the public exception fields and display them in Sentry. But before `readonly` properties, most were private and obtained through getters. Therefore, we need a mechanism to describe custom exception serialization depending on the needs of the end developers.

I couldn't find a mechanism in the Sentry message standard that would allow me to pass custom fields for an exception. If you point me to them, I can try implementing this functionality and send you a PR.

**Comment by cleptric** [comment]
Depending on your use case, you can add arbitrary data manually to the `ExceptionMechnsim`. This can be achieved like https://github.com/getsentry/gib-potato/blob/main/src/Error/SentryErrorLogger.php#L40-L49

You can also further enrich the data sent to Sentry inside [before_send](https://docs.sentry.io/platforms/php/configuration/options/?original_referrer=https%3A%2F%2Fwww.google.com%2F#before-send).

**Comment by erickskrauch** [comment]
Unfortunately, I wasn't able to use `mechanism`'s `data` field. I debugged it: the data is presented on the PHP side, but it seems, that Sentry filters out any unknown fields from `data` and keeps only `code`. So I wrote it differently (in `before_send`):

```php
if ($hint?->exception instanceof Sentry\Serializer\SerializableInterface) {
    $exception = $hint->exception;
    $event->setExtra(array_merge($exception->toSentry(), $event->getExtra()));
}
```

But there are some problems here:
1. If an exception has a parent, its parameters will not be serialized. It is possible to do a recursive search for all ancestors, but this leads us to the following problem.
1. There is no way to bind data to a particular exception. I can introduce a prefix based on the exception name, but if the parent has the same type as any exception in the chain, there will still be a collision.

I don't see a simple solution here, other than extending the Sentry message standard by allowing custom data to be attached to exceptions. However, this would require both changes to the standard and tweaks to the Sentry web interface itself.

**Comment by cleptric** [comment]
![Screenshot 2023-05-15 at 17 43 53](https://github.com/getsentry/sentry-php/assets/6617432/50ed2510-9210-40d5-b8d8-2563207a48cc)

I can attach unknown fields to the mechanism just fine, see `foo: bar`.

**Comment by erickskrauch** [comment]
Oh, how fast time flies. I'm temporarily forced to switch to another task. But this issue is not over yet. I will return to it as soon as I have time.

**Comment by cleptric** [comment]
I'm closing this for the time being as setting abatiary data on the mechanism seems to work fine.
Happy to re-open if you find any other issues with that.
