### ISSUE TITLE
Transport exceptions are swallowed

### ISSUE THREAD

**Issue by olsavmic** [getsentry/sentry-php#1527]
### Problem Statement

Currently `\Sentry\Client::captureEvent` swallows all exceptions thrown by underlying Transport.
```
        try {
            /** @var Response $response */
            $response = $this->transport->send($event)->wait();
            $event = $response->getEvent();

            if (null !== $event) {
                return $event->getId();
            }
        } catch (\Throwable $exception) {
        }
```

this has lead us in wrong directions on several occasions, especially in case of "413 Request Entity Too Large" error.
(Even though we can see the error logs in raw format, so no data is lost, we were trying to discover what's wrong with our application as it sentry issue was missing instead of solving the actual problem).

This issue has been discussed and closed for no visible reason in 
I'd like to reopen https://github.com/getsentry/sentry-php/pull/1322.

### Solution Brainstorm

I understand that the intent was to prevent an infinite loop where exceptions would be logged over and over. The HttpTransport already calls logger->error though in case of network failure for example. 

Therefore, in order to prevent breakage of existing custom instrumentations, I assume it would be OK to just add an error log before the return statement in the Transport implementation.

`\Sentry\Transport\HttpTransport::send`
```
...
        if (ResponseStatus::success() === $sendResponse->getStatus()) {
            return new FulfilledPromise($sendResponse);
        }

       // log error here

       return new RejectedPromise($sendResponse);
}
```

**Comment by cleptric** [comment]
As I literally just ran into the same issue myself, I'll tackle this in the upcoming weeks.

**Comment by cleptric** [comment]
We added a new `logger` option in [4.0.0](https://github.com/getsentry/sentry-php/releases/4.0.0) which makes surfacing these errors more easy.
