### ISSUE TITLE
Package is using abandoned php-http/message-factory

### ISSUE THREAD

**Issue by akshayakbm** [getsentry/sentry-php#1535]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

3.3.0

### Steps to Reproduce

docker alpine:3.18.0  
php version v8.1.19

PHP throws an error for an abandoned package internally used by the sentry package. Throws this fatal error message 
`Fatal error: Uncaught LogicException: You cannot use "Symfony\Component\HttpClient\HttplugClient" as the "php-http/message-factory" package is not installed. Try running "composer require nyholm/psr7". in /home/test_user/www/test-case/vendor/symfony/http-client/HttplugClient.php:49 Stack trace: #0 /home/test_user/www/test-case/vendor/composer/ClassLoader.php(582): include() #1 /home/test_user/www/test-case/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}('...') #2 [internal function]: Composer\Autoload\ClassLoader->loadClass('...') #3 /home/test_user/www/test-case/vendor/sentry/sentry/src/HttpClient/HttpClientFactory.php(113): class_exists('...') #4 /home/test_user/www/test-case/vendor/sentry/sentry/src/HttpClient/HttpClientFactory.php(91): Sentry\HttpClient\HttpClientFactory->resolveClient(Object(Sentry\Options)) #5`

### Expected Result

Just installing composer "sentry/sdk" should work fine without any external package installation.

### Actual Result

`Fatal error: Uncaught LogicException: You cannot use "Symfony\Component\HttpClient\HttplugClient" as the "php-http/message-factory" package is not installed. Try running "composer require nyholm/psr7". in /home/test_user/www/test-case/vendor/symfony/http-client/HttplugClient.php:49 Stack trace: #0 /home/test_user/www/test-case/vendor/composer/ClassLoader.php(582): include() #1 /home/test_user/www/test-case/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}('...') #2 [internal function]: Composer\Autoload\ClassLoader->loadClass('...') #3 /home/test_user/www/test-case/vendor/sentry/sentry/src/HttpClient/HttpClientFactory.php(113): class_exists('...') #4 /home/test_user/www/test-case/vendor/sentry/sentry/src/HttpClient/HttpClientFactory.php(91): Sentry\HttpClient\HttpClientFactory->resolveClient(Object(Sentry\Options)) #5`

**Comment by cleptric** [comment]
Please see https://github.com/getsentry/sentry-php/issues/1533

**Comment by akshayakbm** [comment]
@cleptric  Thank you for considering the issue.

**Comment by cleptric** [comment]
So to confirm, did version 3.18.2 fixed your issue?
