### ISSUE TITLE
Replace deprecated dependency php-http/message-factory

### ISSUE THREAD

**Issue by Radyum** [getsentry/sentry-php#1543]
### Problem Statement

Hello,

The sentry/sentry package requires php-http/message-factory which is deprecated. It creates a deprecation warning in Composer in my projects running with Sentry.

### Solution Brainstorm

The suggested replacement package is psr/http-factory

**Comment by Jean85** [comment]
Duplicate of #1541

**Comment by Radyum** [comment]
My bad :)
