### ISSUE TITLE
fromHeaders method resolution fails in TransactionContext

### ISSUE THREAD

**Issue by maurocolella** [getsentry/sentry-php#1544]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

3.19.1

### Steps to Reproduce

1. Install sentry (with composer).
2. Install sentry Laravel (on Laravel 8).
3. Configure, per: https://docs.sentry.io/platforms/php/guides/laravel
4. In [`sentry-laravel/src/Sentry/Laravel/Tracing/Middleware.php`, L108](https://github.com/getsentry/sentry-laravel/blob/master/src/Sentry/Laravel/Tracing/Middleware.php#L108), `fromHeaders` is not resolved whether through static analysis or live when using the libraries.
5. However, the method is clearly defined in:
https://github.com/getsentry/sentry-php/blob/master/src/Tracing/TransactionContext.php#L3

This was tested using two different PHP runtimes (7.4 and 8.1), with sentry-laravel 3.4.0.

### Expected Result

For the method to be resolved successfully.

### Actual Result

![image](https://github.com/getsentry/sentry-php/assets/761780/0bc9e6f5-445e-405a-97f3-289f285a9654)

**Comment by Jean85** [comment]
Wrong repository, this has to be moved to `sentry-laravel`

**Comment by maurocolella** [comment]
Kindly note that the unresolved method is defined in `sentry-php`, not `sentry-laravel`.

**Comment by Jean85** [comment]
Can you double-check which version of `sentry/sentry` you have? Use `composer show sentry/sentry`

**Comment by maurocolella** [comment]
```
name     : sentry/sentry
descrip. : A PHP SDK for Sentry (http://sentry.io)
keywords : crash-reporting, crash-reports, error-handler, error-monitoring, log, logging, sentry
versions : * 3.19.1
```

```
name     : sentry/sentry-laravel
descrip. : Laravel SDK for Sentry (https://sentry.io)
keywords : crash-reporting, crash-reports, error-handler, error-monitoring, laravel, log, logging, sentry
versions : * 3.4.1
```

**Comment by stayallive** [comment]
This makes little sense 😅 you have the correct versions and everything...

Can you try removing your `vendor` folder and running `composer install` again to re-download/re-build the vendor folder? Maybe something is amiss there but this method is present in that version and I can't figure out what else could be wrong.

If that is not working, please share your full `composer.json` so we can try to investigate further.

**Comment by maurocolella** [comment]
So, good news. I did clear my `vendor` folder and `composer install`, and it confirmed the fluke.

Everything is working as expected now. Sorry for the false flag, and thank you for the prompt reaction.

**Comment by stayallive** [comment]
No worries, better you ask one time too many than too little! Thanks for reporting back.
