### ISSUE TITLE
Required package php-http/message-factory is abandoned

### ISSUE THREAD

**Issue by rintdev** [getsentry/sentry-php#1545]
### Problem Statement

The latest version of sentry/sentry (3.19.1) is using the abandoned package php-http/message-factory (^1.1). 

As said in https://github.com/php-http/message-factory: This package will remain available for the time being to not break legacy code, but we encourage everybody to move to PSR-17.

### Solution Brainstorm

Upgrade to PSR-17.

**Comment by stayallive** [comment]
Duplicate of #1541 (will be fixed at a later date).
