### ISSUE TITLE
Normalize `http.response.status_code` for Metrics & Alerts

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-php#1564]
## Description

Please see the project description: https://github.com/getsentry/team-sdks/issues/9

---

For `http.client` spans, set the response status code on `span.data.http.response.status_code`. See https://develop.sentry.dev/sdk/performance/span-data-conventions/#http

For `http.server` transaction, set the response status code on `event.contexts.response`. See https://github.com/getsentry/relay/blob/master/relay-general/src/protocol/contexts/response.rs

**Comment by mfb** [comment]
Currently for http.server transactions, this method adds an http.status_code tag: https://github.com/getsentry/sentry-php/blob/95d3d3a518010299fc928609ddb05f0067f0b6ac/src/Tracing/Span.php#L244
