### ISSUE TITLE
PHP Fatal error:  Access to undeclared static property: Raven_SanitizeDataProcessor::$values_re

### ISSUE THREAD

**Issue by ablyler** [getsentry/sentry-php#159]
This is with version 0.8.0:

PHP Fatal error:  Access to undeclared static property: Raven_SanitizeDataProcessor::$values_re in .../vendor/raven/raven/lib/Raven/SanitizeDataProcessor.php on line 20

**Comment by ste93cry** [comment]
Closing this as it should be fixed in recent versions of the library
