### ISSUE TITLE
TypeError not reported by Sentry using defaults

### ISSUE THREAD

**Issue by socialpresencenetwork** [getsentry/sentry-php#1590]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

3.18.2

### Steps to reproduce

```php
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require './vendor/autoload.php';
\Sentry\init([
    'dsn' => 'DSN GOES HERE',
    'sample_rate' => 1,
]);

class a {
    public function test()
    {
        $this->foo = new stdClass();
         // Throws an uncaught TypeError
        $this->foo->tags = array_diff($this->foo->tags, []);
    }
}

$a = new a();
$a->test();
```

php.ini also has error reporting as such:
`error_reporting = E_ALL`

### Expected result

Expected result is an entry in the Sentry SaaS platform.

### Actual result

No exception/error entry is added and the problem goes unnoticed.

**Comment by Jean85** [comment]
Confirmation that the snippet produces a type error (but also a warning, and a deprecation under 8.2): https://3v4l.org/3MhoR

**Comment by cleptric** [comment]
I'm not able to reproduce the issue you're seeing.
Executing your script hails two issues in Sentry for me.
