### ISSUE TITLE
Allow Symfony 7

### ISSUE THREAD

**Issue by garak** [getsentry/sentry-php#1596]
### Problem Statement

Symfony 7 will be released next month, it would be nice to get libraries ready before that moment (to allow maintainers of other libs to test it before the release)
By the way, I see the CI configuration in this lib is still using Symfony versions which are not currently supported (e.g. Symfony 3.4)

### Solution Brainstorm

I can propose a pull request to allow Symfony 7 in composer.json and to update the CI accordingly

**Comment by cleptric** [comment]
We won't drop `symfony/options-resolver:3.0` in version 3.0 of this SDK anymore, but it's gone in the upcoming version 4.0.

Adding support for `symfony/options-resolver:7.0` sounds reasonable though, I opened #1597.

**Comment by garak** [comment]
Un update is required in https://github.com/getsentry/sentry-php-sdk as well

**Comment by cleptric** [comment]
We'll release these changes tomorrow.
