### ISSUE TITLE
Error level determination problem

### ISSUE THREAD

**Issue by gabe777** [getsentry/sentry-php#161]
In case of php versions where chained exceptions are enabled, php error levels are not determined correctly (each ends up as default 'error') in `Raven_Client::captureException`.

As it seems this is due to going up in the exception chain at line 251 leaves the `$exception` variable to be `NULL` at the last iteration. (`$exception = $exception->getPrevious()`). 

It is not obvious for me if the level determination (starting at at line 261) is done after the iteration on purpose, but my suggestions would be:
- either to do the whole level determination before the iteration
- or to store the original exception object in a variable before the iteration and use that for determination of severity (error level).

Thank you,
GP

**Comment by stayallive** [comment]
@gabe777 I know a really long time passed but if please do let us know if this is still a problem in the latest SDK version so we can investigate further! Closing this for know.
