### ISSUE TITLE
Symfony/Options-resolver issue when Sentry will be initialized

### ISSUE THREAD

**Issue by neilexfafet** [getsentry/sentry-php#1634]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

4.0

### Steps to reproduce

Issue will display after initialization of Sentry (\Sentry\init(['dsn' => 'MY_SENTRY_DSN']))

### Expected result

Sentry should be able to initialize.

### Actual result

Parse error: syntax error, unexpected 'bool' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /usr/src/app/vendor/symfony/options-resolver/OptionsResolver.php on line 146

**Comment by cleptric** [comment]
Please provide a bit more info about your environment, like PHP version used etc.

**Comment by Jean85** [comment]
That seems an error that would be triggered under PHP below 7.4, and with `symfony/option-resolver` 6.3+, which [requires PHP 8.1+](https://github.com/symfony/symfony/blob/c2ba01eeb246d82652714a2e01a984c0f30ae474/src/Symfony/Component/OptionsResolver/composer.json#L19)

You should check your environment when using `composer update`, or your PHP constraints in `composer.json`.

**Comment by neilexfafet** [comment]
> Please provide a bit more info about your environment, like PHP version used etc.

PHP version was recently upgraded from 7.2 to 8.2

**Comment by neilexfafet** [comment]
> That seems an error that would be triggered under PHP below 7.4, and with `symfony/option-resolver` 6.3+, which [requires PHP 8.1+](https://github.com/symfony/symfony/blob/c2ba01eeb246d82652714a2e01a984c0f30ae474/src/Symfony/Component/OptionsResolver/composer.json#L19)
> 
> You should check your environment when using `composer update`, or your PHP constraints in `composer.json`.

Already tried composer update, as well as downgrading the version of sentry and the option-resolver, still the issue occurs.

**Comment by neilexfafet** [comment]
> That seems an error that would be triggered under PHP below 7.4, and with `symfony/option-resolver` 6.3+, which [requires PHP 8.1+](https://github.com/symfony/symfony/blob/c2ba01eeb246d82652714a2e01a984c0f30ae474/src/Symfony/Component/OptionsResolver/composer.json#L19)
> 
> You should check your environment when using `composer update`, or your PHP constraints in `composer.json`.

After multiple checks, i found out some docker container issues which it did not upgrade my php version but on my docker file it says 8.2. Issue already resolved. Thanks for the help!
