### ISSUE TITLE
[doc] "ignore" configuration options are missing in doc

### ISSUE THREAD

**Issue by smknstd** [getsentry/sentry-php#1643]
### Problem Statement

Two options `ignore_exceptions` and `ignore_transactions` has been added to the config in https://github.com/getsentry/sentry-php/pull/1503

But those are missing from doc https://docs.sentry.io/platforms/php/configuration/options/

### Solution Brainstorm

Mention them in doc please :)

**Comment by cleptric** [comment]
Docs added in https://github.com/getsentry/sentry-docs/pull/8552.
