### ISSUE TITLE
Support for OpenTelemetry

### ISSUE THREAD

**Issue by shyim** [getsentry/sentry-php#1646]
### Problem Statement

Want to push my existing OTEL spans to Sentry. This seems to be possible with other languages, but not PHP?

https://sentry.io/for/opentelemetry/

### Solution Brainstorm

Add support for OTEL

**Comment by cleptric** [comment]
How did you instrument your application?

**Comment by shyim** [comment]
With https://github.com/opentelemetry-php/contrib-auto-symfony

To clear out directly: I just want to have a "Sentry exporter" (I know I could use Sentry directly, but then it's coupled to it), so I can be independent in my code with OTEL and just have the created spans in Sentry.

**Comment by cleptric** [comment]
Have a look at https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/sentryexporter, an exporter is out of scope of the SDK.

**Comment by smeubank** [comment]
> Have a look at https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/sentryexporter, an exporter is out of scope of the SDK.

for anyone else on this issue, the exporter is not supported by Sentry, it is a community exporter
