### ISSUE TITLE
Profiling/Performance not recorded

### ISSUE THREAD

**Issue by tobyberster** [getsentry/sentry-php#1674]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

4.0.0

### Steps to reproduce

I've followed the instructions on how to set up profiling ( https://docs.sentry.io/platforms/php/profiling/ ) and installed excimer via pecl, and checked via phpinfo() that it is loaded properly.

The following code instantiates sentry in a bootstrap.php file:
```
\define('SENTRY_DSN', 'xxx');
\define('SENTRY_ENV', 'prod');
\define('SENTRY_TRACES_SAMPLE_RATE', 1.0);
\define('SENTRY_PROFILES_SAMPLE_RATE', 1.0);
Sentry\init([
        'dsn' => SENTRY_DSN,
        'traces_sample_rate' => SENTRY_TRACES_SAMPLE_RATE,
        'profiles_sample_rate' => SENTRY_PROFILES_SAMPLE_RATE,
        'environment' => SENTRY_ENV,
    ]);
```

Sentry itself works as expected for a while now.

I'm unable to receive/see performance and/or profiling data. I was able to follow the example of triggering a transaction manually which was recorded. But more general traffic does not get profiled and/or transmitted to sentry.

I reached out to the Support team, but they've referred me over to here for further assistance.

### Expected result

Performance/Profiling data shows up in sentry

### Actual result

Nothing shows up. Not sure what logs or screenshots to provide. Happy to share more personal data in a private forum.

**Comment by cleptric** [comment]
The profiler will only work inside a transaction, as they are both tied together.
So you would need to instrument your application to create at least a transaction and the profiler will start doing its thing. (*If your transaction is longer than 20ms, as we require at least two samples for a profile).

**Comment by pyr0hu** [comment]
@cleptric When using the official PHP integrations (Laravel/Symfony), it should automatically create the transactions, right?

**Comment by cleptric** [comment]
If you enable it, by setting a `traces_sample_rate` greater than `0.0`, it does, yes.
