### ISSUE TITLE
PHP7 compatibility

### ISSUE THREAD

**Issue by ohtyap** [getsentry/sentry-php#1675]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

^4.3

### Steps to reproduce

`DebugStdOutLogger` and `DebugFileLogger` are having this method signature:

```
public function log($level, \Stringable|string $message, array $context = []): void
```

This isn't compatible with PHP7

### Expected result

The code should be either compatible with `"php": "^7.2|^8.0"` (as defined in `composer.json`) or the php requirement in `composer.json` should remove `^7.2`

### Actual result

Syntax error when using within PHP7.

**Comment by cleptric** [comment]
The logger we provide is only compatible with the current PSR3 logger interface. We will add additional loggers in the future, for now, please create your own.

**Comment by anibalsanchez** [comment]
On a site with PHP PHP 8.0.28 and composer 2.2.18, after installing sentry/sentry 4.4.0, I'm getting the error:

Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0".

**Comment by Jean85** [comment]
> Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0".

These are issues bound to your dev environment or other dependencies: your last execution of Composer was done under PHP 8.1 (probably locally) and you produced a `composer.lock` for that version. Use a proper local dev environment with the right version of PHP to fix it.

**Comment by Jean85** [comment]
> The logger we provide is only compatible with the current PSR3 logger interface.

@cleptric the PSR-3 has been updated that way, but you still may use the previous signature (with wider argument types, but stricter return type) and maintain backward compatibility, see [PSR Evolution](https://www.php-fig.org/bylaws/psr-evolution/) for further details. As a practical example, see: https://3v4l.org/GivGp
