### ISSUE TITLE
Raven_ErrorHandler::handleFatalError() handles E_STRICT messages

### ISSUE THREAD

**Issue by raebbar** [getsentry/sentry-php#168]
Raven_ErrorHandler::handleFatalError() handles E_STRICT errors and not only fatal errors. 

Only errors of the types E_ERROR | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING should be handled

**Comment by justiniso** [comment]
+1 can we get this change merged into the official library?

**Comment by madssj** [comment]
A solution to this was implemented in bc88ec3a9fa14df4f36ff9ca08b0396b855db4fd and f89ecb3c3a58d5dce8812d5adaeadab8c56c7918 and released in `0.12.0`.

**Comment by madssj** [comment]
Also see #181.

**Comment by jamieburchell** [comment]
I've just run in to this one. I'm getting strict notices reported from the handleFatalError function, but I've set up the client like so:

```
$handler = new Raven_ErrorHandler($client, false, null, E_ALL & ~E_NOTICE & ~E_STRICT);
$handler->registerExceptionHandler();
$handler->registerErrorHandler();
$handler->registerShutdownFunction();
```

Is my understanding of how this should work incorrect, or should the client only report on those types passed in to the constructor?

**Comment by dcramer** [comment]
@jamieburchell it looks like handleFatalError doesn't correctly deal w/ the changes to the newer types. Frankly, we need to go back over this, remove the old option, and ensure all things are using the new "these really are the only error codes I want to capture" bits.

**Comment by dcramer** [comment]
@jamieburchell short term work around, try passing that same value where you have null (the third arg)

**Comment by jamieburchell** [comment]
I've just run in to this issue again and stumbled back here :)

Error reporting is actually turned off in my case (`error_reporting(0)`) but I'm still getting the strict/info messages appearing in Sentry. `handleFatalError` is not factoring in the current error reporting level like `handleError` is. For now I got around it using:

```
$handler = new Raven_ErrorHandler($this->_client, false, [
	E_ERROR,
	E_PARSE,
	E_CORE_ERROR,
	E_CORE_WARNING,
	E_COMPILE_ERROR,
	E_COMPILE_WARNING
]);
```
