### ISSUE TITLE
Sentry ignores error suppression operator in PHP

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry-php#170]
Quote:

I'm using CakePHP and part of my application serves files to users via PHP. Cake's method of doing this includes calls to a function that contains the following lines:
@flush;
@ob_flush;

This causes a problem because Sentry reports the errors that come back from these calls:
ob_flush([8,"ob_flush(): failed to flush buffer. No buffer to flush" and in doing so outputs the file contents to the Sentry log! This means the response time to serve the files increases by an order of magnitude.

**Comment by willemstuursma** [comment]
I have the same issue.

The error suppression operator is useful, many PHP functions raise an error as well as return a specific value. If you want to check the return value, you will need to suppress the error.

**Comment by dcramer** [comment]
Going to close in favor of GH-332 since it is a bit more detailed

**Comment by ryanhughes** [comment]
For anyone who has followed the docs and is trying to find out why suppressed errors are still being reported to sentry, the following worked in my case.

```php
$error_handler = new Raven_ErrorHandler($client);

$error_handler->registerExceptionHandler(false);
$error_handler->registerErrorHandler(false);
$error_handler->registerShutdownFunction(false);
```
