### ISSUE TITLE
Unescaped data passed to bash

### ISSUE THREAD

**Issue by pornel** [getsentry/sentry-php#171]
Proper escaping of data in bash is quite tricky, so it's best to always use [`escapehsellarg`](http://php.net/manual/en/function.escapeshellarg.php).

https://github.com/getsentry/raven-php/blob/8534b131f296597c163cbc408ac2d914f43a1a2c/lib/Raven/Client.php#L572

Secure escaping may also fix the problem mentioned in https://github.com/getsentry/raven-php/blob/8534b131f296597c163cbc408ac2d914f43a1a2c/lib/Raven/Client.php#L488

**Comment by Jean85** [comment]
Closing this since in 2.0 we will be ditching curl exec calls in favor of an actual client.
