### ISSUE TITLE
Initialize the SDK using php auto-prepend-file

### ISSUE THREAD

**Issue by azenned** [getsentry/sentry-php#1712]
### Problem Statement

As the SDK need to be initialised as early as possible in  the application ( \Sentry\init(['dsn' => '___PUBLIC_DSN___' ]); ) 
And the SDK require composer to be loaded , we are missing all composer loader profiling data.

### Solution Brainstorm

Can we use php auto-prepend-file directive to load minimalist php script file and init the SDK ?
https://www.php.net/manual/en/ini.core.php#ini.auto-prepend-file

**Comment by stayallive** [comment]
> we are missing all composer loader profiling data.

If it's just for performance tracing reasons there is another solution. Add a `define('APP_START', microtime(true));` to your entry file as the first line, this way you can just after loading composer set another timestamp all the way up until you are loading Sentry. 

You can then backdate the spans accordingly. We do this [for example](https://github.com/getsentry/sentry-laravel/blob/1b7fc230d940ca6544ffee9195858715170bf166/src/Sentry/Laravel/Tracing/Middleware.php#L238-L252) in our Laravel SDK.

Unless I'm missing something I think the minimal auto-prepend file would look just like that (defining a timestamp) and nothing more really.
