### ISSUE TITLE
Ability to filter request input from being sent to Sentry

### ISSUE THREAD

**Issue by dwightwatson** [getsentry/sentry-php#1724]
### Problem Statement

I would like an easy way to configure this integration from sending certain request input to Sentry. Right now the documentation suggests we use the `before_send` configuration option, but this has two issues.

1. It's a painful amount of code for something very simple. Plus, I couldn't find any ready to go documentation on how to implement it.

```php
'before_send' => function (Event $event, ?EventHint $hint): ?Event {
    $request = $event->getRequest();

    if ($data = Arr::get($request, 'data')) {
        foreach (['password', 'password_confirmation'] as $field) {
            if (Arr::has($data, $field)) {
                $data[$field] = '[FILTERED]';
            }
        }

        $request['data'] = $data;

        $event->setRequest($request);
    }

    return $event;
},
```

2. It isn't supported when using `config:cache`. The [docs suggest that I can use the callable array syntax](https://docs.sentry.io/platforms/php/guides/laravel/configuration/laravel-options/#closures-and-config-caching) but that doesn't seem to work for `before_send.
3. 
```
Symfony\Component\OptionsResolver\Exception\InvalidOptionsException 

The option "before_send" with value array is expected to be of type "callable", but is of type "array".
```

### Solution Brainstorm

Simplest solution would be config option that accepts an array of field names that would be removed or filtered before being sent to Sentry.

```php
'filter_fields' => ['password', 'password_confirmation'],
```

I note that Flare has more advanced options, including middleware that makes it easy to filter input and headers.

```php
CensorRequestBodyFields::class => [
    'censor_fields' => [
        'password',
        'password_confirmation',
    ],
],
CensorRequestHeaders::class => [
    'headers' => [
        'API-KEY',
        'Authorization',
        'Cookie',
        'Set-Cookie',
        'X-CSRF-TOKEN',
        'X-XSRF-TOKEN',
    ]
]
```

**Comment by cleptric** [comment]
Tracking this with https://github.com/getsentry/sentry-php/issues/1784, as part of the next major.
