### ISSUE TITLE
Feature request: User feedback capturing feature

### ISSUE THREAD

**Issue by JanMikes** [getsentry/sentry-php#1727]
### Problem Statement

There is API for sending user feedback, currently in beta. It would be awesome to add support to the official SDK to cover this Sentry feature.

The JavaScript SDK could do the job, but i want to not expose DSN to the user and have the feedback sent via backend with custom form and extra logic in PHP.

### Solution Brainstorm

Probably adding it to the `\Sentry\ClientInterface` + `\Sentry\State\HubInterface` is the way (and ofc to the implementation). 

My current solution is totally own sentry independent http client sending requests to `https://sentry.io/api/0/projects/{{organization_slug}}/:project_slug/user-feedback/` as documented in the official postman collection.

**Comment by cleptric** [comment]
The API is not ready yet and we lack proper defined APIs in the SDKs, too. Backlogging for now.

**Comment by cleptric** [comment]
I'm closing this issue. This does not mean we won't do it sometimes in the future, but as we didn't make any progress since April, it's not worth having it around.
