### ISSUE TITLE
Deprecated: Use of "static" in callables is deprecated in /app/vendor/sentry/sentry/src/Serializer/AbstractSerializer.php on line 264

### ISSUE THREAD

**Issue by emircanerkul** [getsentry/sentry-php#1730]
### How do you use Sentry?

Self-hosted / on-premises

### SDK version

4.6.1

### Steps to reproduce

Have no idea. I'm seeing this in one of our Drupal projects but not the other one. They both use the same version. And the same PHP 8.2. Using https://git.drupalcode.org/project/raven/tree/5.0.9

Linked issue: https://github.com/getsentry/sentry-php/pull/821

### Expected result

There should be no errors.

### Actual result

<img width="1264" alt="image" src="https://github.com/getsentry/sentry-php/assets/11430795/98de6d4b-2b26-4e9a-9b19-72d97e96124f">

**Comment by stayallive** [comment]
This error comes from the code that serializes values, so something being serialized is triggering this. Are you submitting events to Sentry on that page? Or is that page triggering events?

Are you using a Drupal plugin specifically or did you add the PHP SDK yourself to your project? If using a Drupal plugin have you raised the issue there already?

**Comment by emircanerkul** [comment]
@stayallive I didn't create an issue on drupal because it's more related to that sentry/sentry dependency. Shouldn't these checks be done within this package? Yes, something on the page is triggering this error.

**Comment by stayallive** [comment]
A reproduction or failing test would be very helpful here since I have no clue how to trigger this and I'm not setup for Drupal development (hence my suggestion/question if you asked there first) in case it's something Drupal specific. 

I'm sure we eventually have to tackle it here, but there it too little information to reproduce this for me at the moment.

**Comment by mfb** [comment]
This happens if a string happens to be a deprecated callable, and you run `is_callable()` on it.

Can sentry simply add `@` to its `is_callable()` calls to silence the deprecation?

Minimal reproduce case:

```php

require './vendor/autoload.php';

ini_set('error_reporting', E_ALL);
ini_set('zend.exception_ignore_args', FALSE);

\Sentry\init();

class foo {
  function __construct(string $bar) {
    \Sentry\captureException(new \Exception('doh!'));
  }
}

new foo('static::sort');
```

**Comment by cleptric** [comment]
Yes

**Comment by emircanerkul** [comment]
Thank you @mfb for the STP
