### ISSUE TITLE
PHP8.4 compat

### ISSUE THREAD

**Issue by staabm** [getsentry/sentry-php#1744]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

4.7.0

### Steps to reproduce

I think [this line](https://github.com/getsentry/sentry-php/blob/7ed28441a412ca15159e4b4ac3dde2c9f6a55350/src/FrameBuilder.php#L164) needs a change for PHP 8.4 compat - related to https://github.com/php/php-src/pull/13550

see analog symfony change: https://github.com/symfony/symfony/pull/54614

### Expected result

n/a

### Actual result

n/a

**Comment by cleptric** [comment]
Thanks, we'll tackle this closer to the PHP 8.4 release in November.

**Comment by stayallive** [comment]
I have started a PR and moved all your comments to #1760 to track.

Thanks for pointing this change out! If you have any other concerns feel free to comment on the PR!
