### ISSUE TITLE
empty REMOTE_ADDR throwing InvalidArgumentException when using option `send_default_pii: true`

### ISSUE THREAD

**Issue by aless673** [getsentry/sentry-php#1750]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

4.8.0

### Steps to reproduce

1. configure sentry.options.send_default_pii: true
2. in some cases, REMOTE_ADDR is an empty string (not null)
3. error is thrown `Uncaught Exception: The "" value is not a valid IP address.`

### Expected result

Sentry should not throw an exception but set a Unavailable status for the IP address. It should not stop the process of reporting errors because IP address is not available.

### Actual result

exception `InvalidArgumentException` is thrown with the message `Uncaught Exception: The "" value is not a valid IP address` and stop the process of reporting errors to sentry

**Comment by stayallive** [comment]
Agreed, this is indeed a bug, we had not considered it could be an empty string.

Going to be fixed with #1751, thanks for reporting!

**Comment by aless673** [comment]
> Agreed, this is indeed a bug, we had not considered it could be an empty string.
> 
> Going to be fixed with [#1751](https://github.com/getsentry/sentry-php/pull/1751), thanks for reporting!

exceptions still occurs when `RequestListener:59` call the `setIpAddress` method in `UserDataBag:221` with an empty IP `""`

**Comment by stayallive** [comment]
We are fixing this in getsentry/sentry-symfony#931, feel free to continue the conversation there if needed.
