### ISSUE TITLE
Add option to control stack trace size or local variables

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-php#1774]
### Problem Statement

In cases when events are dropped by the Sentry server side for being too large, being able to control the stack trace size and if local variables are added or not to each frame help reducing the event size. 

Currently, the only option is to reduce the number of context lines with `context_lines`. 

### Solution Brainstorm

Add options to limit stack trace size and opt out of local variables.

**Comment by cleptric** [comment]
I rather not add more options for this. Using `before_send`, people can implement this themselves.
