### ISSUE TITLE
CURL : Use CURLSSLOPT_NATIVE_CA on Windows to use system CA store

### ISSUE THREAD

**Issue by thomas-saigne** [getsentry/sentry-php#1775]
### Problem Statement

Hello,

I've got the following issue, due to the missing curl.cafile on windows...
`sentry/sentry: [error] Failed to send debug event [xxxxxxxxxx] to xxxxxxx [project:xx]. Reason: "cURL Error (60) SSL certificate problem: self-signed certificate in certificate chain".`
The problem is on PHP 8.3.8 with Sentry 4.9.0 on Windows, when on Linux, the same code works fine.
So I found 2 solutions with this article ([https://php.watch/articles/php-curl-windows-cainfo-fix](https://php.watch/articles/php-curl-windows-cainfo-fix))
1- Tell cURL to parse the system certificate store : `curl_setopt($ch, CURLOPT_SSL_OPTIONS, CURLSSLOPT_NATIVE_CA);` (seems pretty good 😃 )
2- Get and maintain my own curl.cafile on my project (seems pretty painfull 😢 )

But I can't change the option in curl since it's in the Sentry sdk.

Could you have a look please ? Thanks !

### Solution Brainstorm

In the original article, they give the full if to do it properly (could add a check if system is windows)
`if (defined('CURLSSLOPT_NATIVE_CA') && version_compare(curl_version()['version'], '7.71', '>=')) {`
`    curl_setopt($ch, CURLOPT_SSL_OPTIONS, CURLSSLOPT_NATIVE_CA);`
`}`

But it could also be an option as the httpSslVerifyPeer ?
[src/HttpClient/HttpClient.php::sendRequest](https://github.com/getsentry/sentry-php/blob/88c803ff8f94be0da133dc731d62ddc4ab9def70/src/HttpClient/HttpClient.php#L76)

**Comment by cleptric** [comment]
To make sure, disabling `CURLOPT_SSL_VERIFYPEER` does not work in your case?
Adding an additional option to define which cert store to use seems reasonable, we can add this.

**Comment by thomas-saigne** [comment]
Disabling `CURLOPT_SSL_VERIFYPEER` indeed works, but it's not the way we want it to be in production :/
Thank you for adding the option in the future :)

**Comment by cleptric** [comment]
https://www.php.net/manual/en/function.curl-setopt.php

Oh well 😬 

![Image](https://github.com/user-attachments/assets/c18fa1a1-dcb0-4986-b6d7-a605f2853780)

[CURLOPT_CAPATH](https://www.php.net/manual/en/curl.constants.php#constant.curlopt-capath) does not work on Windows though, https://curl.se/libcurl/c/CURLOPT_CAPATH.html.

**Comment by thomas-saigne** [comment]
> https://www.php.net/manual/en/function.curl-setopt.php
> 
> Oh well 😬
> 
> ![Image](https://github.com/user-attachments/assets/c18fa1a1-dcb0-4986-b6d7-a605f2853780)
> 
> [CURLOPT_CAPATH](https://www.php.net/manual/en/curl.constants.php#constant.curlopt-capath) does not work on Windows though, https://curl.se/libcurl/c/CURLOPT_CAPATH.html.

Yeah... Kind of a bummer to still have issues like this with curl in 2024 😢 
Fortunately, the php downloaded on windows.php.net is built to use OpenSSL ! 👍 

Thanks for the option !

**Comment by cleptric** [comment]
A new option is available in [4.10.0](https://github.com/getsentry/sentry-php/releases/tag/4.10.0).
