### ISSUE TITLE
trace_propagation_targets using exact match

### ISSUE THREAD

**Issue by kkmuffme** [getsentry/sentry-php#1782]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

4.9.0

### Steps to reproduce

https://docs.sentry.io/platforms/php/configuration/options/#trace-propagation-targets

>Entries do not have to be full matches, meaning the URL of a request is matched when it contains a string provided through the option.

when looking at the code https://github.com/getsentry/sentry-php/blob/master/src/Tracing/GuzzleTracingMiddleware.php#L141 this does not seem to be the case though, since it's only checking the host with `in_array`

### Expected result

[trace_propagation_targets](https://docs.sentry.io/platforms/php/configuration/options/#trace-propagation-targets) should behave as documented (which is how it (correctly) works in other SDKs, e.g. JS)

### Actual result

Exact match check

**Comment by stayallive** [comment]
We might want to change this behavior in the future but because that would be a breaking change (especially considering how it works now) I've opted to change the documentation to be correct instead for now: getsentry/sentry-docs#11500.
