### ISSUE TITLE
Request headers are being sent as arrays

### ISSUE THREAD

**Issue by vanschelven** [getsentry/sentry-php#1792]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

any

### Steps to reproduce

her's the spec:

https://github.com/getsentry/sentry-data-schemas/blob/6d2c435b8ce3a67e2065f38374bb437f274d0a6c/relay/event.schema.json#L2039C5-L2039C6

But the php client sends its header values as an array.

I'm sure this is normalized somewhere in the relay or elsewhere, but it's not correct according to the spec

### Expected result

Stick to the spec

### Actual result

Not sticking to the spec

**Comment by cleptric** [comment]
As far as I am concerned, Sentry SaaS and Sentry self-hosted both are able to ingest events from the PHP SDK just fine, so I don't see a reason to make this change.
