### ISSUE TITLE
Transport: fsockopen

### ISSUE THREAD

**Issue by CrazyLionHeart** [getsentry/sentry-php#180]
Is it possible using unstead curl fsockopen? If server does not have curl extension sending event to Sentry not possible

**Comment by ste93cry** [comment]
I know this reply cames really really late, by the way I don't think this will be ever possible in `1.x` version of this library. However, if you still need it you may look at the (still in development) `2.0` version that with the help of [`HTTPlug`](https://github.com/php-http/httplug) will support customizable transports. For now, I'm going to close this
