### ISSUE TITLE
[proposal] Make 1.0 support PHP 5.3+ and use PSR4

### ISSUE THREAD

**Issue by ameliaikeda** [getsentry/sentry-php#192]
PHP 5.2 is long buried and was [end-of-life](https://php.net/eol.php)'d 4 years ago. No major server distro (debian, ubuntu, centos, redhat, fedora, freebsd) provides updates any more, and custom repositories just for this purpose have since stopped giving security updates to 5.2.17<sup>([1](https://webtatic.com/packages/php53/), [2](https://code.google.com/p/php52-backports/) - last updated almost 2 years ago)</sup>.

PHP 5.3 is also [no longer supported](https://php.net/supported-versions.php), but third parties will still likely give 5.3 updates for a few years in response to CVEs, at least.

Rather than encourage people to keep some pretty old configurations up, why not overhaul for a new major release and use [PSR4](http://www.php-fig.org/psr/psr-4/)? raven-php already uses composer, and you can bet quite heavily that pretty much every recent PHP developer using symfony2/laravel/zf2 (or anything else using composer) will jump on the new version like wildfire (rather than using another package that proxies `Raven_*` in order to allow namespaces or just cleaner interfaces to be used).

I can spend the weekend preparing a pull request for this (It's a major change, but namespaces have been in PHP for half a decade now and developers have come to expect them).

Proposal:
- [ ] Start a new branch for namespace support (`1.0` or `php53`, etc)
- [ ] Tag a `1.0` release on the new branch
- [ ] Actively maintain both branches for a short while (possibly 3 months, more if the community offers)
- [ ] Once active maintenance is finished, stick to security updates
- [ ] Stick to [semver](http://semver.org) for releases; `0.*.*` is 5.2+, `1.*.*` is 5.3+

In addition, issues such as #171, as well as general use of `exec` by the package, could be abstracted by a HTTP library such as [Guzzle](https://github.com/guzzle/guzzle) or [Buzz](https://github.com/kriswallsmith/Buzz) (and could use interfaces).

Also, as a minor proof of how non-existant PHP 5.2 support is, [redhat 5](https://access.redhat.com/support/policy/updates/errata/) actually [ships with PHP 5.1.6](http://distrowatch.com/table.php?distribution=redhat) (almost 9 years out of date, but they maintain it), and they're supporting that until November 30 2020 for paid customers, but there is absolutely zero support for PHP 5.2 even for the rock-solid stable legacy servers. It's either PHP 5.1, or PHP 5.3. PHP 5.2 is completely unsupported.

Also I'm not proposing that raven-php breaks backwards compatibility here; it'd be a separate version in composer on a new branch for those that want it.

**Comment by dcramer** [comment]
fwiw I'm ok with this. I dont know much about the PHP version landscape these days but generally Red Hat is a reasonable model to look at it. Usually they side on the "we support this far more than anyone else" so if its not supported there it seems unlikely we need to maintain support.

**Comment by ameliaikeda** [comment]
:+1: 

I have a 4-day weekend, so I could get started on this at least. Shall I do a behemoth pull request and have ongoing discussion on there?

First task: abstracting away the http layer behind an interface. Second: mocks for unit testing.

**Comment by dcramer** [comment]
@ameliaikeda that seems reasonable. I'll try to be fairly responsive on things rather than letting it sit for a month :)

**Comment by ameliaikeda** [comment]
Pull request is at #197

**Comment by localheinz** [comment]
:+1:

**Comment by markushausammann** [comment]
No need to support anything older than 5.5.
5.4 is passed EOL now. PHP 7 is important, though.

**Comment by Jean85** [comment]
Closing this, since #464 got merged in 1.x, and we decided bumping to 5.5/6 and using PSR-4 in 2.x.
