### ISSUE TITLE
When sending data from Raven client fails, error reporting is not useful

### ISSUE THREAD

**Issue by tgr** [getsentry/sentry-php#217]
When `Raven_Client::send_http_synchronous` fails, `Raven_Client::getLastError()` reports the output of `curl_error`. This is typically not useful as Sentry returns a 400 OK response with an `X-Sentry-Error` header on errror; the contents of that header should be returned when present.

(I am using Sentry 7.1.4 and raven-php 0.12.0; looked at the code briefly and it did not seem like that behavior changed in later versions.)

**Comment by jhnferraris** [comment]
Im having the same issue with Raven version of 0.12.0

**Comment by jhnferraris** [comment]
Update: I tried in lower versions 0.10.0 and 0.11.0, both can successfully send reports while 0.12.0 cannot.

**Comment by dcramer** [comment]
@jhnferraris whatever your issue is it seems unrelated to this original ticket, which is specifically talking about the getLastError functionality. In your case you may take a look at the changelog for 0.12.0 and see if any of the items would affect you.

**Comment by stayallive** [comment]
Closing this since this is an really old issue (sorry about that), please let us know if this is still an issue today so we can start investigating!
