### ISSUE TITLE
Tests fail on PHP 7

### ISSUE THREAD

**Issue by brandonsavage** [getsentry/sentry-php#220]
There are two errors on PHP 7 alpha 2:

Hannah:raven-php brandon$ php70 /opt/usr/bin/phpunit 
PHPUnit 4.4.0 by Sebastian Bergmann.

Configuration read from /Users/brandon/Sites/raven-php/phpunit.xml

..............................................I........F....F..

Time: 76 ms, Memory: 6.00Mb

There were 2 failures:

1) Raven_Tests_StacktraceTest::testCanTraceParamContext
Array (...) does not match expected type "NULL".

/Users/brandon/Sites/raven-php/test/Raven/Tests/StacktraceTest.php:35
/opt/usr/bin/phpunit:612

2) Raven_Tests_StacktraceTest::testDoesFixFrameInfo
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'StacktraceTest.php:Raven_Tests_StacktraceTest'
+'TestCase.php:PHPUnit_Framework_TestCase'

/Users/brandon/Sites/raven-php/test/Raven/Tests/StacktraceTest.php:208
/opt/usr/bin/phpunit:612

FAILURES!
Tests: 63, Assertions: 175, Failures: 2, Incomplete: 1.

**Comment by dcramer** [comment]
I assume the first is due to some reflection APIs changing. The other is a bit more concerning as it seems our hacks either aren't working to "fix" the frame list, or stacktraces havent changed.

**Comment by wayneashleyberry** [comment]
I see tests are still failing, is there a plan to fix this?

**Comment by dcramer** [comment]
I haven't looked into this personally. Definitely would appreciate some expertise on the matter, as we (Sentry) don't run PHP and haven't really kept up with the progress in i.

**Comment by remicollet** [comment]
Running test suite against various version

```
$ php70 vendor/bin/phpunit -v
PHPUnit 4.8.27 by Sebastian Bergmann and contributors.

Runtime:	PHP 7.0.12RC1
Configuration:	/work/GIT/sentry-php/phpunit.xml

...............................................................  63 / 111 ( 56%)
......................I.........................

Time: 85 ms, Memory: 6.00MB

There was 1 incomplete test:

1) Raven_Tests_SanitizeDataProcessorTest::testDoesFilterHttpData
Array scrubbing has not been implemented yet.

/work/GIT/sentry-php/test/Raven/Tests/SanitizeDataProcessorTest.php:47

OK, but incomplete, skipped, or risky tests!
Tests: 111, Assertions: 259, Incomplete: 1.

$ php71 vendor/bin/phpunit -v
PHPUnit 4.8.27 by Sebastian Bergmann and contributors.

Runtime:	PHP 7.1.0RC3
Configuration:	/work/GIT/sentry-php/phpunit.xml

...............................................................  63 / 111 ( 56%)
......................I.........................

Time: 82 ms, Memory: 6.00MB

There was 1 incomplete test:

1) Raven_Tests_SanitizeDataProcessorTest::testDoesFilterHttpData
Array scrubbing has not been implemented yet.

/work/GIT/sentry-php/test/Raven/Tests/SanitizeDataProcessorTest.php:47

OK, but incomplete, skipped, or risky tests!
Tests: 111, Assertions: 259, Incomplete: 1.
```

**NOTICE**: but only when **ext-uopz** (sebastian/global-state, so PHPUnit, optional dependency) is installed

**Comment by remicollet** [comment]
See PR #365
