### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by guilhermepsantos** [getsentry/sentry-php#231]
I'm running Sentry 7.7.0 on an Ubuntu server with Nginx as the proxy. The configuration file for Nginx is identical to the one provided in the Sentry documentation (i.e., not accepting any requests over HTTP, instead redirecting them to a TLS connection).

I'm trying to add Raven-PHP to a Laravel application that I've developed. While I had some success with logging errors over an HTTP connection (by "some success" I mean that logging was hit or miss, but I'm assuming that at least some of that should be related to Sentry's sampling system), I'm completely unable to log anything over HTTPS from the application. I am, however, able to log the test events using the `bin/raven test _dsn_` command, with the DSN using the TLS protocol.

Here's the code I'm using to test this out:

``` php
$raven = new Raven_Client(app('config')->get('services.raven.dsn'), array_except(app('config')->get('services.raven'), ['dsn']));
$raven->captureMessage('Hello World!');

var_dump($raven->getLastError());
```

The parameters I have set are `level = error` and `curl_method = sync`. The code above yields the following error message:

```
string 'SSL certificate problem: unable to get local issuer certificate' (length=63)
```

I'm running Raven-PHP 0.12.1. According to #157 this issue was supposed to have been addressed by v0.10 (I can confirm that the bundle is in the _data_ directory). I tried adding a `ca_cert` option with the _.cer_ file extracted from the Sentry server through Chrome (top-level certificate), and then I get this error:

```
string 'error setting certificate verify locations:
  CAfile: /home/*****/rootca.cer
  CApath: /etc/ssl/certs' (length=118)
```

Any ideas (besides removing the TLS requirement or skipping certificate validation)?

**Comment by guilhermepsantos** [comment]
A quick update – it looks like this may be related to our certificate being signed through a SHA256 digest. I'll keep researching and post an update if I figure it out.

**Comment by felixsanz** [comment]
@guilhermepsantos any solution on this?

**Comment by stayallive** [comment]
This might have something to do with the incorrect certs or curl version on your distro.

Older debian / CentOS versions suffer from this, can you `curl -I https://sentry.yourhost.com` or is that failing too?

**Comment by felixsanz** [comment]
I think you can resolve this, the issue is more than a year old

**Comment by guilhermepsantos** [comment]
I'm no longer developing the application I was working on at the time, so I can't provide any additional information about the issue. As suggested by @felixsanz, I'm closing the issue.
