### ISSUE TITLE
Stacktrace frame does not have a 'function' offset

### ISSUE THREAD

**Issue by arunasdilius** [getsentry/sentry-php#234]
On fatal error a frame might not have a 'function' offset which breaks in

raven-php/lib/Raven/Stacktrace.php
line 85:  'function' => $nextframe['function']

Any reason for that?

**Comment by dcramer** [comment]
Seems like an oversight. I assume this just raises warnings locally, but we should def fix it.

**Comment by namenyi** [comment]
@arunasdilius @dcramer I have exactly the same issue, and have even created a PR for that, only in the wrong place, in the deprecated repository. Here it is: https://github.com/getsentry/raven-php/pull/1

**Comment by ste93cry** [comment]
I'm going to close this issue as it should be fixed in `2.x` branch. If that's not the case, feel free to reopen this.
