### ISSUE TITLE
captureException needs to allow overriding the message

### ISSUE THREAD

**Issue by ctadlock** [getsentry/sentry-php#236]
The `captureException` doesnt allow for the caller to override the `message`. This is very annoying for things like `NotFoundException` as when they are logged in Sentry for different urls they all show up as one issue with many events.

<img width="1208" alt="screen shot 2015-09-14 at 10 38 37 am" src="https://cloud.githubusercontent.com/assets/1539397/9857023/0b05ea50-5acd-11e5-959e-b05405baea9c.png">

**Comment by dcramer** [comment]
Overriding the message actually isnt going to change the grouping mechanism here. You can see how that works in our docs:

https://docs.getsentry.com/hosted/rollups/

It's important to know that Sentry isn't logs, and we don't really cater to the "I want to know which URLs are 404ing" cases. We aim to solve exceptions, and generally only exceptions.

That said, I think message should still be customizable as it is on other platforms.

**Comment by ctadlock** [comment]
Grouping things by pure exception class name is borderline useless. NotFound, NullReference.. are classes of exceptions not specific instances of issues in code. Each entry in Sentry should be about a specific issue in the code so it can be analyzed, tracked and resolved. That why you have the "Create GitHub issue" feature. Image if a junior tester assigned you a GitHub issue that was "page not found"; your response would be the issue needs to be more specific and include what page wasn't found. In the case where there were two different code issues one that was mis-linking to page `/a` and one that was mis-linking to page `/b`, I would expect two different GitHub issues and two different Sentry entries. That's not logging, thats good engineering process. Sentry should support the ability for users to decide this is how they want to manage their issues.

**Comment by dcramer** [comment]
@ctadlock we dont group by class name, we group by stacktrace, and you can specify a fingerprint in the client if you want to (as per our docs).

**Comment by ctadlock** [comment]
Stack trace isn't enough for many systems (such as Laravel) and exception types as the stack trace is the same for all exceptions of that class. For example, all NotFoundHttpException exceptions have this exact stack trace below. The fingerprint looks like it could work here, although I think calling a 404 an "advanced use case" is a stretch.

<img width="807" alt="screen shot 2015-09-14 at 12 26 07 pm" src="https://cloud.githubusercontent.com/assets/1539397/9859540/00be867e-5adc-11e5-9899-4d72b6923989.png">

**Comment by dcramer** [comment]
Yeah there's no great way to control this without fingerprint (and its not something we can really automate). We plan to make it so you can do server side rules in the future, but that's not happening in the short term.

**Comment by zhil** [comment]
@ctadlock did you founded solution for this problem? I have exactly the same issue - I keep receiving 404 errors like "/wp-login - not founded", which is very annoying.

Going to add custom exception listener, which will add "fingerprint" to exception. It should solve this issue.

**Comment by dcramer** [comment]
Closing this out as the message attribute is no longer relevant for exceptions.
