### ISSUE TITLE
Add better error handling around HTTP responses

### ISSUE THREAD

**Issue by patrick91** [getsentry/sentry-php#239]
I was having an error while trying to use `raven-php` with an older version of Sentry. Maybe it's worth add a check if the errors is 4xx one?

I think we can check it here: https://github.com/getsentry/raven-php/blob/master/lib/Raven/Client.php#L708 and return the body content as error.

What do you think?

**Comment by dcramer** [comment]
@patrick91 you can use $client->getLastError() if the capture returns unsuccessful

**Comment by patrick91** [comment]
@dcramer sorry I wasn't clear :(

When you get a 4xx you won't get any CURL error, or at least when I tried the error string was empty.

**Comment by dcramer** [comment]
@patrick91 you mean the error message wasnt useful because it was empty?

**Comment by patrick91** [comment]
Yes

**Comment by dcramer** [comment]
We could return an exception class or something similar. At the very least we'd need more a rich error object.

A simple alternatively could be we return HTTP {CODE}: {TEXT}

**Comment by patrick91** [comment]
I'll have a look at it tomorrow if I have time :)

**Comment by patrick91** [comment]
@dcramer hey, sorry but I'm not a PHP expert, I was trying to add some tests before editing the library. It seems that's not possible (in an easy and clean way) to mock the curl library, one [suggested way](http://omni-spot.blogspot.it/2010/09/unit-testing-curl-code-in-php.html) is to create a proxy class.

Do you have any suggestion before I start doing anything?

**Comment by stayallive** [comment]
Closing this since this is an really old issue (sorry about that).

This is probably better addressed already in the 2.0 branch which should make it way easier to catch any transport errors.
