### ISSUE TITLE
Alternatives to autoload

### ISSUE THREAD

**Issue by juanmas07** [getsentry/sentry-php#254]
When using autoload function it breaks several other parts of my project. is there an alternative to load raven-php without using autoloader?

**Comment by juanmas07** [comment]
I'm doing something like this:

require_once __ROOT . "/php/libs/raven-php/lib/Raven/Serializer.php";
require_once __ROOT . "/php/libs/raven-php/lib/Raven/Stacktrace.php";
require_once __ROOT . "/php/libs/raven-php/lib/Raven/ErrorHandler.php";
require_once __ROOT . "/php/libs/raven-php/lib/Raven/Client.php";
require_once __ROOT . "/php/libs/raven-php/lib/Raven/Util.php";
require_once __ROOT . "/php/libs/raven-php/lib/Raven/Compat.php";
require_once __ROOT . "/php/libs/raven-php/lib/Raven/Processor.php";
require_once __ROOT . "/php/libs/raven-php/lib/Raven/Context.php";
require_once __ROOT . "/php/libs/raven-php/lib/Raven/SanitizeDataProcessor.php";

**Comment by mabrahamde** [comment]
Sounds like you have answered the question yourself. ;)
