### ISSUE TITLE
Raven Not invoking default error handler

### ISSUE THREAD

**Issue by kyleobrien91** [getsentry/sentry-php#260]
**Problem**
When running some downtime testing, I realised that if the Raven server isn't available, an exception isn't rethrown or handled by PHP.

**Testing**
Pre Sentry implementation, our log file would be written to when we encountered an exception as per our Nginx setup. As of Sentry implementation, the messages are successfully piped to Sentry however, nothing appears in the log.

Upon testing, I realised that if the sentry server isn't available (switched off in my case), nothing is rethrown to be handled by PHP. This is obviously an issue as one stands the risk of losing valuable output since Sentry doesn't have it and nothing is written to logs.

I had a look around the register functions but as far as I can tell, with `$call_existing_exception_handler = true` as a default param, I can't see any reason that we're not getting any more output in our php error log.

I did implement a control test. Our first and successful test was without any call to Raven. After Raven implementation - no logging. The commenting out of Raven --> no error logging.

``` php
$raven_client = new Raven_Client('long_long_string_here');
$error_handler = new Raven_ErrorHandler($raven_client);
$error_handler->registerExceptionHandler();
$error_handler->registerErrorHandler();
$error_handler->registerShutdownFunction();
```

``` php
throw new Exception('NoooooooO!');
```

**Additional information**
- PHP 5.5.9-1ubuntu4.14

Any ideas on whether this is a bug or an implementation issue?

**Comment by kyleobrien91** [comment]
Some additional debugging. I printed out some vars in ```handleException()```.

As we can see, we never evaluate into ```if (!$isError && $this->call_existing_exception_handler && $this->old_exception_handler) ```. This is seems the obvious reason we're not logging the issue.  

<img width="726" alt="screen shot 2016-02-08 at 23 08 49" src="https://cloud.githubusercontent.com/assets/2432944/12899453/1560ce0a-ceba-11e5-8e92-08650cd93b85.png">

<img width="547" alt="screen shot 2016-02-08 at 23 08 58" src="https://cloud.githubusercontent.com/assets/2432944/12899461/1acda2aa-ceba-11e5-9716-96bfa1e1f1b7.png">

**Comment by kyleobrien91** [comment]
Within ```registerExceptionHandler```, the result of ```set_exception_handler(array($this, 'handleException'))``` is 

```
error_reporting(): 22527
set_exception_handler: 
```

**Comment by dcramer** [comment]
The code is still a bit of a mess in ErrorHandler, and I feel like it might be related. I'm goign through and trying to clean it up right now. We might deprecate/remove some API in here that doesn't need to exist to better support this.

**Comment by kyleobrien91** [comment]
I learnt something today. When we're using PHP's default handler (ie logging to file), then the result of set_exception_handler is NULL.

Therefore, it is incorrect to run this following check on 
```if (!$isError && $this->call_existing_exception_handler && $this->old_exception_handler)```

Since old_exception_handler will be NULL even when using legitimate PHP defaults.

Thus a better check might be

```if (!$isError && $this->call_existing_exception_handler && (is_null($this->old_exception_handler) || $this->old_exception_handler))```

Will submit a PR soon.

**Comment by dcramer** [comment]
@kyle-johnson ah not even related to error handler, sorry (I'll admit I didn't fully read all the comments)

**Comment by kyleobrien91** [comment]
Okay, @dcramer - might need some genius here - the following code checks conditionals fine. However, the implementation of the rethrow is obviously shocking. This results in two messages being piped to Sentry. The differences are below.

Code
```php
if (!$isError && $this->call_existing_exception_handler && (is_null($this->old_exception_handler) || $this->old_exception_handler)) {
            /*
             * This conditional will evaluate to true if using PHP defaults.
             */
            if (is_null($this->old_exception_handler)) {
                $new_exception_handler = set_exception_handler(NULL);
                throw $e;
            } else {
                call_user_func($this->old_exception_handler, $e);
            }
        }
```

1. Okay one here  
<img width="926" alt="screen shot 2016-02-09 at 09 56 38" src="https://cloud.githubusercontent.com/assets/2432944/12910435/73a60030-cf13-11e5-88b5-f5a0dd45609e.png">

2. Not so okay on here  
<img width="926" alt="screen shot 2016-02-09 at 09 56 38" src="https://cloud.githubusercontent.com/assets/2432944/12910440/7db238d2-cf13-11e5-93bc-efbd8a88d836.png">

**Comment by dcramer** [comment]
That looks like it might be from something else. Assuming you're not using any kind of other integrations, I wonder if that's from the shutdown handler?

**Comment by kyleobrien91** [comment]
@dcramer - if you're referring to the code, that was my attempt at changing the conditional inside ```registerExceptionHandler()```. The initial code inside the registerExceptionHandler isn't too extensive. I just do some additional checks for is_null and rethrow the exception in there. I just need your input into whether or not that's acceptable.

**Comment by kyleobrien91** [comment]
@dcramer - further, the result of my code change renders the second message (screenshot 2 above) which looks like Sentry is no longer parsing the message to get output in line with screenshot 1 above.

**Comment by dcramer** [comment]
Answered my own question -- the stacktrace clearly says it happened in handleFatalError.

So the issue here is that re-throwing the exception bubbles it up to the fatal handler, thus duplicating the report. In addition, the fatal handler does not properly extract the exception.

I dont think re-throwing it is a good solution, unless we did it specifically in the case where Sentry fails to report the error upstream.

**Comment by BabakMN** [comment]
Any updates on this issue?

**Comment by dcramer** [comment]
This issue has been resolved for several versions afaik.
