### ISSUE TITLE
Commit 1cac2cc prevents errors from showing up in Sentry when triggered from browser

### ISSUE THREAD

**Issue by msheakoski** [getsentry/sentry-php#265]
Ever since commit 1cac2cc, errors triggered from the sentry CLI tool and PHP scripts run from the CLI correctly show up in Sentry 8.2.1, but when the exceptions are triggered by loading a page in the browser (via the PHP built-in web server), they don't appear in Sentry. I noticed that the event count increases on the bar chart in the Projects page, but clicking on the project does not show the event.

When I rolled back to the previous commit, 9904e23, everything works perfectly. I am running PHP Version 7.0.3.

**Comment by dcramer** [comment]
@msheakoski could you provide more information on a few things such as:

- system locale
- if mb_convert_encoding is available
- if there are any settings related to that which are configured
- any errors from loading the web page
