### ISSUE TITLE
preg_match() in Raven_SanitizeDataProcessor::sanitize()

### ISSUE THREAD

**Issue by streaky** [getsentry/sentry-php#275]
In the recent push of 0.14.0 it seems like sanitize() gets passed an array that can be (or is) filled with objects and tries to preg_match() with those objects as the subject. This makes PHP throw warnings when raven catches an error:

```Warning: preg_match() expects parameter 2 to be string, object given in /home/streaky/[...]/raven/lib/Raven/SanitizeDataProcessor.php on line 54```

I muted the array_walk_recursive() call on 85 because if you play with it too much you open a can of worms - but what it probably needs is some custom recursive method that deals with objects as well as arrays because obviously data people want masked might be in object properties and that would get sent to the server as-is.

Most people probably don't even know this is happening because of the context it never gets reported to sentry and you'll only see it if you actually get an error, but it spews warnings all over pages as it is.

**Comment by dcramer** [comment]
I'm trying to determine where this can be coming from. Technically we no longer serialize the entirety of the PHP packet, but rather explicitly sanitize things which might contain arbitrary values. Are you able to determine what value its failing on by chance?

**Comment by jamieburchell** [comment]
Hey

For me, looking at what the variable is when it chokes, it seems to be an object which is part of my application:

`string(36) "RequestRouter.php:Raven_ErrorHandler"
string(11) "handleError"
string(33) "	public function initController()"
string(2) "	{"
string(50) "		$controllerPath = $this->_controllerPath . '/' ."
string(35) "			$this->_controllerName . '.php';"
string(37) "		if (include_once $controllerPath) {"
string(46) "			if (class_exists($this->_controllerName)) {"
string(45) "				$controller = new $this->_controllerName;"
string(11) "			} else {"
string(42) "				throw new Ib3_RequestRouter_Exception("
string(60) "					'Controller class not found: ' . $this->_controllerName"
string(27) "controllers/WController.php"
object(Ib3_RequestRouter)#13 (10) {
  ["_controllerPath":protected]=>
  string(11) "controllers"
  ["_viewScriptPath":protected]=>
  string(13) "views/scripts"
  ["_controllerName":protected]=>
  string(11) "WController"
  ["_actionName":protected]=>
  string(11) "indexAction"
  ["_viewControllerName":protected]=>
  string(1) "w"
  ["_viewActionName":protected]=>
  string(5) "index"
  ["_format":protected]=>
  string(4) "html"
  ["_controller":protected]=>
  NULL
  ["_viewFile":protected]=>
  NULL
  ["_viewPath"]=>
  string(13) "views/scripts"
}
`

> Warning: preg_match() expects parameter 2 to be string, object given in vendor/raven/raven/lib/Raven/SanitizeDataProcessor.php on line 54

**Comment by dcramer** [comment]
@jamieburchell could you try master?

**Comment by dcramer** [comment]
Closing as fixed unless someone reports otherwise

**Comment by streaky** [comment]
Seems like that's got it, thanks

**Comment by jamieburchell** [comment]
Yup, that issue went away. Thanks.

**Comment by d-lamers** [comment]
I still have this issue on master. Changing the sanitize function to this 

`public function sanitize(&$item, $key)
    {
        is_object($item) ? dd($item) : true;

        if (empty($item)) {
            return;
        }

        if (preg_match($this->values_re, $item)) {
            $item = self::MASK;
        }

        if (empty($key)) {
            return;
        }

        if (preg_match($this->fields_re, $key)) {
            $item = self::MASK;
        }
    }`

Returns an object that is in the session
`object(stdClass)#214 (2) { ["code"]=> string(2) "nl" ["title"]=> string(10) "Nederlands" }`

This fixes the issue

`if (empty($item) || is_object($item)) {
            return;
        }`
