### ISSUE TITLE
Browser gets a 200/OK blank page when default exception handler is registered

### ISSUE THREAD

**Issue by jamieburchell** [getsentry/sentry-php#280]
Using the following code:

```
$client = new Raven_Client(SENTRY_DSN);
$handler = new Raven_ErrorHandler($client, false, null, SENTRY_ERROR_TYPES);
$handler->registerExceptionHandler();
$handler->registerErrorHandler();
$handler->registerShutdownFunction();
```

When an uncaught exception is caught by the `Raven_Client`, the browser receives a 200/OK response and blank page. Commenting out the `registerExceptionHandler()` line gives the expected 500/Internal Server Error response and stock browser message.

Note in the scenario above, there is no existing exception handler registered.

This may be caused by the fact that the exception is actually caught, I'm looking now to see if I can find out more; it would be handy if the response was 500.

**Comment by mitsuhiko** [comment]
Currently raven assumes that a default error handler is set with `set_exception_handler` which we will invoke. if there is no handler we cannot really fall back to default php handling because php does not expose that functionality. I suppose what we could do is if we see that there is no default handler to approximate the default 500 error response somehow.

**Comment by jamieburchell** [comment]
It's a tricky one; I understand that the client should be as unobtrusive as possible and if you start modifying response headers you have to think about what happens if the script is running in a cli environment too, it should probably exit with a 1.

In my use case, I'm trying to integrate this in a CodeIgniter 2.x application *sigh* which has no concept of exceptions or a default exception handler, hence one isn't registered already.

**Comment by dcramer** [comment]
@jamieburchell is it something that is easy enough for you to pass in your own handler? I'm not sure if thats the best solution, but potentially you could re-throw from there. We could also try to handle this internally in the SDK as well.

**Comment by jamieburchell** [comment]
To solve this one I've defined a default exception handler before instructing the Raven client to register it's own. My handler shows a pretty error page and sends a 500 to the browser. Ideally my app would know the difference between a CLI request and not so show the message in the appropriate format and to exit with a non zero value.

I'm thinking though if an exception handler hasn't already been defined the minimum the Raven client should do it send a 500 status code to the browser and exit with a non zero value to cater for CLI requests. Essentially trying to mimic what the response would have been had the Raven client not been used. As it stands it's trying to be unobtrusive but essentially changing the HTTP status code from 500 to 200 by "catching" the exception.

**Comment by luckydonald** [comment]
Because this came up for searching with codeigniter

**Comment by stayallive** [comment]
We are now rethrowing the exception if not other error handler was set so a 500 error will be returned as "normal".

```php
<?php

ini_set('display_errors', false);

require __DIR__ . '/lib/Raven/Autoloader.php';

Raven_Autoloader::register();

$sentry = new Raven_Client;
$sentry->install();

blablabla();
```

This will show a correct 500 response instead of a 200.
