### ISSUE TITLE
Abandon the raven/raven package

### ISSUE THREAD

**Issue by xabbuh** [getsentry/sentry-php#287]
On Packagist it is possible to mark a package as abandon and link to its replacement. It would be nice if you could do that for the raven/raven package.

**Comment by jamieburchell** [comment]
Is it abandoned? I've been using it and it appears to have received an update from 0.14.0 to 0.15.0 recently. It has 

Just noticed the deprecation notice after going in to look at the package so now I'm a bit confused. What does this mean for current installations and what is the link between raven/raven and sentry-php?

**Comment by xabbuh** [comment]
@jamieburchell The readme states it's deprecated and suggest to use `sentry/sentry` instead (see getsentry/raven-php@a90cdcf681a373b5150ee2b430db28d9f670abea).

**Comment by xabbuh** [comment]
Looks like [the documentation](https://getsentry.com/for/php/) needs an update too (it suggest to require the `raven/raven` package).

**Comment by jamieburchell** [comment]
Unlucky for me I chose to integrate Sentry with 60+ of our projects during the 2 weeks this package was deprecated/renamed ;)

**Comment by dcramer** [comment]
@xabbuh good catch on the marketing page!

I looked for a way to suggest the package was deprecated and moved, but didn't see it. Do you know how that process works or if theres a doc?

**Comment by xabbuh** [comment]
@dcramer On packagist.org, there is an "abandon" button for every package you own. After clicking it you can enter the name of the replacing package.

**Comment by dcramer** [comment]
Done, thanks!
