### ISSUE TITLE
If session has object it crashes

### ISSUE THREAD

**Issue by d-lamers** [getsentry/sentry-php#290]
It throws this error

`Error in exception handler: preg_match() expects parameter 2 to be string, object given in /srv/bezorgbeer/vendor/sentry/sentry/lib/Raven/SanitizeDataProcessor.php:56`

This

```
public function sanitize(&$item, $key)
    {
        is_object($item) ? dd($item): true; //Added for test
        if (empty($item)) {
            return;
        }

        if (preg_match($this->values_re, $item)) {
            $item = self::MASK;
        }

        if (empty($key)) {
            return;
        }

        if (preg_match($this->fields_re, $key)) {
            $item = self::MASK;
        }
}
```

Returns this

`object(stdClass)#214 (2) { ["code"]=> string(2) "nl" ["title"]=> string(10) "Nederlands" }`

**Comment by dcramer** [comment]
I'm assuming the attached change will resolve this, which is a step in the right direction

**Comment by dcramer** [comment]
I'm closing this as while I think protecting inputs is good, I'd rather us simply not go down the rabbit hole of trying to magically handle encoding of arbitrary values. If there is still issues with default behavior in Sentry we can work around it, but if you're binding in session data you'll need to serialize it yourself (assuming its not already valid JSON).
