### ISSUE TITLE
Please update Changelog

### ISSUE THREAD

**Issue by romainneutron** [getsentry/sentry-php#293]
Your [changelog](https://github.com/getsentry/sentry-php/blob/master/CHANGES) has not been updated since 0.15.0

Please provide latest changes. 
It's quite important, as you're not yet using semver, I really need to know what has change between my current version and the latest one.

**Comment by dcramer** [comment]
https://github.com/getsentry/sentry-php/commits/master

**Comment by dcramer** [comment]
CHANGES is updated.
