### ISSUE TITLE
notice in phpunit (THE ERROR HANDLER HAS CHANGED!)

### ISSUE THREAD

**Issue by server-may-cry** [getsentry/sentry-php#296]
```
PHPUnit 4.8.25 by Sebastian Bergmann and contributors.

................

Time: 2.58 seconds, Memory: 46.00Mb

OK (16 tests, 105 assertions)

THE ERROR HANDLER HAS CHANGED!
```

after upgrading from [0.18.1](../releases/tag/0.18.1) to [0.19.0](../releases/tag/0.19.0) - [diff](../compare/0.18.1...0.19.0)

**Comment by dcramer** [comment]
Open to suggestions here, but the SDK now installs an error handler by default (which bubbles up). It shouldn't affect anything.

**Comment by server-may-cry** [comment]
Solve by stop enable sentry in test environment. That was wrong.

**Comment by GijsErenstein** [comment]
How i solved this problem:

in bundles.php:
`Sentry\SentryBundle\SentryBundle::class => ['prod' => true],`

and move the sentry.yaml from packages to packages/prod. you could probably tho the same for some more envs where you do want sentry to be active

**Comment by hugochinchilla** [comment]
Can we consider this not fixed?

I have many tests checking the sentry integration and I don't want to disable sentry in test. In test I have decorated the SentryHub with a custom implementation that allows testing sentry without sending events to the server.

**Comment by ste93cry** [comment]
>Can we consider this not fixed?

Yes, but we're tracking the problem in getsentry/sentry-symfony#421 because it involves Symfony

**Comment by hugochinchilla** [comment]
Oh, thank you for pointing this out
