### ISSUE TITLE
Mention BC breaks in CHANGES

### ISSUE THREAD

**Issue by romainneutron** [getsentry/sentry-php#297]
It would be nice to mention BC breaks in `CHANGES`.
It would be awesome to have an `UPGRADE` file that mention how to upgrade from version x to version y

**Comment by dcramer** [comment]
@romainneutron we generally dont have breaking changes. This SDK is super lightweight, and your test suite should be able to deal w/ things like this. Lock in versioning to patch and you're safe.

Generally we're not going to add a lot of excess process here for minimal gain.
