### ISSUE TITLE
Warning: preg_match() expects parameter 2 to be string, object given in vendor/sentry/sentry/lib/Raven/SanitizeDataProcessor.php on line 54

### ISSUE THREAD

**Issue by Repox** [getsentry/sentry-php#300]
I'm running version 0.19.0 and I get the following error message:

    Warning: preg_match() expects parameter 2 to be string, object given in vendor/sentry/sentry/lib/Raven/SanitizeDataProcessor.php on line 54

Vanilla installation, though:

	Raven_Autoloader::register();
	$client = new Raven_Client('https://auth_me@app.getsentry.com/XXXXX');
	$client->setEnvironment(App::site_mode());
	$error_handler = new Raven_ErrorHandler($sentry);
	$error_handler->registerExceptionHandler();
	$error_handler->registerErrorHandler();
	$error_handler->registerShutdownFunction();

Why am I experiencing this?

**Comment by dcramer** [comment]
I don't suppose you have a way you could capture what the value is that it's failing on? It's unclear how we'd be getting unserializable data down that path, but I will work on a resolution.

**Comment by Jay-Pi** [comment]
I had the same Problem using zend framework. The user/authentication data is stored as ArrayObject in $_SESSION.
It seem in version 0.16.0 the was a serialize function called in Client.php before sanitize which is missing now.
```
$serializer = new Raven_Serializer();
$data['user'] = $serializer->serialize($data['user']);
```

**Comment by dcramer** [comment]
@Jay-Pi in the current release we dont actually serialize the session data in automatically anymore (or at least shouldn't be). We decided it was better to let users decide if they wanted any of that data present, and thus is also why we dont serializer the user attribute.

**Comment by Jay-Pi** [comment]
@dcramer I didn't know how to do this using the Raven_ErrorHandler, because it was too easy.
```
$client = new Raven_Client(PHP_ERROR_RAVEN_URL);
$user['user'] = 'foo';
$client->user_context($user);

// Install error handlers and shutdown function to catch fatal errors
$error_handler = new Raven_ErrorHandler($client);
$error_handler->registerExceptionHandler();
$error_handler->registerErrorHandler();
$error_handler->registerShutdownFunction();
```

This works for me.

**Comment by endelwar** [comment]
I can confirm the same behavior with 0.17.0, 0.18.1 and 0.19.0, everything is ok with 0.16.0

**Comment by Repox** [comment]
@dcramer Well, I can confirm by doing a `var_dump` on right before the line in question that I'm getting objects from my code. It actually happens to a lot of my objects.

Here's a var_dump (with xdebug) of `$data` from inside the method `process` (https://github.com/getsentry/sentry-php/blob/0.19.0/lib/Raven/SanitizeDataProcessor.php#L83)

```
array (size=15)
    'user' => 
      array (size=2)
        'id' => string 'fr5kk9eiedkmblcthkqkidvk20' (length=26)
        'data' => 
          array (size=21)
            'adv_filt' => 
              object(Advanced_filter)[27]
                ...
            'aassistant' => 
              object(Aassistant)[28]
                ...
            'language' => string 'danish' (length=6)
            'languages_id' => string '2' (length=1)
            'currency' => string 'DK' (length=2)
            'npk_setup' => 
              array (size=19)
                ...
            'pdf_waiting' => 
              array (size=0)
                ...
            'max_list_result' => null
            'list_sort_order' => string 'standard' (length=8)
            'list_qty_factor' => null
            'cart' => 
              object(shoppingCart)[29]
                ...
            'sts_template_folder' => null
            'currencies' => 
              object(currencies)[31]
                ...
            'newsletter_tb' => string 'a:2:{s:20:"customers_newsletter";i:1;s:9:"customers";b:1;}' (length=58)
            'arena' => 
              object(arena)[32]
                ...
            'checkout_elements' => 
              object(checkout_elements)[33]
                ...
            'products_visited' => 
              array (size=4)
                ...
            'grimm' => 
              array (size=8)
                ...
            'last_list_viewed' => 
              array (size=4)
                ...
            'errorNews' => string '' (length=0)
    'request' => ...
```

Crawling back through the processes, I see that the sanitizing process is started at https://github.com/getsentry/sentry-php/blob/0.19.0/lib/Raven/Client.php#L590 

Going through that method, I see that the `$data` array gets merged with data coming from the method `get_user_data`.

Now, this might be specific to my codebase only, but I see that the culprit is actually when retrieving my session data from that method: https://github.com/getsentry/sentry-php/blob/0.19.0/lib/Raven/Client.php#L470-L472

In my `$_SESSION` data, I have the objects seen in the dump above, which is not handled before reaching the sanitizing method. 

The easy way out might be validating data types in the `sanitize method `Raven_SanitizeDataProcessor`:

```
    public function sanitize(&$item, $key)
    {
        if (empty($item) || is_object($item)) {
            return;
        }

        var_dump(gettype($item));

        if (preg_match($this->values_re, $item)) {
            $item = self::MASK;
        }

        if (empty($key)) {
            return;
        }

        if (preg_match($this->fields_re, $key)) {
            $item = self::MASK;
        }
    }
```

Or maybe actually put effort in pre-sanitizing the contents of `$_SESSION` before merging it for sanitizing.

**Comment by bgaillard** [comment]
Hi, with version `0.20.0` I still encounter errors, in my case the errors appears when I user objects in the `extra` property. 
```php
$this->ravenClient->captureMessage(
    $errorMessage,
    [
        'extra' =>  [
            'prop0' => 'string1',
            'prop1 => 'string2',
            'prop2' => $object // Cause of the error, if removed error disappears
        ]
    ]
);
```

Also if I use the fix propsed by @Repox (i.e addin ` || !is_string($item)` in the `SanitizeDataProcessor` class) then it works.

Is it forbidden to use objects in `extra` ?

**Comment by dcramer** [comment]
Objects are not a thing you should pass into JSON, so while I would have thought the serialization change catch this it's bad form and you should either coerce it to a strong or send a simplified data structure n

**Comment by bgaillard** [comment]
Hi @dcramer, thanks for your response so we'll update our source code to never use objects with Sentry.

**Comment by Repox** [comment]
I have to agree with the point that @bgaillard is trying to make. 

It seems silly that I'm forced to enable my code to be handled differently, because I want a 'smarter'  error handling and logging.

**Comment by dcramer** [comment]
fyi I have a failing test that reproduces this, so we'll ensure it at least doesnt error.

My point stands that you likely want to pass a usable object, since Sentry will just serialize it as 'Object [type]'.

**Comment by dcramer** [comment]
@bgaillard can you confirm, but it seems like you might be passing extra incorrectly here.

captureMessage supports formatted params, so you'd likely be wanting to pass it as the third parameter

**Comment by bgaillard** [comment]
@dcramer, you're absolutly right here :+1: ! 

After reading the code of `captureMessage(...)` and `capture(...)` it seems I should have do this instead. 
```php
$this->ravenClient->captureMessage(
    $errorMessage,
    [],
    [
        'extra' =>  [
            'prop0' => 'string1',
            'prop1 => 'string2',
            'prop2' => $object // Cause of the error, if removed error disappears
        ]
    ]
);
```

This is an other subject but in my opinion those kind of usage problems could be prevented by improving the PHP documentation in the source code. 

For exemple the PHPDoc associated to the `captureMessage(...)` method is not complete.
```php
/**
 * Log a message to sentry
 */
public function captureMessage(
    $message,
    $params=array(),
    $level_or_options=array(),
    $stack=false,
    $vars = null
) {
 ...
}
```

So here its not really easy to understand what's the role of each parameter, future releases should improve this by progressively adding lots of documentation on each PHP method.

```php
/**
 * Log a message to sentry
 *
 * @param string $message Some doc for message...
 * @param array $params Some doc for params...
 * @param array $level_or_options Some doc for level_or_options...
 * @param boolean $stack Some doc for stack...
 * @param mixed $vars Some doc for vars...
 */
public function captureMessage(
    $message,
    $params=array(),
    $level_or_options=array(),
    $stack=false,
    $vars = null
) {
 ...
}
```

Do you agree with those improvement suggestions ?

**Comment by dcramer** [comment]
@bgaillard agreed, I'll get those fixed up!

**Comment by bgaillard** [comment]
@dcramer ok great :+1: , thanks for your efficiency on this case !
