### ISSUE TITLE
getLastEventID for default error/exception handler

### ISSUE THREAD

**Issue by kzap** [getsentry/sentry-php#307]
how would i get the eventId if an exception or error happens?

basically what I'm trying to do if sent the error event id to a PHP page which is displayed to the user, so a redirect, but i cant get any from `$client->getLastEventID()`

Any suggestion as to how to capture the errors/exceptions handlers being used and get the ID before its sent if i dont manually call it?

**Comment by dcramer** [comment]
@kzap if its for global error handling you could register a function (to use as the builtin) and then register Sentry's so it bubbles up. From there you should be able to call out to get the last event ID. Does that solve the case?

p.s. long time no see :)

**Comment by kzap** [comment]
thanks, i saw the $e->event_id being set, so ill set the sentry error handler after my app's error handler and try to get it working.

ps. longtime Sentry user :)

**Comment by kzap** [comment]
ok it works. now im wondering how would i redirect upon fatal error? im guessing i have to override the sentry error handler

**Comment by dcramer** [comment]
@kzap yeah not sure a great way since you need to know precisely which one is fatal. Probably makes sense to subclass the handler.

I'm going to close this out, but if you come up with any reasonable approach and there's something we can improve lmk.

**Comment by kzap** [comment]
yep just made a class which extends the sentry error handler and then overrode the handleException method to redirect on certain errors only:

```
public function handleException($e, $isError = false, $vars = null)
    {
        $e->event_id = $this->client->getIdent($this->client->captureException($e, null, null, $vars));

        if (!$isError && $this->call_existing_exception_handler && $this->old_exception_handler) {
            call_user_func($this->old_exception_handler, $e);
        }

        if ($isError) {
            // handle an exception
            if (in_array($e->getSeverity(), $this->defaultErrorTypes)) {
                header("Location: /errorpage.php?event_id=" . $e->event_id);
            }
        } else {
            header("Location: /errorpage.php?event_id=" . $e->event_id);
        }
    }
```
