### ISSUE TITLE
Gzip header causing error response

### ISSUE THREAD

**Issue by cryode** [getsentry/sentry-php#312]
I'm using Laravel 5.2, with Monolog's (1.19.0) RavenHandler and Sentry-PHP 0.21.1.

Originally using the `raven/raven` package, I saw the deprecated message and chose to upgrade. After installing `sentry/sentry:0.21.1`, messages were no longer appearing in Sentry.

After digging, I discovered the `curl_exec()` response was HTTP 400 with the following content:

    "{"error":"Bad data decoding request (IOError, Not a gzipped file)"}"

Looking at the Sentry releases, the most relevant change was the addition of the `'Content-Encoding' => 'gzip'` header to the request. Commenting this out fixes the issue and errors are sent to Sentry as expected (the `Content-Type` header does not seem to affect anything).

My assumption is that this is likely a compatibility issue with attempting to gzip the data being sent to Sentry. Perhaps Laravel and/or Monolog's data structure is incompatible with the gzip process. There is also a `if function_exists("gzcompress")` check when performing compression - perhaps this header should be included in this `if` statement rather than assuming the content is always gzipped?

Since I am unfamiliar with the data structure(s) Sentry's API is accepting, I don't know exactly which part of my data I can share, and/or at what step. Please let me know what information I can provide, I'm happy to help.

**Comment by dcramer** [comment]
Thanks, and sorry about that!

**Comment by cryode** [comment]
@dcramer Thanks for fixing. I wasn't sure how crucial that header was; glad to see it is an easy fix. Using 0.21.2 Sentry + Laravel + Monolog is working as expected. Cheers :beer:

**Comment by dcramer** [comment]
@cryode yep this was my mistake. I added it yesterday, but totally didn't consider that we're encoding the data rather than sending the binary gzipped structures.
