### ISSUE TITLE
json_encode error with invalid utf-8 characters 

### ISSUE THREAD

**Issue by georgexsh** [getsentry/sentry-php#322]
error message:
```
ErrorException: json_encode(): Invalid UTF-8 sequence in argument
  File "vendor/sentry/sentry/lib/Raven/Compat.php", line 73, in handleError
    return json_encode($value);
  File "/vendor/sentry/sentry/lib/Raven/Compat.php", line 73, in json_encode
    return json_encode($value);
  File "vendor/sentry/sentry/lib/Raven/Client.php", line 716, in send
    $message = Raven_Compat::json_encode($data);
  File "vendor/sentry/sentry/lib/Raven/Client.php", line 639, in capture
    $this->send($data);
  File "vendor/sentry/sentry/lib/Raven/Client.php", line 348, in captureMessage
    return $this->capture($data, $stack, $vars);
...
```

if context variable cotains arbitrary binary data like picture content, `jsen_encode` will generate a warning, and sentry will show that variable value as `None`, eg:

```
function afunc() {
    $f = file_get_contents('sentry_logo.png');
    assert(0);
}
```

related with #6
using sentry-php 0.22.0

**Comment by pengu-fr** [comment]
I have the same problem.
Raven_Compat::json_encode($data) return FALSE with non UTF-8 string. So the sentry API return a 400 and the error isn't reported.

A workaround is to use self::_json_encode instead of json_encode and force to ignore non UTF-8 character in string :
```
if (is_string($value)) {
                $value = iconv('UTF-8', 'UTF-8//IGNORE', $value);
                return sprintf('"%s"',

```
The data won't be usable, but at least the original error will be reported.

**Comment by dcramer** [comment]
iconv is an extension just like the mb encoding stuff? In your case do you actually have the mb encoding extension installed?

**Comment by georgexsh** [comment]
@dcramer yes, we have mbstring extension installed.

**Comment by dcramer** [comment]
@pengu-fr @georgexsh do you happen to have a value that we could use to test this against? I have a hunch I might know whats causing it, but it would be better if we had a test case.

**Comment by dcramer** [comment]
Actually, my apologies, we can likely use the function as an example, which would imply its from local var capture.

**Comment by dcramer** [comment]
``fix/utf-8`` branch has a test reproduction

**Comment by georgexsh** [comment]
@dcramer glad to hear that, and `sentry_logo.png` is the logo file grabbed from https://getsentry.com/branding/

**Comment by tobias-nitsche** [comment]
I had the same problem, and fixed it with 

https://github.com/getsentry/sentry-php/commit/34df3414ef8e98d4c2fd3c65ff75797680a68c3b

Maybe someone tests it with the current master branch?

**Comment by dcramer** [comment]
@tobias-nitsche with arbitrary binary data I still hit the same issue in the branch. I think we just need to guarantee values can be coerced when we're capturing context.

**Comment by dcramer** [comment]
It turns out we just needed to force coercion. If this isn't good enough we can just say 'when currentEncoding fails to define, we show a {unparseable value} error'
