### ISSUE TITLE
`handleFatalError` will catch any type of error, which results in duplicate Sentry entries

### ISSUE THREAD

**Issue by timmipetit** [getsentry/sentry-php#331]
The function `handleFatalError` will currently catch all error that `handleError` will catch as well. For example: we have Sentry configured to catch warnings as well. When the last error on a page is a warning, it will be caught by `handleError` and finally by `handleFatalError` in the shutdown function. This means we get 2 entries in Sentry.

I think there are 2 possible solutions for this:

1. Only catch fatal errors in `handleFatalError`, as the name implies
2. Check if `error_get_last()` has already been reported by `handleError`

**Comment by dcramer** [comment]
This is resolved now
