### ISSUE TITLE
async method: fatal error not sent because curl handler shutdown function has already run

### ISSUE THREAD

**Issue by mfb** [getsentry/sentry-php#337]
If you have curl method set to async, fatal errors are not sent to Sentry because the curl handler shutdown function is registered to run before the fatal error handler shutdown function.

**Comment by mfb** [comment]
a workaround is to manually register another shutdown function after setting up the fatal error handler: `register_shutdown_function(array($client->_curl_handler, 'join'));`

**Comment by dcramer** [comment]
I think we need to refactor the shutdown code -- right now it lives somewhat in ErrorHandler. We can simply register a default shutdown function to always force flush the queue, even outside of async.
