### ISSUE TITLE
Warning:  Invalid argument supplied for foreach() in /../vendor/sentry/sentry/lib/Raven/Client.php on line 700

### ISSUE THREAD

**Issue by TPete** [getsentry/sentry-php#339]
[Commit a59c3e0](https://github.com/getsentry/sentry-php/commit/a59c3e09b97a2e834b7ca1fb6de5823e159c52f6) removed the null check in [Raven\Client::sendUnsentErrors()](https://github.com/getsentry/sentry-php/blob/a59c3e09b97a2e834b7ca1fb6de5823e159c52f6/lib/Raven/Client.php#L698). Looks like the warning is triggered, when `_pending_events` is null.

**Comment by dcramer** [comment]
Thanks, and sorry about that!
