### ISSUE TITLE
Missing Raven_ErrorHandler::getErrorTypesToProcess()

### ISSUE THREAD

**Issue by aschempp** [getsentry/sentry-php#341]
Since updating to the latest version (dependency of `getsentry/sentry-symfony` I get the following error:

> Fatal error: Call to undefined method Raven_ErrorHandler::getErrorTypesToProcess() in vendor/sentry/sentry/lib/Raven/ErrorHandler.php on line 100

**Comment by Jean85** [comment]
Closing this as stale. If this is still applicable, please feel free to comment further and report more info.
