### ISSUE TITLE
handleFatalError reporting suppressed errors

### ISSUE THREAD

**Issue by ls5302** [getsentry/sentry-php#348]
I think the `handleFatalError` method does not work as expected when dealing with the suppression operator as errors are being logged. 

From the PHP docs it looks like the `error_get_last` returns suppressed errors and checking for the `error_reporting !== 0` does not exclude the error. As demonstrated by the following snippet:

```
$dir_age   = @filectime('/tmp/foobar');
print_r(error_get_last());
```

My test scenario uses a functioning Sentry for PHP setup, and the following line
```
$dir_age   = @filectime('/tmp/foobar');
``` 
is logged 'ErrorExceptionActions.php:Raven_ErrorHandler in handleFatalError'.

**Comment by dcramer** [comment]
@ls5302 that's almost certainly true. I guess we could always bind the last_error, even when we dont capture it, as that's the only way I can think of to handle this case.

**Comment by ls5302** [comment]
I'm sorry to report that in my testing this doesn't solve the problem. The _last_handled_error property is empty when the handleFatalError method is called. Looks like the handleError method is never called for `$dir_age   = @filectime('/tmp/foobar');` line.

**Comment by dcramer** [comment]
@ls5302 is the program exiting on that line or does it continue successful after?

**Comment by ls5302** [comment]
It continues... I'm beginning to think it might something changes during the executing of the my application. If I reduce my test to a few lines of code, much like your unit test, the error handler is called as expected and your modified code works as expected. I will try and find the cause of the my problem... and let you know (might be interesting).
