### ISSUE TITLE
Collapse middleware

### ISSUE THREAD

**Issue by stayallive** [getsentry/sentry-php#356]
In my Lumen apps (and also Laravel apps ofcourse) I have a lot of middleware and they pollute the stacktract a lot to the point no one reads them anymore... is there a way to collapse them unless the error was in a middleware ofcourse :)

Example (the bottom three I'm not immediatly interested in):

<img width="923" alt="screen shot 2016-09-19 at 23 34 17" src="https://cloud.githubusercontent.com/assets/1090754/18649780/a1fc7b22-7ec1-11e6-9b9c-7105a78e6bda.png">

Example 2 (only the very top one is interesting in the first place):

<img width="923" alt="screen shot 2016-09-19 at 23 31 55" src="https://cloud.githubusercontent.com/assets/1090754/18649718/4e165f00-7ec1-11e6-8d6f-7342fa8ae1b3.png">

**Comment by dcramer** [comment]
@stayallive not entirely sure what we'd do (other than say like if > X frames in display, show {X collapsed frames}). Usually the app vs full works well-enough, but generally the bigger and more complex your app becomes, the less useful it is.

**Comment by stayallive** [comment]
I would be fine with being able to say everyting under the path `app/Http/Middleware` should be marked as not in-app personally.

Would be really cool to have some way to say the files under these paths should be marked as in app but be bundled together in the interface somehow. Although I did not think that through too well so that might be a horibble idea.

**Comment by dcramer** [comment]
We were discussing an "exclude app paths" config in #343

**Comment by stayallive** [comment]
Damn. I knew I read it somewhere... looked for that issue for 15 mins 👍
