### ISSUE TITLE
ERROR: Fatal Error (1): Using $this when not in object context

### ISSUE THREAD

**Issue by m1l4n** [getsentry/sentry-php#360]
After update(1.4.0) Raven crash on:
ERROR: Fatal Error (1): Using $this when not in object context in [.../vendor/sentry/sentry/lib/Raven/Stacktrace.php, line 147]

**Comment by dcramer** [comment]
Sorry about that! Thought I had thoroughly QA'd these paths, but clearly that wasn't true. 1.4.1 fixes this.
