### ISSUE TITLE
Is there any plan for supporting local timezone?

### ISSUE THREAD

**Issue by JellyBool** [getsentry/sentry-php#362]
I am using sentry for my project but I find it very inconvenience the issue time is always format with UTC time since I am from China.

```php
 if (!isset($data['timestamp'])) {
            $data['timestamp'] = gmdate('Y-m-d\TH:i:s\Z');// Here get UTC time
        }
```
I think it would be really nice if the timezone can also be configurable. Because every time I look into the issue I have to caculate the time.

**Comment by dcramer** [comment]
The displayed time zone can be changed via your account settings
