### ISSUE TITLE
<no message value> when logging to sentry using monolog

### ISSUE THREAD

**Issue by letr0n** [getsentry/sentry-php#364]
I'm logging to sentry using monolog and I'm getting ```<no message value>``` in sentry when logging:

```php
$ravenClient = new Raven_Client('...');

$ravenHandler = new RavenHandler($ravenClient);

$ravenHandler->setFormatter(new LineFormatter("%message% %context% %extra%\n"));

$monolog->pushHandler($ravenHandler);
```

```php
$monolog->error($exception, ['exception' => $exception]);
```

I have no idea if the bug is in the monolog ```RavenHandler``` or the sentry ```Client``` class but it makes sentry logging useless.

Are the parameters passed to ```Client::captureException()```correct? ([RavenHandler.php#L185](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/RavenHandler.php#L185)
) Not easy to tell since the parameters are so poorly documented ([Client.php#L412](https://github.com/getsentry/sentry-php/blob/master/lib/Raven/Client.php#L412)).

_Reference: Seldaek/monolog#867_

**Comment by dcramer** [comment]
Is this on sentry.io? If not you might be using an old version of Sentry which doesnt support the current SDKs. Alternatively, if it's not capturing an exception at all, then its likely the object is not passed correctly.  I'll say this isn't an issue in the PHP SDK either way, as the Sentry server and PHP SDK work as expected.

**Comment by letr0n** [comment]
No. I'm using a self-hosted version and I'm running the latest stable release.

The problem is that you never call ```getMessage()``` on the exception passed as the first parameter. And ```$data``` coming from ```RavenHandler```does not contain the message either.

**Comment by dcramer** [comment]
@letr0n we don't store the message value for exceptions anymore. The server understands the difference between exceptions and non-exceptions, and it will show other data instead.

**Comment by letr0n** [comment]
Just double checked and we're running sentry version 8.1.2 so it's not the latest version after all. I'll upgrade tomorrow and see if that helps.
