### ISSUE TITLE
composer.json requires php >=5.2.4 but monolog 2.x requires php >= 7

### ISSUE THREAD

**Issue by matusch** [getsentry/sentry-php#370]
Hey guys,

first of all thanks for the sentry php client!

But I tried to use it for one of our "older" php apps (php version 5.5.28) and found out that the monolog link in your composer is open for all version. Now we come to an issue:

`  
Problem 1
    - monolog/monolog 2.0.x-dev requires php ^7.0 -> your PHP version (5.5.28) does not satisfy that requirement.
    - monolog/monolog 2.0.x-dev requires php ^7.0 -> your PHP version (5.5.28) does not satisfy that requirement.
    - Installation request for monolog/monolog 2.0.x-dev -> satisfiable by monolog/monolog[2.0.x-dev].
`

Is it possible to change the monolog/monolog to 1.21 so that we can use it further with php version older than php 7?

Thanks!

**Comment by dcramer** [comment]
@matusch we're liberally allowing any version of monolog as a dependency:

https://github.com/getsentry/sentry-php/blob/master/composer.json#L21

This means you should be able to require 1.21 in your own composer file, and sentry/sentry should work just fine with it.

**Comment by Thamaraiselvam** [comment]
created a pull request [(374)](https://github.com/getsentry/sentry-php/pull/377)
