### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted (endless loop)

### ISSUE THREAD

**Issue by cottton** [getsentry/sentry-php#371]
Where and why does the raven client eats the memory?

Here is a very simple test:

    while (true) {
        new \Raven_Client(
            'http://' . md5('foo') . ':' . md5('bar') . '@example.com:5555/baz'
        );
        var_dump(memory_get_usage());
    }
    // Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /.../vendor/sentry/sentry/lib/Raven/Context.php on line 19
    // Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /.../vendor/sentry/sentry/lib/Raven/Client.php on line 126

Using:

    "sentry/sentry": "1.5.0",
    PHP 7.0.11

Thanks,
cottton

**Comment by dcramer** [comment]
We install some basic data handlers when you instantiate the client.  If you want to know more it's easier to just look at the source and see what it's doing.
