### ISSUE TITLE
$client->setAppPath() not worked

### ISSUE THREAD

**Issue by Thamaraiselvam** [getsentry/sentry-php#374]
I have set my application root path 
`$client->setAppPath($path)` but the problem is , I am also getting error events from other paths. 
example my root folder is 
`/opt/lampp/htdocs/wordpress/wp-content/plugins/myplugins` this is my path. but i am also getting events from other path ie
`/opt/lampp/htdocs/wordpres/wp-content/plugins/otherplugins`

**Comment by Thamaraiselvam** [comment]
I want to get events from the particular folder, there are options to exclude paths(`setExcludedAppPaths`). but my case is different I want to include a path. I want events only from that path.

**Comment by dcramer** [comment]
What @stayalive said is correct. We dont have a feature that lets you only capture errors form part of an application.

**Comment by Thamaraiselvam** [comment]
created a pull request [(374)](https://github.com/getsentry/sentry-php/pull/377)
