### ISSUE TITLE
Attribute message is absent in exceptions in 1.x branches

### ISSUE THREAD

**Issue by WoZ** [getsentry/sentry-php#381]
Hi!

I've found that client of 1.x version doesn't pass `message` attribute to sentry with captureException (or handled fatal). We use cyclops as proxy between client and server and cyclops expects to receive message to group errors.

Prior to 1.0.x sentry-php formed data with that attribute, but @dcramer in 882cb7ba12a4a0b32fee12fb00f26722e45e6541 has removed it.

First of all, I've checked official [sentry documentation]( https://docs.sentry.io/clientdev/attributes/#required-attributes) and it says that `message` is required.

So, my question is why it was deleted?

**Comment by dcramer** [comment]
@WoZ modern versions of Sentry no longer utilize the unstructured 'message' attribute, so it has been (slowly) removed from SDKs. It sounds like Cyclops would need updated to understand how better to aggregate things, as message hasn't actually been an accurate aggregation method for a long time.

We definitely need to update the documentation, as its only required if no other structured data is present (and then its automatically transformed into something else).
