### ISSUE TITLE
Breadcrumb ErrorHandler goes to infinite loop

### ISSUE THREAD

**Issue by davidfuhr** [getsentry/sentry-php#383]
When executing my PHPUnit Tests at some point the script stops with return code 255.

After a little debugging I noticed that the Breadcrumb ErrorHandler goes into an into an infinite loop just before the terminaltion of my tests.

The `install()` method sets the `$existingHandler` to `[$this, 'handleError']` [(L44).](https://github.com/getsentry/sentry-php/blob/be1c720b4c0a638b95d28a0f9970aad9e85ca8e4/lib/Raven/Breadcrumbs/ErrorHandler.php#L44) And `handleError()` calls the existingHandler (itself) at the end in [line 36](https://github.com/getsentry/sentry-php/blob/be1c720b4c0a638b95d28a0f9970aad9e85ca8e4/lib/Raven/Breadcrumbs/ErrorHandler.php#L36).

I use the sentry-symfony integration. And I have set my `dsn` to `false` for my testing environment. But appearantly this does not disable the Sentry ErrorHandler despite the comment in https://github.com/getsentry/sentry-symfony/pull/21#issuecomment-244449548

**Comment by dcramer** [comment]
@davidfuhr is it possible your tests are simply reinstalling handlers (or reinstantiating the client) over and over?

**Comment by davidfuhr** [comment]
Thanks! You were right! Sorry for bothering :(
