### ISSUE TITLE
Raven_Client#user_context() no longer accepts $data = null as of 1.6.0

### ISSUE THREAD

**Issue by ianfp** [getsentry/sentry-php#388]
[This commit](https://github.com/getsentry/sentry-php/commit/8a5bff2caacd9eaf850b1d49159a1ff31e49bbac) breaks backwards-compatibility because if `null` is passed, the `array_merge()` triggers a PHP warning (which in my app is converted to an exception).

And indeed, `null` is sometimes passed. Monolog's [RavenHandler](https://github.com/Seldaek/monolog/blob/1.22.0/src/Monolog/Handler/RavenHandler.php#L190) does just that.

**Comment by dcramer** [comment]
should be fixed in 1.6.1

**Comment by ianfp** [comment]
Confirmed, 1.6.1 fixes the issue. Thanks!
