### ISSUE TITLE
Error when setting user context since 1.6.0: array_merge(): Argument #2 is not an array

### ISSUE THREAD

**Issue by tremby** [getsentry/sentry-php#389]
Since #387 I get an error when setting the user context.

The monolog `RavenHandler` stores `$previousUserContext` which in my app ends up being `null` (rather than its initial value of `false`). This happens when `RavenHandler` sets it to the value of `$this->ravenClient->context->user`, which at this point is `null`.

It then calls `user_context` (see https://github.com/Seldaek/monolog/blob/1.22.0/src/Monolog/Handler/RavenHandler.php#L189 which is the latest release right now -- current master has slightly different code but the same issue) with that `null` in the `$data`, which is not an array, hence the error.

I don't know if this is a bug with sentry-php or with the monolog `RavenHandler`, but it's the recent change in behaviour which is causing the error.

**Comment by ianfp** [comment]
Dup of #388, I believe.

**Comment by dcramer** [comment]
Yep, should be fixed in 1.6.1

**Comment by tremby** [comment]
Oh wow, reported just as I typed mine. Thanks!
