### ISSUE TITLE
Error during creation of the raven client

### ISSUE THREAD

**Issue by swim89** [getsentry/sentry-php#390]
Hello, I have a problem during creation of the raven client.

I wrote this code in the top of my page that is called in all pages:
`require_once 'classi/raven/Autoloader.php';`
`Raven_Autoloader::register();`
`$client = (new Raven_Client('https://public: secret@sentry.io/usercode'))->install();`

But my php print: 

> Fatal error: Class 'Raven_Client' not found in /web/htdocs/www.finsicilia.it/home/config.php on line 8

Can you help me to solve it?

Thanks
Luca

**Comment by dcramer** [comment]
Somethings is breaking the autoloader code. If I were you I would try using composer as it will make your life *significantly* easier, and it includes a reusable autoloader. Unfortunately I'm not sure what could cause this to happen without debugging it on your machine, and that's not something we do.

**Comment by dcramer** [comment]
I'm actually going to close this out as it's unclear to my why our autoloader wouldn't be working for you and without more information there's unfortunately little we can do here.
