### ISSUE TITLE
The method Raven_Client::_convertPath() works incorrectly on Windows

### ISSUE THREAD

**Issue by dmitry-fedyuk** [getsentry/sentry-php#392]
The incorrect code: https://github.com/getsentry/sentry-php/blob/1.6.1/lib/Raven/Client.php#L180-L185

```
// we need app_path to have a trailing slash otherwise
// base path detection becomes complex if the same
// prefix is matched
if (substr($path, 0, 1) === '/' && substr($path, -1, 1) !== '/') {
    $path = $path . '/';
}
```

**Comment by dcramer** [comment]
We'll get this (and the relevant ticket resolved). Really wish we could setup windows builds on Travis, as I'm sure we're going to fuck this up again in the future without CI.
