### ISSUE TITLE
The method Raven_Client::getDefaultPrefixes() works incorrectly on Windows

### ISSUE THREAD

**Issue by dmitry-fedyuk** [getsentry/sentry-php#393]
The incorrect code: https://github.com/getsentry/sentry-php/blob/1.6.1/lib/Raven/Client.php#L168-L172

```
private function getDefaultPrefixes()
{
    $value = get_include_path();
    return explode(':', $value);
}
```

![02](https://cloud.githubusercontent.com/assets/83204/21428931/90c6c1be-c86d-11e6-9ed0-a50081fb52e3.png)

**Comment by dcramer** [comment]
Im actually not entirely sure how we should go about making this work.

**Comment by mitsuhiko** [comment]
@dcramer i think on windows the include paths use `;` as separator.

**Comment by mitsuhiko** [comment]
Just verified. Uses `;` for Windows and `:` everywhere else: http://php.net/manual/en/ini.core.php#ini.include-path

**Comment by dcramer** [comment]
https://github.com/getsentry/sentry-php/pull/397
