### ISSUE TITLE
Discarded invalid value for parameter 'sentry.interfaces.Message'

### ISSUE THREAD

**Issue by sergeytsivin** [getsentry/sentry-php#394]
On-premise installation of Sentry 8.10.0 reports this error on every event submitted by Sentry/PHP 1.6.1

> Discarded invalid value for parameter 'sentry.interfaces.Message'

```
{
  "name": "sentry.interfaces.Message",
  "value": {
    "message": {},
    "params": [],
    "formatted": {}
  }
}
```

I guess this could be because 'formatted' attribute is not part of the [interface](https://docs.sentry.io/clientdev/interfaces/message/).

**Comment by dcramer** [comment]
How are you generating this? It's invalid because message and formatted
must be strings.

**Comment by dcramer** [comment]
Closing this until we confirm its an issue internally.

**Comment by sergeytsivin** [comment]
Sorry, I confirm that this is not a bug with Raven_Client but rather wrong parameters being passed to captureMessage method. I use the [yii2-sentry-log log target](https://github.com/intersvyaz/yii2-sentry-log) to report errors via Yii2's built-in logger, and the problem appears to be on that side.
