### ISSUE TITLE
Warnings mangle variables

### ISSUE THREAD

**Issue by mnpenner** [getsentry/sentry-php#398]
There's a bug in [`lib/Raven/Stacktrace.php` on line 181](https://github.com/getsentry/sentry-php/blob/b40ebd0d13d718f2fb4fc2f5c64bd2d07318f0aa/lib/Raven/Stacktrace.php#L181-L196). Specifically, in this loop:

```php
$args = array();
foreach ($frame['args'] as $i => $arg) {
    if (isset($params[$i])) {
        // Assign the argument by the parameter name
        if (is_array($arg)) {
            foreach ($arg as $key => $value) {
                if (is_string($value) || is_numeric($value)) {
                    $arg[$key] = substr($value, 0, $frame_arg_limit);
                }
            }
        }
        $args[$params[$i]->name] = $arg;
    } else {
        $args['param'.$i] = $arg;
    }
}
```

If `$arg` is a &reference then `$arg[$key] = substr(...)` will mutate the original variable.

We had a *very* difficult to trace bug in our software where when a warning was triggered, a random global variable would be truncated to 1024 chars. Took us a long time to track it back to here.

One potential fix is to clone the frame args first:

```php
foreach (clone $frame['args'] as $i => $arg) {
```

**Comment by dcramer** [comment]
Thanks for pointing this out. Clone doesn't quite work, but I have at least a test that reproduces this behavior in some scenarios, so I'll see what we can do.

**Comment by dcramer** [comment]
@mnpenner PR attached, let me know if you think thats sufficient

**Comment by mnpenner** [comment]
@dcramer Thank you for the quick fix! We're going to test against changeset cd04e761c77cb06a25f31daa9eb3ec7a733e402a to make sure it works for our specific scenario. Code looks like it should work.

**Comment by dcramer** [comment]
:+1: once you verify it resolves your issue we'll get it merged + tagged

**Comment by mnpenner** [comment]
@dcramer Yup. We just tested it. Works like a charm. Thank you very much!
