### ISSUE TITLE
Bitwise operators used agains Arrays

### ISSUE THREAD

**Issue by pszalko** [getsentry/sentry-php#401]
I wonder why there are bitwise operators used against `int` and `array` types?
Result of such comparison is almost always false.

Here is an example from [lib/Raven/ErrorHandler.php:122](https://github.com/getsentry/sentry-php/blob/master/lib/Raven/ErrorHandler.php#L122)

```php
        if ($error['type'] & $this->fatal_error_types) {
            $e = new ErrorException(
                @$error['message'], 0, @$error['type'],
                @$error['file'], @$error['line']
            );
            $this->handleException($e, true);
        }
```

I assume it causes that `handleFatalError()` method does not work as expected.

**Comment by dcramer** [comment]
@pszalko at a glance this does seem like it would be broken. I will try to take a look today to confirm and get a fix in.

**Comment by dcramer** [comment]
I was trying to write an actual test for this function (which has been the biggest problem all along), but its seemingly not doable. At the very least I abstracted out the code which performs the check and we have tests now.

**Comment by dcramer** [comment]
I pushed out 1.6.2 which contains this fix
