### ISSUE TITLE
Send information using public key only

### ISSUE THREAD

**Issue by xduh** [getsentry/sentry-php#402]
In JavaScript lib is possible to send configure client with public key only, I wonder it can be useful in PHP too. i.e: Distributed packages.
What you guys think?

**Comment by dcramer** [comment]
It's not and there's no value in it. The key is only used on JS to prevent abuse from accidentally embedding it on other domains. At the end of the day people can still send false errors and it's just the cost of doing business. This is why we provide features to block IPs and other various controls.
