### ISSUE TITLE
PSR-3 Compatible?

### ISSUE THREAD

**Issue by davidbarratt** [getsentry/sentry-php#404]
Is this library PSR-3 compatible?  
http://www.php-fig.org/psr/psr-3/

If not, can it be?

**Comment by davidbarratt** [comment]
I believe we should be able to just include this package as a dependency  
https://packagist.org/packages/psr/log

and then implement the interface.

**Comment by dcramer** [comment]
I think there was a PR to bring in full compatibility. I'd be +1 on supporting it.

**Comment by nokitakaze** [comment]
PSR-3 need namespaces

**Comment by nokitakaze** [comment]
Easy: #426

**Comment by ste93cry** [comment]
Sentry is not a logging library, so I don't think it's appropriate to implement PSR-3. In case, it should _use_ PSR-3. For logging there are libraries like Monolog that works well, and Monolog itself has an handler that reports to Sentry. It seems to me we are just reimplementing something already existent. Plus, Sentry focus on tracking errors, why they happened and where, it's not a place where to store messages like a log file

**Comment by nokitakaze** [comment]
> Sentry is not a logging library

0_o. Sentry is definitely logging library. I use Sentry for logging purpose. It's really usable for this. Otherwise, why would an INFO level be needed?

This is Sentry. One of my projects. Look. It's full of information logs.
![default](https://cloud.githubusercontent.com/assets/9131758/23776120/4f845a06-053d-11e7-9f59-9587c1077884.PNG)

**Comment by dcramer** [comment]
Just to avoid jumping into the weeds:

https://sentry.io/vs/logging/

We think of Sentry as an additional thing beyond logging due to the depth it goes into. People compare it to logging because its the concept they're familiar with. It's a "log", but not traditional logging.

**Comment by ste93cry** [comment]
Quoting from that page:
>You'll need to determine what's right for you, but the important thing to remember is Sentry aims to support a lot, but it's primarily for capturing errors.

@nokitakaze Sure, I did not say that you can not capture logs, I said I think that using Sentry's focus is tracking errors and not log messages. If you want to capture logs, you should use libraries like Monolog that can even report to Sentry (as I said there is an handler for this out-of-the-box), but we shouldn't transform Sentry itself into a logger library. This is my opinion, at least

**Comment by nokitakaze** [comment]
Why do I need two or more logging systems if I have the good one? How can you conceptually separate logs with errors from logs with events? And for what?

**Comment by davidbarratt** [comment]
Making this library _compatible_ with PSR does **not** make Sentry a logger, it just allows it to be used with other tools that are _expecting_ a "logger".

**Comment by ste93cry** [comment]
>Making this library compatible with PSR does not make Sentry a logger

Making a library compatible with PSR-3 for me means accepting an instance of `LoggerInterface` and use it, not implementing the whole RFC. Otherwise, from `user` we became `implementors` (words taken from the PSR-3 document)

**Comment by thomasvargiu** [comment]
If someone wants to use Sentry with PSR-3 you can use this wrapper:
https://github.com/facile-it/sentry-psr-log
Or Monolog:
https://docs.sentry.io/clients/php/integrations/monolog/

**Comment by iSDP** [comment]
Monolog has a built in PSR-3 processor, i use it myself.

**Comment by ste93cry** [comment]
I'm going to close this issue since we're not going to implement PSR-3 as there are already many implementations of the specs like Monolog that are already able to forward the data to our Sentry client
