### ISSUE TITLE
User ip_address or ip?

### ISSUE THREAD

**Issue by Inscure** [getsentry/sentry-php#420]
In documentation here https://docs.sentry.io/learn/search/ is said that we can search by user ip using `user.ip`, but here https://docs.sentry.io/learn/context/ is that user ip should be sent to sentry as `ip_address` in `user_context`. Is that correct? Maybe it should be unified in next major version?

**Comment by stayallive** [comment]
Sorry for the late response, the way the SDK talks to Sentry and how Sentry presents it to the user for filtering is indeed different. 

But according to the SDK and the user docs still correct as of today (as you already saw). 

Possibly in the feature this will be unified but only if the server changes it's protocol to allow for that.

> https://docs.sentry.io/clientdev/interfaces/user/
