### ISSUE TITLE
Can we make ErrorHandler properties protected?

### ISSUE THREAD

**Issue by kzap** [getsentry/sentry-php#422]
All the properties in https://github.com/getsentry/sentry-php/blob/master/lib/Raven/ErrorHandler.php#L35 are private so if one wants to extend the class and use their own errorhandler you have to copy all the methods or do some hacky stuff. Is there a need to be private? Lets just make it protected

**Comment by dcramer** [comment]
+1. Dont see why not.

**Comment by nokitakaze** [comment]
Easy: #425

**Comment by kzap** [comment]
thank you :)
