### ISSUE TITLE
 requested domain name does not match the server's certificate

### ISSUE THREAD

**Issue by MrAbaddon** [getsentry/sentry-php#432]
Hello,
I'm getting the error:

[error] [raven] Unable to communicate securely with peer: requested domain name does not match the server's certificate.

In SSL labs I'm getting a result of A+ in the certificate Test.
The certificate is an alias certificate like *.mydomain.com .

We have sentry installed on permisses. When we were using sentry.io we have no errors. After installing in our servers and use our certificate we start to receive these errors.

Thanks for the help.

Regards,
Bruno Morais

**Comment by dcramer** [comment]
This isn't a place for support, but the tl;dr is "if you run Sentry yourself, you need to be capable of running all of the infrastructure required to support it". I'd strongly recommend just using our SaaS, but if you can't, support is available via other means:

https://sentry.io/support/

**Comment by MrAbaddon** [comment]
Sorry for disturbing. I thought it was a bug but I've manage to solve it.

**Comment by ibuk01** [comment]
and how?
