### ISSUE TITLE
Bypass clipped strings and sliced stacktrace variables

### ISSUE THREAD

**Issue by jessedobbelaere** [getsentry/sentry-php#450]
Hi, most of the time I don't have to log long context data. But if a string is longer than 1024 chars, Raven serializes and displays a string with `{clipped}` at the end, as seen here: https://github.com/getsentry/sentry-php/blob/master/lib/Raven/Serializer.php#L96-L98

Now I do get why this is done. We probably don't want to push (uncontrolled) big amounts of data into Sentry. But in specific case it's quite useful to add a json serialized string to the context array to be able to debug my issue way faster if it ever happens. 

**Are there any options or workarounds in that case to avoid `{clipped}` strings**? It would be nice to have the possibility in both the context array and in the stacktrace variables to show the full output. As seen in the screenshot below, we need to debug something but the requestBody isn't displayed entirely. 

* Context array shows `{clipped}` when strings are >1024 chars
* Stacktrace variables show `...` ellipsis if string is bigger than +- 512 chars. Sometimes vital debugging information is sliced away unfortunately

![screen shot 2017-04-26 at 13 04 46](https://cloud.githubusercontent.com/assets/1352979/25454355/07e74a8c-2a81-11e7-9689-c36021e54409.png)

**Comment by dcramer** [comment]
Ideally we'd have a good answer here, but its complicated. The problems are this:

1. All of this data is arbitrary (we dont know whats important)
2. We **have** to put limits on the size of data because its expensive to process, store, and render
3. It'd be very complex to have a way to describe which attributes are higher priority

I'm totally open to ideas, but its just super complex in general.

**Comment by jessedobbelaere** [comment]
Yeah totally agree. It would make things way too complex to distinguish data that should be fully logged or not, and people could abuse it. I'll close this issue.

**Comment by ezintz** [comment]
Hello, not sure but I guess it would be working properly if the default serializer would be create "correct".  As far as I can see the Raven_Serializer can take two arguments and in the Raven_Client constructor only one is used (https://github.com/getsentry/sentry-php/blob/master/lib/Raven/Client.php#L211). I guess that `$this->serializer = new Raven_Serializer($this->mb_detect_order, $this->message_limit);` would actually fix the issue.

A simple workaround could be something like this.

```php
$options = ['message_limit' => 0];
$client = new Raven_Client($options);
$clientSerializer = new Raven_Serializer($client->mb_detect_order, $client->message_limit);
$client->setSerializer($clientSerializer);
```
