### ISSUE TITLE
Remarks about excluded_app_paths

### ISSUE THREAD

**Issue by JellyBellyDev** [getsentry/sentry-php#452]
Hi guys,
I studied library logic about the `excluded_app_paths` option. 
I noticed that if you use this option, when an error occurs on that path, it is simply omitted from the stacktrace but the error is sent to the sentry itself.
If I wanted to not send sentry notifications if something happened on that path excluded as I can do?
Example: I use an outside library that is no longer maintained that has deprecated features and I do not want to receive any notification about these errors.
Thank you

**Comment by dcramer** [comment]
This configuration is not what you're trying to use it for. If you want to
prevent sending errors there's a should_send_callback (or something
similar, its in the docs).

**Comment by JellyBellyDev** [comment]
Thanks for the advice.
For the chronicle the option is called `send_callback`.
I close.
