### ISSUE TITLE
Exceptions go to Sentry but not to log file for application

### ISSUE THREAD

**Issue by vbjordan** [getsentry/sentry-php#468]
Currently using version 1.6.2 of sentry-php as a composer dependency and I'm seeing this issue with the library:

https://stackoverflow.com/questions/35274672/empty-php-logs-when-using-sentry

So an exception gets sent to Sentry, but the error message doesn't go to the log for the application. Is this a known issue? Is there a workaround or some configuration that needs to be set?

**Comment by vbjordan** [comment]
OK looks like it's fixed in 1.7.0 (#421)

https://github.com/getsentry/sentry-php/blob/master/CHANGELOG.md

This is a pretty bad regression IMO, any idea when that will be officially tagged?

**Comment by Jean85** [comment]
I think only @dcramer can answer this..

**Comment by dcramer** [comment]
Fwiw we don't consider this a regression as behavior never existed before. 

@jean85 I can write up general docs on how I prepare releases if you're interested in shipping 1.7.0?

**Comment by Jean85** [comment]
@dcramer absolutely! Let us know how the flow works; I imagine that you still have to authorize a new release, but we still can do all the heavy lifting for you ;)

**Comment by dcramer** [comment]
https://github.com/getsentry/sentry-php/pull/470

**Comment by dcramer** [comment]
I'm going to close this out, but we'll get 1.7.0 out by EOW.

**Comment by vbjordan** [comment]
That's great news, thanks.

**Comment by dcramer** [comment]
@vbjordan sorry about that, shoudl be live now
