### ISSUE TITLE
Can't install via Composer

### ISSUE THREAD

**Issue by BlackJair** [getsentry/sentry-php#478]
Trying to install via composer require sentry/sentry i get the following error:

  [Composer\Downloader\TransportException]                                     
  The "http://packagist.org/p/sentry/sentry%245c6f9954c87917307ec880e25199dc2  
  4d3b9477df6e41c79f2c914de85722df7.json" file could not be downloaded (HTTP/  
  1.1 404 Not Found)

I'm new to composer and sentry so I have no idea how to follow.

**Comment by ste93cry** [comment]
Can you please post the output of the command `composer diagnose`?

**Comment by BlackJair** [comment]
> Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: WARNING
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: 
                                                                                                                                  
  [Composer\Downloader\TransportException]                                                                                        
  The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:  
  error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed                                               
  Failed to enable crypto                                                                                                         
  failed to open stream: operation failed                                                                                         
                                                                                                                                  

diagnose

**Comment by ste93cry** [comment]
It seems to me pretty clear that you're having problems with the SSL certificate validation process. Please download the [`cacert.pem`](https://curl.haxx.se/ca/cacert.pem) file and place it inside a path of your choice. Then, in the `php.ini` configure the `curl.cainfo` option to point to it and retry

**Comment by ste93cry** [comment]
I'm going to close this issue due to lack of response. If you still have the problem feel free to reopen it
