### ISSUE TITLE
Exclude anonymous functions from app

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry-php#481]
They're not correctly "in app", and if we can't guarantee they are in situations where we've configured an app prefix, let's just exclude them.

```
Exception: An unhandled exception
#38 app/Http/routes.php(16): {closure}
#37 [Anonymous function](0): call_user_func_array
#36 vendor/laravel/framework/src/Illuminate/Routing/Route.php(155): runCallable
#35 vendor/laravel/framework/src/Illuminate/Routing/Route.php(130): run
#34 vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\{closure}
#33 [Anonymous function](0): call_user_func
#32 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): Illuminate\Pipeline\{closure}
#31 [Anonymous function](0): call_user_func
#30 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): then
#29 vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): runRouteWithinStack
#28 vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): dispatchToRoute
#27 vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): dispatch
#26 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Foundation\Http\{closure}
#25 [Anonymous function](0): call_user_func
#24 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): Illuminate\Pipeline\{closure}
#23 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): handle
#22 [Anonymous function](0): call_user_func_array
#21 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#20 vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): handle
#19 [Anonymous function](0): call_user_func_array
#18 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#17 vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): handle
#16 [Anonymous function](0): call_user_func_array
#15 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#14 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): handle
#13 [Anonymous function](0): call_user_func_array
#12 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#11 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): handle
#10 [Anonymous function](0): call_user_func_array
#9 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#8 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): handle
#7 [Anonymous function](0): call_user_func_array
#6 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#5 [Anonymous function](0): call_user_func
#4 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): then
#3 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): sendRequestThroughRouter
#2 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): handle
#1 public/index.php(54): require_once
#0 server.php(21): null
```

**Comment by Jean85** [comment]
Are we sure that we want to do that? Frameworks like Symfony use a lot of anonymous functions, i.e. for event dispatching or request handling, and hiding those steps could make reading the stack trace a bit difficult.

**Comment by dcramer** [comment]
@Jean85 i think this only affects internal PHP functions, but I'm not sure.

**Comment by ste93cry** [comment]
Are we sure that in branch `2.x` this has not been fixed yet? I refactored a lot of the code that handles the stacktraces, and if I remember correctly the anonymous functions should have the appropriate caller file path

**Comment by Jean85** [comment]
@ste93cry if you refactored this, it's great!

@dcramer actually I see as anonymous functions any closure or inline function, so a lot of framework code can be considered like that.

**Comment by dcramer** [comment]
I'm not sure if it's changed in 2.x but as I've said before, while the rewrite is great, it doesn't mean we're abandoning things until it's done.

**Comment by dcramer** [comment]
@Jean85 i think the thing we need to confirm is, do the closures that are defined in Foo.php show up as being defined there? The main issue is the ones that are without file location.

Per @stayallive's suggestion in the PR, I do think we can improve by doing reflection when possible, and that might ensure that "all app code has a filename".

**Comment by Jean85** [comment]
This is an example from my setup with Symfony 3:

![sentry_anon_functions](https://user-images.githubusercontent.com/6729988/28770550-daa67b42-75df-11e7-8248-8f404c941b7a.jpg)

Obviously, the first row above that is my controller. Is this enough?

**Comment by dcramer** [comment]
mmm yeah we will want to confirm if we do reflection if we still get the controller as the filename, since the main goal is to avoid breaking apart the stacktrace repeatedly (which is what happens in laravel right now)

**Comment by Jean85** [comment]
I do not have a Laravel app to do the same test... someone else?

**Comment by stayallive** [comment]
Yeah I didn't test the code yet but will try it out to see if it helps on Laravel.
