### ISSUE TITLE
registerErrorHandler() configuration problem

### ISSUE THREAD

**Issue by bojanpejic** [getsentry/sentry-php#488]
https://github.com/getsentry/sentry-php/blob/9c35545d7be65f42dd7aaf95f4da2d695fdeff38/lib/Raven/ErrorHandler.php#L175

For old error handler, shouldn't be more appropriate to try to get the error level set and pass it there? 

Maybe something like:
```
$this->old_error_handler = set_error_handler(array($this, 'handleError'), error_reporting());
```

Issue in which I've actually run was related to `Raven_ErrorHandler->registerErrorHandler()`, although I've passed parameters over there like:
```
$errorTypes = array(
            E_ERROR,
            E_PARSE,
            E_CORE_ERROR,
            E_CORE_WARNING,
            E_COMPILE_ERROR,
            E_COMPILE_WARNING,
            E_STRICT,
            E_RECOVERABLE_ERROR,
            E_DEPRECATED,
        );

$error_handler->registerErrorHandler(true, $errorTypes);
```

I was still getting reported `E_NOTICE` errors, it felt like the desired configuration didn't take effect at all. I've just recently started to use Sentry and I'm still getting to know it, so in case I've missed something over there or regarding configuration excuse me.

**Comment by stayallive** [comment]
I have not tested this yet but I think what you are doing is right but it should not be passed as an array but a single integer that can be built like this (which would mean that the type hint is wrong):

```php
$errorTypes = E_ERROR | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_STRICT | E_RECOVERABLE_ERROR | E_DEPRECATED;

$error_handler->registerErrorHandler(true, $errorTypes);
```

**Comment by bojanpejic** [comment]
@stayallive Thanks! For now it looks like it works like you suggested, but I'm continue to follow it. 

What about `$this->old_error_handler` is it okay to be initialized with `E_ALL` instead trying to get the configuration of it?
```
$this->old_error_handler = set_error_handler(array($this, 'handleError'), E_ALL);
```

**Comment by stayallive** [comment]
Because we cannot retrieve how the old error handler was registered unfortunatly. See #475

**Comment by bojanpejic** [comment]
I see it now, was checking that issue earlier, but actually forgot about it. I'm closing this issue, since there is already one created.
