### ISSUE TITLE
Extend Raven_ErrorHandler - why is client private?

### ISSUE THREAD

**Issue by Ugoku** [getsentry/sentry-php#497]
We want to extend Raven_ErrorHandler in our project, to do some custom logic in `handleException`, but found that we can't access `$this->client` because it has private access.

Why is the reason that this is private and not protected? And is this something you are willing to change?
Thanks!

**Comment by ste93cry** [comment]
As far as I see the property is `protected`, not `private`.

https://github.com/getsentry/sentry-php/blob/9c35545d7be65f42dd7aaf95f4da2d695fdeff38/lib/Raven/ErrorHandler.php#L35

**Comment by Ugoku** [comment]
Whoops, sorry... we were running 1.6 and I didn't see it in the changelogs. Thanks for the quick reply!
