### ISSUE TITLE
Null DSN on Windows causes a curl timeout

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [getsentry/sentry-php#498]
Working fine on linux, on our development copies we omit the connection DSN to reduce calls.

One of our devs on Windows is facing a curl timeout showing a difference in curl or raven handling between linux and windows.

I've had a small look through and can see linux only async handling but we aren't using that option, so that's not the cause. Most likely an issue with one of the sync calls.

Will attempt to debug through and see where the issue might be.

**Comment by ste93cry** [comment]
Can you please elaborate this part:

>on our development copies we omit the connection DSN to reduce calls

**Comment by stayallive** [comment]
@Caffe1neAdd1ct do you have an update for us on the matter? 

Did you already have a chance to debug through it and find the culprit?

**Comment by stayallive** [comment]
Since we have not heard back from you I will close this issue for now. 

Please do re-open if you have more info and the issue persists!
