### ISSUE TITLE
realpath() open_basedir restriction in effect

### ISSUE THREAD

**Issue by thamaraiselvam** [getsentry/sentry-php#512]
> sentry-php-master/lib/Raven/Client.php

`$path = @realpath($value);`

This line causes the warning, it should have checked the `is_readable` before gets the `realpath`

**Comment by Jean85** [comment]
This piece of code is not present in the 2.0 branch, so it's already solved there.
As per the 1.x version, doesn't the `@` silence the warning? It's really strange...

**Comment by Thamaraiselvam** [comment]
`@` just suppress the error from the view, but it can be caught by the `error_get_last()` , Since its a WordPress site, Some plugins catch this error.

And 2.0 branch is stable? and I do not see any specific requirements for it.

**Comment by Jean85** [comment]
Nope, 2.0 is still under development. If you want, you can send a PR with the fix, it should be easy; please include tests.

**Comment by ste93cry** [comment]
>This piece of code is not present in the 2.0 branch, so it's already solved there.

Unfortunately the code has just moved location, but it's present in two places in the `2.x` codebase. A fix should be prepated for that new version too

**Comment by Thamaraiselvam** [comment]
Gotcha, I will add fix for it

**Comment by andreasschroth** [comment]
Can't confirm it's fixed. It still occurs with the very latest 1.9.2.

**Comment by stayallive** [comment]
@andreasschroth if you are still seeing this could you create an new issue with details about your php version and what is passed to the function and being reported. Wrote a quick test but that did not surface the issue for me.

**Comment by andreasschroth** [comment]
@stayallive Thanks for your reply. I was about to open a new issue already, actually, but as it fits 100% this issue I thought I comment here first. New issue is created: #653
