### ISSUE TITLE
A specific include path causes Sentry to fail

### ISSUE THREAD

**Issue by Luke-SF** [getsentry/sentry-php#513]
As an example, have "sentry" folder in folder/classes directory and this as folder/setup.php:

```php
ini_set( "include_path", "./:/usr/local/lib/php:/path/to/folder/classes" );

//Also always report exceptions:
include_once('sentry/lib/Raven/Autoloader.php');
$SFRaven_Client = new Raven_Client('thekey');
$error_handler = new Raven_ErrorHandler($SFRaven);
$error_handler->registerExceptionHandler();
$error_handler->registerErrorHandler();
$error_handler->registerShutdownFunction();
$SFRaven_Client->handleError(E_WARNING, 'Raven init', __FILE__, __LINE__ );
```

The autoloader.php starts to load (add echo and it echos out), but the requires in it are not working. 

PHP Fatal error:  Uncaught Error: Class 'Raven_Client' not found

**Comment by Jean85** [comment]
Have you tried to use `new \Raven_Client` with a backslash? What version of the lib are you using?

(I've edited your post to have syntax highlighting)

**Comment by Luke-SF** [comment]
The latest one, just downloaded zipped master yesterday. No I didn't try that, but dirname(dirname( instead of '/../' seems to work, not sure why it was built like that?

**Comment by Luke-SF** [comment]
No, one parameter in dirname() pre-php7.

That weird starting \ in classname seems to work, but where is that documented?

**Comment by Jean85** [comment]
Well with the leading backslash you're just expliciting that it's from the root namespace. Maybe you have a namespace declared that collides with the non-prefixed class name?

**Comment by stayallive** [comment]
This looks like a namespace declaration issue causing the class to not be found. Explicitly using `\Sentry_Client` or `use Sentry_Client` (before using `Sentry_Client`) should fix this.

If the problem persists while using the above things please re-open so we can investigate further.
