### ISSUE TITLE
Monolog user info is not handled like Raven_Client::user_context

### ISSUE THREAD

**Issue by pontus-mp** [getsentry/sentry-php#518]
The documentation for the [Monolog integration](https://docs.sentry.io/clients/php/integrations/monolog/) hints that user info can be sent in $record['context']['user'], but this way it ends up as "additional data". If you instead call $ravenClient->[user_context](https://docs.sentry.io/clients/php/config/#sentry-php-request-context)($userData), data appears in the user section in sentry.

There's probably a call to Raven_Client::user_context missing somewhere in the Monolog integration.

**Comment by Jean85** [comment]
That part of documentation is not handled here, but in this repo: https://github.com/getsentry/sentry-docs
Please reopen this issue there, or even correct this by submitting a PR! Thanks!
