### ISSUE TITLE
No timeouts set

### ISSUE THREAD

**Issue by willemstuursma** [getsentry/sentry-php#520]
There are no timeouts set on the cURL implementation. If the sentry host cannot be reached, it may take an exceptionally long time before cURL gives up.

I think it would be better to give up after a few seconds. Such long running requests usually worsen the problem.

<img width="486" alt="schermafbeelding 2017-12-01 om 11 36 29" src="https://user-images.githubusercontent.com/701299/33479081-05864c0e-d68c-11e7-9fa6-d302c74d6aee.png">

**Comment by Jean85** [comment]
We should provide an option to set it, in both 1.x and 2.x branches.

**Comment by stayallive** [comment]
Is that not what https://github.com/getsentry/sentry-php/blob/master/lib/Raven/Client.php#L164 is supposed to do @Jean85?

**Comment by Jean85** [comment]
Yes you're right, I've missed it! It's handled in there: https://github.com/getsentry/sentry-php/blob/e1001f80d07f08cbf8d2648cb707ea43bf3e5794/lib/Raven/Client.php#L1051-L1068

@willemstuursma can you debug further and check your setup? The option is already in there, and the default is 2 seconds.

**Comment by willemstuursma** [comment]
You are right, it's there in my setup too! (I am using the Symfony bundle). It's in a different method so I didn't really notice it right away.

Still took 20 seconds somehow, some maybe DNS lookup? I was connected to wifi with no actual internet connection.

**Comment by Jean85** [comment]
Looking at the [CURL docs](https://curl.haxx.se/libcurl/c/curl_easy_setopt.html), since we set the `CURLOPT_TIMEOUT` (docs [here](https://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT.html)), we are covering the entire request.

**Comment by stayallive** [comment]
I am not sure how that profiler works, but could it be 10 exceptions logged (totalling in 20s wait time)?

**Comment by stayallive** [comment]
@willemstuursma please let us know if the problem persists and the curl timeout is somehow not honored so we can investigate furthur, my current assumption is that the timeout was changed in the config or there are maybe 10 requests to Sentry totalling 20 seconds of wait time).
