### ISSUE TITLE
Unable to capture exception with malformed UTF-8 data in enclosing function variables

### ISSUE THREAD

**Issue by refaim** [getsentry/sentry-php#560]
If any of automatically captured function variables contain invalid UTF-8 data then Raven_Compat::json_encode fails to encode variables frame and server responds with 400 HTTP error code. As a result we will never know about the exception just because some variable in the enclosing function was bad.

**Comment by Jean85** [comment]
Thank you for reporting this issue!
Can you reproduce this with a test? I would like to understand if this affects the future 2.x release or not...

**Comment by ste93cry** [comment]
Closing this as it's pretty old. This has been fixed in the latest version of `2.2`

**Comment by Jean85** [comment]
FTR, the fix is #934
