### ISSUE TITLE
Monolog Breadcrumbs handler does not support Throwable

### ISSUE THREAD

**Issue by hkdobrev** [getsentry/sentry-php#561]
It seems to me the Monolog breadcrumbs handler does not support `Throwable`, but only `Exception`:

https://github.com/getsentry/sentry-php/blob/512661046e403dc5eb5ae192d5a6cda10e068a95/lib/Raven/Breadcrumbs/MonologHandler.php#L63-L68

In contrast the `RavenHandler` in Monolog itself supports both in `context[exception]`:

https://github.com/seldaek/monolog/blob/fd8c787753b3a2ad11bc60c063cff1358a32a3b4/src/Monolog/Handler/RavenHandler.php#L182-L187

**Comment by stayallive** [comment]
Hey @hkdobrev, thanks for reporting, PR #586 is opened to resolve this.

**Comment by Jean85** [comment]
Reopening until the fix is merged.
