### ISSUE TITLE
[2.0] Adding the PHP version

### ISSUE THREAD

**Issue by Jean85** [getsentry/sentry-php#562]
A PR was open under the Symfony integration repo (https://github.com/getsentry/sentry-symfony/pull/118) to add the PHP version as a default tag (thanks @hjanuschka !).

I turned it down because I think that this should be done in the base client here. I investigated a bit, and @mitsuhiko told me that there's an already supported context to do that, which looks like this:

```json
"contexts": {
    "runtime": {
        "version": "7.1",
        "name": "php"
    }
}
```

IMHO this should target the new client, what do you think?

**Comment by ste93cry** [comment]
>I think that this should be done in the base client here

I strongly agree. We could initialize the global runtime context with the data or initialize the runtime context of the event as the result will be the same. Alternately, (maybe the clearer option, but also maybe too much over engineered) we could create a specialized middleware

**Comment by Jean85** [comment]
Ok so #564 already implemented this for 1.x. If we port the tests from there into the 2.x branch we are good! :+1:

**Comment by ste93cry** [comment]
I was thinking, would it make sense to create a `RuntimeContext` class that validates that the only values that can be set are the one allowed by the SDK interface and in the constructor it initializes itself with some good defaults?

**Comment by ste93cry** [comment]
Closing since this has been implemented in both versions `1.x` and `2.x`
