### ISSUE TITLE
Reject back-to-back duplicate errors/messages

### ISSUE THREAD

**Issue by MeredithAnya** [getsentry/sentry-php#563]
I'm not sure if this possible to add, but if so, it seems reasonable to attempt to reject back-to-back errors that are the same and caused by the same user. Similar to what the JavaScript SDK has here: https://github.com/getsentry/raven-js/pull/861

**Comment by Jean85** [comment]
As discussed on Slack, I think we should target this feature to the 2.x branch.
I think that this is feasible, but I didn't delve into the code to prove it.

@stayallive @ste93cry what do you think?

**Comment by Spriz** [comment]
It seems like this was already a feature on the 1.x release? Was this removed intentionally?

**Comment by ste93cry** [comment]
I'm not aware of any feature like this on `1.x` and this has never been implemented in `2.x`, at least for now
