### ISSUE TITLE
Setting event_id on Exceptions can cause exceptions

### ISSUE THREAD

**Issue by leongersen** [getsentry/sentry-php#579]
I know this is very much an edge case, but I ran into the following problem:

A third party library I'm using throws a custom exception that has a `__set` method. This set method isn't intended to be used with unknown properties, and throws when Sentry/Raven tries to set `$e->event_id` on [this line](https://github.com/getsentry/sentry-php/blob/4b4131a65976cd3f8e320bed2b224474743b6e91/lib/Raven/ErrorHandler.php#L81).

For reproduction:

```PHP
Class CarelessSetException extends \Exception {

    public function __set ( $var, $value ) {
        if ( $var === 'event_id' ) throw new \Exception('Loop!');
    }
}
```

**Comment by Jean85** [comment]
Thanks for reporting this issue! What's the behavior of the client in this circumstance? It does report just one event that traces back to this? Or it creates a proper loop sending multiple events?

**Comment by leongersen** [comment]
The new exception seems to interupt the logging process, so neither: I just end up with no logging.

**Comment by stayallive** [comment]
@leongersen on what PHP version are you? I tried to reproduce using the following but got the `Loop!` exception reported just fine, the `CarelessSetException` is discarded, but there is definitly something sent!

```php
<?php

require __DIR__ . '/vendor/autoload.php';

ini_set('memory_limit', '8M');

$sentry = new Raven_Client('valid_dsn_trust_me');
$sentry->install();

Class CarelessSetException extends \Exception
{
    public function __set($var, $value)
    {
        if ($var === 'event_id') {
            throw new \Exception('Loop!');
        }
    }
}


function throw_me($name)
{
    throw new CarelessSetException("I am throwed: {$name}!");
}

throw_me('throwable');
```

**Comment by stayallive** [comment]
Although reporting the inner exception (which is not really important here since caused by the error tracking) is also not a good idea I created #587 but I am not sure if we should, although I don't see any reason against it 👍
