### ISSUE TITLE
More flexible app path inclusion / exclusion

### ISSUE THREAD

**Issue by stayallive** [getsentry/sentry-php#595]
Currently we have the `app_path` and the `excluded_app_paths` option to define if a stack frame is in the app context or outside.

How we do it in Laravel as a default:

```php
new Raven_Client([
    // ... other options
	'app_path' => '/var/www/app',
    'excluded_app_paths' => [
        '/var/www/app/vendor',
    ],
]);
```

However I would like to do mark some vendored folders as `in_app` for our own packages or packages that we maintain.

-----

I am not sure what the best way to go about this is but simply adding a `included_app_paths` seems silly... but is also the only way I can think of to keep backwards compat and allow the above to work.

```php
new Raven_Client([
    // ... other options
	'app_path' => '/var/www/app',
    'excluded_app_paths' => [
        '/var/www/app/vendor',
    ],
	'included_app_paths' => [
        '/var/www/app/vendor/foo/bar',
		'/var/www/app/vendor/bar/foo',
    ],
]);
```

Also I don't think adding all composer package folders you don't care about to `excluded_app_paths` is a no-go either since that makes a huge list that needs maintaining on every composer update operation or when adding/removing packages.

What are your thoughts?

**Comment by Jean85** [comment]
First thing first: do we have support on the Sentry server side for this kind of stuff?

**Comment by stayallive** [comment]
`in_app` is being sent for each stac frame already and is very much supported. The first 2 options already exists in the sdk too and is being used by default for Laravel/Lumen apps. 

So yes. Very much supported by the server. 

Just trying to see if we can include some dirs inside the excluded dirs to include a few vendored folders.

**Comment by stayallive** [comment]
Also, as you possibly meant that. `in_app` is handled locally by the sdk itself, not the server so those paths are not sent to the server so it can figure out how to determine if theyre part of the app.

**Comment by ste93cry** [comment]
What about changing the behaviour of the `in_app` by accepting globs (like Grunt or Gulp does)? This way we could have a single configuration option that handles both the included and the excluded paths

**Comment by Jean85** [comment]
I agree, it's probably simpler. If the `in_app` receives a single string, we could internally wrap it in a single-item array and go forward, without any BC.

**Comment by ste93cry** [comment]
>Should we target this into 2.x?

Imho, yes as it makes no sense to introduce new features on `1.x`

>If the in_app receives a single string, we could internally wrap it in a single-item array and go forward, without any BC.

I was thinking more of having the option accept either a single string or an array of strings representing globs, the way Grunt [does](https://gruntjs.com/configuring-tasks#globbing-patterns)

**Comment by Jean85** [comment]
> I was thinking more of having the option accept either a single string or an array of strings representing globs, the way Grunt does

Yes, I was saying the same, I was just talking about the internal implementation/handling of it.

**Comment by Jean85** [comment]
@HazAT should we reconsider this issue for 2.0?

**Comment by HazAT** [comment]
I would not discard the idea just not for `2.0`.
I will add it to the `2.1` milestone.
This issue is somewhat related https://github.com/getsentry/sentry-php/issues/706
