### ISSUE TITLE
Allow sanitization (not just removal) of cookie values

### ISSUE THREAD

**Issue by jon-simpkins** [getsentry/sentry-php#598]
In SanitizeDataProcessor.php, the `sanitizeHttp` function does not actually run the cookies array through the sanitize function, so if you have a 'password' cookie (just for the sake of argument), the value of that cookie will be reported to Sentry rather than being replaced with '******'

The fix is the one-line change to add:
'array_walk_recursive($cookies, array($this, 'sanitize'));'
to line 94 of the file, any objections?

**Comment by Jean85** [comment]
Cookies should be already fully sanitized by the `Raven_Processor_RemoveCookiesProcessor`.

**Comment by jon-simpkins** [comment]
Well sort of, they're removed entirely in that processor. Would y'all be open to adding something like `Raven_Processor_SanitizeCookiesProcessor` (in the same vein as the one for headers) that would allow for finer-grain blacklisting of the cookie values?

**Comment by ste93cry** [comment]
>Would y'all be open to adding something like Raven_Processor_SanitizeCookiesProcessor (in the same vein as the one for headers) that would allow for finer-grain blacklisting of the cookie value

In version 2.x (which is still in development) the updated version of the `SanitizeCookiesProcessor` (which is the updated version of the one which is being discussed here) does exactly what you want and let users have full control of which cookies are sanitized

**Comment by jon-simpkins** [comment]
Oh, that's perfect. Is there already an issue tracking this then?

**Comment by ste93cry** [comment]
PR is #533 and it's already merged in branch `2.x`, however as far as I know there are no plans to backport this feature to `1.x`

**Comment by jon-simpkins** [comment]
I'm happy to wait for the feature in 2.x. Thanks for being so responsive!
