### ISSUE TITLE
Weird Exception

### ISSUE THREAD

**Issue by pesseyjulien** [getsentry/sentry-php#607]
Hi,

I'm getting this following error which I do not understand :

`Cannot access protected property Raven_ErrorHandler::$error_types in /home/ec2-user/www/api-football/releases/29052018-013805/vendor/sentry/sentry/lib/Raven/ErrorHandler.php:109
`

Full log :

`ErrorException: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Cannot access protected property Raven_ErrorHandler::$error_types in /home/ec2-user/www/api-football/releases/29052018-013805/vendor/sentry/sentry/lib/Raven/ErrorHandler.php:109`

Stack trace:
```
#0 [internal function]: Raven_ErrorHandler->handleError(8, 'Undefined prope...', '/home/ec2-user/...', 629, Array)
#1 /home/ec2-user/www/api-football/releases/29052018-013805/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php(629): ReflectionProperty->getValue(Object(Addict\Bundle\FeedBundle\Document\Categorie))
#2 /home/ec2-user/www/api-football/releases/29052018-013805/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php(702): Doctrine\ODM\MongoDB\UnitOfWork->getDocumentActualData(Object(Addict\Bundle\FeedBundle\Document\Categorie))
#3 /home/ec2-user/www/api-football/releases/29052018-013805/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php(689): Doctrine\ODM\MongoDB\UnitOfWork->computeOrRecomputeChangeSet(O
#1 vendor/sentry/sentry/lib/Raven/ErrorHandler.php(109): handleFatalError
#0 vendor/sentry/sentry/lib/Raven/ErrorHandler.php(0): null
```

Thanks in advance for your help,
Julien

**Comment by stayallive** [comment]
Hey @pesseyjulien this is a very weird error indeed since yes the `error_types` is protected but as far as I can see is accessed from within the class it's defined in so should be good.

The stack is very confusing and I can't get it to trigger this exception from a few quick tests.

Do you have a small piece of code / application where we you can reproduce so we can investigate?

Also did you make any changes to the Symfony integration or adaptations other than the default installation instructions?

**Comment by pesseyjulien** [comment]
Thanks for the quick feedback.

Here is what I essentially do : 


```
        $dm = $this->get('doctrine_mongodb.odm.document_manager');
        $categorie = $dm->getRepository('AddictFeedBundle:Categorie')->find($id);
        if (is_null($categorie)) {
            throw new ResourceNotFoundException("Unable to find categorie with id '".$id."'");
        }

        $categorie = $this->hydrateCategorieFromParams($params, $categorie);
        $dm->merge($categorie);
        $dm->flush();

        $view = $this->view(array('categorie' => $categorie));
        return $this->handleView($view);

```

This is part of an API. The weirdest part maybe, is that when I tried to update my document using this endpoint, I had a bunch of errors 500, with this exception, and then, at some point, it was working.

So i'm guessing it was a temporary issue, but which one that is the question !

**Comment by Jean85** [comment]
This issue comes from https://github.com/getsentry/sentry-symfony/issues/135

**Comment by pesseyjulien** [comment]
I think it was an issue within my code, but not very well handle by sentry, which was causing another issue on top of it ! 

That would explain the weird stack trace.

**Comment by stayallive** [comment]
If you happen to know what the issue is and can reproduce (what kind of scenario triggers it) we can possibly improve the SDK to handle that case better. But without repro it could be a lot of things.
