### ISSUE TITLE
To use X-Forwarded data or not?

### ISSUE THREAD

**Issue by malc0mn** [getsentry/sentry-php#631]
Given #594 and the comment referred to in that issue as to why **not** to use the data provided by the `X-Forwarded` headers, I would like to open a discussion on this topic with a **proposal** on a possible solution.

**1. Why X-Fowarded headers?**
As we probably all know, `X-Forwarded` headers are usually set by reverse proxies to indicate the original request status, usually by means of these basic ones:
- `X-Fowarded-For`: IP address of client **and** proxies, multiples separated by a comma
- `X-Fowarded-Proto`: http or https
- `X-Fowarded-Port`: 80, 443, ...

These get added by a reverse proxy since they usually modify the original request when forwarding it to the receiving backend because:
- the receiver is running on a different port
- the reverse proxy is (also) doing HTTPS offloading
- ...

The receiver can use the data provided by these headers to inspect the original request.

In PHP these headers are all transformed to uppercase and dashes will become underscores and all are available through the global `$_SERVER` [array](http://php.net/manual/en/reserved.variables.server.php).

Depending on the setup, one can choose to _copy over_ the `X-Forwarded` data to the 'default' PHP provided placeholders:
- `X-Fowarded-For` => `$_SERVER['REMOTE_ADDR']`
- `X-Fowarded-Proto` => `$_SERVER['HTTPS']` (usually a value of `on` or `off` but according to the docs "_Set to a non-empty value if the script was queried through the HTTPS protocol_".
- `X-Fowarded-Port` => `$_SERVER['SERVER_PORT']`

As rightfully pointed out, we cannot safely trust `X-Forwarded` headers as they can easily be added by anyone, even the client performing the original request.
Consider the `sentry-php` client running on a site that is *not* behind a reverse proxy, then blindly relying on those headers is a security risk as anyone can set them with any content.
**Even with a setup that copies over the data to the 'default' PHP provided placeholders, it can still be problematic.**

**2. So this is all about trust: can we trust these headers or not?**
Short answer: yes. So if we could indicate that `sentry-php` can trust these headers, then we can safely use them.

**3. Possible solution**
Trusting these headers _could_ be as easy as adding a configuration option `trusted_proxies` which would hold an array of IP addresses (v4 and v6) of the trusted proxies.
Validation of the `X-Forwarded` headers then needs to check IF **at least one** of the `trusted_proxies` IP addresses is present in the `X-Forwarded-For` header THEN they can be trusted.
Last required step is to filter out the `trusted_proxies` IP addresses from the `X-Forwarded-For` header in order to have the client's IP address that originally made the request.

**4. What about validating the content of the other `X-Forwarded` headers?**
When a user adds `trusted_proxies` IP adresses, I would say we can completely trust the headers and do not need to validate them, safe for the `X-Forwarded-For` header obviously.
The user **will** need to be made aware of the consequences of setting the `trusted_proxies` option.

**5. Why do this at all?**
Simply to support as much setups as possible and to keep Sentry at the top of the pile? That and with cloud based architecture and IAAS, you just cannot rely on _this should be solved in the reverse proxy setup_. If that was always the case, the `X-Forwarded` headers would have no reasons at all for existing.

**Comment by jbbr** [comment]
Any news on this? It's very common to have a load balancer in front of a web-application.
In this cases X-Forwarded-For CAN be trusted if set by the load balancer.

That's why usually an array of trusted proxy hosts can be configured, defaulting to none.
Trusting all hosts/wilcard should be supported too, as it's required in environments like Docker, where one usually don't know the ip address of the load balancer (Docker networking or firewall will prevent circumventing the load balancer)

https://github.com/fideloper/TrustedProxy for reference

**Comment by Jean85** [comment]
FYI the official Symfony integration already supports this, just by enabling the [`setTrustedProxies` method](https://symfony.com/doc/current/deployment/proxies.html).

**Comment by ste93cry** [comment]
Closing this issue as the packages that integrates the SDK with the most popular frameworks should already support this feature indirectly. About the plain SDK I feel that we should not support it out-of-the-box for a few reasons:

- This package is a library that just consumes data and should not be the place where you configure whether to trust or not the IPs
- Supporting this feature means that we should maintain all the logic to check whether a given IP is allowed according to the rules which is rather complex

**Comment by malc0mn** [comment]
@Jean85 fantastic, this eliminates the need for this entirely 😬
@ste93cry reason one is crystal clear and in that case this is obviously not functionality that You want in this library.
