### ISSUE TITLE
Discarded invalid parameter 'transaction' 

### ISSUE THREAD

**Issue by gjuric** [getsentry/sentry-php#643]
I've just upgraded my dependencies to the latest (2.x) version of the client and I started getting errors in my Sentry installation:

    Discarded invalid parameter 'transaction' 

I see that the this was changed in pull request #601 

I don't see `transaction` mentioned in the [documentation](https://docs.sentry.io/clientdev/attributes/).

On the server I am running Sentry 8.19.0 and client libraries are:

    sentry/sentry                  1.9.1
    sentry/sentry-symfony          2.0.3

Am I missing something or is this a bug?

**Comment by stayallive** [comment]
At some point this changed in the SDK protocol.

I believe the latest 8.x (8.22) should handle this parameter correctly. Sentry 9 and sentry.io does for sure. 

If you can't upgrade yet I would recommend to downgrade the library or ignore the message for now, although you are probably missing the transaction/culprit of the error.

**Comment by ste93cry** [comment]
Could it be that when we renamed the `transaction` attribute to `culprit` in the SDK we forgot to increase the protocol version to `7`? I think I’ve read somewhere the new name was available since that version of the protocol

**Comment by stayallive** [comment]
That is a very good question, I will check in with the team to verify.

**Comment by ste93cry** [comment]
I just checked again the docs and what I've seen about the protocol version was referring to the `fingerprint` attribute. The SDK reference still talks of the `culprit` attribute, so it's not even updated. At this point I'm not sure about what the problem is

**Comment by gjuric** [comment]
Should I open an issue on https://github.com/getsentry/sentry ?

@ste93cry I suppose that was a typo, but `culprit` was renamed to `transaction` not the other way around.

**Comment by stayallive** [comment]
No need. I am checking in with the team to see if we need to take a look at the protocol. However I think everybody is enjoying their weekend 🍻 will update here if I get some info back.

**Comment by ste93cry** [comment]
@stayallive Any news from the team?

**Comment by Jean85** [comment]
I'll ping them again.

**Comment by stayallive** [comment]
Yes, sorry about the late response @gjuric, this kind of watered to the background.

After a talk we unfortunately have to tell you to upgrade your Sentry server (to 8.22 which is confirmed not throwing these errors) or use an older version of the sentry-php dependency.

The documentation is scheduled to be updated in the coming week so the transaction will not be absent there.

**Comment by gjuric** [comment]
Thank you, I will probably be able to test this out tomorrow or next week.

**Comment by ste93cry** [comment]
@gjuric were you able to test if upgrading the server fixed the issue? @stayallive shouldn't this be handled at "protocol" level by incrementing its version?

**Comment by stayallive** [comment]
@ste93cry not sure, this was the reply I got from the people working on Sentry itself, I am not familiar enough with it to say anything useful about what the protocol version actually defines. 

I can only assume that if the protocol version defines the attributes it will only work backwards, the older server sees a new attribute it doesn't know and complains or it sees a newer protocol it does not know how to handle. Breaks either way.

**Comment by gjuric** [comment]
Unfortunately not yet, the upgrade has been postponed for next week.

**Comment by gjuric** [comment]
I can confirm that the errors are not being shown on the latest version of Sentry 9.0.0
