### ISSUE TITLE
[2.0] Update docs

### ISSUE THREAD

**Issue by Jean85** [getsentry/sentry-php#650]
After #637, we need to review the docs to update them to 2.0 with the new usage of the client.

**Comment by ste93cry** [comment]
#651 updates the documentation index

**Comment by LeoColomb** [comment]
Also don't forget to update [upgrade notes](https://github.com/getsentry/sentry-php/blob/6e1f60484e292549938686299ce0363111eac65d/UPGRADE-2.0.md), some changes made to reflect #670 (basically renames) are not reflected in these notes. 🙂

**Comment by ste93cry** [comment]
Documentation has been merged in getsentry/sentry-docs#609 while #738 updates the CHANGELOG and UPGRADE documents in this repository

**Comment by HazAT** [comment]
@LeoColomb We will write/release proper Changelog once we drop the `beta` tag.

**Comment by ste93cry** [comment]
Since this issue is pretty old and both docs and README/CHANGELOG/UPGRADE files have been updated I'm going to close it
