### ISSUE TITLE
How to exclude info and warnings requests

### ISSUE THREAD

**Issue by Br3eno** [getsentry/sentry-php#655]
Hello guys.

I implement sentry on a system that does not have the architecture to use the composer in the right way.
Implement by making include of sentry autoload.
It worked normally, but the system in question was very poorly programmed (totally structured) has no exception handling etc ...
I would like to know how to exclude requests for the sentry service that has an "info or warning" level.

Thanks for help.

**Comment by stayallive** [comment]
Hey @Br3eno,

You should be able to do the following:

```php
$raven = new Raven_Client('https://YOURDSN', array(
	'send_callback' => function ($data) {
		return !in_array($data['level'], array(
            Raven_Client::INFO, 
            Raven_Client::WARNING,
        ));
	},
));
$raven->install();
```

This works because the `send_callback` checks if `false` is the return value, if so it stops the event sending.

**Comment by Br3eno** [comment]
Thanks...
This work fine...
 I'll keep like this until you restructure the system the right way. Thank you very much.
Sentry is very util.
