### ISSUE TITLE
How can I manage multiple loggers/channels ?

### ISSUE THREAD

**Issue by smknstd** [getsentry/sentry-php#657]
Hi ! In my php app, I log errors in different logging channels (https://seldaek.github.io/monolog/doc/01-usage.html#leveraging-channels)

> Channels would allow you to identify the logger that issued every record. You can easily grep through the log files filtering this or that channel.

It seems really usefull to keep that information in sentry and being able to filter errors based on that criteria. What do you think, how you guyz do that ? Thanx

**Comment by ste93cry** [comment]
The `logger` property of the event object should be what you need. For example, in `1.x` you could call the `capture` method the way shown below and in Sentry you will see that the logger is what you set

```php
$client = new Raven_Client();
$client->capture(['logger' => 'monolog channel']);
```

**Comment by smknstd** [comment]
I missed that this information was already wired to a sentry tag, thanx !

https://github.com/Seldaek/monolog/blob/334b8d8783a1262c3b8311d6599889d82e9cc58c/src/Monolog/Handler/RavenHandler.php#L158
