### ISSUE TITLE
[2.0] Serializer::serializeCallable() fails

### ISSUE THREAD

**Issue by mindplay-dk** [getsentry/sentry-php#664]
The `Serializer` failed to serialize my callable - here's a stack-trace:

![image](https://user-images.githubusercontent.com/103348/46424209-c6ab2100-c738-11e8-9b12-2a7281abf82f.png)

It was trying to serialize an instance of this:

https://github.com/mindplay-dk/middleman/blob/master/src/Delegate.php

That's `ReflectionFunction::__construct()` being called at the bottom of the stack-trace, not sure why the class-name is left out here, but looks like a case that isn't handled? The class implements `__invoke()`, and you probably need to check for that explicitly - something like what I'm doing here:

https://github.com/mindplay-dk/readable/blob/master/src/readable.php#L161

Would you like a PR for this?

**Comment by Jean85** [comment]
PR is more than welcome! We started serializing callables in #620, so it wasn't tested so much....

**Comment by Jean85** [comment]
I should have fixed this in #701 (precisely with b851590)

**Comment by mindplay-dk** [comment]
@Jean85 looks good 👍
