### ISSUE TITLE
User agent -> browser translation

### ISSUE THREAD

**Issue by fruitl00p** [getsentry/sentry-php#689]
When using the PHP agent (1.9.2) we're reading the correct user agent from issues created, but the browser icon is always 'unknown' as if the useragent to browser translation stuff that we're used to from the JS client isn't properly handled?

Can i force / massage the data in some way to make it work? (i.e. by passing more parameters into the Raven_client somehow?)

Thanks!

**Comment by stayallive** [comment]
Check out: getsentry/sentry#8555

**Comment by fruitl00p** [comment]
@stayallive thanks! this is exactly the same issue and I would have expected the serverside of sentry to parse out the browser info based on the (already given) context...

**Comment by stayallive** [comment]
Yep, I'm trying to figure out with the server guys what the best course of action is, IMO the server should do this but it's not being done... so some work is required... to be continued 😄

**Comment by ste93cry** [comment]
Closing since this has been fixed in getsentry/sentry#10679
