### ISSUE TITLE
[2.0] Revisit `init` parameters

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-php#695]
Right now init looks like this

```php
function init(array $options = [], ?ClientBuilder $clientBuilder = null): void
```

as mentioned https://github.com/getsentry/sentry-php/pull/682#discussion_r233652663
this is a bit confusing.

**Comment by ste93cry** [comment]
>One possible good solution that I see here would be reducing the scope of the ClientBuilder to a simpler TransportFactory, because that is the only proper dependency that needs to be handled outside of simple options.

As you said the serializer is another dependency that should not be handled as an option, so we still have the need of having a builder if we want to provide users with something they can quickly use to build up a client instance

**Comment by Jean85** [comment]
I've put the serializer as an other dep of the client and as a property of the builder in #701
