### ISSUE TITLE
better ignoring / of errors

### ISSUE THREAD

**Issue by fruitl00p** [getsentry/sentry-php#696]
In relation to #606 i'd like to see some way of ignoring any type of error or exception ... 

Currently some errors are ignoreable via the shouldCaptureFatalError() function. But shouldn't the `handleError` and `handleException` have the same option to exclude some error / exception? 

By way of i.e. 'shouldCaptureError' and 'shouldCaptureException' (and maybe keep the 
 'shouldCaptureFatalError' for consistency sake?

The code change seems fairly simple, but before i hack in a PR, i'd like to question why the original issue #606 and subsequent PR #583 deliberately didn't go for a wider solution to allowing ignoring every type of exception / error... ?

**Comment by Jean85** [comment]
As of now, we have the 2.0 branch under development, where a single `before_send` callback would be used as a stopgap for any kind of event ready to be sent to Sentry. Would this solve your need?

**Comment by ste93cry** [comment]
>deliberately didn't go for a wider solution to allowing ignoring every type of exception / error... ?

I may be missing something but, at least in `2.0`, the `excluded_options` uses `instanceof` which means that you can catch all types of errors or exceptions by configuring it using the base classes `\Exception` or `\Throwable`

**Comment by fruitl00p** [comment]
@Jean85  @ste93cry I am currently using a 1.x version of the client as the 2+ isn't (officially) released yet... 

If the before_send callback is there this would 'fix' my issue comepletely! Excellent... 
As for the excluded_exceptions, this wouldn't catch non exception errors thus the before_send seems like the only proper way to solve this issue :)

Thanks!

Any timeline available for 2.x?

**Comment by ste93cry** [comment]
>I am currently using a 1.x version of the client as the 2+ isn't (officially) released yet...

Sorry, I know less the `1.x` version but AFAIK the behavior of the `excluded_exceptions` was ported there from the `2.0` version so they should work the same

>As for the excluded_exceptions, this wouldn't catch non exception errors

Since PHP 7 some errors can be catched because they are thrown as exceptions

>Any timeline available for 2.x?

I think that it should be ready for the end of the year, maybe before. You should ask @HazAT that knows the timeline better than me

**Comment by HazAT** [comment]
Yeah, plan for `2.x` is to ship before EOY.

**Comment by ste93cry** [comment]
@fruitl00p I just saw that `1.x` has a `send_callback` option that you can use to do whatever you need before an event is sent including not sending it at all if you return `false` from it. I think that that with the combination of `excluded_exceptions` should be enough, can you check and let us know if it helps you fix your issue?

https://github.com/getsentry/sentry-php/blob/7b7e88d93027c4f149c3cb5e929b3b9f8427e01c/lib/Raven/Client.php#L1035-L1040

**Comment by ste93cry** [comment]
@fruitl00p I just saw that `1.x` has a `send_callback` option that you can use to do whatever you need before an event is sent including not sending it at all if you return `false` from it. I think that that with the combination of `excluded_exceptions` should be enough, can you check and let us know if it helps you fix your issue?

https://github.com/getsentry/sentry-php/blob/7b7e88d93027c4f149c3cb5e929b3b9f8427e01c/lib/Raven/Client.php#L1035-L1040

**Comment by fruitl00p** [comment]
@ste93cry Excellent! This works like a charm and gives me full control over exactly what is eventually sent *and* if it's actually sent at all!

Great!
