### ISSUE TITLE
Breadcrumbs Errorhandler always calls existing Errorhandler

### ISSUE THREAD

**Issue by christophlehmann** [getsentry/sentry-php#722]
In https://github.com/getsentry/sentry-php/blob/master/lib/Raven/Breadcrumbs/ErrorHandler.php#L33 we do not check if we should call the existing error handler

```
        if ($this->existingHandler !== null) {
            return call_user_func($this->existingHandler, $code, $message, $file, $line, $context);
        } else {
            return false;
        }
```

and in https://github.com/getsentry/sentry-php/blob/master/lib/Raven/ErrorHandler.php#L119 we check it

```
        if ($this->call_existing_error_handler) {
            if ($this->old_error_handler !== null) {
                return call_user_func(
                    $this->old_error_handler,
                    $type,
                    $message,
                    $file,
                    $line,
                    $context
                );
            } else {
                return false;
            }
        }
```

Is it correct or should we uniform it?

**Comment by ste93cry** [comment]
I'm not sure about it but the only reason I see that could explain why it's the way it is apart from the option of missing code is that the breadcrumb handler should be as transparent as possible and never "break" the chain of error handlers

**Comment by christophlehmann** [comment]
The point is, given i register an error handler with 

`set_error_handler([$this, 'handleError'], E_ERROR);`

the error handler wants to handle E_ERROR only, but `Raven_Breadcrumbs_ErrorHandler` forwards E_ALL. 

Due to https://bugs.php.net/bug.php?id=54033) it seems not possible to get the error level of an earlier error handler, but what we can do is to add an option for it and check it like
```
if ($earlierErrorLevel & $code) {
    // Call earlier error handler
} 
```

**Comment by ste93cry** [comment]
Closing this as it's really old and no further development except for bug fixes is expected for version `1.x`.
