### ISSUE TITLE
Including commits in a release?

### ISSUE THREAD

**Issue by fruitl00p** [getsentry/sentry-php#725]
We've been integrating the sentry-cli into our deployments and trying to register our releases and commits.

But this doesn't seem to work? In our deployment we use the sentry_cli docker image as per the documentation:
```shell
VERSION="get the git hash"
echo "Create a new release (${VERSION}) in sentry";
# Create a release
${SENTRY_CLI} releases new -p ${APPLICATION_NAME} ${VERSION}
echo "Associating commits with the release (${VERSION})";
# Associate commits with the release
${SENTRY_CLI} releases set-commits --auto ${VERSION}
```
This outputs the following:
```shell
Create a new release (406f9f1) in sentry
Created release 406f9f1.
Associating commits with the release (406f9f1)
+----------------+--------------+
| Repository     | Revision     |
+----------------+--------------+
| [the name of our repo] | ccc905d1448c |
+----------------+--------------+
```

But if we check the releases for the project in https://sentry.io/[org/project]/releases/ we can see releases as they are used in the issue reporting, but for all releases the actual commits are empty ? 

I'm probably doing it wrong... ? but where?

**Comment by ste93cry** [comment]
I believe that this is not the right repository to talk about this problem as it's related to the `sentry-cli` package and not the PHP SDK. Please open the issue in [getsentry/sentry-cli](https://github.com/getsentry/sentry-cli) or in [getsentry/sentry](https://github.com/getsentry/sentry)

**Comment by fruitl00p** [comment]
@ste93cry Thanks. I thought it might have been related to the presentation in sentry.io since it's a PHP project... :smile: I'll re-ask in the CLI repo.

**Comment by alubina** [comment]
For the sake of privacy I masked repository name with `organization/application` and
 have similar issue. I associate commits 'by hand' with
`sentry-cli releases set-commits --commit "oragnization/project@3.135.0..3.136.0" 3.136.0 --log-level=DEBUG`
The output looks as follows:
`
| organization/application | f5028540c840 -> 91d80fcc9935 |
` 
Commit hashes are real, but the commits list remains empty. Any hints?

**Comment by stayallive** [comment]
@alubina I don't think we as the PHP SDK maintainers can help you with this, sentry-cli and the commit integration inside Sentry is not powered by this SDK and is totally separated.

You can check out if getsentry/sentry-cli#445 relates to your issue possibly and/or open up a [support ticket](https://sentry.io/support) if you are on sentry.io so that someone can check with you if your git integration is running and/or what might be happening.
