### ISSUE TITLE
mb_substr() should be used on strings, if available (2.0 and master branches)

### ISSUE THREAD

**Issue by mfb** [getsentry/sentry-php#727]
There are places in the 2.0 and master branches where strings are truncated using substr(), which results in invalid UTF-8 if a multibyte character is truncated.  Strings should be truncated by mb_substr() if the function is available.

See e.g.

```php
if (isset($data['message'])) {
  $data['message'] = substr($data['message'], 0, $this->message_limit);
}
```

```php
$event->setMessage(substr($message, 0, Client::MESSAGE_MAX_LENGTH_LIMIT), $messageParams);
```

**Comment by mfb** [comment]
It looks like 2.0 branch requires mbstring so we don't need conditional logic there?  Except, there is some already - `if (function_exists('mb_detect_encoding')`

**Comment by ste93cry** [comment]
Since we're requiring `mbstring` any conditional that exists can be removed safely, so green light for cleaning up the code

**Comment by mfb** [comment]
On the 2.0 branch it looks like there is a hardcoded message limit?  I don't think that's a good idea, based on my experience with apps that dump huge SQL query strings (along with other useless stuff) into the message, which was needed to debug the bad SQL. This required me to set message limit to as much as 8192 characters, which Sentry server is perfectly happy to accept.

**Comment by Jean85** [comment]
> On the 2.0 branch it looks like there is a hardcoded message limit? I don't think that's a good idea [...]

@HazAT what do you think about this? Should we make the message limit customizable?
