### ISSUE TITLE
context_lines setting is never used

### ISSUE THREAD

**Issue by mattzuba** [getsentry/sentry-php#740]
I was attempting to limit the lines of context by setting `context_lines => 1`, but it looks like it's hard coded for 5 lines of pre and post context: https://github.com/getsentry/sentry-php/blob/master/src/Stacktrace.php#L134

**Comment by ste93cry** [comment]
Good catch, I don't know if I would classify it as a bug but it's indeed not meant to be hardcoded like that. The constant should probably be removed or used as default value for the option itself while the code should use the option, obviously. Would you mind opening a PR to fix it?
