### ISSUE TITLE
Disable http plug discovery when using custom transport

### ISSUE THREAD

**Issue by CharlotteDunois** [getsentry/sentry-php#741]
I'm using this SDK (the 2.0 beta version) inside an asynchronous ReactPHP application, but due to the broken http-plug reactphp client I've made my own sentry transport which uses the already available HTTP client inside my application. But due to the way how the client is built inside the client builder, even when I set a custom transport, the client builder tries to find a http plug HTTP client using the http plug discovery mechanism.

As such I have to set a custom strategy to mitigate this.
```php
$class = \get_class((new class() {
    static function getCandidates() {
        return array(array('class' => function () {}));
    }
}));

\Http\Discovery\ClassDiscovery::setStrategies(array($class));
```

Would you be interested in a simple patch to not do the discovery if a transport is set? From what I've seen the HTTP client is only used when building a transport. So the patch would be to simply check whether a transport is set or not.

https://github.com/getsentry/sentry-php/blob/5ec1fbec3ff7c32dda49f234a2d5db5759393676/src/ClientBuilder.php#L260-L268

The simple patch would be to change
https://github.com/getsentry/sentry-php/blob/5ec1fbec3ff7c32dda49f234a2d5db5759393676/src/ClientBuilder.php#L264-L265
to
```php
if($this->transport === null) {
    $this->httpClient = $this->httpClient ?? HttpAsyncClientDiscovery::find();
    $this->transport = $this->createTransportInstance();
}
```

Of course you're welcome to do the simple change yourself. :)

**Comment by ste93cry** [comment]
I could be missing something, but looking at the source code if you want to use a custom HTTP client you can just set it using the `ClientBuilder::setHttpClient()` method. Whichever instance set will be used by the configured transport so it should work

```php
$httpClient = new CustomHttpClient();

$clientBuilder = ClientBuilder::create(['dsn' => '__PUBLIC_DSN__']);
$clientBuilder->setHttpClient($httpClient);

// $client will use the default transport HttpTransport with the configured CustomHttpClient client
$client = $clientBuilder->getClient();
```

**Comment by CharlotteDunois** [comment]
I'm not using http plug at all. It's a completely custom HTTP client with _no_ integration of http plug.

**Comment by ste93cry** [comment]
I still don't get how it's using the HttpClient from HTTPlug. If you set the transport yourself no call will be made to either the `ClientBuilder::createHttpClientInstance()` or `ClientBuilder::createTransportInstance` methods, so even though the PSR-7 factories and the HTTP client are discovered by the `*Discovery` classes they won't be used at all

**Comment by CharlotteDunois** [comment]
The issue is that there is no HttpClient from HTTPlug and thus an exception is thrown by `HttpAsyncClientDiscovery::find()`.

By making the proposed changes, we don't make any unnecessary discoveries when they are not used at all.

**Comment by ste93cry** [comment]
Got it now, I misunderstood your first message sorry. I see the problem now and agree with you we should not autodiscover anything if a custom transport is set, but probably I would think about if it really makes sense to expose the `ClientBuilder::setHttpClient()` method instead of just the ones related to the PSR-7 factories and the transport itself. This way cases like the one you described will not happen and if someone wants to customize the HTTP client then they have to set the transport themselves too. Does it makes sense?

**Comment by CharlotteDunois** [comment]
That does make sense. I'd also say that these three lines could be moved into `createTransportInstance()`
https://github.com/getsentry/sentry-php/blob/master/src/ClientBuilder.php#L262-L264

Since they're related to the used transport and a custom transport won't use them in any way.
