### ISSUE TITLE
Support named parameters for event messages

### ISSUE THREAD

**Issue by mfb** [getsentry/sentry-php#750]
In version 1.x, we can send messages with named parameters to Sentry server, e.g.
```
$message = 'Hello %planet.';
$params = ['%planet' => 'world'];
$data['sentry.interfaces.Message'] = [
  'message' => $message,
  'params' => $params,
  'formatted' => strtr($message, $params),
];
```
I'm not sure how to do this for events in 2.x - it looks like it forcibly sets `formatted` to `vsprintf($this->message, $this->messageParams)`.

**Comment by ste93cry** [comment]
I don't see any reference in the [docs](https://docs.sentry.io/development/sdk-dev/interfaces/message/) for named parameters and looking at version `1.x` `vsprintf` was used too, the only way to do what you described was to manually edit the payload of the event so I think we should not support this use case if it's not an official feature

**Comment by mfb** [comment]
Yes we are using `sentry.interfaces.Message`, which does support `params` being a dictionary, and they are rendered nicely in the Sentry UI.  All we need is a way to pass in the formatted message, rather than always forcibly generating it.
