### ISSUE TITLE
Stacktrace and FatalErrorException problem

### ISSUE THREAD

**Issue by sztyup** [getsentry/sentry-php#761]
Symfony and Laravel, and probably many other framework uses a Symfony\Component\Debug\Exception\FatalErrorException in its own Fatal error handling process before passing it to Sentry.
The problem is it doesn't return the stacktrace  in a standard debug_backtrace format, but replaces the arguments array indexes to the name of the variable if using xdebug.
`
[args] => Array
(
[0] => true
)
`
becomes
`
[args] => Array
(
[variableName] => true
)
`
This causes Sentry\StackTrace::getFrameArgumentsValues function to emit a Warning: A non-numeric value encountered while processing the above Exception. This whole thing makes debugging much more difficult.
If you think this is not edge case enough to warrant a fix, i would be happy to start working on a PR.

**Comment by ste93cry** [comment]
Fixed in #763
