### ISSUE TITLE
Invalid Argument Exception when Installing 2.0.0-beta2 via Composer

### ISSUE THREAD

**Issue by warely** [getsentry/sentry-php#773]
I'm unable to install Sentry for PHP via composer using the command:
`composer require sentry/sentry:2.0.0-beta2`

I get the following message:

`[InvalidArgumentException]                                                                                      
  Package sentry/sentry at version 2.0.0-beta2 has a PHP requirement incompatible with your PHP version (7.0.33)`

**Comment by ste93cry** [comment]
As the message clearly says, we support only PHP versions greater than or equal to PHP 7.1

**Comment by ste93cry** [comment]
Closing this since the question got answered
