### ISSUE TITLE
Raven won't catch fatal errors.

### ISSUE THREAD

**Issue by SteveEdson** [getsentry/sentry-php#78]
I see theres code for `handleFatalError()`, is raven-php able to automatically catch fatal errors? I've registered the error handlers using:

```
// Install error handlers
$error_handler = new Raven_ErrorHandler($client);
$error_handler->registerExceptionHandler();
$error_handler->registerErrorHandler();
```

Fatal errors still show up in my PHP error log, but nothing shows up in Sentry. (Warnings and notices work).

Is this a problem with my PHP.ini / config, or is it simply not supported?

Thanks.

**Comment by stayallive** [comment]
Catching parse errors is not possible in PHP except if they occur in an included script, and sentry-php does catch & report those correctly.
