### ISSUE TITLE
Silence or remove pretty-package-versions dependency?

### ISSUE THREAD

**Issue by dwightwatson** [getsentry/sentry-php#782]
After upgrading to version `2.0` (from using `sentry-laravel` under the hood) I'm now seeing this additional output every time I run a composer update command.

```
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
```

It appears this is triggered by this library pulling in `jean85/pretty-package-versions` - and I wonder if that package is required, or if there is a way to silence it from creating output for end-users of this library. I don't know if making it a dev dependency might resolve the situation.

**Comment by Jean85** [comment]
That package is used to report SDK and dependencies versions in the event. Can I ask what's the issue with that output? It logs the fact that it's writing in the vendor folder, and it's useful to show if something goes wrong (like wrong permissions on that dir).

**Comment by dwightwatson** [comment]
It's not the sort of thing I'd expect the Sentry package to add to my app. All of a sudden I start seeing additional output from Composer from a package I haven't explicitly installed, and it looks suspicious/concerning. Generally I don't think a package should be cluttering console output for the end-user.

**Comment by Jean85** [comment]
I can assure you that that package is more than secure. It's written by one of Doctrine's maintainers, it has surpassed [14 million installs](https://packagist.org/packages/ocramius/package-versions/stats), and the fact that it manifest itself speaks to its transparency.

**Comment by dwightwatson** [comment]
I didn't say the package wasn't secure, but that suddenly getting output in your console from another package you're not familiar with *looks suspicious*. It required me to look up my `composer.lock` file to find out where that package had come from and work my way back up to find it was Sentry.

**Comment by Jean85** [comment]
I would suggest you to you to use `composer why vendor/package` to do this kind of investigation in the future. In our case, if I run that from the Symfony integration:
```
$ composer why jean85/pretty-package-versions
phpstan/phpstan        0.11.2      requires  jean85/pretty-package-versions (^1.0.3)  
sentry/sentry          2.0.0       requires  jean85/pretty-package-versions (^1.2)    
sentry/sentry-symfony  dev-master  requires  jean85/pretty-package-versions (^1.0)    
```
If you use the `-t` option, it even shows you the result with a tree format, with eventual intermediate dependencies.

I'm closing this as solved, feel free to reply further.

**Comment by dwightwatson** [comment]
`why` is a neat tip, thanks for that.

Still seems like an odd addition to me but clearly that view isn't shared so I'll leave it as is.

Regardless, thank you for your work on this package and congratulations on hitting 1.0 🔥

**Comment by dreammonkey** [comment]
Just got this in my ci/cd pipeline and clueless...

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for jean85/pretty-package-versions 2.0.2 -> satisfiable by jean85/pretty-package-versions[2.0.2].
    - jean85/pretty-package-versions 2.0.2 requires composer-runtime-api ^2.0.0 -> no matching package found.
  Problem 2
    - jean85/pretty-package-versions 2.0.2 requires composer-runtime-api ^2.0.0 -> no matching package found.
    - sentry/sentry 3.1.4 requires jean85/pretty-package-versions ^1.5|^2.0.1 -> satisfiable by jean85/pretty-package-versions[2.0.2].
    - Installation request for sentry/sentry 3.1.4 -> satisfiable by sentry/sentry[3.1.4].
```

**Comment by ste93cry** [comment]
@dreammonkey please open a new issue if you feel you need help or support, don't comment on a PR that is 2 years old and that has nothing to do with your question 😉

**Comment by dreammonkey** [comment]
you're right

**Comment by e-stankevicius** [comment]
I agree with @ste93cry , you should not comment on PR that is 2 years old.
