### ISSUE TITLE
Checking for "@" in handleError on the 2.0 release

### ISSUE THREAD

**Issue by Jasonoro** [getsentry/sentry-php#784]
This issue is _very_ similar to #332. Currently Sentry automatically logs any error that’s suppressed by the “@” operator in PHP. There is however no easy way to disable this. You could do it by creating your own ErrorHandler with associated Integration but that’s a lot of work and a bunch of duplicate code due to those classes being final. Is there a way we can get a config option (or maybe this to be the default) so our Sentry issues don’t get spammed with a bunch of ignored 'errors'?

**Comment by stayallive** [comment]
Hey @Jasonoro, we are already working on bringing it back how it was and make it opt-in via a configuration option.

**Comment by ste93cry** [comment]
This has been resolved in `2.0.1`, please give it a try and feel free to reopen this issue if something is still wrong
