### ISSUE TITLE
HttpTransport example does not work

### ISSUE THREAD

**Issue by cosminardeleanu** [getsentry/sentry-php#787]
Your example from https://docs.sentry.io/platforms/php/#httptransport does not work, or is incomplete.

Used version 2.0.1.

Please add a working version and/or fix the code.

Context: I am trying to send messages, via queues, so i store the `Event` and dispatch it later, by using the HttpTransport.

```php
use Http\Discovery\HttpAsyncClientDiscovery;
use Http\Discovery\MessageFactoryDiscovery;
use Sentry\ClientBuilder;
use Sentry\Transport\HttpTransport;

$options = ['dsn' => '...'];
$builder = ClientBuilder::create($options);
$options = $builder->getOptions();

$transport = new HttpTransport($options, HttpAsyncClientDiscovery::find(), MessageFactoryDiscovery::find());
$builder->setTransport($transport);
$client = $builder->getClient();

echo $client->captureMessage('test message'); // Does not work.

$event = ... // Gathered from queue, serialized object.
$transport->send($event); // Also does not work.
```

This example does not work.
Looking deep in the sentry code, i have seen that the http transport model, is being filled with various plugins, that actually makes the guzzle6 adapter to work: 

`new BaseUriPlugin($uriFactory->createUri($options->getDsn()))` and `new AuthenticationPlugin(new SentryAuthentication($options, $sdkIdentifier, $sdkVersion));`.

The only working around was to use the `PluginClient` and copy/paste the logic from `ClientBuilder`, `private function createHttpClientInstance(): PluginClient`.

**Comment by Jean85** [comment]
As a workaround, you could use the Hub with no default integrations, and send the events from there. IT should result in a smaller code example that works.

**Comment by javascriptlove** [comment]
Can't get it to work also, the example is broken and/or incomplete. Seems like we still have to use the old Raven

**Comment by Jean85** [comment]
This issue could be related to the issues we're facing with async transport...

**Comment by ste93cry** [comment]
I don't think so, I believe that as written by @cosminardeleanu when you set your transport then you lose all the automation done to set the plugins to the HTTP client needed to authenticate with the server. It's a pity and we can think about fixing it, but for now it's this way

**Comment by B-Galati** [comment]
Just had the same issue, IMHO the spool transport is not usable right now from a DX perspective.

**Comment by B-Galati** [comment]
My workaround for now is to use reflection: 

```
$reflection = new \ReflectionClass(ClientBuilder::class);
$method = $reflection->getMethod('createTransportInstance');
$method->setAccessible(true);
$httpTransport = $method->invoke($clientBuilder);
```

**Comment by RageZBla** [comment]
@Jean85 would it acceptable to add a `createHttpClientWithPlugin` method to the `ClientBuilder`. That way the users could get their client wrapped without copy pasting the logic.

**Comment by Jean85** [comment]
I'm not sure on how we should go with that but yes, we were already discussing something like that with @ste93cry. A PR is more than welcome, so we can discuss it over the code.

**Comment by RageZBla** [comment]
@ste93cry @Jean85 if someone can review #855 and getsentry/sentry-docs#1122 :bowing_man:

**Comment by ste93cry** [comment]
Closing as the official documentation has been fixed
