### ISSUE TITLE
How to config error level to send in v2?

### ISSUE THREAD

**Issue by vincent-lu** [getsentry/sentry-php#793]
Previously I was using Sentry 1.* and notice level errors weren't reported to sentry. But just recently upgraded to 2.0.1 I'm getting a lot of notice level errors.

The code I'm using is:
```
\Sentry\init([
    'environment' => 'production',
    'dsn' => 'MY_DSN',
]);
```

Anyone know if/how I can suppress notice level errors?

**Comment by Jean85** [comment]
You have to use the `error_types` options, that accepts a bitemask, in the same way that the native `error_reporting` PHP function does.

In your care, you'll want to use `E_ALL & ~E_NOTICE`. Thanks for reporting this, it seems that the option is not documented very well.

**Comment by vincent-lu** [comment]
Thanks for the quick reply.

Can you please confirm this is what I should use?
```
\Sentry\init([
    'environment' => 'production',
    'dsn' => 'MY_DSN',
    'error_types' => E_ALL & ~E_NOTICE,
]);
```

**Comment by Jean85** [comment]
Yes, that's correct.

**Comment by vincent-lu** [comment]
Thanks @Jean85 appreciate your help. Confirmed working.

Strange in `UPGRADE-2.0.md` it says:

> The `error_types` option has been removed.

**Comment by ste93cry** [comment]
>Strange in UPGRADE-2.0.md it says:
>
>    The error_types option has been removed.

Thanks for spotting this, the option was probably removed during the development and then re-added later. We will update the document asap
