### ISSUE TITLE
Unexpected exception when instantiating class.

### ISSUE THREAD

**Issue by santoshkumar-io** [getsentry/sentry-php#795]
I am trying to integrate the sentry in my existing **Laravel 5.5** nad **PHP v 7.2** application.
Steps I followed-

`composer require sentry/sentry php-http/curl-client guzzlehttp/psr7`

Added following in "boot" method of  AppServiceProvider.php
`\Sentry\init(['dsn' => config('sentry.dsn') ]);`

Following is my composer.json

```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.0.0",
        "artisaninweb/laravel-soap": "0.2.*",
        "consoletvs/identify": "^1.3",
        "cyber-duck/laravel-excel": "^1.2",
        "fideloper/proxy": "~3.3",
        "geoip2/geoip2": "^2.7",
        "guzzlehttp/psr7": "^1.5",
        "laravel/framework": "5.5.*",
        "laravel/passport": "4.0.3",
        "laravel/tinker": "~1.0",
        "opentok/opentok": "2.3.x",
        "paragonie/random_compat": "2.*",
        "pbmedia/laravel-ffmpeg": "^1.3",
        "php-http/curl-client": "^2.0",
        "predis/predis": "^1.1",
        "sentry/sentry": "^2.0",
        "symfony/polyfill-iconv": "^1.6",
        "torann/geoip": "^1.0",
        "yajra/laravel-datatables-oracle": "^8.3"
    },
    "require-dev": {
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "laravel/dusk": "^2.0",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~6.0",
        "staudenmeir/dusk-updater": "^1.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}

```

Here is the error I am getting
Unexpected exception when instantiating class.

> Previous exceptions
> No PSR-17 response factory found. Install a package from this list: https://packagist.org/providers/psr/http-factory-implementation (0)
> Could not find resource using any discovery strategy. Find more information at http://docs.php-http.org/en/latest/discovery.html#common-errors - Puli Factory is not available - No valid candidate found using strategy "Http\Discovery\Strategy\CommonClassesStrategy". We tested the following candidates: . - No valid candidate found using strategy "Http\Discovery\Strategy\CommonPsr17ClassesStrategy". We tested the following candidates: Nyholm\Psr7\Factory\Psr17Factory, Zend\Diactoros\ResponseFactory, Http\Factory\Diactoros\ResponseFactory, Http\Factory\Guzzle\ResponseFactory, Http\Factory\Slim\ResponseFactory. (0)

Any quick solution is highly appreciated.
Looking forward to hear from you.
Thanks.

**Comment by ste93cry** [comment]
Please look at the last comments in getsentry/sentry-laravel#214, they should help you solve your issue. Also since you're using Laravel I suggest you to use the official integration `sentry-laravel` instead of setting up manually the SDK

**Comment by ste93cry** [comment]
I'm going to close this issue as it seems that is has been resolved or there is no need for help anymore. In case I'm wrong feel free to reopen it!
