### ISSUE TITLE
REQ: option to turn off Puli in http-php/discovery

### ISSUE THREAD

**Issue by shawnheide** [getsentry/sentry-php#801]
I noticed that after installing sentry that I started getting multiple exceptions on every request related to the http-php/discovery checking for multiple classes to use. After looking into the issue it seems that they check for a plugin (puli/composer-plugin) that is no longer maintained and just allow the exceptions to be thrown before checking for other classes that are installed.

In one of the [issues on their package](https://github.com/php-http/discovery/issues/117), they mentioned just using the static function [`setStrategies`](https://github.com/php-http/discovery/blob/master/src/ClassDiscovery.php#L117) to remove the class related to Puli. Would it be possible to add an option to remove Puli from the strategies that http-php/discovery uses?

Something like the following worked in my testing, but I'm not sure familiar enough with sentry-php yet so I just thought I'd check before writing a PR. Any thoughts? Thanks.
```php
$strategies = [
    \Http\Discovery\Strategy\PuliBetaStrategy::class,
    \Http\Discovery\Strategy\CommonClassesStrategy::class,
    \Http\Discovery\Strategy\CommonPsr17ClassesStrategy::class,
];
if ($options['disable_puli']) {
    $strategies = array_slice($strategies, 1);
}
\Http\Discovery\ClassDiscovery::setStrategies($strategies);
```

**Comment by ste93cry** [comment]
First of all I would like to apologize for not replying before. Let me say that adding such option is not something I'm willing to do simply because in my opinion as a library we should not have options to change the behavior of a third party vendor. Calling the `ClassDiscovery::setStrategies` method in your own code is enough to fix the issue.

>I noticed that after installing sentry that I started getting multiple exceptions on every request related to the http-php/discovery checking for multiple classes to use.

I'm unable to reproduce the issue locally. The exception is thrown and catched and only if the `ClassDiscovery` class cannot find any suitable implementation of what it's looking for the exception is rethrown. Are you sure you have the minimum set of required packages for the SDK to work installed? Have you tried instead requiring in your `composer.json` `sentry/sdk` if you don't want to bother chosing such dependencies?

**Comment by shawnheide** [comment]
No worries, thanks for getting back to me. Sorry I should have clarified earlier that I am actually using sentry-laravel. Due to how the configuration from sentry-laravel is passed down to sentry-php, I couldn't find a way to do this within sentry-laravel and since the package is bootstrapped at the beginning of the app creation I can't use the `setStrategies` method myself.

I also can't install the required dependency, puli/composer-plugin, since it is no longer supported and is incompatible with the current version of symfony/process. I'm happy to just fork sentry-laravel and make it work, but I thought I'd see if you had a better suggestion. Thanks again for your time and help.

**Comment by ste93cry** [comment]
Mmm, since the method is static and is not part of a service you should be able to call it before the bootstrap of the application in some places. I don't Laravel, but @stayallive should be able to help you

**Comment by ste93cry** [comment]
Mmm, since the method is static and is not part of a service you should be able to call it before the bootstrap of the application in some place. I don't know Laravel, but @stayallive should be able to help you

**Comment by stayallive** [comment]
@shawnheide you should be able to call the `setStrategies` from the register method of any service provider. We should only load Sentry and thus do the class discovery in the `boot` period of the service providers (`register` is first).

So if you do the `setStrategies` call in the register method of for example your `AppServiceProvider` you should be good 👍 

If not it would be helpful to get you composer.json so I can try to reproduce and see how we should get around it, but I think the above should work out.

**Comment by shawnheide** [comment]
@stayallive I thought I had tried that, but I guess not because it definitely works. Thanks for all the help.

**Comment by stayallive** [comment]
@shawnheide great to hear! No problem at all, thanks for letting us know it works 👍
