### ISSUE TITLE
Request body not sent with 2.0

### ISSUE THREAD

**Issue by nesl247** [getsentry/sentry-php#803]
In 1.x, the request body was sent. From what I can see, it was sent in the `data` field of the `request` field. In 2.0, the `RequestIntegration` does not handle this at all, and there is no other location that I can see that even modifies the `request` field.

**Comment by ste93cry** [comment]
This feature is not available out-of-the-box because the [SDK specs](https://docs.sentry.io/development/sdk-dev/interfaces/http/) says that it should not be sent by default since it can contain very large data and it makes sense. You can however make your own integration that will get the data and append it to the event

**Comment by nesl247** [comment]
Was this in the upgrade guide in some way? I did not see it. Also, would it not make more sense to offer this as an option that is defaulted to false rather than to require every project to implement code to have the same functionality as version 1?

**Comment by ste93cry** [comment]
>Was this in the upgrade guide in some way

I'm sorry for this, I've checked and we missed to document it. The good news is that we are going to implement the feature, but it will be disabled by default and it will work differently from before. To have a preview you can take a look at how the [`request_bodies`](https://docs.sentry.io/error-reporting/configuration/?platform=python#request-bodies) option in the Python SDK works

**Comment by nesl247** [comment]
That's exactly what I'm looking for. Do you have an idea when this will be implemented? We're starting to rollout Sentry to all of our micro-services, and I'd love to have this already rather than doing this custom for now.

**Comment by ste93cry** [comment]
I cannot provide an ETA because we don't know when we will release the next version due to other changes that we would like to do for that release too, but I can definitely say that this feature will be in `2.1`

**Comment by Jean85** [comment]
@nesl247 feel free to submit a PR following the Python behavior if you want, it would be greatly appreciated. That way you'll be able to use your fork in the meantime, and be sure to have the same code in 2.1.

**Comment by ste93cry** [comment]
Note: I'm already working on implementing such feature, be aware of this so that we don't do the work twice :wink:

**Comment by nesl247** [comment]
I'll just wait on 2.1.

**Comment by ste93cry** [comment]
Closing this since this has been fixed with the related PR
