### ISSUE TITLE
SENTRY_RELEASE and SENTRY_ENVIRONMENT

### ISSUE THREAD

**Issue by nesl247** [getsentry/sentry-php#804]
It looks like these two (`SENTRY_RELEASE` and `SENTRY_ENVIRONMENT`) are missing support in at least v2. I haven't checked v1.

See https://docs.sentry.io/error-reporting/configuration/?platform=php#release

I see support for it in `sentry-python` but not here.

**Comment by ste93cry** [comment]
I suppose that this should be supported across all SDKs. Would you mind opening a PR to fix the issue? The change should be pretty easy and require to just edit the defaults in the `Options` class
