### ISSUE TITLE
Default Type of Event::$exceptions must be an array

### ISSUE THREAD

**Issue by tonybolzan** [getsentry/sentry-php#805]
In Envent class, the default value for `private $exceptions;` is implicit `null`
https://github.com/getsentry/sentry-php/blob/master/src/Event.php#L127
But `public function getExceptions(): array` return only array
https://github.com/getsentry/sentry-php/blob/master/src/Event.php#L538

This cause a failure if I call `getExceptions` inside callback `before_send`  and don't have exceptions, for example, calling `captureMessage()`

**Comment by ste93cry** [comment]
Thanks for spotting this! Would you mind opening a PR to fix the issue?
