### ISSUE TITLE
Event without exceptions and an empty message

### ISSUE THREAD

**Issue by notFloran** [getsentry/sentry-php#820]
Hi, I use the last version of [sentry-symfony](https://github.com/getsentry/sentry-symfony) integration and I have issues with the `excluded_exceptions` option.

If an exception that match `excluded_exceptions` is throw then an `<unlabeled event>` event is created in Sentry:

![Capture d’écran 2019-05-22 à 07 29 43](https://user-images.githubusercontent.com/523981/58149480-6b945300-7c63-11e9-9171-7d753b671156.png)

Is seems the problem came from this: https://github.com/getsentry/sentry-php/blob/master/src/EventFactory.php#L148 -> the event has no message and no exception as the exception are ignored.

**Comment by DanielSchwiperich** [comment]
Experiencing the same Problem with sentry-symfony *3.0.0*
We've excluded HttpNotFoundExceptions bug get now unlabeled events

**Comment by Jean85** [comment]
#822 has been merged. Please test it, it should fix your issue.

**Comment by JanMikes** [comment]
Hi, i run into same issue (fixed in master), looking forward to this gets tagged  😉
