### ISSUE TITLE
Monolog handler fails when the extra data has numeric array keys

### ISSUE THREAD

**Issue by pontus-mp** [getsentry/sentry-php#833]
If $key is an integer in the following line, the function call will fail with `Uncaught TypeError: Argument 1 passed to Sentry\State\Scope::setExtra() must be of the type string, integer given`.

https://github.com/getsentry/sentry-php/blob/50f58938ef857c398e188b79c2fc5036f1adbeb2/src/Monolog/Handler.php#L62

I suggest adding a cast to string there, or possibly making the first argument to setExtra more relaxed.

**Comment by ste93cry** [comment]
Good catch! I don't have an example in mind of why the `$key` should not be a `string`, so I would say that casting is the best solution here. Are you willing to open a PR to fix it?

**Comment by pontus-mp** [comment]
Sure, done!
