### ISSUE TITLE
[Monolog] Add possibility to configure user context from `$record`

### ISSUE THREAD

**Issue by JanMikes** [getsentry/sentry-php#837]
Hello! As I mentioned in #836 it would be nice to allow configuration of event completely through monolog.

Taking user either from `$record['extra']['user']` or `$record['context']['user']` would do so 😉 

It was possible to do it in Raven handler before: https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/RavenHandler.php#L177

**Comment by ste93cry** [comment]
Closing this due to explanation given in other similar issues :smile:
