### ISSUE TITLE
[Monolog] Make use of Event::$logger

### ISSUE THREAD

**Issue by JanMikes** [getsentry/sentry-php#838]
Hello, this is more likely question and maybe proposal to do so - why are we not using `Sentry\Event::$logger` and instead using it as custom extra key: `$scope->setExtra('monolog.channel', $record['channel']);`

Imho saving channel name to the logger instead would be better for the UX.

**Comment by ste93cry** [comment]
After investigating a bit I finally found out where the `logger` attribute is shown in the UI of Sentry (I admit I never noticed that small text below the error message in the issues list...), so I agree with you on setting it. However, I don't have a valid point to say that we should not also set it in the `extra` context.

**Comment by JanMikes** [comment]
>  I don't have a valid point to say that we should not also set it in the extra context.

Yeah, why not 😉

**Comment by ste93cry** [comment]
Are you willing to open a PR addressing the issue?

**Comment by JanMikes** [comment]
Yes, i would love to!

**Comment by JanMikes** [comment]
I was thinking about adding just channel name, but decided to add it this way - `monolog.$channel` imho it is better, feedback is appreciated.
