### ISSUE TITLE
Remove static method from HubInterface

### ISSUE THREAD

**Issue by B-Galati** [getsentry/sentry-php#845]
Hello,

I don't see the point of having these 2 methods in HubInterface:

- `public static function getCurrent(): self`
- `public static function setCurrent(self $hub): self`

As we cannot know which implementation is the right one to use. 

IMHO, it's great that the SDK proposed a static access to the Hub but it should be opt-in and not part of the initial contract.

An alternative would be to type hint the interface with `HubInterface` instead of self, WDYT?

FYI I got the issue because I created a decorator to deal with the Spool Transport that is hard to setup.

**Comment by ste93cry** [comment]
There seems to be a lot of questions here, so I will try to address all of them :wink: 

>An alternative would be to type hint the interface with HubInterface instead of self, WDYT?

That is indeed a wrong typehint that should have never been that, but we cannot change it anymore without breaking BC so it must stay as that. For the same reason, no methods can be added or removed from the `HubInterface` interface.

>it's great that the SDK proposed a static access to the Hub but it should be opt-in and not part of the initial contract

The hub holds in its state the current hub instance (there can be only one active at once) and those methods are the way to get and set it. I agree that it's not the purpose of this class to hold such state, the alternative would be to have a singleton object that holds such instance. To clarify, in the JS SDK this is represented by the `Carrier` concept while in the Python SDK this should be the `HubManager`. Like before, we cannot change the interface anyway without breaking BC so those methods can became a proxy to something else but have to stay until the next major version which is unlikely to came soon

**Comment by B-Galati** [comment]
> There seems to be a lot of questions here, so I will try to address all of them wink
> 
> > An alternative would be to type hint the interface with HubInterface instead of self, WDYT?
> 
> That is indeed a wrong typehint that should have never been that, but we cannot change it anymore without breaking BC so it must stay as that. For the same reason, no methods can be added or removed from the `HubInterface` interface.

It would not be a dramatic BC break to change self by `HubInterface` as it stays relatively compatible.

Thank you for your answers :+1:

**Comment by Jean85** [comment]
I would like to agree with B-Galati, changing to interface widens the return, so it shouldn't be a BC, but unfortunately it is, PHP doesn't like widen interfaces: https://3v4l.org/R78b3

Proper contravariance will be present in PHP 7.4: https://wiki.php.net/rfc/covariant-returns-and-contravariant-parameters

**Comment by ste93cry** [comment]
Actually changing the typehint of the parameter can be done without breaking BC because even if it was typehinted as `self` the only way for child classes to respect the contract was to typehint against the interface, so we are safe. Unfortunately the return type cannot be changed :cry:

**Comment by B-Galati** [comment]
Just want to understand why it's not possible if it's already broken?

Anyway it's not a big deal.

**Comment by ste93cry** [comment]
>Just want to understand why it's not possible if it's already broken?

The point is that it's not broken from a strictly-speaking technical perspective. If we change the return typehint to something else we are going to break the code of any people that implemented the interface and as you can image this isn't feasible. However, changing the parameter's typehint is more than welcome and we would gladly accept a contribution for this

**Comment by ste93cry** [comment]
Closing as this issue has been fixed in #849
