### ISSUE TITLE
Different errors while tyring to drupal drush 

### ISSUE THREAD

**Issue by sepal** [getsentry/sentry-php#862]
Hi,

I'm trying to debug some issues with drupals cache layer using sentry, but encountered some problems. I'm using v2 of the library without the raven module.

I want to basically send a custom event if a [certain cache id is set](https://git.drupalcode.org/project/drupal/blob/7.x/includes/cache.inc#L141), so that I can debug what causes the faulty cache entry. My code basically looks likes this:

```
function cache_set($cid, $data, $bin = 'cache', $expire = CACHE_PERMANENT) {
 if ($cid == 'some cache id') {
    $dsn = variable_get('recruiter_sentry_dsn');
    Sentry\init(['dsn' => $dsn]);

    Sentry\configureScope(function (Sentry\State\Scope $scope) use ($cid, $data, $bin) {
      $scope->setTag('cid', $cid);
      $scope->setExtra('data', $data);
      $scope->setExtra('bin', $bin);
    });

    Sentry\captureMessage("cache_set");
  }
    
  return _cache_get_object($bin)->set($cid, $data, $expire);
}
```

This works for web requests, but when I run [drush](https://www.drush.org/), which works over the CLI, for example for cron requests or refreshing the cache periodically, I get some error messages. 

The first issue is that sentry expects `$_SERVER['HTTP_USER_AGENT']` to be a string or a numeric value. Since drupal is called from the CLI there is no user agent and I get the following error:
```
<h1>Additional uncaught exception thrown while handling exception.</h1><h2>Original</h2><p>Zend\Diactoros\Exception\InvalidArgumentException: Invalid header value type; must be a string or numeric; received NULL in Zend\Diactoros\HeaderSecurity::assertValid() (line 139 of /var/www/html/profiles/recruiter/vendor/zendframework/zend-diactoros/src/HeaderSecurity.php).</p><h2>Additional</h2><p>Zend\Diactoros\Exception\InvalidArgumentException: Invalid header value type; must be a string or numeric; received NULL in Zend\Diactoros\HeaderSecurity::assertValid() (line 139 of /var/www/html/profiles/recruiter/vendor/zendframework/zend-diactoros/src/HeaderSecurity.php).</p><hr />
Fatal error: Uncaught Zend\Diactoros\Exception\InvalidArgumentException: Invalid header value type; must be a string or numeric; received NULL in /var/www/html/profiles/recruiter/vendor/zendframework/zend-diactoros/src/HeaderSecurity.php:139
Stack trace:
#0 /var/www/html/profiles/recruiter/vendor/zendframework/zend-diactoros/src/MessageTrait.php(398): Zend\Diactoros\HeaderSecurity::assertValid(NULL)
#1 [internal function]: Zend\Diactoros\ServerRequest->Zend\Diactoros\{closure}(NULL)
#2 /var/www/html/profiles/recruiter/vendor/zendframework/zend-diactoros/src/MessageTrait.php(401): array_map(Object(Closure), Array)
#3 /var/www/html/profiles/recruiter/vendor/zendframework/zend-diactoros/src/MessageTrait.php(338): Zend\Diactoros\ServerRequest->filterHeaderValue(Array)
#4 /var/www/html/profiles/recruiter/vendor/zendframework/zend-diactoros/src/RequestTrait.php(80): Zend\Diactoros\ServerRequest->setHeaders(Array)
#5 /var/www/html/profiles/recruiter/vendor/zendframework/zend-diactoros/src/ServerRequest.php(99): Zend\Diactoros\Se in /var/www/html/profiles/recruiter/vendor/zendframework/zend-diactoros/src/HeaderSecurity.php on line 139
```

I can get passed that by setting the user agent to an empty string manually. If I do that, the second issue arrises. I get a lot of this warnings and my drush process hangs:

```
curl_multi_info_read(): supplied resource is not a valid cURL Multi  [warning]
Handle resource MultiRunner.php:88
```

Is there something I have to set if I want to use sentry with php script called via bash, i.e. not a web request?

**Comment by ste93cry** [comment]
The issue may lie around this line:

https://github.com/getsentry/sentry-php/blob/75118eab8b59a2f1b3148c5c0a242fcef92ad523/src/Integration/RequestIntegration.php#L82

Can you try to disable the `RequestIntegration` integration and see if it works?

**Comment by Jean85** [comment]
You should check for the value of `$_SERVER['REQUEST_METHOD']`; maybe it's set but it's `null`?

**Comment by sepal** [comment]
> You should check for the value of $_SERVER['REQUEST_METHOD']; maybe it's set but it's null?

yes, `$_SERVER['REQUEST_METHOD']` is set to `null`, but `\PHP_SAPI` returns `'cli'` so $request is still set to `null` and `ServerRequestFactory::fromGlobals()` is not run. I can see  that the assertion fails before the code in RequestIntegration is run, so disabling `RequestIntegration` will not help I guess.

You can find the backtrace here:
https://gist.github.com/sepal/6a501b1884265b78269a07f0eebba686

**Comment by Jean85** [comment]
Thanks! So this is the culprit: https://github.com/getsentry/sentry-php/blob/75118eab8b59a2f1b3148c5c0a242fcef92ad523/src/EventFactory.php#L97
