### ISSUE TITLE
New versions missing from Packagist

### ISSUE THREAD

**Issue by WesCossick** [getsentry/sentry-php#866]
New versions of `sentry/sdk` are missing from Packagist: https://packagist.org/packages/sentry/sdk.

Packagist, however, does have the new versions for `sentry/sentry`: https://packagist.org/packages/sentry/sentry.

**Comment by ste93cry** [comment]
This is because the `sentry/sdk` package has a pretty wide constraint for the `sentry/sentry` dependency, so there is no need to release new versions of the package until we release a new major version or until we decide that a certain version of the package should absolutely require at least a minimum version `X.Y.Z` of the latter package

**Comment by WesCossick** [comment]
If you're using Sentry's SDK in a Docker image, then you can't upgrade from `2.0.3` to a newer version (at least without making modifications to unrelated files or lines of code). This is because Docker only rebuilds steps in a Dockerfile when the contents have changed. But if you can't change the `composer.json` file to reference `2.1.1` instead of `2.0.3`, then the version never changes.

Further, if you want to target a specific SDK version, you simply can't.

**Comment by ste93cry** [comment]
>Further, if you want to target a specific SDK version, you simply can't

As long as you specify in your own project a constraint for `sentry/sentry` that does not conflict with the one of the `sentry/sdk` package you can force the version of the "main" package

>But if you can't change the composer.json file to reference 2.1.1 instead of 2.0.3, then you're perpetually stuck with 2.0.3

The version of both packages is written in the `composer.lock`, so as long as you run `composer update` (for all dependencies or for a specific dependency like `sentry/sentry`) you will download the newest version and the Docker image will be rebuilt. Am I missing something?

>What is the benefit of doing it this way?

There is no real benefit, we are simply avoiding to keep in sync the versions of two packages as it makes releasing new versions way more simple and we didn't had yet a good reason to not do it this way 😉

**Comment by WesCossick** [comment]
> The version of both packages is written in the composer.lock, so as long as you run composer update (for all dependencies or for a specific dependency like sentry/sentry) you will download the newest version and the Docker image will be rebuilt. Am I missing something?

If you make use of `composer.lock` files and run Composer locally to install or update dependencies, then yes, the lock file will change and that would trigger a rebuild with Docker.

However, when a project consists of hundreds of microservices, each with a different set of composer dependencies, it's not practical to maintain locally-installed copies of every dependency inside each microservice or manually run `composer update` within each one whenever a new version of a dependency is released. Especially when Docker is responsible for installing the dependencies during the build process.

Instead, it's much more practical to simply include a `composer.json` file that looks like…

```json
{
	"require": {
		"sentry/sdk": "X.X.X"
	}
}
```

…and do a find-and-replace to replace Sentry's version.

> As long as you specify in your own project a constraint for sentry/sentry that does not conflict with the one of the sentry/sdk package you can force the version of the "main" package.

You are correct, though, that if you add a `"sentry/sentry": "X.X.X"` line to your `composer.json` file, then yes, Sentry's SDK will use that version as long as it doesn't conflict with its own constraint.

This, however, is a rather unintuitive way of coercing Sentry into using a specific version. It's also more error-prone because now you need to maintain two independent version references for one dependency and always be watching `sentry/sdk`'s constraint to make sure it doesn't conflict.

> There is no real benefit, we are simply avoiding to keep in sync the versions of two packages as it makes releasing new versions way more simple and we didn't had yet a good reason to not do it this way 😉

It's y'all's call, but hopefully, you'll consider publishing `sentry/sdk` versions each time a new version of `sentry/sentry` is released. `sentry/sdk`'s version constraint for `sentry/sentry` could then be changed to reference the exact matching version of `sentry/sentry`. Is this something you could automate so that it's not difficult to keep the two packages in sync?

**Comment by ste93cry** [comment]
>However, when a project consists of hundreds of microservices, each with a different set of composer dependencies, it's not practical to maintain locally-installed copies of every dependency inside each microservice or manually run composer update within each one whenever a new version of a dependency is released. Especially when Docker is responsible for installing the dependencies during the build process.

I'm not sure I get what you are trying to do or explain here. If you need to update the package, be it `sentry/sentry` or `sentry/sdk` you will have to run `composer update` so the vendors will be updated anyway... I don't see how having the same versions tagged on both packages helps you

>This, however, is a rather unintuitive way of coercing Sentry into using a specific version. It's also more error-prone because now you need to maintain two independent version references for one dependency and always be watching sentry/sdk's constraint to make sure it doesn't conflict.

This is no different from using for example `symfony/symfony` and then forcing a specific version of one component of the framework. `sentry/sdk` is just a metapackage that simplifies the installation of the SDK by including some packages that you normally would have to install yourself but that in this case we do for you. If you prefer, you can directly require the main package and install the missing dependencies to make it work (e.g. the cURL HTTP client). Also, the only reasons I have in mind about why `sentry/sdk` constraint would change is that we release a new major version or we have to mark as conflicting a version

>Is this something you could automate so that it's not difficult to keep the two packages in sync?

I don't know since I'm not responsible for the releases, but I think that we are open to change the process if we find out that it makes sense to do it. @HazAT WDYT?

**Comment by WesCossick** [comment]
> I'm not sure I get what you are trying to do or explain here. If you need to update the package, be it `sentry/sentry` or `sentry/sdk` you will have to run `composer update` so the vendors will be updated anyway... I don't see how having the same versions tagged on both packages helps you

Running `composer update` is useful for updating packages when you have a local copy of them installed. What I'm saying is that, at least with our team's larger codebases, we do not maintain a local copy of the `vendor/` folder inside every one of our hundreds of microservices. Therefore, we do not use `composer update` to update packages. We also don't use `composer.lock` files. Instead, to update a package, we simply change its version number in the `composer.json` file and let Docker run `composer install` during the build process.

If you treat the `sentry/sdk` as purely a metapackage only present for conveniently installing a collection of other packages, then maybe there's no reason to publish new versions; although, that's a strong maybe. However, since I would wager to guess that most everyone is using this package as the primary way of installing Sentry's SDK, then I believe it's appropriate for it to have corresponding versions published for each release of the SDK.

**Comment by WesCossick** [comment]
I would also add, while I'm not especially familiar with Symphony, it looks like [`symfony/symfony`](https://packagist.org/packages/symfony/symfony) and its components all have a new version published with every release.

**Comment by mfb** [comment]
I think most folks use composer.lock to tell their docker build which versions to install in the image. If you're in a "weird" situation where you don't want to do it that way, then specifying the sentry/sentry version seems like an ok workaround to me.

symfony packages do get a new release made for every patch version, even if there have been no changes in that particular library, but I wouldn't say every suite of packages needs to work that way.

**Comment by ste93cry** [comment]
>I would also add, while I'm not especially familiar with Symphony, it looks like symfony/symfony and its components all have a new version published with every release.

I'm sorry I didn't explain myself well, I didn't mean that Symfony doesn't release new versions of all packages with every release, it was just an example package to explain that you could overwrite the version of each single component in the `composer.lock`

>f you're in a "weird" situation where you don't want to do it that way, then specifying the sentry/sentry version seems like an ok workaround to me

I agree, imho this is a weird setup and I wonder how you can develop your applications if you don't have the vendors installed locally. By the way, at the moment of writing the best options you have are to still require the metapackage and then overwrite the version of the main package or require directly the main package
