### ISSUE TITLE
Sentry dev dependencies

### ISSUE THREAD

**Issue by himynameisseb** [getsentry/sentry-php#869]
When installing sentry via composer:
`composer require sentry/sdk`

Or in our case, installing the raven (sentry integration module for Drupal):
`composer require 'drupal/raven:^2.21`
(which in turn requires the sentry library)

We notice that there are a lot of dev dependencies added to our `/vendors` directory.

As we want to use Sentry on our production environments for better logging, this would suggest that the development libraries need to be on our production environments.

Ideally, we do not want development libraries on production environments.  We are able to remove the dev dependencies for production and Sentry seems to still work.

Maybe this bug report becomes a question rather than a bug (sorry if so).

Is it possible to remove the dev libraries as dependencies so that we can easily require Sentry without requiring development libraries?

(Or is it that Sentry is not currently going to be working correctly on live and we think it is? Or is our usage incorrect and we should not be installing it as we are?)

Thanks!

**Comment by ste93cry** [comment]
When you require the package it should not download the `dev-dependencies`. Which one are you seeing in your `vendor` folder?

**Comment by himynameisseb** [comment]
Hia, thanks for the quick response. There are quite a few. Below is a snippet of some:

`vendor/behat`
`vendor/bin/phpcbf`
`vendor/bin/phpcs`
`vendor/bin/phpunit`
`vendor/doctrine`
...

If I check the vendor composer file: `vendor/sentry/sentry/composer.json`

I notice that the dependencies are:
```"require-dev": {
        "friendsofphp/php-cs-fixer": "^1.8.0",
        "phpunit/phpunit": "^4.8.35 || ^5.7",
        "monolog/monolog": "*"
    },
    "require": {
        "php": "^5.3|^7.0",
        "ext-curl": "*"
    }```

`phpunit` will in turn require a lot of other dev dependencies.

You cannot use '--no-dev' when doing a `require` (as far as I know).  This could be circumvented by doing a `composer install` with the `--no-dev` flag. Is this what we should be doing?

Thanks

**Comment by mfb** [comment]
If you want to avoid getting all the drupal dev dependencies, you will need to add `--update-no-dev` whenever you require a package, e.g. `composer require --update-no-dev drupal/raven`

**Comment by himynameisseb** [comment]
OK, thanks. Not sure if you are related to the team who manage the Sentry website/portal. Would be great to put some info about this on there or update the installation documentation.

Thanks!

**Comment by mfb** [comment]
@himynameisseb your issue is with drupal dev dependencies - it's not related to Sentry at all.  (I am also not related to Sentry at all :)

**Comment by ste93cry** [comment]
When doing a plain `composer require` there is no need to specify anything as it won't install by default the `dev-dependencies`. If you instead do `composer install` it will if you don't specify the `--no-dev` flag. This is how Composer works though and it's not something that depends on us and that we should document

**Comment by mfb** [comment]
Drupal projects can use `composer install --no-dev` and `composer require --update-no-dev` to avoid installing the numerous dev dependencies defined in the top-level composer.json file.  It could be better documented by drupal folks but that's neither here nor there for this issue queue :)

**Comment by himynameisseb** [comment]
OK fair enough, we will install it with `--update-no-dev`. Or indeed we can just add it to our composer.json and just run `composer install --no-dev` for now.

It could be that there is a line somewhere or something in my local composer.json that is forcing dev dependencies by default? (if there is such a thing). Or maybe I just need to read up why Drupal will do this?

Anyways. I have a resolution now so thanks all.

If anyone does have a definitive answer as to why a standard `composer require` would include the dev dependencies when it shouldn't, I'd be interested to hear why.

**Comment by himynameisseb** [comment]
Closing as have a resolution. Please feel free to re-open or comment.

**Comment by mfb** [comment]
My 2 cents is that when you type `composer require ...` you must be in a dev environment (assuming you don't have an AI typing `composer require` commands in production :) so it makes sense that composer installs the dev dependencies you defined in your composer.json, by default. You add `--update-no-dev` to avoid this.

Likewise when scripting (or manually replicating) a production deployment you use `composer install --no-dev` to avoid installing your dev dependencies.

**Comment by himynameisseb** [comment]
@mfb - Yes, you're right.

We should never be building to production without the `--no-dev` flag! For this project it is an issue with our build process and the fact that we include all the vendors in our repo... which really we should be doing when building the artifacts for release.
