### ISSUE TITLE
Events receiving HTTP 400 in v2.1.2

### ISSUE THREAD

**Issue by NGTOne** [getsentry/sentry-php#871]
Exactly what it says on the tin. After upgrading from 2.1.1 to 2.1.2 this morning, events sent to our on-prem Sentry would get back an HTTP 400 with the following response body: `{"error":"No JSON data was found"}`. Upon further investigation (hampered by the fact that there's no `debug` option for the PHP SDK), I discovered that the request being made did, in fact, have an empty body. This was seen by manually dumping out both the request and response bodies from the `catch` in `HttpTransport->cleanupPendingRequests()`.

My `init` takes only a DSN and environment - everything else is left to the defaults.

I then worked around the issue by reverting to 2.1.1.

**Comment by ste93cry** [comment]
Take a look at #857 since that fixed a bug where the request was actually not be compressed before sending, but if your server is misconfigured then you get the exact error you are reporting.

**Comment by robertlemke** [comment]
I stumbled over the same problem, also after upgrading from 2.1.1 to 2.1.2. I'm using sentry.io, not Sentry on on-prem, so I would guess that Nginx is configured correctly there, right?

Dumping the silenced exception in `HttpTransport->cleanupPendingRequests()` I also see a HTTP 400, and I also see an empty Request body.

So, is this a bug in the SDK, a misconfiguration of the sentry.io servers or something I missed?

**Comment by ste93cry** [comment]
Can you please test whether it works if you set the `enable_compression` option to `false`?

**Comment by kralos** [comment]
I can confirm, `enable_compression: false` fixes the issue

**Comment by ste93cry** [comment]
@NGTOne Can you please check whether rewinding the stream before dumping the request body gives you some data?

**Comment by jaredtking** [comment]
I am observing the same behavior as @kralos. We're using Sentry+Symfony and seeing this response from the sentry.io endpoint:
```
{"error":"No JSON data was found"}
```

What is odd is that we only see this issue on CLI, but not in web requests. Setting `enable_compression: false` fixes the issue on CLI.

We have the same issue on PHP 7.2 and PHP 7.3.

**Comment by svensp** [comment]
I get this error using php 7.3, gesentry/sentry-laravel and a self hosted sentry instance.

I played around a bit and calling `wait` on the CurlPromise right away works.

I believe this is because cleanupPendingRequests is called from the destructor of the HttpTransport.

```
The destructor method will be called as soon as all references to a particular object are removed or when the object is explicitly destroyed or in any order in shutdown sequence.
```

The GzipEncodeStream object or some object depending on it has already been destructed at this point.

Just a theory thought, I have not been able to come up with a way to confirm this yet.

**Comment by ste93cry** [comment]
After investigating I found out that we may have hit hard some PHP bug, otherwise I don't have any other explanation for this. Basically, the problem arises when using `exit`. This little script reproduces the problem:

```php
use Http\Message\Encoding\GzipEncodeStream;
use Zend\Diactoros\StreamFactory;

require_once __DIR__ . '/vendor/autoload.php';

register_shutdown_function(function () {
    $stream = (new StreamFactory())->createStream('hello world');
    $stream->rewind();

    $stream = new GzipEncodeStream($stream);

    var_dump($stream->getContents()); // This outputs an empty string
});

exit(1); // If this line is commented out the var_dump works as expected
```

**Comment by kralos** [comment]
> After investigating I found out that we may have hit hard some PHP bug, otherwise I don't have any other explanation for this. Basically, the problem arises when using `exit`. 

This sounds more like a race condition bug to me, exit could be forcing php shutdown before the stream has data.

**Comment by ste93cry** [comment]
I also see that the destructor of the user filter is called before the `onClose` method. [This](https://bugs.php.net/bug.php?id=75931) PHP bug may somewhat be related maybe

**Comment by thomasvargiu** [comment]
It happens even with exceptions

**Comment by schoenkaft** [comment]
We've hit some issues issues as well. We're using the `sentry/sdk` package, and it seems the only solutions seem to specifically require and downgrade `sentry/sentry` (to `2.1.1`), or set the default `enable_compression` to `false`.

So the basic '[Getting Started](https://docs.sentry.io/error-reporting/quickstart/?platform=php)' from the documentation currently does not work:

```php
Sentry\init(['dsn' => '...' ]);

// Doesn't show up in Sentry
throw new Exception("My first Sentry error!");
```

It also seems that the request hangs for quite a while in our application.

- `enable_compression: true`: **5–10s** (plus the event doesn't get sent at all)
- `enable_compression: false`: **~600ms**

Note that this doesn't seem to happen in a reduced test case, only in our application.

**Comment by JanMikes** [comment]
I can confirm #877 fixes that.

Our composer.json:
```
"sentry/sdk": "^2.0",
"sentry/sentry": "dev-no-streaming-gzip as 2.1.2",
```

**Comment by Jean85** [comment]
You should run `composer update sentry/sdk --with-dependencies` though!

**Comment by kralos** [comment]
Verified on my project as now fixed, nice work @stayallive 

```
php-http/guzzle6-adapter               v2.0.1
sentry/sdk                             2.0.3
sentry/sentry                          2.1.3
sentry/sentry-symfony                  3.1.0
symfony/monolog-bridge                 v4.3.4
symfony/monolog-bundle                 v3.4.0
```

**Comment by stayallive** [comment]
@cRUSHr2012 please update to sentry/sentry 2.1.3, this will fix it without needing to disable the compression.

**Comment by jni-heyloyalty** [comment]
Currently, I has the same issue as @robertlemke 
I solved it by downgrading to sentry/sentry 2.1.1.

**Comment by stayallive** [comment]
@jni-heyloyalty do you still have this issue on `2.2.x` (`2.2.6` is the latest at the time of this comment)?

I would try upgrading instead of downgrading and if you still have this issue on `2.2.x` please open a new issue!

**Comment by jni-heyloyalty** [comment]
@stayallive 
The sentry/sentry 2.1.3 works but produces duplicated events, while 2.2.6 seems to work and produces only one event.
Thanks for your effort.

**Comment by stayallive** [comment]
@jni-heyloyalty Yep, please use the latest and greatest, a lot of offert went in `2.2` including fixes for duplicated events. If you still have issues please do open up a new issue so we can investigate!

**Comment by jni-heyloyalty** [comment]
Works :)

    "sentry/sdk": "^2.0",
    "sentry/sentry": "2.2.6",    
    "sentry/sentry-laravel": "1.5.0",

**Comment by jni-heyloyalty** [comment]
@stayallive Instead of suppressing errors please let them bubble up or send them to the centralized log for the respective system it is integrated into, it would have saved me lots of time.

**Comment by stayallive** [comment]
@jni-heyloyalty please open up a new issue if you think something is broken (but first search for related issues like #907, #935).
