### ISSUE TITLE
Update meta `sentry/sdk` package

### ISSUE THREAD

**Issue by cgsmith** [getsentry/sentry-php#873]
Can someone update the meta package `sentry/sdk` to have the correct versions?

**Comment by Jean85** [comment]
Changing the metapackage version is not required, as already explained in https://github.com/getsentry/sentry-php-sdk/pull/3. That is only a metapackage that will suggest a transport implementaton, and it already allows `sentry/sentry:^2.0`. Hence, if you need to update, you can update your composer.lock with `composer update`, or a more specific `composer update sentry/sentry`.
