### ISSUE TITLE
Sentry uses a lot of walltime

### ISSUE THREAD

**Issue by OskarStark** [getsentry/sentry-php#878]
![Screenshot 2019-09-10 15 18 22](https://user-images.githubusercontent.com/995707/64617281-7aec0780-d3de-11e9-9823-fa947522aa2a.png)

Maybe this `wait()` can be fixed by using the new Symfony HttpClient?

**Comment by Jean85** [comment]
`wait` is just waiting for the requests to go to the Sentry server, that's not something that you can optimize at the code level. The Sentry client 2.0 uses HTTPlug, so you can switch your HTTP transport as you wish, I'm not sure if the SF client already has an adapter for it, but it can for sure, since it has a PSR-18 adapter.

Also, IIRC with the current behavior, this wait is called in the shutdown function, so even after that your response has been rendered to the client.

**Comment by OskarStark** [comment]
Hmm you could be right. Or did I miss something @nicolas-grekas?

**Comment by nicolas-grekas** [comment]
https://github.com/php-http/curl-client/issues/55

**Comment by Jean85** [comment]
Thanks @nicolas-grekas for pointing that out. 

Closing since this seems to be a downstream issue with the Curl transport. As a workaround, you can switch out to any different transport supported by HTTPlug.

**Comment by nicolas-grekas** [comment]
I would recommend using the Symfony HttpClient by default. Version 4.4 will ship an `HttplugClient` btw.

**Comment by mfb** [comment]
ouch https://twitter.com/jderusse/status/1115333801419399170

**Comment by B-Galati** [comment]
I ended up doing this:

```php
class SentryHttpClient implements HttpAsyncClient
{
    private $client;

    public function __construct()
    {
        $factory = new Psr17Factory();

        // DO NOT use the http client from Symfony or you could turn into an infinite loop depending on your monolog config and the if logging of HTTP request is enabled or not
        $client = HttpClient::create(['timeout' => 2]);

        $this->client = new Psr18Client($client, $factory, $factory);
    }

    /**
     * {@inheritdoc}
     */
    public function sendAsyncRequest(RequestInterface $request)
    {
        try {
            $response = $this->client->sendRequest($request);
        } catch (RequestExceptionInterface $e) {
            return new HttpRejectedPromise(new RequestException($e->getMessage(), $request, $e));
        } catch (NetworkExceptionInterface $e) {
            return new HttpRejectedPromise(new NetworkException($e->getMessage(), $request, $e));
        }

        return new HttpFulfilledPromise($response);
    }
}
```

Works like a charm, thank you @nicolas-grekas!

I'll update my symfony guide ASAP :-)

**Comment by OskarStark** [comment]
Thank you @B-Galati, let me please know when its done 😃

**Comment by B-Galati** [comment]
@OskarStark Yes it's about to be merged in https://github.com/B-Galati/monolog-sentry-handler/pull/8

Let me know for any feedback please :-)

**Comment by garak** [comment]
@B-Galati what about proposing your code to Httplug lib?
See the HttpClient issue mentioned above

**Comment by B-Galati** [comment]
@garak the proposed implementation is a dumb one that aims at solving a specific problem. I am not even sure it respects HttpPlug specs.

In any case it is something that should be done in Symfony: see symfony/symfony#33710.
