### ISSUE TITLE
\Sentry\init(['dns' => '']) triggers HttpTransport::delaySendingUntilShutdown deprecated error

### ISSUE THREAD

**Issue by Kleingeld** [getsentry/sentry-php#884]
After upgrading to Sentry 2.2.0 the application started sending this error: 

> Delaying the sending of the events using the "Sentry\Transport\HttpTransport" class is deprecated since version 2.2 and will not work in 3.0.

Only problem is the transport is initialized by Sentry itself after calling:
`\Sentry\init(['dsn' => '_PUBLIC_DSN_']);`

The default of delaySendingUntilShutdown = true, but I see no way to overwrite it from within sentry::init. 

So sentry is triggering itself to send errors about this to sentry.io.

Any idea how to fix the sentry::init to stop this issue, for now i commented out the 

`@trigger_error(sprintf('Delaying the sending of the events using the...`

line to stop the application from floading sentry.io

**Comment by Kleingeld** [comment]
Changes to came to this error are in this commit: [https://github.com/getsentry/sentry-php/commit/5dfc0edb215fa1af5ecff698131a2fb501ac6dc2](https://github.com/getsentry/sentry-php/commit/5dfc0edb215fa1af5ecff698131a2fb501ac6dc2)

**Comment by PVGrad** [comment]
For now you can only freeze the version in composer.json
`"sentry/sentry": "2.1.3"`
And wait for a fix then

**Comment by HazAT** [comment]
We are already working on the fix, `2.1.1` is minutes away, we will update the issue.

**Comment by Kleingeld** [comment]
@HazAT thank you!

**Comment by HazAT** [comment]
`2.2.1` has been released containing the fix, sorry for the inconvenience and thanks for reporting.
