### ISSUE TITLE
BC Break on 2.2.0

### ISSUE THREAD

**Issue by brunowowk** [getsentry/sentry-php#887]
#852 introduced some BC breaks on `src/State/Scope.php` by removing the public methods:

- getTags
- getExtra
- getUser
- getFingerprint
- getLevel
- getBreadcrumbs

this change broke the upstream as predicted on https://github.com/getsentry/sentry-symfony/issues/239

Don't know what's the versioning schema over here, but maybe you guys could revert it and schedule the deprecation for 3.0.0, as most upstreams probably use semver

**Comment by ste93cry** [comment]
All those methods were marked as `@internal` and their only purpose was to make unit tests work. When we rewrote the mentioned tests to not use them they became useless. As the [documentation](https://docs.phpdoc.org/references/phpdoc/tags/internal.html) about the tag says, code marked as internal should not be used by the public and if you do you do it at your own risk. There is indeed a technical BC here, but not in the way you are supposed to be interested in. Summarizing: everything marked as `@internal` does not fall into the BC promise. We usually follow the [BC promise of Symfony](https://symfony.com/doc/current/contributing/code/bc.html) as it's pretty clear and explanatory of what can and can not be done (of course some things may not apply to our project). I will quote some documentation excerpts here for future reference:

>The `@internal` tag can be used as counterpart of the `@api` tag, indicating that the associated Structural Elements are used purely for the internal workings of this piece of software.

>Experimental Features and code marked with the `@internal` tags are excluded from our Backward Compatibility promise.

**Comment by brunowowk** [comment]
My bad, I hadn't noticed the `@internal` on those diffs. 😅
Sorry about the bother, I'll follow up on `sentry-symfony`

**Comment by Jean85** [comment]
`sentry-symfony` is ready to go, we will tag a new version that will include getsentry/sentry-symfony#239 ASAP. Right now the last tagged version just triggers a few deprecations; those removed methods where used just in tests there too.

**Comment by brunowowk** [comment]
TYSM @Jean85 ✌

**Comment by ste93cry** [comment]
A good idea may be to update the README to specify the fact that we strive to follow Semver and also that we try to follow as close as possible the BC Promise document from Symfony. Any contribution is more than welcome on this :smile:
