### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function Sentry\init()

### ISSUE THREAD

**Issue by cmedias** [getsentry/sentry-php#893]
I can't include it to my project. I get this error message:

Fatal error: Uncaught Error: Call to undefined function Sentry\init() ...

**Comment by Jean85** [comment]
Did you follow the README instructions? Did you use Composer to install the dependency?

**Comment by cmedias** [comment]
Well, I think so. I installed it via composer and it was added in the vendor folder of my project.
After this, I added this line at the beginnen of my CoreRequesthandler:

`Sentry\init(['dsn' => 'https://###']);`

**Comment by cmedias** [comment]
After adding the include at the beginning `require_once 'vendor/autoload.php';`, now I get this error:

Warning: require([DIR]/vendor): failed to open stream: Success in [DIR]/vendor/composer/autoload_real.php on line 66 

Call Stack: 0.0020 384904 
1. {main}() [DIR]/index.php:0 0.0196 406248 
2. require_once('[DIR]/vendor/autoload.php') [DIR]/index.php:10 0.0227 419960 
3. ComposerAutoloaderInitf884902efb91daa8556499790f6fe6ab::getLoader() [DIR]/vendor/autoload.php:7 0.0289 480488 
4. composerRequiref884902efb91daa8556499790f6fe6ab() [DIR]/vendor/composer/autoload_real.php:56 
Fatal error: require(): Failed opening required '[DIR]/vendor/composer/..' (include_path='.:/var/packages/PEAR/target') in [DIR]/vendor/composer/autoload_real.php on line 66

Call Stack: 0.0020 384904 
1. {main}() [DIR]/index.php:0 0.0196 406248 
2. require_once('[DIR]/vendor/autoload.php') [DIR]/index.php:10 0.0227 419960 
3. ComposerAutoloaderInitf884902efb91daa8556499790f6fe6ab::getLoader() [DIR]/vendor/autoload.php:7 0.0289 480488 
4. composerRequiref884902efb91daa8556499790f6fe6ab() [DIR]/vendor/composer/autoload_real.php:56`

**Comment by Jean85** [comment]
It seems to me that you do not have a working autoloader configuration with Composer. You should fix that first.

**Comment by cmedias** [comment]
I reinstalled the sentry-package and now the autoloader works. Thanks for your support anyway!

**Comment by tibz7** [comment]
Hello, I'm having a similar issue, but reinstalling it did not help. 
I'm using php7.4 with phalcon 4.1. 
I have a loader.php which loads the composer/autoload_namespace.php and composer/autoload_psr4.php.
