### ISSUE TITLE
Add phptek/sentry package for SilverStripe projects

### ISSUE THREAD

**Issue by phptek** [getsentry/sentry-php#895]
Hi, I'm the maintainer of https://github.com/phptek/silverstripe-sentry - the most popular of the small handful of packages for Sentry integration with [SilverStripe](https://silverstripe.org) projects. Please consider listing the package on your README.

Thanks heaps!

**Comment by stayallive** [comment]
Hey @phptek, right now we're fixing the current list of integrations with #874, it would be greatly appreciated if you can create a PR after #874 is merged adding the SilverStripe integration.

Thanks for creating it in the first place! 😄 Have you considered upgrading the Sentry to SDK to 2.x yet?

**Comment by phptek** [comment]
Hey there and thanks - yes, "3.0" (branch) and "3.0-alpha1" (tag) are both built on top of the v2 SDK.

I'll sort a PR for your README ASAP. :-)

**Comment by phptek** [comment]
Done! See #896
