### ISSUE TITLE
Uncaught TypeError: Return value of Http\Client\Curl\PromiseCore::getException() must implement interface Throwable, instance of Nyholm\Psr7\Response

### ISSUE THREAD

**Issue by luckyraul** [getsentry/sentry-php#900]
PHP message: PHP Fatal error:  Uncaught TypeError: Return value of Http\Client\Curl\PromiseCore::getException() must implement interface Throwable, instance of Nyholm\Psr7\Response returned in ```/var/www/releases/20191015093018/vendor/php-http/curl-client/src/PromiseCore.php:194```

```
Stack trace:
#0 /var/www/releases/20191015093018/vendor/php-http/curl-client/src/CurlPromise.php(103): Http\Client\Curl\PromiseCore->getException()
#1 /var/www/releases/20191015093018/vendor/sentry/sentry/src/Transport/HttpTransport.php(110): Http\Client\Curl\CurlPromise->wait()
#2 /var/www/releases/20191015093018/vendor/sentry/sentry/src/Client.php(117): Sentry\Transport\HttpTransport->send(Object(Sentry\Event))
#3 /var/www/releases/20191015093018/vendor/sentry/sentry/src/Client.php(103): Sentry\Client->captureEvent(Array, Object(Sentry\State\Scope))
```

**Comment by luckyraul** [comment]
probably https://github.com/php-http/curl-client/issues/60

**Comment by Jean85** [comment]
The Curl adapter seems to be buggy, as already reported in #878. We're moving away from it and migrating to use Guzzle, with #890 and https://github.com/getsentry/sentry-php-sdk/pull/4. I would suggest to use Guzzle manually in the meantime.

**Comment by ste93cry** [comment]
Closing because this is a bug in the Httplug Curl client and there is nothing we can do on our side
