### ISSUE TITLE
Not compatible with PHP < 7.3

### ISSUE THREAD

**Issue by AndreiIgna** [getsentry/sentry-php#906]
In `composer.json` the requirement for PHP shows 
```
"require": {
        "php": "^7.1",
```

but actually requires 7.3, because of https://github.com/Ocramius/PackageVersions dependency

Can the dependency be locked to a version that works on 7.1? There's still projects that use this version of PHP

**Comment by ste93cry** [comment]
Wrong, Composer will require a version of `ocramius/package-versions` that is compatible with it (proof is our CI that tests against all versione of PHP from `7.1` to `7.4` :wink:) Also take a look at #850, you could find some comments helpful to solve the issue

**Comment by AndreiIgna** [comment]
Thanks @ste93cry, searched before for similar Issue, but haven't seen that one. Useful info there 👍🏼
