### ISSUE TITLE
Monolog package non dev requirement

### ISSUE THREAD

**Issue by TheLevti** [getsentry/sentry-php#908]
Shouldn't be the `"monolog/monolog": "^1.3|^2.0",` composer requirement in the non-dev section instead? It is clearly used in a class (`Sentry\Monolog\Handler`) that might be used in production without the dev packages installed.

**Comment by Jean85** [comment]
That's an optional part of the library, that's why it's not under `require`. We could add that in the `suggest` section too to highlight this fact, maybe?

**Comment by TheLevti** [comment]
Ah I understand, makes sense now. Thanks for the clarification.

Yeah why not? I mean if its not too much work of course.

**Comment by Jean85** [comment]
You're welcome to open a PR yourself if you want!

**Comment by TheLevti** [comment]
No problem, will do it.
