### ISSUE TITLE
Possibility capture stacktrace for messages

### ISSUE THREAD

**Issue by evolcon** [getsentry/sentry-php#918]
I've created an package for framework yii2, but there is problem with capturing of stacktrace for messages, i can't find any way how to resolve this problem without writing a lot of code.

The class EventFactory in method createWithStacktrace() uses a variable in array payLoad['stacktrace'], but there is no ability to configure this array by methods Hub::captureMessage() and Client::captureMessage(), so then i tried to configure an event, and send messages by method 
 Hub::captureEvent() or Client::captureEvent(), now we can set stacktrace to payLoad but we can't set any function params which will be called by method prepareEvent(), for example we must set function parameter withStackTrace = true, but there is no ability to do this.

**Comment by Jean85** [comment]
Stacktraces are always attached when capturing errors. The `attach_stack_trace` option instead is used to enable stacktrace attachment on `captureMessage` only. It's and end user option.

**Comment by ste93cry** [comment]
Did you manage to solve the issue?

**Comment by ste93cry** [comment]
Closing this because either the issue has been solved or there is no more need for help. Feel free to reopen if this is not the case
