### ISSUE TITLE
Add support for Symfony 5

### ISSUE THREAD

**Issue by garak** [getsentry/sentry-php#922]
Symfony 5 is currently in beta and will be stable [in two weeks](https://symfony.com/releases).

**Comment by ste93cry** [comment]
Would you mind opening a PR for this targeting the `master` branch?

**Comment by garak** [comment]
I tried to, but unfortunately it's currently not possible until we get support from `friendsofphp/php-cs-fixer` and `php-http/client-common`.
Opened issues in respective repos too.

**Comment by Jean85** [comment]
Can you cross-link them here?

**Comment by Jean85** [comment]
First one already resolved: https://github.com/php-http/client-common/pull/175 now we need to wait for a tag.

The other one has a pending PR, which has a green build: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4608

**Comment by pkruithof** [comment]
Both issues have been resolved/tagged. So I don't think this issue is blocked anymore. Can we proceed with it?
