### ISSUE TITLE
sentry with error : Puli Factory is not available

### ISSUE THREAD

**Issue by wzfjesun** [getsentry/sentry-php#933]
I installed sentry widh docker on https://github.com/getsentry/onpremise,

sentry send error has the error:

> [15-Dec-2019 12:41:42 Asia/Shanghai] PHP   8. frontend\controllers\SiteController->actionIndex() /var/www/html/api/vendor/yiisoft/yii2/base/InlineAction.php:57
[15-Dec-2019 12:41:42 Asia/Shanghai] PHP   9. Sentry\init() /var/www/html/api/frontend/controllers/SiteController.php:39
[15-Dec-2019 12:41:42 Asia/Shanghai] PHP  10. Sentry\ClientBuilder->getClient() /var/www/html/api/vendor/sentry/sentry/src/functions.php:14
[15-Dec-2019 12:41:42 Asia/Shanghai] PHP  11. Sentry\ClientBuilder->createTransportInstance() /var/www/html/api/vendor/sentry/sentry/src/ClientBuilder.php:269
[15-Dec-2019 12:41:42 Asia/Shanghai] PHP  12. Http\Discovery\HttpAsyncClientDiscovery::find() /var/www/html/api/vendor/sentry/sentry/src/ClientBuilder.php:342
[15-Dec-2019 12:41:42 Asia/Shanghai] PHP  13. Http\Discovery\ClassDiscovery::findOneByType() /var/www/html/api/vendor/php-http/discovery/src/HttpAsyncClientDiscovery.php:25
[15-Dec-2019 12:41:42 Asia/Shanghai] PHP  14. call_user_func:{/var/www/html/api/vendor/php-http/discovery/src/ClassDiscovery.php:56}() /var/www/html/api/vendor/php-http/discovery/src/ClassDiscovery.php:56
[15-Dec-2019 12:41:42 Asia/Shanghai] PHP  15. Http\Discovery\Strategy\PuliBetaStrategy::getCandidates() /var/www/html/api/vendor/php-http/discovery/src/ClassDiscovery.php:56
[15-Dec-2019 12:41:42 Asia/Shanghai] PHP  16. Http\Discovery\Strategy\PuliBetaStrategy::getPuliDiscovery() /var/www/html/api/vendor/php-http/discovery/src/Strategy/PuliBetaStrategy.php:80
[15-Dec-2019 12:41:42 Asia/Shanghai] PHP  17. Http\Discovery\Strategy\PuliBetaStrategy::getPuliFactory() /var/www/html/api/vendor/php-http/discovery/src/Strategy/PuliBetaStrategy.php:65
[15-Dec-2019 12:41:42 Asia/Shanghai] PHP Http\Discovery\Exception\PuliUnavailableException:  Puli Factory is not available in /var/www/html/api/vendor/php-http/discovery/src/Strategy/PuliBetaStrategy.php on line 40

below is my code:

>  \Sentry\init(['dsn' => 'http://b5d567a702dc4a6395d1c3a238f6bbf5@192.168.1.108:9100/5']);
            try {
                throw new \Exception('foo bar');
            } catch (\Exception $exception) {
                \Sentry\captureException($exception);
            }

I use php 7.2 ,sentry 9.1.2, maybe i had something wrong ,please help me

**Comment by ste93cry** [comment]
Please ensure that you either install the `sentry/sdk` package instead of `sentry/sentry` or if you required the latter you also require a PSR-7 implementation and an HTTP client adapter for Httplug. Please see the README of this repository for a few commands that can help you get started quickly

**Comment by wzfjesun** [comment]
i had remove sentry/sentry. and run composer update, still has the same error
below is my compose.json
> "require": {
        "php": ">=5.6.0",
        "yiisoft/yii2": "~2.0.14",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0 || ~2.1.0",
        "firebase/php-jwt": "^5.0",
        "yiisoft/yii2-redis": "~2.0.0",
        "workerman/gatewayclient": "^3.0",
        "ua-parser/uap-php": "v3.9.0",
        "psr/log": "^1.1",
        "aliyuncs/oss-sdk-php": "^2.3",
        "monolog/monolog": "^2.0",
        "mongodb/mongodb": "^1.5",
        "himiklab/yii2-sitemap-module": "*",
        "sentry/sdk": "2.0.3",
        "notamedia/yii2-sentry": "^1.4"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.1.0",
        "yiisoft/yii2-gii": "~2.1.0",
        "yiisoft/yii2-faker": "~2.0.0",
        "codeception/base": "^2.4.0",
        "phpunit/phpunit": "~5.7.27 || ~6.5.5",
        "codeception/verify": "~0.5.0 || ~1.1.0",
        "symfony/browser-kit": ">=2.7 <=4.2.4"
    },

but in composer.lock file ,still has the sentry/sentry , should i remove the sentry/sentry?

**Comment by ste93cry** [comment]
>but in composer.lock file ,still has the sentry/sentry

You should never touch manually the `.lock` file as it's handled by Composer itself. Also, it's normal that the `sentry/sentry` package is listed there because it's a dependency of `sentry/sdk`. Can you please post the output of the `composer show` command?

**Comment by wzfjesun** [comment]
> aliyuncs/oss-sdk-php               v2.3.1   Aliyun OSS SDK for PHP
behat/gherkin                      v4.6.0   Gherkin DSL parser for PHP 5.3
bower-asset/bootstrap              v3.4.1  
bower-asset/inputmask              3.3.11  
bower-asset/jquery                 3.4.1   
bower-asset/punycode               v1.3.2  
bower-asset/yii2-pjax              2.0.7.1 
cebe/markdown                      1.2.1    A super fast, highly extensible...
clue/stream-filter                 v1.4.1   A simple and modern approach to...
codeception/base                   2.5.6    BDD-style testing framework
codeception/phpunit-wrapper        6.7.1    PHPUnit classes used by Codecep...
codeception/stub                   2.1.0    Flexible Stub wrapper for PHPUn...
codeception/verify                 1.1.0    BDD assertion library for PHPUnit
composer/ca-bundle                 1.2.5    Lets you find a path to the sys...
doctrine/instantiator              1.3.0    A small, lightweight utility to...
doctrine/lexer                     1.2.0    PHP Doctrine Lexer parser libra...
egulias/email-validator            2.1.11   A library for validating emails...
ezyang/htmlpurifier                v4.12.0  Standards compliant HTML filter...
firebase/php-jwt                   v5.0.0   A simple library to encode and ...
fzaninotto/faker                   v1.9.1   Faker is a PHP library that gen...
guzzlehttp/promises                v1.3.1   Guzzle promises library
guzzlehttp/psr7                    1.6.1    PSR-7 message implementation th...
himiklab/yii2-sitemap-module       1.2.1    Yii2 module for automatically g...
http-interop/http-factory-guzzle   1.0.0    An HTTP Factory using Guzzle PSR7
jean85/pretty-package-versions     1.2      A wrapper for ocramius/package-...
mongodb/mongodb                    1.5.1    MongoDB driver library
monolog/monolog                    2.0.1    Sends your logs to files, socke...
myclabs/deep-copy                  1.9.3    Create deep copies (clones) of ...
notamedia/yii2-sentry              1.4.1    Yii2 logger for Sentry
ocramius/package-versions          1.4.2    Composer plugin that provides e...
opis/closure                       3.5.1    A library that can be used to s...
paragonie/random_compat            v9.99.99 PHP 5.x polyfill for random_byt...
phar-io/manifest                   1.0.1    Component for reading phar.io m...
phar-io/version                    1.0.1    Library for handling version in...
php-http/client-common             2.1.0    Common HTTP Client implementati...
php-http/curl-client               2.0.0    PSR-18 and HTTPlug Async client...
php-http/discovery                 1.7.0    Finds installed HTTPlug impleme...
php-http/httplug                   v2.0.0   HTTPlug, the HTTP client abstra...
php-http/message                   1.8.0    HTTP Message related tools
php-http/message-factory           v1.0.2   Factory interfaces for PSR-7 HT...
php-http/promise                   v1.0.0   Promise used for asynchronous H...
phpdocumentor/reflection-common    2.0.0    Common reflection classes used ...
phpdocumentor/reflection-docblock  4.3.2    With this component, a library ...
phpdocumentor/type-resolver        1.0.1    A PSR-5 based resolver of Class...
phpspec/php-diff                   v1.1.0   A comprehensive library for gen...
phpspec/prophecy                   1.9.0    Highly opinionated mocking fram...
phpunit/php-code-coverage          5.3.2    Library that provides collectio...
phpunit/php-file-iterator          1.4.5    FilterIterator implementation t...
phpunit/php-text-template          1.2.1    Simple template engine.
phpunit/php-timer                  1.0.9    Utility class for timing
phpunit/php-token-stream           2.0.2    Wrapper around PHP's tokenizer ...
phpunit/phpunit                    6.5.14   The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       5.0.10   Mock Object library for PHPUnit
psr/container                      1.0.0    Common Container Interface (PHP...
psr/http-client                    1.0.0    Common interface for HTTP clients
psr/http-factory                   1.0.1    Common interfaces for PSR-7 HTT...
psr/http-message                   1.0.1    Common interface for HTTP messages
psr/log                            1.1.2    Common interface for logging li...
ralouphie/getallheaders            3.0.3    A polyfill for getallheaders.
ramsey/uuid                        3.9.1    Formerly rhumsaa/uuid. A PHP 5....
sebastian/code-unit-reverse-lookup 1.0.1    Looks up which function or meth...
sebastian/comparator               2.1.3    Provides the functionality to c...
sebastian/diff                     2.0.1    Diff implementation
sebastian/environment              3.1.0    Provides functionality to handl...
sebastian/exporter                 3.1.2    Provides the functionality to e...
sebastian/global-state             2.0.0    Snapshotting of global state
sebastian/object-enumerator        3.0.3    Traverses array structures and ...
sebastian/object-reflector         1.1.1    Allows reflection of object att...
sebastian/recursion-context        3.0.0    Provides functionality to recur...
sebastian/resource-operations      1.0.0    Provides a list of PHP built-in...
sebastian/version                  2.0.1    Library that helps with managin...
sentry/sdk                         2.0.3    This is a metapackage shipping ...
sentry/sentry                      2.2.5    A PHP SDK for Sentry (http://se...
swiftmailer/swiftmailer            v6.2.3   Swiftmailer, free feature-rich ...
symfony/browser-kit                v4.2.4   Symfony BrowserKit Component
symfony/console                    v4.4.1   Symfony Console Component
symfony/css-selector               v4.4.1   Symfony CssSelector Component
symfony/dom-crawler                v4.4.1   Symfony DomCrawler Component
symfony/event-dispatcher           v4.4.1   Symfony EventDispatcher Component
symfony/event-dispatcher-contracts v1.1.7   Generic abstractions related to...
symfony/finder                     v4.4.1   Symfony Finder Component
symfony/options-resolver           v4.4.1   Symfony OptionsResolver Component
symfony/polyfill-ctype             v1.13.1  Symfony polyfill for ctype func...
symfony/polyfill-iconv             v1.13.1  Symfony polyfill for the Iconv ...
symfony/polyfill-intl-idn          v1.13.1  Symfony polyfill for intl's idn...
symfony/polyfill-mbstring          v1.13.1  Symfony polyfill for the Mbstri...
symfony/polyfill-php72             v1.13.1  Symfony polyfill backporting so...
symfony/polyfill-php73             v1.13.1  Symfony polyfill backporting so...
symfony/service-contracts          v2.0.1   Generic abstractions related to...
symfony/yaml                       v4.4.1   Symfony Yaml Component
theseer/tokenizer                  1.1.3    A small library for converting ...
ua-parser/uap-php                  v3.9.0   A multi-language port of Browse...
webmozart/assert                   1.6.0    Assertions to validate method i...
workerman/gatewayclient            v3.0.13 
yiisoft/yii2                       2.0.30   Yii PHP Framework Version 2
yiisoft/yii2-bootstrap             2.0.10   The Twitter Bootstrap extension...
yiisoft/yii2-composer              2.0.8    The composer plugin for Yii ext...
yiisoft/yii2-debug                 2.1.12   The debugger extension for the ...
yiisoft/yii2-faker                 2.0.4    Fixture generator. The Faker in...
yiisoft/yii2-gii                   2.1.3    The Gii extension for the Yii f...
yiisoft/yii2-redis                 2.0.11   Redis Cache, Session and Active...
yiisoft/yii2-swiftmailer           2.1.2    The SwiftMailer integration for...
zendframework/zend-diactoros       2.2.1    PSR HTTP Message implementations
@ste93cry

**Comment by ste93cry** [comment]
Ok so first thing I noticed is that you are using a package that integrates Sentry with the framework of your choice, so technically speaking requiring `sentry/sdk` is not required either as it's a dependency of that one. Anyway, I installed a fresh copy of the Yii2 framework using the `composer create-project` command and then I required the `notamedia/yii2-sentry` package. I then tried to initialize Sentry in the `yii` file as a test and it worked. As far as I see from the list of dependencies you have posted above it seems to me that everything is ok: you have the SDK, the framework integration, a PSR-7 implementation package (`guzzlehttp/psr7`) and an HTTP client (`php-http/curl-client`), so I don't really understand where the problem lies because I cannot reproduce it. The error is pretty self-explanatory: it doesn't find a suitable HTTP client and so it cannot automatically initialize the SDK, however all the required packages are installed so it makes no sense. Probably the error is in some other part of your project that I don't have access to and so I cannot help you more: the only thing left that I can suggest is to either try debugging the `Http\Discovery\HttpAsyncClientDiscovery` class or create a sample project that replicates the problem and that you can share publicy

**Comment by wzfjesun** [comment]
I found the reason. I used the 9100 port  for mapping, but the 9100 port of the firewall was not enabled. But the 9100  is accessible via browser i feel strange. 

> Http\Discovery\Exception\PuliUnavailableExceptio 
 
this error information misled me too. Thank you very much for your quick reply and installation of yii2 framework. Thank you again. @ste93cry
