### ISSUE TITLE
Silent failure with cURL errors

### ISSUE THREAD

**Issue by alexkmerz** [getsentry/sentry-php#935]
If any cURL errors are thrown, sentry catches these without the ability to forward them to the sentry dashboard.

This results in nothing being logged in either sentry or other logs.

Replication: 

Install sentry and comment out the cacert file path in php.ini.

I can imagine this could catch a lot of people out.

**Comment by ste93cry** [comment]
This is a known problem. Of course if the transport fails (e.g. one using cURL) nothing can be logged in Sentry, but we should indeed at least fallback to traditional logging locally. #907 was opened to add support for PSR-3 logger around the codebase where it made sense, however work on it is still in progress. Until the point where such PR will be merged, the only viable solution is to create your own transport and log yourself whatever you think is important for you

**Comment by ste93cry** [comment]
Closing this because it should be solved in #989
