### ISSUE TITLE
Adding stack traces via captureEvent

### ISSUE THREAD

**Issue by TamasSzigeti** [getsentry/sentry-php#939]
Hi,

seems `Sentry\Client#captureEvent` doesn't apply the `attach_stacktrace` option as `captureMessage` does, and there seems to be no easy way to send stack traces along with events, unless it is an exception.

Can this tiny but important feature be added, please?

**Comment by Jean85** [comment]
This seems more of a bug than a feature IMHO; thanks for reporting this.

@HazAT @ste93cry @stayallive do you agree?

**Comment by ste93cry** [comment]
It's a bug indeed, thus I created a PR to fix it
