### ISSUE TITLE
zendframework/zend-diactoros is abandoned

### ISSUE THREAD

**Issue by garak** [getsentry/sentry-php#947]
>Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.

**Comment by rask** [comment]
https://github.com/getsentry/sentry-php/pull/946

**Comment by stayallive** [comment]
There is already a PR merged replacing the abandoned Zend package: #945 

This will be released somewhere next week. The package was _just_ abandoned a few days ago so no worries, it will work fine until the new version is released 👍

**Comment by Jean85** [comment]
Closing as #945 got merged.
