### ISSUE TITLE
Error: Call to undefined function Sentry\mb_strpos()

### ISSUE THREAD

**Issue by GeSup** [getsentry/sentry-php#949]
Welcome,
I have issue when try to add sentry to php project. I install composer and go with instructions:
I add require ‘path to autoload.php’
install composer require sentry/sdk:2.0.3
add Sentry\init([‘dsn’ => my dns]);
add error:
```
try {
$this->functionFailsForSure();
} catch (\Throwable $exception) {
Sentry\captureException($exception);
}
```
but it make my app stop working, so I add Sentry\captureException($exception); in try catch and get Error: Call to undefined function Sentry\mb_strpos().
I have installed mb_strpos.
How to fix it?

**Comment by Jean85** [comment]
`ext-mbstring` is a requirement for this package, so you have to have it installed for it to work. In the latest version of this lib, I can see only 2 usages of that function:
 * https://github.com/getsentry/sentry-php/blob/c9b253229b95f8e5bbf6a3661a170a0be0f80563/src/Stacktrace.php#L155
 * https://github.com/getsentry/sentry-php/blob/c9b253229b95f8e5bbf6a3661a170a0be0f80563/src/Stacktrace.php#L285

It seems fine to me, are you sure that you have the extension enabled?

**Comment by GeSup** [comment]
php -m shows that it is.

**Comment by stayallive** [comment]
@GeSup there is a difference between running `php -m` and a web request are you testing everything by running `php` from the command line or are you getting the errors from a web request (as in in your browser when accessing your code)?

If you get the errors on a web request you could check using [`phpinfo()`](https://www.php.net/manual/en/function.phpinfo.php) to make sure the `mbstring` extension is also enabled in the web environment.

**Comment by GeSup** [comment]
I getting errors form a web request. phpinfo() shows there is no mbstring. I using docker that why it dosen't work. Thanks.

**Comment by stayallive** [comment]
No problem, I'm not sure what's happening there but maybe the docs of your container can provide you with the instructions of enabling the correct extension.

I'll close this issue, feel free to re-open or create a new one if something else comes up!
