### ISSUE TITLE
Fatal error "Unknown Status Code" when handling error with quota exhausted

### ISSUE THREAD

**Issue by TPETb** [getsentry/sentry-php#952]
```
PHP Fatal error:  Uncaught Http\Client\Common\Exception\ClientErrorException: Unknown Status Code in /var/www/html/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php:83
Stack trace:
#0 /var/www/html/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php(65): Http\Client\Common\Plugin\ErrorPlugin->transformResponseToException(Object(GuzzleHttp\Psr7\Request), Object(Zend\Diactoros\Response))
#1 [internal function]: Http\Client\Common\Plugin\ErrorPlugin->Http\Client\Common\Plugin\{closure}(Object(Zend\Diactoros\Response))
#2 /var/www/html/vendor/php-http/curl-client/src/PromiseCore.php(215): call_user_func(Object(Closure), Object(Zend\Diactoros\Response))
#3 /var/www/html/vendor/php-http/curl-client/src/MultiRunner.php(99): Http\Client\Curl\PromiseCore->fulfill()
#4 /var/www/html/vendor/php-http/curl-client/src/CurlPromise.php(99): Http\Client\Curl\MultiRunner->wait(Object(Http\Client\Curl\PromiseCore))
#5 /var/www/html/vendor/sentry/sentry/src/Transport/HttpTransport.php(109): Http\Client\Curl\CurlPromise->wait(false)
```

In short, Http adapter cannot recognize the code that Sentry server returns and throws an exception causing app failure.

Sentry Documentation doesn't say that one must wrap `\Sentry\captureException()` or alike invocation into a try-catch, meaning apps that have some logic AFTER sentry report (e.g. showing error to client) will lose this logic once exhausting their quota.

It seems to be a significant problem.

**Comment by ste93cry** [comment]
We catch any exception or error thrown while sending the request, so it should not happen. Can you please ensure that you are using the latest version?

https://github.com/getsentry/sentry-php/blob/161bd50dbae1468a165c1b3b14eda47f91f7f746/src/Transport/HttpTransport.php#L120-L124

**Comment by TPETb** [comment]
@ste93cry thanks for reaching out so soon.

True, we are using a more outdated 2.0.4 version. Gotta update =)

Closing this issue because it was actually fixed in https://github.com/getsentry/sentry-php/commit/61845ada198ebc9ba357c4bd8e2c89e4f4af0179

Best regards!
