### ISSUE TITLE
Changed logic for in_app_include && in_app_exclude

### ISSUE THREAD

**Issue by tpdrs** [getsentry/sentry-php#953]
Before #909 we deducted from project root all excludes. Now logic changed and we add to excludes all includes.

### Example before #909
- project_root = /app
- in_app_exclude = /app/vendor

And if comes frame with path /app/vendor/xxx it **not appears** in sentry.

### Example after #909 
- in_app_include = /app
- in_app_exclude = /app/vendor

And if comes frame with path /app/vendor/xxx it **appears** in sentry because we check in_app_include in the end of function.

**Comment by ste93cry** [comment]
You're right, the `in_app_include` option should take precedence over the `in_app_exclude` option. I will fix it asap
