### ISSUE TITLE
Missing method to get project ID

### ISSUE THREAD

**Issue by markushausammann** [getsentry/sentry-php#954]
For example when logging CSP violations with Sentry, the projectID is needed. Of course this is the last part of the sentry key but with the old Raven SDK it was possible to do `$client->project` to get the project ID. I couldn't find a way to get the project ID with the new SDK. Would be nice to have that.

**Comment by markushausammann** [comment]
Actually, it's the same for the other parts of the DNS.

**Comment by ste93cry** [comment]
Actually I just noticed that the `Options` class already has a [getter](https://github.com/getsentry/sentry-php/blob/161bd50dbae1468a165c1b3b14eda47f91f7f746/src/Options.php#L328-L331) for the project ID, and it makes sense as we use it in the HTTP transport along with the public and secret keys. Is something else missing?

**Comment by markushausammann** [comment]
Let me look into that and see if I can use it.

**Comment by ste93cry** [comment]
I'm going to close this issue as it seems solved. Feel free to reopen if you still think that there is something that should be done
