### ISSUE TITLE
2.3.0 with manual integration produces useless backtrace

### ISSUE THREAD

**Issue by pilif** [getsentry/sentry-php#957]
We have configured Sentry with a manual integration in order to do "stuff" with certain throwables before sending them off to sentry. 

Since upgrading to 2.3.0, the backtrace reported on sentry.io is completely useless because it contains only one frame, the one where our custom handler calls `captureException`.

Here's what we're doing:

```php
$options = new Options([
    'default_integrations' => false,
    'dsn' => $dsn,
    'error_types' => error_reporting(),
    'environment' => '' /* some code to find the env */,
    'release' => '' /* some code to find the release */,
    'attach_stacktrace' => true,
    'prefixes' => [APP_ROOT],
    'project_root' => APP_ROOT,
    'in_app_exclude' => [APP_ROOT . '/vendor/sentry'],
]);
$options->setIntegrations([
    new ModulesIntegration(),
    new RequestIntegration($options),
    new class () implements IntegrationInterface{

        public function setupOnce(): void
        {
            $errorHandler = ErrorHandler::registerOnceExceptionHandler();
            $errorHandler->addExceptionHandlerListener(static function (\Throwable $throwable): void {
                if ($throwable instanceof SomeClass) {
                    handle_this_one_ourselves($throwable);
                    return;
                }
                SentrySdk::getCurrentHub()->captureException($throwable);
            });
            $fhh = ErrorHandler::registerOnceFatalErrorHandler();
            $fhh->addFatalErrorHandlerListener(function (FatalErrorException $exception): void {
                SentrySdk::getCurrentHub()->captureException($exception);
            });
        }
    }
]);
$builder = new ClientBuilder($options);
SentrySdk::getCurrentHub()->bindClient($builder->getClient());
```

in 2.0, 2.1, and 2.2 up to and including 2.2.6, this is fine and on sentry.io it reports unhandled exceptions with a backtrace pointing to the exact spot there the exception happened.

In 2.3.0 however, the exception has an empty backtrace that just contains the one frame where we do `captureException` above

<img width="550" alt="Screen Shot 2020-01-16 at 13 12 59" src="https://user-images.githubusercontent.com/4990/72524336-fca6e280-3861-11ea-9bc7-bfb17da199de.png">

I did check the release notes for 2.3.0 but I could not see anything that pointed to this having changed.

**Comment by pilif** [comment]
I have bisected the client. the behavior changed at

6412b841bf2edf40c3f6586bbefa542150748307

Also, when looking at the data, I see what's going on: Prior to 6412b841bf2edf40c3f6586bbefa542150748307, the request sent to the server didn't contain a `stacktrace` key, after that commit it does.

And it seems like the sentry.io server seems to prefer the top-level `stacktrace` field over the one provided by the `exceptions` field.

I don't know whether this is an issue on the side of the sentry server or the client library, so I'm not sure whether submitting a patch to the client here is going to be helpful or not.

**Comment by pilif** [comment]
I investigated fixing this inside of our application via a `before_send` handler, but there's a small issue: Even though the `$stacktrace` field of `Event` is nullable, the `setStacktrace(Stacktrace $stacktrace): void handler doesn't allow setting a null stacktrace.

In the end the fix on the application side is still possible, but it requires `Reflection` to make the `$stacktrace` field accessible and set it to `null` in `before_send`.

**Comment by ste93cry** [comment]
>And it seems like the sentry.io server seems to prefer the top-level `stacktrace` field over the one provided by the `exceptions` field.

So, I discussed about this with @untitaker and what he said to me is that before Sentry 8 this was not the behavior, but a probable regression changed it and noone noticed it until now. I will open a PR to change here the conditions that control how the `stacktrace` key is set when `attach_stacktrace = true` so that we are aligned with what the [Python SDK](https://github.com/getsentry/sentry-python/blob/9a42f95bace9f2a5d85a7abc7f543442b6317d91/sentry_sdk/client.py#L138-L155) does, but it may also be fixed on the server in the future

>Even though the `$stacktrace` field of `Event` is nullable, the `setStacktrace(Stacktrace $stacktrace): void` handler doesn't allow setting a null stacktrace.

This is clearly another bug that I will fix, thanks for spotting it
