### ISSUE TITLE
Option to disable variables in stack traces

### ISSUE THREAD

**Issue by anka-213** [getsentry/sentry-php#965]
We don't want to log sensitive user data, but we do want to have stack traces. Is there an option to do this?

**Comment by ste93cry** [comment]
There isn't any option tailored specifically at disabling the capturing of the arguments of the functions, however you can use the `before_send` option to attach a callback that will run right before the event is sent and that allows you to edit any of its data. Take a look at #959, it's pretty similar to what you are asking and I've posted an example to show how you can access the stacktraces

**Comment by anka-213** [comment]
I looked at that code, but I don't know what the `// ...` is supposed to be filled with. How do you do the actual scrubbing?

**Comment by ste93cry** [comment]
Well, it depends on what you want to do of course. Since you asked for an option to disable vars capturing, I assume that you don't want to log any of the arguments of a frame, so something like this should work:

```php
foreach ($stacktrace->getFrames() as $frame) {
    $frame->setVars([]);
}
```

**Comment by anka-213** [comment]
@ste93cry Thanks! So the complete code would look something like this?

```
\Sentry\init([
    ...,
    'before_send' => static function (Event $event): Event {
        $stacktrace = $event->getStacktrace();

        if (null !== $stacktrace) {
            foreach ($stacktrace->getFrames() as $frame) {
               $frame->setVars([]);
            }
        }

        $exceptions = $event->getExceptions();

        foreach ($exceptions as $exception) {
            if (!isset($exception['stacktrace'])) {
                continue;
            }
            $stacktrace = $exception['stacktrace'];

            foreach ($stacktrace->getFrames() as $frame) {
               $frame->setVars([]);
            }
        }

        return $event;
    }
]);
```

**Comment by ste93cry** [comment]
Exactly. That code will strip from the frame all arguments of each function, thus not sending any sensitive data. You can then adjust the code to do other things according to your needs, mine is just an example

**Comment by cweiske** [comment]
We had do prune stack trace variables to comply with GDPR, since the variable values may contain personal information. Sending them ouside the EU to Google (hosted sentry) is not allowed.

**Comment by fredericgboutin-yapla** [comment]
I don't understand why server side data scrubbing with default scrubbers does NOT apply for stack trace variables. I'm a long time Sentry user and this is (somewhat surprisingly) the first time I saw a clear text password in Sentry.

![image](https://user-images.githubusercontent.com/91906601/207448609-ac7fed79-8e35-4d57-ad23-14f34ce312c5.png)

Go under `Project → Settings → Security & Privacy → Data Scrubber + Use Default Scrubbers`

> Apply default scrubbers to prevent things like passwords and credit cards from being stored

**Comment by cleptric** [comment]
@fredericgboutin-yapla I moved your comment over to https://github.com/getsentry/sentry/issues/42317, as Server-Side Data Scrubbing does not happen in the PHP SDK.
Please let us know on this issue if you're using SaaS or self-hosted, thank you.
