### ISSUE TITLE
HttpTransport::cleanupPendingRequests is called twice when process ends

### ISSUE THREAD

**Issue by B-Galati** [getsentry/sentry-php#970]
Hello,

I juste noticed that `\Sentry\Transport\HttpTransport::cleanupPendingRequests()` is called when php process ends.

It is called by `__destruct()` method and also by a `register_shutdown_function`.

Is this by design or is it a bug?

**Comment by Jean85** [comment]
It's kind of a failsafe, calling it twice shouldn't have any side effect. There are some situations (see #927) where the shutdown function could be missed.

**Comment by B-Galati** [comment]
Thanks! Closing.
