### ISSUE TITLE
Don't use keep-alive connections

### ISSUE THREAD

**Issue by codekandis** [getsentry/sentry-php#972]
I wrote an own sentry client wrapping the PHP Sentry SDK with its default integration. I wrote unit tests covering 100 % of the code, including the necessary integration tests.

In my integration tests I

* capture a message / error / exception
* use the returned event ID to query the Sentry API
* compare the received data stored with the event with my local data

This worked fine a couple of months ago. But since two months the event only shows up at sentry.io **after** the unit test has been stopped. So I assume there's some keep-alive setting that has been made since the recent releases. So sentry.io waits for further data until the client closes the connection. I assume that has been set with the package `php-http/curl-client`.

I'm sorry I cannot tell you which 2.x SDK Version worked and since when that changed.

---
**Update**

I forgot to mention I tested my assumption by inserting `sleep()` calls between the event capturings and the API requests with various time spans from 5 to 20 seconds. As soon the timeout has passed and the API request failed the event shows up in the issues at sentry.io.

**Comment by stayallive** [comment]
Hi @codekandis, there is no keep-alive connections at play here :)

If you take a peek at the `HttpTransport` you can see it delays sending to after the PHP request/execution to allow the application to show an error page before waiting for a Sentry request.

https://github.com/getsentry/sentry-php/blob/7acdcdd1d507e29a38b4c282527a2ae3c9fca130/src/Transport/HttpTransport.php

This means that only after your CLI request finishes (in this case phpunit) requests are transported. I'm not sure why this wouldn't have been the case before but there have been changes and fixes around this over the 2.x lifetime.

To get around this you can implement something like this in your tests: https://github.com/getsentry/sentry-laravel/blob/d6aa3aa87adbacf622f4ffe09a4e17b40bd20da0/src/Sentry/Laravel/Integration.php#L93-L100

This will flush the queue and transport all pending requests. If you do this after your tests but before you validate the request arrives you should be good 👍

**Comment by codekandis** [comment]
Thx for that detailed info.

So it's correct to say, e. g. I have a cronjob running processing a huge time consuming data load, all messages sent to sentry.io are in fact sent until the cronjob finishes? The same would apply to websites delivering a huge download, generated server side on the fly.

**Comment by Jean85** [comment]
Yes. The last PR that addressed this issue is #905.

**Comment by stayallive** [comment]
Yes, so to clarify when 3.0 comes around this behaviour will change, but for now this is the default behaviour, if you need events to be sent immediately you can [replace the transport](https://docs.sentry.io/platforms/php/#transport) (you can re-use the default `HttpTransport` but with the `$delaySendingUntilShutdown` set to `false`) or manually flush the queue.

**Comment by codekandis** [comment]
I used the flushing approach. It was easier to implement than to have a custom transport implementation. And I'm able to enable / disable it now by configuration. It's working now.

Thank you guys, for your advices!
