### ISSUE TITLE
PHP Integration

### ISSUE THREAD

**Issue by oktaykalfa** [getsentry/sentry-php#986]
Hello, i have installed sentry/sdk via:

composer require sentry/sdk:2.1.0

then i have added this line to my project

\Sentry\init([‘dsn’ => ‘https://mycode@sentry.io/myprojectnumber’]);

Lastly, i added this line to test sentry

throw new Exception(“TEST sentry.”);

But nothing is happened. PHP side is not working but Javascript side is working well. This is just ruined all of my day and still working on it.

This is how i’m installed & my code block :

https://aws1.discourse-cdn.com/standard10/uploads/sentry/original/2X/8/8fa306b719242dd05eafee01abbe64ca9923a6a3.png

Thanks for helping.
Regards.

**Comment by ste93cry** [comment]
In the past we had issues with some PHP installations where the `curl.cainfo` and `openssl.cafile` INI settings weren’t set, so please take a look if this is your case too

**Comment by oktaykalfa** [comment]
@ste93cry i thank you so much, based on your comment, i found the problem.

Solution: in your php.ini file you need to declare your 'cacert.pem'.
curl.cainfo = "C:\Projects\cacert.pem"
this lines comes empty on default installation.

Cacert.pem file can be downloaded from below.
https://curl.haxx.se/docs/caextract.html

Farewell.
