### ISSUE TITLE
how to attach uploaded files?

### ISSUE THREAD

**Issue by ghost** [getsentry/sentry-php#996]
people will upload excels to our app but the excel contents may not fit to our requirements and sometimes our app will crash... therefore, it could be easier for us if we can have the file to test.

**Comment by stayallive** [comment]
As far as I know this is not a feature supported by the Sentry server (attaching files to events). 

This might be best handled in your app to keep the excel source file until the job succeeds or the user deletes it. 

This way you can re-download the file as much as you want (and the end-user can too).

**Comment by wppd** [comment]
thanks for suggestion, I was also thinking about uploading files to cloud and attach the link as extra context when crashes.

**Comment by wppd** [comment]
@

**Comment by peterrattew** [comment]
Would be great if this was added to the SDK!

**Comment by Kolyunya** [comment]
Seems like newer versions of the Sentry server actually do support attachments. There are docs for some SDKs ([1](https://docs.sentry.io/platforms/native/enriching-events/attachments/), [2](https://docs.sentry.io/platforms/javascript/enriching-events/attachments/), [3](https://docs.sentry.io/platforms/dotnet/enriching-events/attachments/)), but not for PHP. Can we have support of attachments for PHP, please?

**Comment by ste93cry** [comment]
There's no reason to not support this now that the server does, however I have no ETA to share on when this will happen, if it will. 

_Disclaimer: I'm not a Sentry employee, so while me as a OSS contributor don't have a plan to implement this anytime soon, maybe the Sentry guys have it_

**Comment by Kolyunya** [comment]
@ste93cry could someone from the team at least reopen this issue?

**Comment by Kolyunya** [comment]
@Jean85 is it possible to add this one to the backlog? Thank you!

**Comment by ste93cry** [comment]
Added, thanks. I cannot promised anything about if and when this will be implemented (but contribution is welcome of course, even though it may not be that easy), but it's definitely something we want to keep track of

**Comment by vladanpaunovic** [comment]
While we will add this at some point in the future, I believe this is possible for you to do this on your own already today. 😉 

The way we did it in the Javascript SDK, before introducing our own api to do that was just by calling the sentry api directly.

It is quite easy. I dig up the old commit with the code example for you (in JS though, but you can easily rewrite this in php).

https://github.com/getsentry/sentry-docs/blob/e6536cff4d6ecaddc19fbee9d3de1771d270034f/src/includes/enriching-events/add-attachment/javascript.mdx

**Comment by jankonas** [comment]
Hello, is someone working on this or is help appreciated?

**Comment by Fabccc** [comment]
Digging this issue, since April 2023, a new major version was published.
Is it possible to re-open this issue ? Every main Sentry's SDK support this feature but not php
