### ISSUE TITLE
Unable to mock captureException method with Mockery

### ISSUE THREAD

**Issue by borislav-angelov** [getsentry/sentry-php#997]
I am trying to mock captureException method, but the problem is that class \Sentry\State\Hub is defined as final and the following statement does not work:

\Sentry\Laravel\Facade::shouldReceive('captureException')->with($exception)->once();

it throws 
`
Mockery\Exception: The class \Sentry\State\Hub is marked final and its methods cannot be replaced. Classes marked final can be passed in to \Mockery::mock() as instantiated objects to create a partial mock, but only if the mock is not subject to type hinting checks.
`

Is there any reason why \Sentry\State\Hub class is defined as final?

**Comment by Jean85** [comment]
Yes, to reduce API surface and make maintainability easier for us.

All classes declared as `final` also have an interface, so you can mock that to avoid this issue.

**Comment by borislav-angelov** [comment]
Thanks, I understand, so if somebody is interested, the workaround that I am currently using is:

`
        $sentry = $this->mock(Sentry\State\HubInterface, function ($mock) use ($exception) {
            $mock->shouldReceive('captureException')->with($exception)->once();
        });

        App::instance('sentry', $sentry);
`

just keep in mind that according to the Laravel documentation, we can also use Facade mocking like that

Sentry::shouldReceive('captureException')->with($exception)->once();

but because of the **final** class definition, that Facade mocking does not work.

**Comment by stayallive** [comment]
There is nothing I can do on the Laravel side to fix this, the way @borislav-angelov describes looks to me to be a valid workaround, the class is final, no magic I can do to change that to allow the facade to know to mock the interface as far as I know.

**Comment by dacgray** [comment]
For Codeception people, you can do this:

```php
            $sentry = Stub::makeEmpty(
                HubInterface::class,
                [
                    'captureException' => Expected::once()
                ],
                $this
            );
```

**Comment by Jean85** [comment]
In general, mocking the interface is the best approach, because you avoid leaning on methods of the concrete class, that could be missing.

Closing as we found the solution.

**Comment by gabrielanhaia** [comment]
It was closed but I would like to answer and document another alternative while using `prophecy`.

I was facing the same problem when mocking a call for `Sentry\ClientInterface::captureMessage`:

`$this->sentryClient->captureMessage($errorMessage)->shouldBeCalledOnce();`
The error I see is `Prophecy\Exception\Doubler\ClassMirrorException: Could not reflect class Sentry\EventId as it is marked final.`

The solution for me was just to define the expectation of return as `null`:
`        $this->sentryClient->captureMessage($errorMessage)->shouldBeCalledOnce()->willReturn(null);`

**Comment by Jean85** [comment]
Another solution would be:
```php
 $this->sentryClient->captureMessage($errorMessage)->shouldBeCalledOnce()->willReturn(new EventId());
```
